@ stub D3DAssemble
@ stub DebugSetMute
@ stub D3DCompile
@ stub D3DCompressShaders
@ stub D3DCreateBlob
@ stub D3DDecompressShaders
@ stub D3DDisassemble10Effect
@ stub D3DDisassemble
@ stub D3DGetBlobPart
@ stub D3DGetDebugInfo
@ stub D3DGetInputAndOutputSignatureBlob
@ stub D3DGetInputSignatureBlob
@ stub D3DGetOutputSignatureBlob
@ stub D3DPreprocess
@ stub D3DReflect
@ stub D3DReturnFailure1
@ stub D3DStripShader
