@ stub DllCanUnloadNow
@ stub DllGetClassObject
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub HrDiAddComponentToINetCfg
@ stub LanaCfgFromCommandArgs
@ stub ModemClassCoInstaller
@ stub NetCfgDiagFromCommandArgs
@ stub NetCfgDiagRepairRegistryBindings
@ stub NetClassInstaller
@ stub NetPropPageProvider
@ stub RasAddBindings
@ stub RasCountBindings
@ stub RasRemoveBindings
@ stub SvchostChangeSvchostGroup
@ stub UpdateLanaConfigUsingAnswerfile
