@ stub GetDpiForMonitor
@ stub GetProcessDpiAwareness
@ stub GetScaleFactorForDevice
@ stub GetScaleFactorForMonitor
@ stub RegisterScaleChangeEvent
@ stub RegisterScaleChangeNotifications
@ stub RevokeScaleChangeNotifications
@ stub SetProcessDpiAwareness
@ stub UnregisterScaleChangeEvent
