# Old C runtime library. All functions provided by msvcrt

@ forward ??2@YAPAXI@Z msvcrt.??2@YAPAXI@Z
@ forward ??3@YAXPAX@Z msvcrt.??3@YAXPAX@Z
@ forward ?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z msvcrt.?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z
@ forward _CIacos msvcrt._CIacos
@ forward _CIasin msvcrt._CIasin
@ forward _CIatan msvcrt._CIatan
@ forward _CIatan2 msvcrt._CIatan2
@ forward _CIcos msvcrt._CIcos
@ forward _CIcosh msvcrt._CIcosh
@ forward _CIexp msvcrt._CIexp
@ forward _CIfmod msvcrt._CIfmod
@ forward _CIlog msvcrt._CIlog
@ forward _CIlog10 msvcrt._CIlog10
@ forward _CIpow msvcrt._CIpow
@ forward _CIsin msvcrt._CIsin
@ forward _CIsinh msvcrt._CIsinh
@ forward _CIsqrt msvcrt._CIsqrt
@ forward _CItan msvcrt._CItan
@ forward _CItanh msvcrt._CItanh
@ forward _HUGE_dll msvcrt._HUGE
@ forward _XcptFilter msvcrt._XcptFilter
@ cdecl __GetMainArgs(ptr ptr ptr long) __GetMainArgs
@ forward __argc_dll msvcrt.__argc
@ forward __argv_dll msvcrt.__argv
@ forward __dllonexit msvcrt.__dllonexit
@ forward __doserrno msvcrt.__doserrno
@ forward __fpecode msvcrt.__fpecode
@ forward __isascii msvcrt.__isascii
@ forward __iscsym msvcrt.__iscsym
@ forward __iscsymf msvcrt.__iscsymf
@ forward __mb_cur_max_dll msvcrt.__mb_cur_max
@ forward __pxcptinfoptrs msvcrt.__pxcptinfoptrs
@ forward __threadhandle msvcrt.__threadhandle
@ forward __threadid msvcrt.__threadid
@ forward __toascii msvcrt.__toascii
@ forward _abnormal_termination msvcrt._abnormal_termination
@ forward _access msvcrt._access
@ forward _acmdln_dll msvcrt._acmdln
@ forward _aexit_rtn_dll msvcrt._aexit_rtn
@ forward _amsg_exit msvcrt._amsg_exit
@ forward _assert msvcrt._assert
@ extern _basemajor_dll CRTDLL__basemajor_dll
@ extern _baseminor_dll CRTDLL__basemajor_dll
@ extern _baseversion_dll CRTDLL__basemajor_dll
@ forward _beep msvcrt._beep
@ forward _beginthread msvcrt._beginthread
@ forward _c_exit msvcrt._c_exit
@ forward _cabs msvcrt._cabs
@ forward _cexit msvcrt._cexit
@ forward _cgets msvcrt._cgets
@ forward _chdir msvcrt._chdir
@ forward _chdrive msvcrt._chdrive
@ forward _chgsign msvcrt._chgsign
@ forward _chmod msvcrt._chmod
@ forward _chsize msvcrt._chsize
@ forward _clearfp msvcrt._clearfp
@ forward _close msvcrt._close
@ forward _commit msvcrt._commit
@ forward _commode_dll msvcrt._commode
@ forward _control87 msvcrt._control87
@ forward _controlfp msvcrt._controlfp
@ forward _copysign msvcrt._copysign
@ forward _cprintf msvcrt._cprintf
@ extern _cpumode_dll CRTDLL__cpumode_dll
@ forward _cputs msvcrt._cputs
@ forward _creat msvcrt._creat
@ forward _cscanf msvcrt._cscanf
@ forward _ctype msvcrt._ctype
@ forward _cwait msvcrt._cwait
@ forward _daylight_dll msvcrt._daylight
@ forward _dup msvcrt._dup
@ forward _dup2 msvcrt._dup2
@ forward _ecvt msvcrt._ecvt
@ forward _endthread msvcrt._endthread
@ forward _environ_dll msvcrt._environ
@ forward _eof msvcrt._eof
@ forward _errno msvcrt._errno
@ forward _except_handler2 msvcrt._except_handler2
@ forward _execl msvcrt._execl
@ forward _execle msvcrt._execle
@ forward _execlp msvcrt._execlp
@ forward _execlpe msvcrt._execlpe
@ forward _execv msvcrt._execv
@ forward _execve msvcrt._execve
@ forward _execvp msvcrt._execvp
@ forward _execvpe msvcrt._execvpe
@ forward _exit msvcrt._exit
@ forward _expand msvcrt._expand
@ forward _fcloseall msvcrt._fcloseall
@ forward _fcvt msvcrt._fcvt
@ forward _fdopen msvcrt._fdopen
@ forward _fgetchar msvcrt._fgetchar
@ forward _fgetwchar msvcrt._fgetwchar
@ forward _filbuf msvcrt._filbuf
@ forward _fileinfo_dll msvcrt._fileinfo
@ forward _filelength msvcrt._filelength
@ forward _fileno msvcrt._fileno
@ forward _findclose msvcrt._findclose
@ forward _findfirst msvcrt._findfirst
@ forward _findnext msvcrt._findnext
@ forward _finite msvcrt._finite
@ forward _flsbuf msvcrt._flsbuf
@ forward _flushall msvcrt._flushall
@ forward _fmode_dll msvcrt._fmode
@ forward _fpclass msvcrt._fpclass
@ forward _fpieee_flt msvcrt._fpieee_flt
@ forward _fpreset msvcrt._fpreset
@ forward _fputchar msvcrt._fputchar
@ forward _fputwchar msvcrt._fputwchar
@ forward _fsopen msvcrt._fsopen
@ cdecl _fstat(long ptr) CRTDLL__fstat
@ forward _ftime msvcrt._ftime
@ forward _ftol msvcrt._ftol
@ forward _fullpath msvcrt._fullpath
@ forward _futime msvcrt._futime
@ forward _gcvt msvcrt._gcvt
@ forward _get_osfhandle msvcrt._get_osfhandle
@ forward _getch msvcrt._getch
@ forward _getche msvcrt._getche
@ forward _getcwd msvcrt._getcwd
@ forward _getdcwd msvcrt._getdcwd
@ forward _getdiskfree msvcrt._getdiskfree
@ forward _getdllprocaddr msvcrt._getdllprocaddr
@ forward _getdrive msvcrt._getdrive
@ forward _getdrives msvcrt._getdrives
@ forward _getpid msvcrt._getpid
@ forward _getsystime msvcrt._getsystime
@ forward _getw msvcrt._getw
@ forward _global_unwind2 msvcrt._global_unwind2
@ forward _heapchk msvcrt._heapchk
@ forward _heapmin msvcrt._heapmin
@ forward _heapset msvcrt._heapset
@ forward _heapwalk msvcrt._heapwalk
@ forward _hypot msvcrt._hypot
@ forward _initterm msvcrt._initterm
@ forward _iob msvcrt._iob
@ forward _isatty msvcrt._isatty
@ forward _isctype msvcrt._isctype
@ forward _ismbbalnum msvcrt._ismbbalnum
@ forward _ismbbalpha msvcrt._ismbbalpha
@ forward _ismbbgraph msvcrt._ismbbgraph
@ forward _ismbbkalnum msvcrt._ismbbkalnum
@ forward _ismbbkana msvcrt._ismbbkana
@ forward _ismbbkpunct msvcrt._ismbbkpunct
@ forward _ismbblead msvcrt._ismbblead
@ forward _ismbbprint msvcrt._ismbbprint
@ forward _ismbbpunct msvcrt._ismbbpunct
@ forward _ismbbtrail msvcrt._ismbbtrail
@ forward _ismbcalpha msvcrt._ismbcalpha
@ forward _ismbcdigit msvcrt._ismbcdigit
@ forward _ismbchira msvcrt._ismbchira
@ forward _ismbckata msvcrt._ismbckata
@ forward _ismbcl0 msvcrt._ismbcl0
@ forward _ismbcl1 msvcrt._ismbcl1
@ forward _ismbcl2 msvcrt._ismbcl2
@ forward _ismbclegal msvcrt._ismbclegal
@ forward _ismbclower msvcrt._ismbclower
@ forward _ismbcprint msvcrt._ismbcprint
@ forward _ismbcspace msvcrt._ismbcspace
@ forward _ismbcsymbol msvcrt._ismbcsymbol
@ forward _ismbcupper msvcrt._ismbcupper
@ forward _ismbslead msvcrt._ismbslead
@ forward _ismbstrail msvcrt._ismbstrail
@ forward _isnan msvcrt._isnan
@ forward _itoa msvcrt._itoa
@ forward _j0 msvcrt._j0
@ forward _j1 msvcrt._j1
@ forward _jn msvcrt._jn
@ forward _kbhit msvcrt._kbhit
@ forward _lfind msvcrt._lfind
@ forward _loaddll msvcrt._loaddll
@ forward _local_unwind2 msvcrt._local_unwind2
@ forward _locking msvcrt._locking
@ forward _logb msvcrt._logb
@ forward _lrotl msvcrt._lrotl
@ forward _lrotr msvcrt._lrotr
@ forward _lsearch msvcrt._lsearch
@ forward _lseek msvcrt._lseek
@ forward _ltoa msvcrt._ltoa
@ forward _makepath msvcrt._makepath
@ forward _matherr msvcrt._matherr
@ forward _mbbtombc msvcrt._mbbtombc
@ forward _mbbtype msvcrt._mbbtype
@ forward _mbccpy msvcrt._mbccpy
@ forward _mbcjistojms msvcrt._mbcjistojms
@ forward _mbcjmstojis msvcrt._mbcjmstojis
@ forward _mbclen msvcrt._mbclen
@ forward _mbctohira msvcrt._mbctohira
@ forward _mbctokata msvcrt._mbctokata
@ forward _mbctolower msvcrt._mbctolower
@ forward _mbctombb msvcrt._mbctombb
@ forward _mbctoupper msvcrt._mbctoupper
@ forward _mbctype msvcrt._mbctype
@ forward _mbsbtype msvcrt._mbsbtype
@ forward _mbscat msvcrt._mbscat
@ forward _mbschr msvcrt._mbschr
@ forward _mbscmp msvcrt._mbscmp
@ forward _mbscpy msvcrt._mbscpy
@ forward _mbscspn msvcrt._mbscspn
@ forward _mbsdec msvcrt._mbsdec
@ forward _mbsdup msvcrt._mbsdup
@ forward _mbsicmp msvcrt._mbsicmp
@ forward _mbsinc msvcrt._mbsinc
@ forward _mbslen msvcrt._mbslen
@ forward _mbslwr msvcrt._mbslwr
@ forward _mbsnbcat msvcrt._mbsnbcat
@ forward _mbsnbcmp msvcrt._mbsnbcmp
@ forward _mbsnbcnt msvcrt._mbsnbcnt
@ forward _mbsnbcpy msvcrt._mbsnbcpy
@ forward _mbsnbicmp msvcrt._mbsnbicmp
@ forward _mbsnbset msvcrt._mbsnbset
@ forward _mbsncat msvcrt._mbsncat
@ forward _mbsnccnt msvcrt._mbsnccnt
@ forward _mbsncmp msvcrt._mbsncmp
@ forward _mbsncpy msvcrt._mbsncpy
@ forward _mbsnextc msvcrt._mbsnextc
@ forward _mbsnicmp msvcrt._mbsnicmp
@ forward _mbsninc msvcrt._mbsninc
@ forward _mbsnset msvcrt._mbsnset
@ forward _mbspbrk msvcrt._mbspbrk
@ forward _mbsrchr msvcrt._mbsrchr
@ forward _mbsrev msvcrt._mbsrev
@ forward _mbsset msvcrt._mbsset
@ forward _mbsspn msvcrt._mbsspn
@ forward _mbsspnp msvcrt._mbsspnp
@ forward _mbsstr msvcrt._mbsstr
@ forward _mbstok msvcrt._mbstok
@ forward _mbstrlen msvcrt._mbstrlen
@ forward _mbsupr msvcrt._mbsupr
@ forward _memccpy msvcrt._memccpy
@ forward _memicmp msvcrt._memicmp
@ forward _mkdir msvcrt._mkdir
@ forward _mktemp msvcrt._mktemp
@ forward _msize msvcrt._msize
@ forward _nextafter msvcrt._nextafter
@ forward _onexit msvcrt._onexit
@ forward _open msvcrt._open
@ forward _open_osfhandle msvcrt._open_osfhandle
@ extern _osmajor_dll CRTDLL__osmajor_dll
@ extern _osminor_dll CRTDLL__osminor_dll
@ extern _osmode_dll CRTDLL__osmode_dll
@ forward _osver_dll msvcrt._osver
@ extern _osversion_dll CRTDLL__osversion_dll
@ forward _pclose msvcrt._pclose
@ forward _pctype_dll msvcrt._pctype
@ forward _pgmptr_dll msvcrt._pgmptr
@ forward _pipe msvcrt._pipe
@ forward _popen msvcrt._popen
@ forward _purecall msvcrt._purecall
@ forward _putch msvcrt._putch
@ forward _putenv msvcrt._putenv
@ forward _putw msvcrt._putw
@ forward _pwctype_dll msvcrt._pwctype
@ forward _read msvcrt._read
@ forward _rmdir msvcrt._rmdir
@ forward _rmtmp msvcrt._rmtmp
@ forward _rotl msvcrt._rotl
@ forward _rotr msvcrt._rotr
@ forward _scalb msvcrt._scalb
@ forward _searchenv msvcrt._searchenv
@ forward _seterrormode msvcrt._seterrormode
@ forward _setjmp msvcrt._setjmp
@ forward _setmode msvcrt._setmode
@ forward _setsystime msvcrt._setsystime
@ forward _sleep msvcrt._sleep
@ forward _snprintf msvcrt._snprintf
@ forward _snwprintf msvcrt._snwprintf
@ forward _sopen msvcrt._sopen
@ forward _spawnl msvcrt._spawnl
@ forward _spawnle msvcrt._spawnle
@ forward _spawnlp msvcrt._spawnlp
@ forward _spawnlpe msvcrt._spawnlpe
@ forward _spawnv msvcrt._spawnv
@ forward _spawnve msvcrt._spawnve
@ forward _spawnvp msvcrt._spawnvp
@ forward _spawnvpe msvcrt._spawnvpe
@ forward _splitpath msvcrt._splitpath
@ cdecl _stat(str ptr) CRTDLL__stat
@ forward _statusfp msvcrt._statusfp
@ forward _strcmpi msvcrt._strcmpi
@ forward _strdate msvcrt._strdate
@ cdecl _strdec(str str) _strdec
@ forward _strdup msvcrt._strdup
@ forward _strerror msvcrt._strerror
@ forward _stricmp msvcrt._stricmp
@ forward _stricoll msvcrt._stricoll
@ cdecl _strinc(str) _strinc
@ forward _strlwr msvcrt._strlwr
@ cdecl _strncnt(str long) _strncnt
@ cdecl _strnextc(str) _strnextc
@ forward _strnicmp msvcrt._strnicmp
@ cdecl _strninc(str long) _strninc
@ forward _strnset msvcrt._strnset
@ forward _strrev msvcrt._strrev
@ forward _strset msvcrt._strset
@ cdecl _strspnp(str str) _strspnp
@ forward _strtime msvcrt._strtime
@ forward _strupr msvcrt._strupr
@ forward _swab msvcrt._swab
@ forward _sys_errlist msvcrt._sys_errlist
@ forward _sys_nerr_dll msvcrt._sys_nerr
@ forward _tell msvcrt._tell
@ forward _tempnam msvcrt._tempnam
@ forward _timezone_dll msvcrt._timezone
@ forward _tolower msvcrt._tolower
@ forward _toupper msvcrt._toupper
@ forward _tzname msvcrt._tzname
@ forward _tzset msvcrt._tzset
@ forward _ultoa msvcrt._ultoa
@ forward _umask msvcrt._umask
@ forward _ungetch msvcrt._ungetch
@ forward _unlink msvcrt._unlink
@ forward _unloaddll msvcrt._unloaddll
@ forward _utime msvcrt._utime
@ forward _vsnprintf msvcrt._vsnprintf
@ forward _vsnwprintf msvcrt._vsnwprintf
@ forward _wcsdup msvcrt._wcsdup
@ forward _wcsicmp msvcrt._wcsicmp
@ forward _wcsicoll msvcrt._wcsicoll
@ forward _wcslwr msvcrt._wcslwr
@ forward _wcsnicmp msvcrt._wcsnicmp
@ forward _wcsnset msvcrt._wcsnset
@ forward _wcsrev msvcrt._wcsrev
@ forward _wcsset msvcrt._wcsset
@ forward _wcsupr msvcrt._wcsupr
@ forward _winmajor_dll msvcrt._winmajor
@ forward _winminor_dll msvcrt._winminor
@ forward _winver_dll msvcrt._winver
@ forward _write msvcrt._write
@ forward _wtoi msvcrt._wtoi
@ forward _wtol msvcrt._wtol
@ forward _y0 msvcrt._y0
@ forward _y1 msvcrt._y1
@ forward _yn msvcrt._yn
@ forward abort msvcrt.abort
@ forward abs msvcrt.abs
@ forward acos msvcrt.acos
@ forward asctime msvcrt.asctime
@ forward asin msvcrt.asin
@ forward atan msvcrt.atan
@ forward atan2 msvcrt.atan2
@ forward atexit msvcrt.atexit
@ forward atof msvcrt.atof
@ forward atoi msvcrt.atoi
@ forward atol msvcrt.atol
@ forward bsearch msvcrt.bsearch
@ forward calloc msvcrt.calloc
@ forward ceil msvcrt.ceil
@ forward clearerr msvcrt.clearerr
@ forward clock msvcrt.clock
@ forward cos msvcrt.cos
@ forward cosh msvcrt.cosh
@ forward ctime msvcrt.ctime
@ forward difftime msvcrt.difftime
@ forward div msvcrt.div
@ forward exit msvcrt.exit
@ forward exp msvcrt.exp
@ forward fabs msvcrt.fabs
@ forward fclose msvcrt.fclose
@ forward feof msvcrt.feof
@ forward ferror msvcrt.ferror
@ forward fflush msvcrt.fflush
@ forward fgetc msvcrt.fgetc
@ forward fgetpos msvcrt.fgetpos
@ forward fgets msvcrt.fgets
@ forward fgetwc msvcrt.fgetwc
@ forward floor msvcrt.floor
@ forward fmod msvcrt.fmod
@ forward fopen msvcrt.fopen
@ forward fprintf msvcrt.fprintf
@ forward fputc msvcrt.fputc
@ forward fputs msvcrt.fputs
@ forward fputwc msvcrt.fputwc
@ forward fread msvcrt.fread
@ forward free msvcrt.free
@ forward freopen msvcrt.freopen
@ forward frexp msvcrt.frexp
@ forward fscanf msvcrt.fscanf
@ forward fseek msvcrt.fseek
@ forward fsetpos msvcrt.fsetpos
@ forward ftell msvcrt.ftell
@ forward fwprintf msvcrt.fwprintf
@ forward fwrite msvcrt.fwrite
@ forward fwscanf msvcrt.fwscanf
@ forward getc msvcrt.getc
@ forward getchar msvcrt.getchar
@ forward getenv msvcrt.getenv
@ forward gets msvcrt.gets
@ forward gmtime msvcrt.gmtime
@ forward is_wctype msvcrt.is_wctype
@ forward isalnum msvcrt.isalnum
@ forward isalpha msvcrt.isalpha
@ forward iscntrl msvcrt.iscntrl
@ forward isdigit msvcrt.isdigit
@ forward isgraph msvcrt.isgraph
@ forward isleadbyte msvcrt.isleadbyte
@ forward islower msvcrt.islower
@ forward isprint msvcrt.isprint
@ forward ispunct msvcrt.ispunct
@ forward isspace msvcrt.isspace
@ forward isupper msvcrt.isupper
@ forward iswalnum msvcrt.iswalnum
@ forward iswalpha msvcrt.iswalpha
@ forward iswascii msvcrt.iswascii
@ forward iswcntrl msvcrt.iswcntrl
@ forward iswctype msvcrt.iswctype
@ forward iswdigit msvcrt.iswdigit
@ forward iswgraph msvcrt.iswgraph
@ forward iswlower msvcrt.iswlower
@ forward iswprint msvcrt.iswprint
@ forward iswpunct msvcrt.iswpunct
@ forward iswspace msvcrt.iswspace
@ forward iswupper msvcrt.iswupper
@ forward iswxdigit msvcrt.iswxdigit
@ forward isxdigit msvcrt.isxdigit
@ forward labs msvcrt.labs
@ forward ldexp msvcrt.ldexp
@ forward ldiv msvcrt.ldiv
@ forward localeconv msvcrt.localeconv
@ forward localtime msvcrt.localtime
@ forward log msvcrt.log
@ forward log10 msvcrt.log10
@ forward longjmp msvcrt.longjmp
@ forward malloc msvcrt.malloc
@ forward mblen msvcrt.mblen
@ forward mbstowcs msvcrt.mbstowcs
@ forward mbtowc msvcrt.mbtowc
@ forward memchr msvcrt.memchr
@ forward memcmp msvcrt.memcmp
@ forward memcpy msvcrt.memcpy
@ forward memmove msvcrt.memmove
@ forward memset msvcrt.memset
@ forward mktime msvcrt.mktime
@ forward modf msvcrt.modf
@ forward perror msvcrt.perror
@ forward pow msvcrt.pow
@ forward printf msvcrt.printf
@ forward putc msvcrt.putc
@ forward putchar msvcrt.putchar
@ forward puts msvcrt.puts
@ forward qsort msvcrt.qsort
@ forward raise msvcrt.raise
@ forward rand msvcrt.rand
@ forward realloc msvcrt.realloc
@ forward remove msvcrt.remove
@ forward rename msvcrt.rename
@ forward rewind msvcrt.rewind
@ forward scanf msvcrt.scanf
@ forward setbuf msvcrt.setbuf
@ forward setlocale msvcrt.setlocale
@ forward setvbuf msvcrt.setvbuf
@ forward signal msvcrt.signal
@ forward sin msvcrt.sin
@ forward sinh msvcrt.sinh
@ forward sprintf msvcrt.sprintf
@ forward sqrt msvcrt.sqrt
@ forward srand msvcrt.srand
@ forward sscanf msvcrt.sscanf
@ forward strcat msvcrt.strcat
@ forward strchr msvcrt.strchr
@ forward strcmp msvcrt.strcmp
@ forward strcoll msvcrt.strcoll
@ forward strcpy msvcrt.strcpy
@ forward strcspn msvcrt.strcspn
@ forward strerror msvcrt.strerror
@ forward strftime msvcrt.strftime
@ forward strlen msvcrt.strlen
@ forward strncat msvcrt.strncat
@ forward strncmp msvcrt.strncmp
@ forward strncpy msvcrt.strncpy
@ forward strpbrk msvcrt.strpbrk
@ forward strrchr msvcrt.strrchr
@ forward strspn msvcrt.strspn
@ forward strstr msvcrt.strstr
@ forward strtod msvcrt.strtod
@ forward strtok msvcrt.strtok
@ forward strtol msvcrt.strtol
@ forward strtoul msvcrt.strtoul
@ forward strxfrm msvcrt.strxfrm
@ forward swprintf msvcrt.swprintf
@ forward swscanf msvcrt.swscanf
@ forward system msvcrt.system
@ forward tan msvcrt.tan
@ forward tanh msvcrt.tanh
@ forward time msvcrt.time
@ forward tmpfile msvcrt.tmpfile
@ forward tmpnam msvcrt.tmpnam
@ forward tolower msvcrt.tolower
@ forward toupper msvcrt.toupper
@ forward towlower msvcrt.towlower
@ forward towupper msvcrt.towupper
@ forward ungetc msvcrt.ungetc
@ forward ungetwc msvcrt.ungetwc
@ forward vfprintf msvcrt.vfprintf
@ forward vfwprintf msvcrt.vfwprintf
@ forward vprintf msvcrt.vprintf
@ forward vsprintf msvcrt.vsprintf
@ forward vswprintf msvcrt.vswprintf
@ forward vwprintf msvcrt.vwprintf
@ forward wcscat msvcrt.wcscat
@ forward wcschr msvcrt.wcschr
@ forward wcscmp msvcrt.wcscmp
@ forward wcscoll msvcrt.wcscoll
@ forward wcscpy msvcrt.wcscpy
@ forward wcscspn msvcrt.wcscspn
@ forward wcsftime msvcrt.wcsftime
@ forward wcslen msvcrt.wcslen
@ forward wcsncat msvcrt.wcsncat
@ forward wcsncmp msvcrt.wcsncmp
@ forward wcsncpy msvcrt.wcsncpy
@ forward wcspbrk msvcrt.wcspbrk
@ forward wcsrchr msvcrt.wcsrchr
@ forward wcsspn msvcrt.wcsspn
@ forward wcsstr msvcrt.wcsstr
@ forward wcstod msvcrt.wcstod
@ forward wcstok msvcrt.wcstok
@ forward wcstol msvcrt.wcstol
@ forward wcstombs msvcrt.wcstombs
@ forward wcstoul msvcrt.wcstoul
@ forward wcsxfrm msvcrt.wcsxfrm
@ forward wctomb msvcrt.wctomb
@ forward wprintf msvcrt.wprintf
@ forward wscanf msvcrt.wscanf
@ forward _itow msvcrt._itow
@ forward _ltow msvcrt._ltow
