/* Runtime classes stub for windows.xbox.dll
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#pragma makedep register

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "activation.idl";
