@ stub CfAbortOperation
@ stub CfCloseAppPolicy
@ stub CfCloseHandle
@ stub CfConnectSyncRoot
@ stub CfConvertToPlaceholder
@ stub CfCreatePlaceholders
@ stub CfDehydratePlaceholder
@ stub CfDehydratePlaceholderEx
@ stub CfDisconnectSyncRoot
@ stub CfEnumAppPolicy
@ stub CfExecute
@ stub CfGetCorrelationVector
@ stub CfGetLastSyncStatus
@ stdcall CfGetPlaceholderInfo(ptr long ptr long ptr)
@ stub CfGetPlaceholderRangeInfo
@ stub CfGetPlaceholderRangeInfoForHydration
@ stub CfGetPlaceholderStateFromAttributeTag
@ stub CfGetPlaceholderStateFromFileInfo
@ stub CfGetPlaceholderStateFromFindData
@ stub CfGetPlatformInfo
@ stub CfGetSyncRootInfoByHandle
@ stub CfGetSyncRootInfoByPath
@ stub CfGetTransferKey
@ stub CfGetWin32HandleFromProtectedHandle
@ stub CfHydratePlaceholder
@ stub CfHydratePlaceholderWithAttributionPrivate
@ stub CfLockProperties
@ stub CfOpenAppPolicy
@ stub CfOpenFileWithOplock
@ stub CfOpenProgressEvent
@ stub CfQueryProgress
@ stub CfQuerySyncProviderStatus
@ stub CfReferenceProtectedHandle
@ stub CfRegisterSyncRoot
@ stub CfReleaseProtectedHandle
@ stub CfReleaseTransferKey
@ stub CfReportProviderProgress
@ stub CfReportProviderProgress2
@ stub CfReportSyncStatus
@ stub CfRetrieveProperties
@ stub CfRevertPlaceholder
@ stub CfSetAppPolicy
@ stub CfSetCorrelationVector
@ stub CfSetInSyncState
@ stub CfSetPinState
@ stub CfStoreProperties
@ stub CfTestToggleSyncMsgThreadWaitEvent
@ stub CfUnlockProperties
@ stub CfUnregisterSyncRoot
@ stub CfUpdatePlaceholder
@ stub CfUpdateSyncProviderStatus
