1 stub GetUnIsoRegionCode
@ stub AppendUserLanguageInputMethods
@ stub AppendUserLanguageInternal
@ stub AppendUserLanguages
@ stub Bcp47BufferFromLcid
@ stub Bcp47FindClosestLanguage
@ stub Bcp47FromCompactTagInternal
@ stub Bcp47FromHkl
@ stub Bcp47FromLcid
@ stub Bcp47GetAbbreviation
@ stub Bcp47GetDirectionality
@ stub Bcp47GetDistance
@ stub Bcp47GetExtensionSingletons
@ stub Bcp47GetExtensionSubstring
@ stub Bcp47GetIsoLanguageCode
@ stub Bcp47GetIsoScriptCode
@ stub Bcp47GetLanguageName
@ stub Bcp47GetMuiForm
@ stub Bcp47GetNeutralForm
@ stub Bcp47GetNlsForm
@ stub Bcp47GetSubtagMapInternal
@ stub Bcp47GetUnIsoRegionCode
@ stub Bcp47IsWellFormed
@ stub Bcp47Normalize
@ stub ClearApplicationLanguageOverride
@ stub ClearApplicationManifestLanguages
@ stub ClearHttpAcceptLanguageOptOut
@ stub ClearUserDisplayLanguageOverride
@ stub ClearUserLocaleFromLanguageProfileOptOut
@ stub CompactTagFromBcp47Internal
@ stub DllGetActivationFactory
@ stub DllGetClassObject
@ stub GetApplicationLanguageOverride
@ stub GetApplicationLanguages
@ stub GetApplicationManifestLanguages
@ stub GetAppropriateUserLocaleForUserLanguages
@ stub GetAppropriateUserPreferredAndDisplayLanguagesForUser
@ stub GetClosestMatchingUserLanguage
@ stub GetDisplayLanguagesForAllUsers
@ stdcall GetFontFallbackLanguageList(wstr long ptr ptr)
@ stub GetHttpAcceptLanguageOptOut
@ stub GetInputMethodOverrideForUser
@ stub GetPendingUserDisplayLanguage
@ stub GetRelevantLocalesFromLanguageTags
@ stub GetSerializedUserLanguageProfile
@ stub GetSerializedUserLanguagesForUser
@ stub GetStartingUserDisplayLanguage
@ stub GetUserDisplayLanguageOverride
@ stub GetUserLanguageInputMethods
@ stub GetUserLanguageInputMethodsForUser
@ stub GetUserLanguages
@ stub GetUserLanguagesForAllUsers
@ stub GetUserLanguagesForUser
@ stub GetUserLocaleFromLanguageProfileOptOut
@ stub IsTransientLcid
@ stub LanguageListAsMuiForm
@ stub LcidFromBcp47
@ stub RemoveInputsForAllLanguagesInternal
@ stub RemoveUserLanguageInputMethods
@ stub ResolveLanguages
@ stub SetApplicationLanguageOverride
@ stub SetApplicationManifestLanguages
@ stub SetHttpAcceptLanguageOptOut
@ stub SetInputMethodOverride
@ stub SetPreviousUserDisplayLanguages
@ stub SetStartingUserDisplayLanguage
@ stub SetUserDisplayLanguageOverride
@ stub SetUserLanguageInputMethods
@ stub SetUserLanguagesInternal
@ stub SetUserLanguagesInternalCore
@ stub SetUserLocaleFromLanguageProfileOptOut
