@ stub SLpAuthenticateGenuineTicketResponse
@ stub SLpBeginGenuineTicketTransaction
@ stub SLpCheckProductKey
@ stub SLpGetGenuineBlob
@ stub SLpGetGenuineLocal
@ stub SLpGetLicenseAcquisitionInfo
@ stub SLpGetMachineUGUID
@ stub SLpVLActivateProduct
@ stdcall SLClose(ptr)
@ stub SLConsumeRight
@ stub SLConsumeWindowsRight
@ stub SLDepositOfflineConfirmationId
@ stub SLFireEvent
@ stub SLGenerateOfflineInstallationId
@ stub SLGetInstalledSAMLicenseApplications
@ stub SLGetLicense
@ stub SLGetLicenseFileId
@ stub SLGetLicenseInformation
@ stdcall SLGetLicensingStatusInformation(ptr ptr ptr wstr ptr ptr)
@ stub SLGetPKeyId
@ stub SLGetPKeyInformation
@ stub SLGetPolicyInformation
@ stub SLGetPolicyInformationDWORD
@ stub SLGetProductSkuInformation
@ stub SLGetSAMLicense
@ stub SLGetSLIDList
@ stub SLGetServiceInformation
@ stdcall SLGetWindowsInformation(wstr ptr ptr ptr)
@ stdcall SLGetWindowsInformationDWORD(wstr ptr)
@ stub SLInstallLicense
@ stub SLInstallProofOfPurchase
@ stub SLInstallSAMLicense
@ stdcall SLOpen(ptr)
@ stub SLReArmWindows
@ stub SLRegisterEvent
@ stub SLRegisterWindowsEvent
@ stub SLUninstallLicense
@ stub SLUninstallProofOfPurchase
@ stub SLUninstallSAMLicense
@ stub SLUnregisterEvent
@ stub SLUnregisterWindowsEvent
