apiset api-ms-win-appmodel-runtime-internal-l1-1-1 = kernelbase.dll
apiset api-ms-win-appmodel-runtime-l1-1-2 = kernelbase.dll
apiset api-ms-win-audiocore-spatial-config-l1-1-0 = windows.media.devices.dll
apiset api-ms-win-base-bootconfig-l1-1-0 = advapi32.dll
apiset api-ms-win-base-util-l1-1-0 = advapi32.dll
apiset api-ms-win-core-apiquery-l1-1-0 = ntdll.dll
apiset api-ms-win-core-apiquery-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-appcompat-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-appinit-l1-1-0 = kernel32.dll
apiset api-ms-win-core-atoms-l1-1-0 = kernel32.dll
apiset api-ms-win-core-backgroundtask-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-biplmapi-l1-1-5 = twinapi.appcore.dll
apiset api-ms-win-core-biplmapi-l1-2-0 = twinapi.appcore.dll
apiset api-ms-win-core-biptcltapi-l1-1-7 = twinapi.appcore.dll
apiset api-ms-win-core-calendar-l1-1-0 = kernel32.dll
apiset api-ms-win-core-com-l1-1-1 = combase.dll
apiset api-ms-win-core-com-l2-1-1 = coml2.dll
apiset api-ms-win-core-com-midlproxystub-l1-1-0 = combase.dll
apiset api-ms-win-core-com-private-l1-1-0 = combase.dll
apiset api-ms-win-core-com-private-l1-2-0 = combase.dll
apiset api-ms-win-core-com-private-l1-3-0 = combase.dll
apiset api-ms-win-core-comm-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-commandlinetoargv-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-console-ansi-l2-1-0 = kernel32.dll
apiset api-ms-win-core-console-internal-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-console-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-console-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-console-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-console-l2-2-0 = kernelbase.dll
apiset api-ms-win-core-console-l3-1-0 = kernelbase.dll
apiset api-ms-win-core-console-l3-2-0 = kernelbase.dll
apiset api-ms-win-core-crt-l1-1-0 = msvcrt.dll
apiset api-ms-win-core-crt-l2-1-0 = msvcrt.dll
apiset api-ms-win-core-datetime-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-debug-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-delayload-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-enclave-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-errorhandling-l1-1-3 = kernelbase.dll
apiset api-ms-win-core-featurestaging-l1-1-0 = shcore.dll
apiset api-ms-win-core-fibers-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-fibers-l2-1-1 = kernelbase.dll
apiset api-ms-win-core-file-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-file-ansi-l2-1-0 = kernel32.dll
apiset api-ms-win-core-file-fromapp-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-file-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-file-l1-2-2 = kernelbase.dll
apiset api-ms-win-core-file-l2-1-2 = kernelbase.dll
apiset api-ms-win-core-firmware-l1-1-0 = kernel32.dll
apiset api-ms-win-core-guard-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-handle-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-heap-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-heap-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-heap-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-heap-obsolete-l1-1-0 = kernel32.dll
apiset api-ms-win-core-interlocked-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-interlocked-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-io-l1-1-1 = kernel32.dll
apiset api-ms-win-core-ioring-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-job-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-job-l2-1-0 = kernel32.dll
apiset api-ms-win-core-kernel32-legacy-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-kernel32-legacy-l1-1-5 = kernel32.dll
apiset api-ms-win-core-kernel32-private-l1-1-2 = kernel32.dll
apiset api-ms-win-core-kernel32-private-l1-2-0 = kernel32.dll
apiset api-ms-win-core-largeinteger-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-libraryloader-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-libraryloader-l1-2-2 = kernelbase.dll
apiset api-ms-win-core-libraryloader-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-libraryloader-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-localization-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-localization-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-localization-l1-2-2 = kernelbase.dll
apiset api-ms-win-core-localization-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-localization-obsolete-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-localization-obsolete-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-localization-obsolete-l1-3-0 = kernelbase.dll
apiset api-ms-win-core-localization-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-localregistry-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-marshal-l1-1-0 = combase.dll
apiset api-ms-win-core-memory-l1-1-4 = kernelbase.dll
apiset api-ms-win-core-misc-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-multipleproviderrouter-l1-1-0 = mpr.dll
apiset api-ms-win-core-namedpipe-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-namedpipe-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-namedpipe-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-namespace-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-namespace-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-normalization-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-path-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-pcw-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-perfcounters-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-perfcounters-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-perfstm-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-privateprofile-l1-1-1 = kernel32.dll
apiset api-ms-win-core-processenvironment-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-processenvironment-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-processenvironment-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-processsecurity-l1-1-0 = kernel32.dll
apiset api-ms-win-core-processsnapshot-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-processthreads-l1-1-3 = kernel32.dll
apiset api-ms-win-core-processtopology-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-processtopology-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-processtopology-obsolete-l1-1-0 = kernel32.dll
apiset api-ms-win-core-processtopology-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-profile-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-psapi-ansi-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-psapi-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-psapi-obsolete-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-psapiansi-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-psm-app-l1-1-0 = twinapi.appcore.dll
apiset api-ms-win-core-psm-appnotify-l1-1-0 = twinapi.appcore.dll
apiset api-ms-win-core-psm-key-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-psm-plm-l1-1-3 = twinapi.appcore.dll
apiset api-ms-win-core-psm-plm-l1-2-0 = twinapi.appcore.dll
apiset api-ms-win-core-psm-plm-l1-3-0 = twinapi.appcore.dll
apiset api-ms-win-core-psm-rtimer-l1-1-1 = twinapi.appcore.dll
apiset api-ms-win-core-psm-tc-l1-1-1 = twinapi.appcore.dll
apiset api-ms-win-core-quirks-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-realtime-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-registry-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-registry-l2-1-0 = advapi32.dll
apiset api-ms-win-core-registry-l2-2-0 = advapi32.dll
apiset api-ms-win-core-registry-l2-3-0 = advapi32.dll
apiset api-ms-win-core-registry-private-l1-1-0 = advapi32.dll
apiset api-ms-win-core-registryuserspecific-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-rtlsupport-l1-1-0 = ntdll.dll
apiset api-ms-win-core-rtlsupport-l1-2-0 = ntdll.dll
apiset api-ms-win-core-shlwapi-legacy-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-shlwapi-obsolete-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-shlwapi-obsolete-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-shutdown-ansi-l1-1-0 = advapi32.dll
apiset api-ms-win-core-shutdown-l1-1-0 = advapi32.dll
apiset api-ms-win-core-sidebyside-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-sidebyside-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-slapi-l1-1-0 = slc.dll
apiset api-ms-win-core-state-helpers-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-string-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-string-l2-1-0 = kernelbase.dll
apiset api-ms-win-core-string-obsolete-l1-1-0 = kernel32.dll
apiset api-ms-win-core-stringansi-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-stringloader-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-synch-ansi-l1-1-0 = kernel32.dll
apiset api-ms-win-core-synch-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-synch-l1-2-1 = kernelbase.dll
apiset api-ms-win-core-sysinfo-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-sysinfo-l1-2-1 = kernelbase.dll
apiset api-ms-win-core-sysinfo-l2-1-0 = advapi32.dll
apiset api-ms-win-core-systemtopology-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-threadpool-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-threadpool-l1-2-0 = kernelbase.dll
apiset api-ms-win-core-threadpool-legacy-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-threadpool-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-timezone-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-timezone-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-toolhelp-l1-1-0 = kernel32.dll
apiset api-ms-win-core-ums-l1-1-0 = kernel32.dll
apiset api-ms-win-core-url-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-util-l1-1-0 = kernel32.dll
apiset api-ms-win-core-version-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-version-private-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-versionansi-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-windowsceip-l1-1-0 = kernelbase.dll
apiset api-ms-win-core-windowserrorreporting-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-winrt-error-l1-1-1 = combase.dll
apiset api-ms-win-core-winrt-errorprivate-l1-1-1 = combase.dll
apiset api-ms-win-core-winrt-l1-1-0 = combase.dll
apiset api-ms-win-core-winrt-propertysetprivate-l1-1-1 = wintypes.dll
apiset api-ms-win-core-winrt-registration-l1-1-0 = combase.dll
apiset api-ms-win-core-winrt-robuffer-l1-1-0 = wintypes.dll
apiset api-ms-win-core-winrt-roparameterizediid-l1-1-0 = combase.dll
apiset api-ms-win-core-winrt-string-l1-1-1 = combase.dll
apiset api-ms-win-core-wow64-l1-1-1 = kernelbase.dll
apiset api-ms-win-core-xstate-l1-1-0 = ntdll.dll
apiset api-ms-win-core-xstate-l2-1-0 = kernelbase.dll
apiset api-ms-win-crt-conio-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-convert-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-environment-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-filesystem-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-heap-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-locale-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-math-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-multibyte-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-private-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-process-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-runtime-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-stdio-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-string-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-time-l1-1-0 = ucrtbase.dll
apiset api-ms-win-crt-utility-l1-1-0 = ucrtbase.dll
apiset api-ms-win-deprecated-apis-advapi-l1-1-0 =
apiset api-ms-win-deprecated-apis-legacy-l1-1-0 =
apiset api-ms-win-deprecated-apis-legacy-l1-2-0 =
apiset api-ms-win-deprecated-apis-obsolete-l1-1-0 = kernelbase.dll
apiset api-ms-win-devices-config-l1-1-1 = cfgmgr32.dll
apiset api-ms-win-devices-query-l1-1-1 = cfgmgr32.dll
apiset api-ms-win-devices-swdevice-l1-1-1 = cfgmgr32.dll
apiset api-ms-win-downlevel-advapi32-l1-1-0 = kernelbase.dll
apiset api-ms-win-downlevel-advapi32-l2-1-0 = sechost.dll
apiset api-ms-win-downlevel-advapi32-l4-1-0 = advapi32.dll
apiset api-ms-win-downlevel-kernel32-l1-1-0 = kernelbase.dll
apiset api-ms-win-downlevel-kernel32-l2-1-0 = kernel32.dll
apiset api-ms-win-downlevel-normaliz-l1-1-0 = kernelbase.dll
apiset api-ms-win-downlevel-ole32-l1-1-0 = combase.dll
apiset api-ms-win-downlevel-shell32-l1-1-0 = shcore.dll
apiset api-ms-win-downlevel-shlwapi-l1-1-0 = kernelbase.dll
apiset api-ms-win-downlevel-shlwapi-l2-1-0 = shcore.dll
apiset api-ms-win-downlevel-user32-l1-1-0 = kernelbase.dll
apiset api-ms-win-downlevel-version-l1-1-0 = kernelbase.dll
apiset api-ms-win-dwmapi-l1-1-0 = dwmapi.dll
apiset api-ms-win-dx-d3dkmt-l1-1-0 = gdi32.dll
apiset api-ms-win-eventing-classicprovider-l1-1-0 = kernelbase.dll
apiset api-ms-win-eventing-consumer-l1-1-0 = sechost.dll
apiset api-ms-win-eventing-controller-l1-1-0 = sechost.dll
apiset api-ms-win-eventing-legacy-l1-1-0 = advapi32.dll
apiset api-ms-win-eventing-obsolete-l1-1-0 = sechost.dll
apiset api-ms-win-eventing-provider-l1-1-0 = kernelbase.dll
apiset api-ms-win-eventing-tdh-l1-1-2 = tdh.dll
apiset api-ms-win-eventlog-legacy-l1-1-0 = advapi32.dll
apiset api-ms-win-eventlog-private-l1-1-0 = advapi32.dll
apiset api-ms-win-gaming-deviceinformation-l1-1-0 = kernelbase.dll
apiset api-ms-win-gaming-tcui-l1-1-0 = gamingtcui.dll
apiset api-ms-win-gdi-dpiinfo-l1-1-0 = gdi32.dll
apiset api-ms-win-http-time-l1-1-0 = kernelbase.dll
apiset api-ms-win-input-ie-interactioncontext-l1-1-0 =
apiset api-ms-win-legacy-shlwapi-l1-1-0 = kernelbase.dll
apiset api-ms-win-mm-joystick-l1-1-0 = winmm.dll
apiset api-ms-win-mm-mci-l1-1-0 = winmm.dll
apiset api-ms-win-mm-misc-l1-1-1 = winmm.dll
apiset api-ms-win-mm-misc-l2-1-0 = winmm.dll
apiset api-ms-win-mm-mme-l1-1-0 = winmm.dll
apiset api-ms-win-mm-playsound-l1-1-0 = winmm.dll
apiset api-ms-win-mm-time-l1-1-0 = winmm.dll
apiset api-ms-win-ntuser-dc-access-l1-1-0 = user32.dll
apiset api-ms-win-ntuser-ie-message-l1-1-0 = user32.dll
apiset api-ms-win-ntuser-ie-window-l1-1-0 = user32.dll
apiset api-ms-win-ntuser-ie-wmpointer-l1-1-0 = user32.dll
apiset api-ms-win-ntuser-rectangle-l1-1-0 = user32.dll
apiset api-ms-win-ntuser-sysparams-l1-1-0 = user32.dll
apiset api-ms-win-obsolete-localization-l1-1-0 = kernelbase.dll
apiset api-ms-win-obsolete-psapi-l1-1-0 = kernelbase.dll
apiset api-ms-win-obsolete-shlwapi-l1-1-0 = kernelbase.dll
apiset api-ms-win-ole32-ie-l1-1-0 = ole32.dll
apiset api-ms-win-oobe-notification-l1-1-0 = kernel32.dll
apiset api-ms-win-perf-legacy-l1-1-0 = advapi32.dll
apiset api-ms-win-power-base-l1-1-0 = powrprof.dll
apiset api-ms-win-power-limitsmanagement-l1-1-0 = powrprof.dll
apiset api-ms-win-power-setting-l1-1-0 = powrprof.dll
apiset api-ms-win-ro-typeresolution-l1-1-1 = wintypes.dll
apiset api-ms-win-rtcore-minuser-private-l1-1-1 =
apiset api-ms-win-rtcore-navigation-l1-1-0 =
apiset api-ms-win-rtcore-ntuser-clipboard-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-draw-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-powermanagement-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-private-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-shell-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-synch-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-window-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-winevent-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-wmpointer-l1-1-0 = user32.dll
apiset api-ms-win-rtcore-ntuser-wmpointer-l1-2-0 = user32.dll
apiset api-ms-win-rtcore-ole32-clipboard-l1-1-0 = ole32.dll
apiset api-ms-win-rtcore-session-l1-1-0 =
apiset api-ms-win-security-accesshlpr-l1-1-0 = sechost.dll
apiset api-ms-win-security-activedirectoryclient-l1-1-0 = ntdsapi.dll
apiset api-ms-win-security-appcontainer-l1-1-0 = kernelbase.dll
apiset api-ms-win-security-audit-l1-1-1 = sechost.dll
apiset api-ms-win-security-base-ansi-l1-1-0 = advapi32.dll
apiset api-ms-win-security-base-l1-1-0 = kernelbase.dll
apiset api-ms-win-security-base-l1-2-0 = kernelbase.dll
apiset api-ms-win-security-base-private-l1-1-1 = kernelbase.dll
apiset api-ms-win-security-capability-l1-1-0 = sechost.dll
apiset api-ms-win-security-cpwl-l1-1-0 = advapi32.dll
apiset api-ms-win-security-credentials-l1-1-0 = sechost.dll
apiset api-ms-win-security-credentials-l2-1-0 = sechost.dll
apiset api-ms-win-security-cryptoapi-l1-1-0 = cryptsp.dll
apiset api-ms-win-security-grouppolicy-l1-1-0 = kernelbase.dll
apiset api-ms-win-security-isolatedcontainer-l1-1-1 = shcore.dll
apiset api-ms-win-security-isolationapi-l1-1-0 = sechost.dll
apiset api-ms-win-security-isolationapi-l1-2-0 = sechost.dll
apiset api-ms-win-security-isolationpolicy-l1-1-0 = sechost.dll
apiset api-ms-win-security-isolationpolicy-l1-2-0 = sechost.dll
apiset api-ms-win-security-logon-l1-1-1 = advapi32.dll
apiset api-ms-win-security-lsalookup-ansi-l2-1-0 = advapi32.dll
apiset api-ms-win-security-lsalookup-l1-1-1 = sechost.dll
apiset api-ms-win-security-lsalookup-l2-1-1 = advapi32.dll
apiset api-ms-win-security-lsapolicy-l1-1-0 = sechost.dll
apiset api-ms-win-security-provider-ansi-l1-1-0 = advapi32.dll
apiset api-ms-win-security-provider-l1-1-0 = advapi32.dll
apiset api-ms-win-security-sddl-ansi-l1-1-0 = advapi32.dll
apiset api-ms-win-security-sddl-l1-1-0 = sechost.dll
apiset api-ms-win-security-sddl-private-l1-1-0 = sechost.dll
apiset api-ms-win-security-sddlparsecond-l1-1-0 = sechost.dll
apiset api-ms-win-security-systemfunctions-l1-1-0 = advapi32.dll
apiset api-ms-win-security-trustee-l1-1-1 = advapi32.dll
apiset api-ms-win-service-core-ansi-l1-1-0 = advapi32.dll
apiset api-ms-win-service-core-l1-1-1 = sechost.dll
apiset api-ms-win-service-legacy-l1-1-0 = advapi32.dll
apiset api-ms-win-service-management-l1-1-0 = sechost.dll
apiset api-ms-win-service-management-l2-1-0 = sechost.dll
apiset api-ms-win-service-private-l1-1-1 = sechost.dll
apiset api-ms-win-service-private-l1-2-0 = sechost.dll
apiset api-ms-win-service-winsvc-l1-1-0 = sechost.dll
apiset api-ms-win-service-winsvc-l1-2-0 = sechost.dll
apiset api-ms-win-shcore-comhelpers-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-obsolete-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-path-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-registry-l1-1-1 = shcore.dll
apiset api-ms-win-shcore-scaling-l1-1-1 = shcore.dll
apiset api-ms-win-shcore-stream-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-stream-winrt-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-sysinfo-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-taskpool-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-thread-l1-1-0 = shcore.dll
apiset api-ms-win-shcore-unicodeansi-l1-1-0 = shcore.dll
apiset api-ms-win-shell-associations-l1-1-3 = windows.storage.dll
apiset api-ms-win-shell-changenotify-l1-1-1 = windows.storage.dll
apiset api-ms-win-shell-dataobject-l1-1-1 = windows.storage.dll
apiset api-ms-win-shell-namespace-l1-1-1 = windows.storage.dll
apiset api-ms-win-shell-shdirectory-l1-1-0 = shcore.dll
apiset api-ms-win-shell-shell32legacy-shdirectory-l1-1-0 =
apiset api-ms-win-shell-shellcom-l1-1-0 = shell32.dll
apiset api-ms-win-shell-shellfolders-l1-1-0 = windows.storage.dll
apiset api-ms-win-shlwapi-ie-l1-1-0 = shlwapi.dll
apiset api-ms-win-shlwapi-winrt-storage-l1-1-1 = shlwapi.dll
apiset api-ms-win-stateseparation-helpers-l1-1-0 = kernelbase.dll
apiset api-ms-win-storage-exports-external-l1-1-2 = windows.storage.dll
apiset api-ms-win-storage-exports-internal-l1-1-0 = windows.storage.dll
apiset ext-ms-mf-pal-l2-1-1 =
apiset ext-ms-onecore-appchromeapi-l1-1-0 =
apiset ext-ms-onecore-appdefaults-l1-1-0 = windows.storage.dll
apiset ext-ms-onecore-appmodel-deployment-internal-l1-1-0 = appxdeploymentclient.dll
apiset ext-ms-onecore-appmodel-emclient-l1-1-0 =
apiset ext-ms-onecore-appmodel-emsvcs-l1-1-0 =
apiset ext-ms-onecore-appmodel-pacmanclient-l1-1-0 =
apiset ext-ms-onecore-comp-dwmmonitor-l1-1-0 =
apiset ext-ms-onecore-dcomp-l1-1-0 = dcomp.dll
apiset ext-ms-onecore-defaultdiscovery-l1-1-0 =
apiset ext-ms-onecore-hcap-svf-l1-1-0 =
apiset ext-ms-onecore-hlink-l1-1-0 = hlink.dll
apiset ext-ms-onecore-mpc-input-l1-1-0 =
apiset ext-ms-onecore-orientation-l1-1-0 =
apiset ext-ms-onecore-shellchromeapi-l1-1-2 =
apiset ext-ms-onecore-shellremindersapi-l1-1-0 =
apiset ext-ms-onecore-shlwapi-l1-1-0 = shlwapi.dll
apiset ext-ms-win-adsi-activeds-l1-1-0 = activeds.dll
apiset ext-ms-win-advapi32-auth-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-encryptedfile-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-eventingcontroller-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-eventlog-ansi-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-eventlog-l1-1-1 = advapi32.dll
apiset ext-ms-win-advapi32-hwprof-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-idletask-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-lsa-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-msi-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-npusername-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-ntmarta-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-psm-app-l1-1-0 = twinapi.appcore.dll
apiset ext-ms-win-advapi32-registry-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-safer-l1-1-0 = advapi32.dll
apiset ext-ms-win-advapi32-shutdown-l1-1-0 = advapi32.dll
apiset ext-ms-win-appcompat-apphelp-l1-1-2 = apphelp.dll
apiset ext-ms-win-appmodel-appcontainerpath-l1-1-0 =
apiset ext-ms-win-appmodel-datasharingservice-extensions-l1-1-0 =
apiset ext-ms-win-appmodel-deployment-l1-1-1 =
apiset ext-ms-win-appmodel-deploymentvolumes-l1-1-1 =
apiset ext-ms-win-appmodel-opc-l1-1-0 = opcservices.dll
apiset ext-ms-win-appmodel-shellexecute-l1-1-0 = windows.storage.dll
apiset ext-ms-win-appmodel-usercontext-l1-1-0 =
apiset ext-ms-win-appmodel-viewscalefactor-l1-1-0 =
apiset ext-ms-win-audio-spatial-systemsound-l1-1-0 =
apiset ext-ms-win-audiocore-pal-l1-2-0 =
apiset ext-ms-win-audiocore-policymanager-l1-1-1 =
apiset ext-ms-win-audiocore-spatial-l1-1-0 =
apiset ext-ms-win-authz-claimpolicies-l1-1-0 = authz.dll
apiset ext-ms-win-authz-context-l1-1-0 = authz.dll
apiset ext-ms-win-base-psapi-l1-1-0 = psapi.dll
apiset ext-ms-win-base-rstrtmgr-l1-1-0 = rstrtmgr.dll
apiset ext-ms-win-bluetooth-apis-internal-l1-1-0 = bluetoothapis.dll
apiset ext-ms-win-bluetooth-apis-l1-1-0 = bluetoothapis.dll
apiset ext-ms-win-bluetooth-apis-private-l1-1-0 = bluetoothapis.dll
apiset ext-ms-win-casting-device-l1-1-0 =
apiset ext-ms-win-ci-xbox-l1-1-0 =
apiset ext-ms-win-cloudap-tbal-l1-1-0 =
apiset ext-ms-win-clouddomainjoin-usermanagement-l1-1-0 =
apiset ext-ms-win-cluster-clusapi-l1-1-5 = clusapi.dll
apiset ext-ms-win-cluster-resutils-l1-1-3 = resutils.dll
apiset ext-ms-win-cng-rng-l1-1-1 = bcryptprimitives.dll
apiset ext-ms-win-com-apartmentrestriction-l1-1-0 =
apiset ext-ms-win-com-coml2-l1-1-1 = coml2.dll
apiset ext-ms-win-com-ole32-l1-1-3 = ole32.dll
apiset ext-ms-win-com-ole32-l1-2-0 = ole32.dll
apiset ext-ms-win-com-ole32-l1-3-0 = ole32.dll
apiset ext-ms-win-com-ole32-l1-4-0 = ole32.dll
apiset ext-ms-win-com-sta-l1-1-0 = ole32.dll
apiset ext-ms-win-com-suspendresiliency-l1-1-0 =
apiset ext-ms-win-composition-holographic-l1-1-0 =
apiset ext-ms-win-compositor-hosting-l1-1-0 = user32.dll
apiset ext-ms-win-containers-policymanagercli-l1-1-1 =
apiset ext-ms-win-core-app-package-registration-l1-1-1 =
apiset ext-ms-win-core-app-package-volume-l1-1-0 =
apiset ext-ms-win-core-container-init-l1-1-0 =
apiset ext-ms-win-core-dhcp6client-l1-1-0 =
apiset ext-ms-win-core-iuri-l1-1-0 = urlmon.dll
apiset ext-ms-win-core-licensemanager-l1-1-2 =
apiset ext-ms-win-core-marshal-l2-1-0 = ole32.dll
apiset ext-ms-win-core-psm-extendedresourcemode-l1-1-0 =
apiset ext-ms-win-core-stateseparationext-l1-1-0 =
apiset ext-ms-win-core-winrt-remote-l1-1-0 =
apiset ext-ms-win-core-winsrv-min-l1-1-0 =
apiset ext-ms-win-core-xbrm-l1-1-1 =
apiset ext-ms-win-coreui-l1-1-0 =
apiset ext-ms-win-crypto-xbox-l1-1-0 =
apiset ext-ms-win-drvinst-desktop-l1-1-0 = newdev.dll
apiset ext-ms-win-dwmapi-ext-l1-1-0 = dwmapi.dll
apiset ext-ms-win-dwmapidxgi-ext-l1-1-1 = dwmapi.dll
apiset ext-ms-win-dx-d3d9-l1-1-0 = d3d9.dll
apiset ext-ms-win-dx-d3dkmt-dxcore-l1-1-3 = dxcore.dll
apiset ext-ms-win-dx-d3dkmt-gdi-l1-1-0 = gdi32.dll
apiset ext-ms-win-dx-ddraw-l1-1-0 = ddraw.dll
apiset ext-ms-win-dx-dinput8-l1-1-0 = dinput8.dll
apiset ext-ms-win-dxcore-internal-l1-1-0 = dxcore.dll
apiset ext-ms-win-dxcore-l1-1-0 = dxcore.dll
apiset ext-ms-win-eventing-pdh-l1-1-2 = pdh.dll
apiset ext-ms-win-eventing-tdh-ext-l1-1-0 = tdh.dll
apiset ext-ms-win-eventing-tdh-priv-l1-1-0 = tdh.dll
apiset ext-ms-win-feclient-encryptedfile-l1-1-3 = feclient.dll
apiset ext-ms-win-fs-vssapi-l1-1-0 = vssapi.dll
apiset ext-ms-win-gaming-devicefamily-l1-1-0 =
apiset ext-ms-win-gaming-xinput-l1-1-0 = xinputuap.dll
apiset ext-ms-win-gdi-clipping-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-dc-create-l1-1-1 = gdi32.dll
apiset ext-ms-win-gdi-dc-l1-2-0 = gdi32.dll
apiset ext-ms-win-gdi-devcaps-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-draw-l1-1-1 = gdi32.dll
apiset ext-ms-win-gdi-edgegdi-l1-1-0 =
apiset ext-ms-win-gdi-font-l1-1-1 = gdi32.dll
apiset ext-ms-win-gdi-gdiplus-l1-1-0 = gdiplus.dll
apiset ext-ms-win-gdi-internal-desktop-l1-1-4 = gdi32.dll
apiset ext-ms-win-gdi-internal-uap-init-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-metafile-l1-1-2 = gdi32.dll
apiset ext-ms-win-gdi-path-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-print-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-private-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-render-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-rgn-l1-1-0 = gdi32.dll
apiset ext-ms-win-gdi-wcs-l1-1-0 = gdi32.dll
apiset ext-ms-win-hcihealth-utils-l1-1-0 =
apiset ext-ms-win-hyperv-compute-l1-1-1 =
apiset ext-ms-win-hyperv-compute-l1-2-4 =
apiset ext-ms-win-hyperv-computenetwork-l1-1-1 =
apiset ext-ms-win-hyperv-computestorage-l1-1-1 =
apiset ext-ms-win-hyperv-devicevirtualization-l1-1-1 =
apiset ext-ms-win-hyperv-devicevirtualization-l1-2-2 =
apiset ext-ms-win-hyperv-hgs-l1-1-0 =
apiset ext-ms-win-hyperv-hvemulation-l1-1-0 =
apiset ext-ms-win-hyperv-hvplatform-l1-1-5 =
apiset ext-ms-win-ie-textinput-l1-1-0 =
apiset ext-ms-win-imm-l1-1-2 = imm32.dll
apiset ext-ms-win-kernel32-appcompat-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-datetime-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-elevation-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-errorhandling-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-file-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-localization-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-package-current-l1-1-0 = kernelbase.dll
apiset ext-ms-win-kernel32-package-l1-1-1 = kernelbase.dll
apiset ext-ms-win-kernel32-process-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-quirks-l1-1-1 = kernel32.dll
apiset ext-ms-win-kernel32-registry-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-sidebyside-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-transacted-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-updateresource-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernel32-windowserrorreporting-l1-1-1 = kernel32.dll
apiset ext-ms-win-kernelbase-processthread-l1-1-0 = kernel32.dll
apiset ext-ms-win-kernelbase-processthread-l1-2-0 = kernel32.dll
apiset ext-ms-win-kioskmode-config-l1-1-0 =
apiset ext-ms-win-mapi-mapi32-l1-1-0 = mapistub.dll
apiset ext-ms-win-media-avi-l1-1-0 = avifil32.dll
apiset ext-ms-win-media-codecpack-mounting-l1-1-0 =
apiset ext-ms-win-mf-devicespecific-l1-1-0 =
apiset ext-ms-win-mf-vfw-l1-1-0 =
apiset ext-ms-win-mininput-extensions-l1-1-0 =
apiset ext-ms-win-mm-msacm-l1-1-0 = msacm32.dll
apiset ext-ms-win-mm-pehelper-l1-1-0 = mf.dll
apiset ext-ms-win-mm-wmvcore-l1-1-0 = wmvcore.dll
apiset ext-ms-win-msa-device-l1-1-0 =
apiset ext-ms-win-msi-misc-l1-1-0 = msi.dll
apiset ext-ms-win-msimg-draw-l1-1-0 = msimg32.dll
apiset ext-ms-win-net-vpn-l1-1-0 =
apiset ext-ms-win-networking-iphlpsvc-l1-1-0 =
apiset ext-ms-win-networking-mpssvc-l1-1-0 =
apiset ext-ms-win-networking-ncsiuserprobe-l1-1-0 =
apiset ext-ms-win-networking-teredo-l1-1-0 = windows.networking.connectivity.dll
apiset ext-ms-win-networking-wlanapi-l1-1-0 = wlanapi.dll
apiset ext-ms-win-networking-wlanstorage-l1-1-0 =
apiset ext-ms-win-networking-xblconnectivity-l1-1-0 =
apiset ext-ms-win-newdev-config-l1-1-2 = newdev.dll
apiset ext-ms-win-ntdsapi-activedirectoryclient-l1-1-1 = ntdsapi.dll
apiset ext-ms-win-ntuser-caret-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-chartranslation-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-dc-access-ext-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-dde-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-dialogbox-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-draw-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-gui-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-gui-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-gui-l1-3-0 = user32.dll
apiset ext-ms-win-ntuser-keyboard-ansi-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-keyboard-l1-1-1 = user32.dll
apiset ext-ms-win-ntuser-keyboard-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-keyboard-l1-3-0 = user32.dll
apiset ext-ms-win-ntuser-menu-l1-1-2 = user32.dll
apiset ext-ms-win-ntuser-message-l1-1-1 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-3-0 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-5-1 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-6-0 = user32.dll
apiset ext-ms-win-ntuser-misc-l1-7-0 = user32.dll
apiset ext-ms-win-ntuser-mit-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-mouse-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-powermanagement-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-private-l1-1-1 = user32.dll
apiset ext-ms-win-ntuser-private-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-private-l1-3-3 = user32.dll
apiset ext-ms-win-ntuser-private-l1-4-0 = user32.dll
apiset ext-ms-win-ntuser-private-l1-5-0 = user32.dll
apiset ext-ms-win-ntuser-private-l1-6-0 = user32.dll
apiset ext-ms-win-ntuser-rawinput-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-rawinput-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-rectangle-ext-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-rim-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-rim-l1-2-0 = user32.dll
apiset ext-ms-win-ntuser-rotationmanager-l1-1-1 = user32.dll
apiset ext-ms-win-ntuser-server-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-string-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-synch-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-sysparams-ext-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-touch-hittest-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-uicontext-ext-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-window-l1-1-4 = user32.dll
apiset ext-ms-win-ntuser-windowclass-l1-1-1 = user32.dll
apiset ext-ms-win-ntuser-windowstation-ansi-l1-1-0 = user32.dll
apiset ext-ms-win-ntuser-windowstation-l1-1-1 = user32.dll
apiset ext-ms-win-odbc-odbc32-l1-1-0 = odbc32.dll
apiset ext-ms-win-ole32-bindctx-l1-1-0 = ole32.dll
apiset ext-ms-win-ole32-ie-ext-l1-1-0 = ole32.dll
apiset ext-ms-win-ole32-oleautomation-l1-1-0 = ole32.dll
apiset ext-ms-win-oleacc-l1-1-0 = oleacc.dll
apiset ext-ms-win-onecore-shutdown-l1-1-0 = twinapi.appcore.dll
apiset ext-ms-win-oobe-query-l1-1-0 =
apiset ext-ms-win-perception-device-l1-1-1 =
apiset ext-ms-win-printer-prntvpt-l1-1-2 = prntvpt.dll
apiset ext-ms-win-printer-winspool-core-l1-1-0 = winspool.drv
apiset ext-ms-win-printer-winspool-l1-1-4 = winspool.drv
apiset ext-ms-win-printer-winspool-l1-2-0 = winspool.drv
apiset ext-ms-win-profile-extender-l1-1-0 = userenv.dll
apiset ext-ms-win-profile-load-l1-1-0 =
apiset ext-ms-win-ras-rasapi32-l1-1-0 = rasapi32.dll
apiset ext-ms-win-ras-rasdlg-l1-1-0 = rasdlg.dll
apiset ext-ms-win-ras-tapi32-l1-1-1 = tapi32.dll
apiset ext-ms-win-remotewipe-platform-l1-1-0 =
apiset ext-ms-win-ro-typeresolution-l1-1-1 = wintypes.dll
apiset ext-ms-win-rometadata-dispenser-l1-1-0 = rometadata.dll
apiset ext-ms-win-rtcore-gdi-devcaps-l1-1-0 = gdi32.dll
apiset ext-ms-win-rtcore-gdi-object-l1-1-0 = gdi32.dll
apiset ext-ms-win-rtcore-gdi-rgn-l1-1-0 = gdi32.dll
apiset ext-ms-win-rtcore-minuser-display-l1-1-0 =
apiset ext-ms-win-rtcore-minuser-host-l1-1-0 =
apiset ext-ms-win-rtcore-minuser-input-l1-1-4 =
apiset ext-ms-win-rtcore-minuser-internal-l1-1-0 =
apiset ext-ms-win-rtcore-minuser-private-ext-l1-1-3 =
apiset ext-ms-win-rtcore-ntuser-cursor-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-dc-access-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-dialogbox-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-dpi-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-dpi-l1-2-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-draw-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-gui-l1-1-1 =
apiset ext-ms-win-rtcore-ntuser-iam-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-inputintercept-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-integration-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-keyboard-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-message-ansi-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-message-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-mininit-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-misc-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-mouse-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-powermanagement-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-private-l1-1-1 =
apiset ext-ms-win-rtcore-ntuser-rawinput-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-rawinput-l1-2-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-synch-ext-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-syscolors-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-sysparams-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-usersecurity-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-window-ansi-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-window-ext-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-window-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-winevent-ext-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-winstamin-l1-1-0 =
apiset ext-ms-win-rtcore-ntuser-wmpointer-l1-1-0 = user32.dll
apiset ext-ms-win-rtcore-ntuser-wmpointermin-l1-1-0 =
apiset ext-ms-win-rtcore-ole32-dragdrop-l1-1-0 = ole32.dll
apiset ext-ms-win-rtcore-ole32-misc-l1-1-0 = ole32.dll
apiset ext-ms-win-rtcore-webview-l1-1-0 =
apiset ext-ms-win-secur32-translatename-l1-1-0 = secur32.dll
apiset ext-ms-win-security-chambers-l1-1-1 =
apiset ext-ms-win-security-credui-l1-1-0 = credui.dll
apiset ext-ms-win-security-crosscontainerauthhelper-l1-1-0 =
apiset ext-ms-win-security-cryptui-l1-1-0 = cryptui.dll
apiset ext-ms-win-security-developerunlock-l1-1-0 =
apiset ext-ms-win-security-deviceid-l1-1-0 =
apiset ext-ms-win-security-kerberos-l1-1-0 = kerberos.dll
apiset ext-ms-win-security-slc-l1-1-0 = slc.dll
apiset ext-ms-win-security-winscard-l1-1-1 = winscard.dll
apiset ext-ms-win-session-usertoken-l1-1-0 = wtsapi32.dll
apiset ext-ms-win-session-winlogon-notify-l1-1-0 =
apiset ext-ms-win-session-winsta-l1-1-4 = winsta.dll
apiset ext-ms-win-session-wtsapi32-l1-1-0 = wtsapi32.dll
apiset ext-ms-win-setupapi-classinstallers-l1-1-2 = setupapi.dll
apiset ext-ms-win-setupapi-inf-l1-1-1 = setupapi.dll
apiset ext-ms-win-setupapi-logging-l1-1-0 = setupapi.dll
apiset ext-ms-win-shell-aclui-l1-1-0 = aclui.dll
apiset ext-ms-win-shell-browsersettingsync-l1-1-0 =
apiset ext-ms-win-shell-comctl32-da-l1-1-0 = comctl32.dll
apiset ext-ms-win-shell-comctl32-init-l1-1-0 = comctl32.dll
apiset ext-ms-win-shell-comctl32-l1-1-0 = comctl32.dll
apiset ext-ms-win-shell-comctl32-window-l1-1-0 = comctl32.dll
apiset ext-ms-win-shell-comdlg32-l1-1-0 = comdlg32.dll
apiset ext-ms-win-shell-directory-l1-1-0 = windows.storage.dll
apiset ext-ms-win-shell-exports-internal-l1-1-0 = shell32.dll
apiset ext-ms-win-shell-propsys-l1-1-1 = propsys.dll
apiset ext-ms-win-shell-shdocvw-l1-1-0 = shdocvw.dll
apiset ext-ms-win-shell-shell32-l1-2-0 = shell32.dll
apiset ext-ms-win-shell-shell32-l1-3-0 = shell32.dll
apiset ext-ms-win-shell-shell32-l1-4-0 = shell32.dll
apiset ext-ms-win-shell-shell32-l1-5-0 = shell32.dll
apiset ext-ms-win-shell-shlwapi-l1-1-1 = shlwapi.dll
apiset ext-ms-win-shell-shlwapi-l1-2-0 = shlwapi.dll
apiset ext-ms-win-shell32-shellcom-l1-1-0 = windows.storage.dll
apiset ext-ms-win-shell32-shellfolders-l1-1-1 = windows.storage.dll
apiset ext-ms-win-shell32-shellfolders-l1-2-1 = windows.storage.dll
apiset ext-ms-win-storage-iscsidsc-l1-1-0 =
apiset ext-ms-win-sxs-oleautomation-l1-1-0 = sxs.dll
apiset ext-ms-win-sysmain-sfltapi-l1-1-0 =
apiset ext-ms-win-system-metrics-override-l1-1-1 =
apiset ext-ms-win-test-sys1-l1-1-0 =
apiset ext-ms-win-test-sys2-l1-1-0 =
apiset ext-ms-win-tsf-msctf-l1-1-4 = msctf.dll
apiset ext-ms-win-ui-viewmanagement-l1-1-0 =
apiset ext-ms-win-uiacore-l1-1-3 = uiautomationcore.dll
apiset ext-ms-win-usp10-l1-1-0 = gdi32.dll
apiset ext-ms-win-uxtheme-themes-l1-1-0 = uxtheme.dll
apiset ext-ms-win-wer-reporting-l1-1-3 = wer.dll
apiset ext-ms-win-wer-wct-l1-1-0 = wer.dll
apiset ext-ms-win-wer-xbox-l1-1-4 =
apiset ext-ms-win-wevtapi-eventlog-l1-1-3 = wevtapi.dll
apiset ext-ms-win-windowing-external-l1-1-0 = windows.ui.dll
apiset ext-ms-win-windowing-internal-l1-1-0 =
apiset ext-ms-win-winlogon-mincreds-l1-1-0 =
apiset ext-ms-win-winrt-storage-l1-1-0 = windows.storage.dll
apiset ext-ms-win-winrt-storage-l1-2-3 = windows.storage.dll
apiset ext-ms-win-wlan-scard-l1-1-0 = winscard.dll
apiset ext-ms-win-wpn-phoneext-l1-1-0 =
apiset ext-ms-win-wrp-sfc-l1-1-0 = sfc.dll
apiset ext-ms-win-xaml-pal-l1-1-0 =
apiset ext-ms-win-xaudio-platform-l1-1-0 =
apiset ext-ms-win-xblauth-console-l1-1-0 =
apiset ext-ms-win-xboxlive-xboxnetapisvc-l1-1-0 =
apiset ext-ms-win32-subsystem-query-l1-1-0 =
apiset ext-ms-windowscore-deviceinfo-l1-1-0 =
