@ stub AssociateColorProfileWithDeviceA
@ stub AssociateColorProfileWithDeviceW
@ stub CheckBitmapBits
@ stub CheckColors
@ stdcall CloseColorProfile(ptr)
@ stub ConvertColorNameToIndex
@ stub ConvertIndexToColorName
@ stub CreateColorTransformA
@ stub CreateColorTransformW
@ stub CreateDeviceLinkProfile
@ stub CreateMultiProfileTransform
@ stub CreateProfileFromLogColorSpaceA
@ stub CreateProfileFromLogColorSpaceW
@ stub DeleteColorTransform
@ stub DisassociateColorProfileFromDeviceA
@ stub DisassociateColorProfileFromDeviceW
@ stub EnumColorProfilesA
@ stub EnumColorProfilesW
@ stub GenerateCopyFilePaths
@ stub GetCMMInfo
@ stub GetColorDirectoryA
@ stub GetColorDirectoryW
@ stub GetColorProfileElement
@ stub GetColorProfileElementTag
@ stub GetColorProfileFromHandle
@ stub GetColorProfileHeader
@ stub GetCountColorProfileElements
@ stub GetNamedProfileInfo
@ stub GetPS2ColorRenderingDictionary
@ stub GetPS2ColorRenderingIntent
@ stub GetPS2ColorSpaceArray
@ stub GetStandardColorSpaceProfileA
@ stub GetStandardColorSpaceProfileW
@ stub InstallColorProfileA
@ stub InstallColorProfileW
@ stub InternalGetDeviceConfig
@ stub InternalGetPS2CSAFromLCS
@ stub InternalGetPS2ColorRenderingDictionary
@ stub InternalGetPS2ColorSpaceArray
@ stub InternalGetPS2PreviewCRD
@ stub InternalSetDeviceConfig
@ stub IsColorProfileTagPresent
@ stub IsColorProfileValid
@ stdcall OpenColorProfileA(ptr long long long)
@ stdcall OpenColorProfileW(ptr long long long)
@ stub RegisterCMMA
@ stub RegisterCMMW
@ stub SelectCMM
@ stub SetColorProfileElement
@ stub SetColorProfileElementReference
@ stub SetColorProfileElementSize
@ stub SetColorProfileHeader
@ stub SetStandardColorSpaceProfileA
@ stub SetStandardColorSpaceProfileW
@ stub SpoolerCopyFileEvent
@ stub TranslateBitmapBits
@ stub TranslateColors
@ stub UninstallColorProfileA
@ stub UninstallColorProfileW
@ stub UnregisterCMMA
@ stub UnregisterCMMW
