@ stub GdipAddPathArc
@ stub GdipAddPathArcI
@ stub GdipAddPathBezier
@ stub GdipAddPathBezierI
@ stub GdipAddPathBeziers
@ stub GdipAddPathBeziersI
@ stub GdipAddPathClosedCurve2
@ stub GdipAddPathClosedCurve2I
@ stub GdipAddPathClosedCurve
@ stub GdipAddPathClosedCurveI
@ stub GdipAddPathCurve2
@ stub GdipAddPathCurve2I
@ stub GdipAddPathCurve3
@ stub GdipAddPathCurve3I
@ stub GdipAddPathCurve
@ stub GdipAddPathCurveI
@ stub GdipAddPathEllipse
@ stub GdipAddPathEllipseI
@ stub GdipAddPathLine2
@ stub GdipAddPathLine2I
@ stub GdipAddPathLine
@ stub GdipAddPathLineI
@ stub GdipAddPathPath
@ stub GdipAddPathPie
@ stub GdipAddPathPieI
@ stub GdipAddPathPolygon
@ stub GdipAddPathPolygonI
@ stub GdipAddPathRectangle
@ stub GdipAddPathRectangleI
@ stub GdipAddPathRectangles
@ stub GdipAddPathRectanglesI
@ stub GdipAddPathString
@ stub GdipAddPathStringI
@ stdcall GdipAlloc(long)
@ stub GdipBeginContainer2
@ stub GdipBeginContainer
@ stub GdipBeginContainerI
@ stub GdipBitmapGetPixel
@ stub GdipBitmapLockBits
@ stub GdipBitmapSetPixel
@ stub GdipBitmapSetResolution
@ stub GdipBitmapUnlockBits
@ stub GdipClearPathMarkers
@ stub GdipCloneBitmapArea
@ stub GdipCloneBitmapAreaI
@ stub GdipCloneBrush
@ stub GdipCloneCustomLineCap
@ stub GdipCloneFont
@ stub GdipCloneFontFamily
@ stub GdipCloneImage
@ stub GdipCloneImageAttributes
@ stub GdipCloneMatrix
@ stub GdipClonePath
@ stub GdipClonePen
@ stub GdipCloneRegion
@ stub GdipCloneStringFormat
@ stub GdipClosePathFigure
@ stub GdipClosePathFigures
@ stub GdipCombineRegionPath
@ stub GdipCombineRegionRect
@ stub GdipCombineRegionRectI
@ stub GdipCombineRegionRegion
@ stub GdipComment
@ stub GdipCreateAdjustableArrowCap
@ stub GdipCreateBitmapFromDirectDrawSurface
@ stub GdipCreateBitmapFromFile
@ stub GdipCreateBitmapFromFileICM
@ stub GdipCreateBitmapFromGdiDib
@ stub GdipCreateBitmapFromGraphics
@ stub GdipCreateBitmapFromHBITMAP
@ stub GdipCreateBitmapFromHICON
@ stub GdipCreateBitmapFromResource
@ stub GdipCreateBitmapFromScan0
@ stub GdipCreateBitmapFromStream
@ stub GdipCreateBitmapFromStreamICM
@ stub GdipCreateCachedBitmap
@ stub GdipCreateCustomLineCap
@ stub GdipCreateFont
@ stub GdipCreateFontFamilyFromName
@ stub GdipCreateFontFromDC
@ stub GdipCreateFontFromLogfontA
@ stub GdipCreateFontFromLogfontW
@ stub GdipCreateFromHDC2
@ stdcall GdipCreateFromHDC(long ptr)
@ stdcall GdipCreateFromHWND(long ptr)
@ stub GdipCreateFromHWNDICM
@ stub GdipCreateHBITMAPFromBitmap
@ stub GdipCreateHICONFromBitmap
@ stub GdipCreateHalftonePalette
@ stub GdipCreateHatchBrush
@ stub GdipCreateImageAttributes
@ stub GdipCreateLineBrush
@ stub GdipCreateLineBrushFromRect
@ stub GdipCreateLineBrushFromRectI
@ stub GdipCreateLineBrushFromRectWithAngle
@ stub GdipCreateLineBrushFromRectWithAngleI
@ stub GdipCreateLineBrushI
@ stub GdipCreateMatrix2
@ stub GdipCreateMatrix3
@ stub GdipCreateMatrix3I
@ stub GdipCreateMatrix
@ stub GdipCreateMetafileFromEmf
@ stub GdipCreateMetafileFromFile
@ stub GdipCreateMetafileFromStream
@ stub GdipCreateMetafileFromWmf
@ stub GdipCreateMetafileFromWmfFile
@ stub GdipCreatePath2
@ stub GdipCreatePath2I
@ stub GdipCreatePath
@ stub GdipCreatePathGradient
@ stub GdipCreatePathGradientFromPath
@ stub GdipCreatePathGradientI
@ stub GdipCreatePathIter
@ stdcall GdipCreatePen1(long long long ptr)
@ stub GdipCreatePen2
@ stub GdipCreateRegion
@ stub GdipCreateRegionHrgn
@ stub GdipCreateRegionPath
@ stub GdipCreateRegionRect
@ stub GdipCreateRegionRectI
@ stub GdipCreateRegionRgnData
@ stdcall GdipCreateSolidFill(long ptr)
@ stub GdipCreateStreamOnFile
@ stub GdipCreateStringFormat
@ stub GdipCreateTexture2
@ stub GdipCreateTexture2I
@ stub GdipCreateTexture
@ stub GdipCreateTextureIA
@ stub GdipCreateTextureIAI
@ stdcall GdipDeleteBrush(ptr)
@ stub GdipDeleteCachedBitmap
@ stub GdipDeleteCustomLineCap
@ stub GdipDeleteFont
@ stub GdipDeleteFontFamily
@ stdcall GdipDeleteGraphics(ptr)
@ stub GdipDeleteMatrix
@ stub GdipDeletePath
@ stub GdipDeletePathIter
@ stdcall GdipDeletePen(ptr)
@ stub GdipDeletePrivateFontCollection
@ stub GdipDeleteRegion
@ stub GdipDeleteStringFormat
@ stub GdipDisposeImage
@ stub GdipDisposeImageAttributes
@ stub GdipDrawArc
@ stub GdipDrawArcI
@ stdcall GdipDrawBezier(ptr ptr long long long long long long long long)
@ stub GdipDrawBezierI
@ stub GdipDrawBeziers
@ stub GdipDrawBeziersI
@ stub GdipDrawCachedBitmap
@ stub GdipDrawClosedCurve2
@ stub GdipDrawClosedCurve2I
@ stub GdipDrawClosedCurve
@ stub GdipDrawClosedCurveI
@ stub GdipDrawCurve2
@ stub GdipDrawCurve2I
@ stub GdipDrawCurve3
@ stub GdipDrawCurve3I
@ stub GdipDrawCurve
@ stub GdipDrawCurveI
@ stub GdipDrawDriverString
@ stub GdipDrawEllipse
@ stub GdipDrawEllipseI
@ stub GdipDrawImage
@ stub GdipDrawImageI
@ stub GdipDrawImagePointRect
@ stub GdipDrawImagePointRectI
@ stub GdipDrawImagePoints
@ stub GdipDrawImagePointsI
@ stub GdipDrawImagePointsRect
@ stub GdipDrawImagePointsRectI
@ stub GdipDrawImageRect
@ stub GdipDrawImageRectI
@ stub GdipDrawImageRectRect
@ stub GdipDrawImageRectRectI
@ stub GdipDrawLine
@ stdcall GdipDrawLineI(ptr ptr long long long long)
@ stub GdipDrawLines
@ stub GdipDrawLinesI
@ stub GdipDrawPath
@ stub GdipDrawPie
@ stub GdipDrawPieI
@ stub GdipDrawPolygon
@ stub GdipDrawPolygonI
@ stub GdipDrawRectangle
@ stdcall GdipDrawRectangleI(ptr ptr long long long long)
@ stub GdipDrawRectangles
@ stub GdipDrawRectanglesI
@ stub GdipDrawString
@ stub GdipEmfToWmfBits
@ stub GdipEndContainer
@ stub GdipEnumerateMetafileDestPoint
@ stub GdipEnumerateMetafileDestPointI
@ stub GdipEnumerateMetafileDestPoints
@ stub GdipEnumerateMetafileDestPointsI
@ stub GdipEnumerateMetafileDestRect
@ stub GdipEnumerateMetafileDestRectI
@ stub GdipEnumerateMetafileSrcRectDestPoint
@ stub GdipEnumerateMetafileSrcRectDestPointI
@ stub GdipEnumerateMetafileSrcRectDestPoints
@ stub GdipEnumerateMetafileSrcRectDestPointsI
@ stub GdipEnumerateMetafileSrcRectDestRect
@ stub GdipEnumerateMetafileSrcRectDestRectI
@ stub GdipFillClosedCurve2
@ stub GdipFillClosedCurve2I
@ stub GdipFillClosedCurve
@ stub GdipFillClosedCurveI
@ stub GdipFillEllipse
@ stub GdipFillEllipseI
@ stub GdipFillPath
@ stub GdipFillPie
@ stub GdipFillPieI
@ stub GdipFillPolygon2
@ stub GdipFillPolygon2I
@ stub GdipFillPolygon
@ stub GdipFillPolygonI
@ stub GdipFillRectangle
@ stub GdipFillRectangleI
@ stub GdipFillRectangles
@ stub GdipFillRectanglesI
@ stub GdipFillRegion
@ stub GdipFlattenPath
@ stub GdipFlush
@ stdcall GdipFree(ptr)
@ stub GdipGetAdjustableArrowCapFillState
@ stub GdipGetAdjustableArrowCapHeight
@ stub GdipGetAdjustableArrowCapMiddleInset
@ stub GdipGetAdjustableArrowCapWidth
@ stub GdipGetAllPropertyItems
@ stdcall GdipGetBrushType(ptr ptr)
@ stub GdipGetCellAscent
@ stub GdipGetCellDescent
@ stub GdipGetClip
@ stub GdipGetClipBounds
@ stub GdipGetClipBoundsI
@ stub GdipGetCompositingMode
@ stub GdipGetCompositingQuality
@ stub GdipGetCustomLineCapBaseCap
@ stub GdipGetCustomLineCapBaseInset
@ stub GdipGetCustomLineCapStrokeCaps
@ stub GdipGetCustomLineCapStrokeJoin
@ stub GdipGetCustomLineCapType
@ stub GdipGetCustomLineCapWidthScale
@ stub GdipGetDC
@ stub GdipGetDpiX
@ stub GdipGetDpiY
@ stub GdipGetEmHeight
@ stub GdipGetEncoderParameterList
@ stub GdipGetEncoderParameterListSize
@ stub GdipGetFamily
@ stub GdipGetFamilyName
@ stub GdipGetFontCollectionFamilyCount
@ stub GdipGetFontCollectionFamilyList
@ stub GdipGetFontHeight
@ stub GdipGetFontHeightGivenDPI
@ stub GdipGetFontSize
@ stub GdipGetFontStyle
@ stub GdipGetFontUnit
@ stub GdipGetGenericFontFamilyMonospace
@ stub GdipGetGenericFontFamilySansSerif
@ stub GdipGetGenericFontFamilySerif
@ stub GdipGetHatchBackgroundColor
@ stub GdipGetHatchForegroundColor
@ stub GdipGetHatchStyle
@ stub GdipGetHemfFromMetafile
@ stub GdipGetImageAttributesAdjustedPalette
@ stub GdipGetImageBounds
@ stub GdipGetImageDecoders
@ stub GdipGetImageDecodersSize
@ stub GdipGetImageDimension
@ stub GdipGetImageEncoders
@ stub GdipGetImageEncodersSize
@ stub GdipGetImageFlags
@ stub GdipGetImageGraphicsContext
@ stub GdipGetImageHeight
@ stub GdipGetImageHorizontalResolution
@ stub GdipGetImagePalette
@ stub GdipGetImagePaletteSize
@ stub GdipGetImagePixelFormat
@ stub GdipGetImageRawFormat
@ stub GdipGetImageThumbnail
@ stub GdipGetImageType
@ stub GdipGetImageVerticalResolution
@ stub GdipGetImageWidth
@ stub GdipGetInterpolationMode
@ stub GdipGetLineBlend
@ stub GdipGetLineBlendCount
@ stub GdipGetLineColors
@ stub GdipGetLineGammaCorrection
@ stub GdipGetLinePresetBlend
@ stub GdipGetLinePresetBlendCount
@ stub GdipGetLineRect
@ stub GdipGetLineRectI
@ stub GdipGetLineSpacing
@ stub GdipGetLineTransform
@ stub GdipGetLineWrapMode
@ stub GdipGetLogFontA
@ stub GdipGetLogFontW
@ stub GdipGetMatrixElements
@ stub GdipGetMetafileDownLevelRasterizationLimit
@ stub GdipGetMetafileHeaderFromEmf
@ stub GdipGetMetafileHeaderFromFile
@ stub GdipGetMetafileHeaderFromMetafile
@ stub GdipGetMetafileHeaderFromStream
@ stub GdipGetMetafileHeaderFromWmf
@ stub GdipGetNearestColor
@ stub GdipGetPageScale
@ stub GdipGetPageUnit
@ stub GdipGetPathData
@ stub GdipGetPathFillMode
@ stub GdipGetPathGradientBlend
@ stub GdipGetPathGradientBlendCount
@ stub GdipGetPathGradientCenterColor
@ stub GdipGetPathGradientCenterPoint
@ stub GdipGetPathGradientCenterPointI
@ stub GdipGetPathGradientFocusScales
@ stub GdipGetPathGradientGammaCorrection
@ stub GdipGetPathGradientPath
@ stub GdipGetPathGradientPointCount
@ stub GdipGetPathGradientPresetBlend
@ stub GdipGetPathGradientPresetBlendCount
@ stub GdipGetPathGradientRect
@ stub GdipGetPathGradientRectI
@ stub GdipGetPathGradientSurroundColorCount
@ stub GdipGetPathGradientSurroundColorsWithCount
@ stub GdipGetPathGradientTransform
@ stub GdipGetPathGradientWrapMode
@ stub GdipGetPathLastPoint
@ stub GdipGetPathPoints
@ stub GdipGetPathPointsI
@ stub GdipGetPathTypes
@ stub GdipGetPathWorldBounds
@ stub GdipGetPathWorldBoundsI
@ stub GdipGetPenBrushFill
@ stub GdipGetPenColor
@ stub GdipGetPenCompoundArray
@ stub GdipGetPenCompoundCount
@ stub GdipGetPenCustomEndCap
@ stub GdipGetPenCustomStartCap
@ stub GdipGetPenDashArray
@ stub GdipGetPenDashCap197819
@ stub GdipGetPenDashCount
@ stub GdipGetPenDashOffset
@ stub GdipGetPenDashStyle
@ stub GdipGetPenEndCap
@ stub GdipGetPenFillType
@ stub GdipGetPenLineJoin
@ stub GdipGetPenMiterLimit
@ stub GdipGetPenMode
@ stub GdipGetPenStartCap
@ stub GdipGetPenTransform
@ stub GdipGetPenUnit
@ stub GdipGetPenWidth
@ stub GdipGetPixelOffsetMode
@ stub GdipGetPointCount
@ stub GdipGetPropertyCount
@ stub GdipGetPropertyIdList
@ stub GdipGetPropertyItem
@ stub GdipGetPropertyItemSize
@ stub GdipGetPropertySize
@ stub GdipGetRegionBounds
@ stub GdipGetRegionBoundsI
@ stub GdipGetRegionData
@ stub GdipGetRegionDataSize
@ stub GdipGetRegionHRgn
@ stub GdipGetRegionScans
@ stub GdipGetRegionScansCount
@ stub GdipGetRegionScansI
@ stub GdipGetRenderingOrigin
@ stub GdipGetSmoothingMode
@ stub GdipGetSolidFillColor
@ stub GdipGetStringFormatAlign
@ stub GdipGetStringFormatDigitSubstitution
@ stub GdipGetStringFormatFlags
@ stub GdipGetStringFormatHotkeyPrefix
@ stub GdipGetStringFormatLineAlign
@ stub GdipGetStringFormatMeasurableCharacterRangeCount
@ stub GdipGetStringFormatTabStopCount
@ stub GdipGetStringFormatTabStops
@ stub GdipGetStringFormatTrimming
@ stub GdipGetTextContrast
@ stub GdipGetTextRenderingHint
@ stub GdipGetTextureImage
@ stub GdipGetTextureTransform
@ stub GdipGetTextureWrapMode
@ stub GdipGetVisibleClipBounds
@ stub GdipGetVisibleClipBoundsI
@ stub GdipGetWorldTransform
@ stub GdipGraphicsClear
@ stub GdipImageForceValidation
@ stub GdipImageGetFrameCount
@ stub GdipImageGetFrameDimensionsCount
@ stub GdipImageGetFrameDimensionsList
@ stub GdipImageRotateFlip
@ stub GdipImageSelectActiveFrame
@ stub GdipInvertMatrix
@ stub GdipIsClipEmpty
@ stub GdipIsEmptyRegion
@ stub GdipIsEqualRegion
@ stub GdipIsInfiniteRegion
@ stub GdipIsMatrixEqual
@ stub GdipIsMatrixIdentity
@ stub GdipIsMatrixInvertible
@ stub GdipIsOutlineVisiblePathPoint
@ stub GdipIsOutlineVisiblePathPointI
@ stub GdipIsStyleAvailable
@ stub GdipIsVisibleClipEmpty
@ stub GdipIsVisiblePathPoint
@ stub GdipIsVisiblePathPointI
@ stub GdipIsVisiblePoint
@ stub GdipIsVisiblePointI
@ stub GdipIsVisibleRect
@ stub GdipIsVisibleRectI
@ stub GdipIsVisibleRegionPoint
@ stub GdipIsVisibleRegionPointI
@ stub GdipIsVisibleRegionRect
@ stub GdipIsVisibleRegionRectI
@ stub GdipLoadImageFromFile
@ stub GdipLoadImageFromFileICM
@ stub GdipLoadImageFromStream
@ stub GdipLoadImageFromStreamICM
@ stub GdipMeasureCharacterRanges
@ stub GdipMeasureDriverString
@ stub GdipMeasureString
@ stub GdipMultiplyLineTransform
@ stub GdipMultiplyMatrix
@ stub GdipMultiplyPathGradientTransform
@ stub GdipMultiplyPenTransform
@ stub GdipMultiplyTextureTransform
@ stub GdipMultiplyWorldTransform
@ stub GdipNewInstalledFontCollection
@ stub GdipNewPrivateFontCollection
@ stub GdipPathIterCopyData
@ stub GdipPathIterEnumerate
@ stub GdipPathIterGetCount
@ stub GdipPathIterGetSubpathCount
@ stub GdipPathIterHasCurve
@ stub GdipPathIterIsValid
@ stub GdipPathIterNextMarker
@ stub GdipPathIterNextMarkerPath
@ stub GdipPathIterNextPathType
@ stub GdipPathIterNextSubpath
@ stub GdipPathIterNextSubpathPath
@ stub GdipPathIterRewind
@ stub GdipPlayMetafileRecord
@ stub GdipPrivateAddFontFile
@ stub GdipPrivateAddMemoryFont
@ stub GdipRecordMetafile
@ stub GdipRecordMetafileFileName
@ stub GdipRecordMetafileFileNameI
@ stub GdipRecordMetafileI
@ stub GdipRecordMetafileStream
@ stub GdipRecordMetafileStreamI
@ stub GdipReleaseDC
@ stub GdipRemovePropertyItem
@ stub GdipResetClip
@ stub GdipResetImageAttributes
@ stub GdipResetLineTransform
@ stub GdipResetPageTransform
@ stub GdipResetPath
@ stub GdipResetPathGradientTransform
@ stub GdipResetPenTransform
@ stub GdipResetTextureTransform
@ stub GdipResetWorldTransform
@ stub GdipRestoreGraphics
@ stub GdipReversePath
@ stub GdipRotateLineTransform
@ stub GdipRotateMatrix
@ stub GdipRotatePathGradientTransform
@ stub GdipRotatePenTransform
@ stub GdipRotateTextureTransform
@ stub GdipRotateWorldTransform
@ stub GdipSaveAdd
@ stub GdipSaveAddImage
@ stub GdipSaveGraphics
@ stub GdipSaveImageToFile
@ stub GdipSaveImageToStream
@ stub GdipScaleLineTransform
@ stub GdipScaleMatrix
@ stub GdipScalePathGradientTransform
@ stub GdipScalePenTransform
@ stub GdipScaleTextureTransform
@ stub GdipScaleWorldTransform
@ stub GdipSetAdjustableArrowCapFillState
@ stub GdipSetAdjustableArrowCapHeight
@ stub GdipSetAdjustableArrowCapMiddleInset
@ stub GdipSetAdjustableArrowCapWidth
@ stub GdipSetClipGraphics
@ stub GdipSetClipHrgn
@ stub GdipSetClipPath
@ stub GdipSetClipRect
@ stub GdipSetClipRectI
@ stub GdipSetClipRegion
@ stub GdipSetCompositingMode
@ stub GdipSetCompositingQuality
@ stub GdipSetCustomLineCapBaseCap
@ stub GdipSetCustomLineCapBaseInset
@ stub GdipSetCustomLineCapStrokeCaps
@ stub GdipSetCustomLineCapStrokeJoin
@ stub GdipSetCustomLineCapWidthScale
@ stub GdipSetEmpty
@ stub GdipSetImageAttributesCachedBackground
@ stub GdipSetImageAttributesColorKeys
@ stub GdipSetImageAttributesColorMatrix
@ stub GdipSetImageAttributesGamma
@ stub GdipSetImageAttributesNoOp
@ stub GdipSetImageAttributesOutputChannel
@ stub GdipSetImageAttributesOutputChannelColorProfile
@ stub GdipSetImageAttributesRemapTable
@ stub GdipSetImageAttributesThreshold
@ stub GdipSetImageAttributesToIdentity
@ stub GdipSetImageAttributesWrapMode
@ stub GdipSetImagePalette
@ stub GdipSetInfinite
@ stub GdipSetInterpolationMode
@ stub GdipSetLineBlend
@ stub GdipSetLineColors
@ stub GdipSetLineGammaCorrection
@ stub GdipSetLineLinearBlend
@ stub GdipSetLinePresetBlend
@ stub GdipSetLineSigmaBlend
@ stub GdipSetLineTransform
@ stub GdipSetLineWrapMode
@ stub GdipSetMatrixElements
@ stub GdipSetMetafileDownLevelRasterizationLimit
@ stub GdipSetPageScale
@ stub GdipSetPageUnit
@ stub GdipSetPathFillMode
@ stub GdipSetPathGradientBlend
@ stub GdipSetPathGradientCenterColor
@ stub GdipSetPathGradientCenterPoint
@ stub GdipSetPathGradientCenterPointI
@ stub GdipSetPathGradientFocusScales
@ stub GdipSetPathGradientGammaCorrection
@ stub GdipSetPathGradientLinearBlend
@ stub GdipSetPathGradientPath
@ stub GdipSetPathGradientPresetBlend
@ stub GdipSetPathGradientSigmaBlend
@ stub GdipSetPathGradientSurroundColorsWithCount
@ stub GdipSetPathGradientTransform
@ stub GdipSetPathGradientWrapMode
@ stub GdipSetPathMarker
@ stub GdipSetPenBrushFill
@ stub GdipSetPenColor
@ stub GdipSetPenCompoundArray
@ stub GdipSetPenCustomEndCap
@ stub GdipSetPenCustomStartCap
@ stub GdipSetPenDashArray
@ stub GdipSetPenDashCap197819
@ stub GdipSetPenDashOffset
@ stub GdipSetPenDashStyle
@ stub GdipSetPenEndCap
@ stub GdipSetPenLineCap197819
@ stub GdipSetPenLineJoin
@ stub GdipSetPenMiterLimit
@ stub GdipSetPenMode
@ stub GdipSetPenStartCap
@ stub GdipSetPenTransform
@ stub GdipSetPenUnit
@ stub GdipSetPenWidth
@ stub GdipSetPixelOffsetMode
@ stub GdipSetPropertyItem
@ stub GdipSetRenderingOrigin
@ stub GdipSetSmoothingMode
@ stub GdipSetSolidFillColor
@ stub GdipSetStringFormatAlign
@ stub GdipSetStringFormatDigitSubstitution
@ stub GdipSetStringFormatFlags
@ stub GdipSetStringFormatHotkeyPrefix
@ stub GdipSetStringFormatLineAlign
@ stub GdipSetStringFormatMeasurableCharacterRanges
@ stub GdipSetStringFormatTabStops
@ stub GdipSetStringFormatTrimming
@ stub GdipSetTextContrast
@ stub GdipSetTextRenderingHint
@ stub GdipSetTextureTransform
@ stub GdipSetTextureWrapMode
@ stub GdipSetWorldTransform
@ stub GdipShearMatrix
@ stub GdipStartPathFigure
@ stub GdipStringFormatGetGenericDefault
@ stub GdipStringFormatGetGenericTypographic
@ stub GdipTestControl
@ stub GdipTransformMatrixPoints
@ stub GdipTransformMatrixPointsI
@ stub GdipTransformPath
@ stub GdipTransformPoints
@ stub GdipTransformPointsI
@ stub GdipTransformRegion
@ stub GdipTranslateClip
@ stub GdipTranslateClipI
@ stub GdipTranslateLineTransform
@ stub GdipTranslateMatrix
@ stub GdipTranslatePathGradientTransform
@ stub GdipTranslatePenTransform
@ stub GdipTranslateRegion
@ stub GdipTranslateRegionI
@ stub GdipTranslateTextureTransform
@ stub GdipTranslateWorldTransform
@ stub GdipVectorTransformMatrixPoints
@ stub GdipVectorTransformMatrixPointsI
@ stub GdipWarpPath
@ stub GdipWidenPath
@ stub GdipWindingModeOutline
@ stub GdiplusNotificationHook
@ stub GdiplusNotificationUnhook
@ stdcall GdiplusShutdown(ptr)
@ stdcall GdiplusStartup(ptr ptr ptr)
