@ stub AreThereVisibleLogoffScriptsInternal
@ stub AreThereVisibleShutdownScriptsInternal
@ stub EnterCriticalPolicySectionInternal
@ stub ForceSyncFgPolicyInternal
@ stub FreeGPOListInternalA
@ stub FreeGPOListInternalW
@ stub GenerateGPNotificationInternal
@ stub GetAppliedGPOListInternalA
@ stub GetAppliedGPOListInternalW
@ stub GetGPOListInternalA
@ stub GetGPOListInternalW
@ stub GetNextFgPolicyRefreshInfoInternal
@ stub GetPreviousFgPolicyRefreshInfoInternal
@ stub HasPolicyForegroundProcessingCompletedInternal
@ stub IsSyncForegroundPolicyRefresh
@ stub LeaveCriticalPolicySectionInternal
@ stub RefreshPolicyExInternal
@ stub RefreshPolicyInternal
@ stub RegisterGPNotificationInternal
@ stub RsopLoggingEnabledInternal
@ stub UnregisterGPNotificationInternal
@ stub WaitForMachinePolicyForegroundProcessingInternal
@ stub WaitForUserPolicyForegroundProcessingInternal
