  3 stub GetProxyDllInfo
400 stub @
402 stub @
403 stub @
404 stub @
405 stub @
406 stub @
407 stub @
408 stub @
409 stub @
410 stub @
411 stub @
412 stub @
413 stub @
414 stub @
415 stub @
416 stub @
417 stub @
418 stub @
420 stub @
421 stub @
422 stub @

@ stub ClearPropVariantArray
@ stub ClearVariantArray
@ stub DllCanUnloadNow
@ stub DllGetClassObject
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub InitPropVariantFromBooleanVector
@ stub InitPropVariantFromBuffer
@ stub InitPropVariantFromCLSID
@ stub InitPropVariantFromDoubleVector
@ stub InitPropVariantFromFileTime
@ stub InitPropVariantFromFileTimeVector
@ stub InitPropVariantFromGUIDAsString
@ stub InitPropVariantFromInt16Vector
@ stub InitPropVariantFromInt32Vector
@ stub InitPropVariantFromInt64Vector
@ stub InitPropVariantFromPropVariantVectorElem
@ stub InitPropVariantFromResource
@ stub InitPropVariantFromStrRet
@ stub InitPropVariantFromStringAsVector
@ stub InitPropVariantFromStringVector
@ stub InitPropVariantFromUInt16Vector
@ stub InitPropVariantFromUInt32Vector
@ stub InitPropVariantFromUInt64Vector
@ stub InitPropVariantVectorFromPropVariant
@ stub InitVariantFromBooleanArray
@ stub InitVariantFromBuffer
@ stub InitVariantFromDoubleArray
@ stub InitVariantFromFileTime
@ stub InitVariantFromFileTimeArray
@ stub InitVariantFromGUIDAsString
@ stub InitVariantFromInt16Array
@ stub InitVariantFromInt32Array
@ stub InitVariantFromInt64Array
@ stub InitVariantFromResource
@ stub InitVariantFromStrRet
@ stub InitVariantFromStringArray
@ stub InitVariantFromUInt16Array
@ stub InitVariantFromUInt32Array
@ stub InitVariantFromUInt64Array
@ stub InitVariantFromVariantArrayElem
@ stub PSCoerceToCanonicalValue
@ stub PSCreateAdapterFromPropertyStore
@ stub PSCreateDelayedMultiplexPropertyStore
@ stub PSCreateMemoryPropertyStore
@ stub PSCreateMultiplexPropertyStore
@ stub PSCreatePropertyChangeArray
@ stub PSCreatePropertyStoreFromObject
@ stub PSCreatePropertyStoreFromPropertySetStorage
@ stub PSCreateSimplePropertyChange
@ stub PSEnumeratePropertyDescriptions
@ stub PSFormatForDisplay
@ stub PSFormatForDisplayAlloc
@ stub PSFormatPropertyValue
@ stub PSGetItemPropertyHandler
@ stub PSGetItemPropertyHandlerWithCreateObject
@ stub PSGetNameFromPropertyKey
@ stub PSGetNamedPropertyFromPropertyStorage
@ stub PSGetPropertyDescription
@ stub PSGetPropertyDescriptionByName
@ stub PSGetPropertyDescriptionListFromString
@ stub PSGetPropertyFromPropertyStorage
@ stub PSGetPropertyKeyFromName
@ stub PSGetPropertySystem
@ stub PSGetPropertyValue
@ stub PSLookupPropertyHandlerCLSID
@ stdcall PSPropertyKeyFromString(wstr ptr)
@ stub PSRefreshPropertySchema
@ stdcall PSRegisterPropertySchema(wstr)
@ stub PSSetPropertyValue
@ stdcall PSStringFromPropertyKey(ptr ptr long)
@ stdcall PSUnregisterPropertySchema(wstr)
@ stdcall PropVariantChangeType(ptr ptr long long)
@ stub PropVariantCompareEx
@ stub PropVariantGetBooleanElem
@ stub PropVariantGetDoubleElem
@ stub PropVariantGetElementCount
@ stub PropVariantGetFileTimeElem
@ stub PropVariantGetInt16Elem
@ stub PropVariantGetInt32Elem
@ stub PropVariantGetInt64Elem
@ stub PropVariantGetStringElem
@ stub PropVariantGetUInt16Elem
@ stub PropVariantGetUInt32Elem
@ stub PropVariantGetUInt64Elem
@ stub PropVariantToBSTR
@ stub PropVariantToBoolean
@ stub PropVariantToBooleanVector
@ stub PropVariantToBooleanVectorAlloc
@ stub PropVariantToBooleanWithDefault
@ stub PropVariantToBuffer
@ stub PropVariantToDouble
@ stub PropVariantToDoubleVector
@ stub PropVariantToDoubleVectorAlloc
@ stub PropVariantToDoubleWithDefault
@ stub PropVariantToFileTime
@ stub PropVariantToFileTimeVector
@ stub PropVariantToFileTimeVectorAlloc
@ stub PropVariantToGUID
@ stub PropVariantToInt16
@ stub PropVariantToInt16Vector
@ stub PropVariantToInt16VectorAlloc
@ stub PropVariantToInt16WithDefault
@ stub PropVariantToInt32
@ stub PropVariantToInt32Vector
@ stub PropVariantToInt32VectorAlloc
@ stub PropVariantToInt32WithDefault
@ stub PropVariantToInt64
@ stub PropVariantToInt64Vector
@ stub PropVariantToInt64VectorAlloc
@ stub PropVariantToInt64WithDefault
@ stub PropVariantToStrRet
@ stub PropVariantToString
@ stub PropVariantToStringAlloc
@ stub PropVariantToStringVector
@ stub PropVariantToStringVectorAlloc
@ stub PropVariantToStringWithDefault
@ stub PropVariantToUInt16
@ stub PropVariantToUInt16Vector
@ stub PropVariantToUInt16VectorAlloc
@ stub PropVariantToUInt16WithDefault
@ stub PropVariantToUInt32
@ stub PropVariantToUInt32Vector
@ stub PropVariantToUInt32VectorAlloc
@ stub PropVariantToUInt32WithDefault
@ stub PropVariantToUInt64
@ stub PropVariantToUInt64Vector
@ stub PropVariantToUInt64VectorAlloc
@ stub PropVariantToUInt64WithDefault
@ stub PropVariantToVariant
@ stub StgDeserializePropVariant
@ stub StgSerializePropVariant
@ stub VariantCompare
@ stub VariantGetBooleanElem
@ stub VariantGetDoubleElem
@ stub VariantGetElementCount
@ stub VariantGetInt16Elem
@ stub VariantGetInt32Elem
@ stub VariantGetInt64Elem
@ stub VariantGetStringElem
@ stub VariantGetUInt16Elem
@ stub VariantGetUInt32Elem
@ stub VariantGetUInt64Elem
@ stub VariantToBoolean
@ stub VariantToBooleanArray
@ stub VariantToBooleanArrayAlloc
@ stub VariantToBooleanWithDefault
@ stub VariantToBuffer
@ stub VariantToDosDateTime
@ stub VariantToDouble
@ stub VariantToDoubleArray
@ stub VariantToDoubleArrayAlloc
@ stub VariantToDoubleWithDefault
@ stub VariantToFileTime
@ stub VariantToGUID
@ stub VariantToInt16
@ stub VariantToInt16Array
@ stub VariantToInt16ArrayAlloc
@ stub VariantToInt16WithDefault
@ stub VariantToInt32
@ stub VariantToInt32Array
@ stub VariantToInt32ArrayAlloc
@ stub VariantToInt32WithDefault
@ stub VariantToInt64
@ stub VariantToInt64Array
@ stub VariantToInt64ArrayAlloc
@ stub VariantToInt64WithDefault
@ stub VariantToPropVariant
@ stub VariantToStrRet
@ stub VariantToString
@ stub VariantToStringAlloc
@ stub VariantToStringArray
@ stub VariantToStringArrayAlloc
@ stub VariantToStringWithDefault
@ stub VariantToUInt16
@ stub VariantToUInt16Array
@ stub VariantToUInt16ArrayAlloc
@ stub VariantToUInt16WithDefault
@ stub VariantToUInt32
@ stub VariantToUInt32Array
@ stub VariantToUInt32ArrayAlloc
@ stub VariantToUInt32WithDefault
@ stub VariantToUInt64
@ stub VariantToUInt64Array
@ stub VariantToUInt64ArrayAlloc
@ stub VariantToUInt64WithDefault
