@ stub SystemPrng
@ stub AcceptSecurityContext
@ stub AcquireCredentialsHandleW
@ stub AddCredentialsW
@ stub ApplyControlToken
@ stub BCryptCloseAlgorithmProvider
@ stub BCryptCreateHash
@ stub BCryptDecrypt
@ stub BCryptDeriveKey
@ stub BCryptDeriveKeyCapi
@ stub BCryptDeriveKeyPBKDF2
@ stub BCryptDestroyHash
@ stub BCryptDestroyKey
@ stub BCryptDestroySecret
@ stub BCryptDuplicateHash
@ stub BCryptDuplicateKey
@ stub BCryptEncrypt
@ stub BCryptEnumAlgorithms
@ stub BCryptEnumProviders
@ stub BCryptExportKey
@ stub BCryptFinalizeKeyPair
@ stub BCryptFinishHash
@ stub BCryptFreeBuffer
@ stub BCryptGenRandom
@ stub BCryptGenerateKeyPair
@ stub BCryptGenerateSymmetricKey
@ stub BCryptGetFipsAlgorithmMode
@ stub BCryptGetProperty
@ stub BCryptHashData
@ stub BCryptImportKey
@ stub BCryptImportKeyPair
@ stub BCryptKeyDerivation
@ stub BCryptOpenAlgorithmProvider
@ stub BCryptRegisterConfigChangeNotify
@ stub BCryptResolveProviders
@ stub BCryptSecretAgreement
@ stub BCryptSetProperty
@ stub BCryptSignHash
@ stub BCryptUnregisterConfigChangeNotify
@ stub BCryptVerifySignature
@ stub CompleteAuthToken
@ stub CredMarshalTargetInfo
@ stub DeleteSecurityContext
@ stub EnumerateSecurityPackagesW
@ stub ExportSecurityContext
@ stub FreeContextBuffer
@ stub FreeCredentialsHandle
@ stub GetSecurityUserInfo
@ stub ImpersonateSecurityContext
@ stub ImportSecurityContextW
@ stub InitSecurityInterfaceW
@ stub InitializeSecurityContextW
@ stub KSecRegisterSecurityProvider
@ stub KSecValidateBuffer
@ stub LsaEnumerateLogonSessions
@ stub LsaGetLogonSessionData
@ stub MakeSignature
@ stub MapSecurityError
@ stub QueryContextAttributesW
@ stub QueryCredentialsAttributesW
@ stub QuerySecurityContextToken
@ stub QuerySecurityPackageInfoW
@ stub RevertSecurityContext
@ stub SealMessage
@ stub SecLookupAccountName
@ stub SecLookupAccountSid
@ stub SecLookupWellKnownSid
@ stub SecMakeSPN
@ stub SecMakeSPNEx
@ stub SecMakeSPNEx2
@ stub SecSetPagingMode
@ stub SetCredentialsAttributesW
@ stub SslDecryptPacket
@ stub SslEncryptPacket
@ stub SslExportKey
@ stub SslFreeObject
@ stub SslGetServerIdentity
@ stub SslImportKey
@ stub SslLookupCipherSuiteInfo
@ stub SslOpenProvider
@ stub SspiAcceptSecurityContextAsync
@ stub SspiAcquireCredentialsHandleAsyncW
@ stub SspiCompareAuthIdentities
@ stub SspiCopyAuthIdentity
@ stub SspiCreateAsyncContext
@ stub SspiDeleteSecurityContextAsync
@ stub SspiEncodeAuthIdentityAsStrings
@ stub SspiEncodeStringsAsAuthIdentity
@ stub SspiFreeAsyncContext
@ stub SspiFreeAuthIdentity
@ stub SspiFreeCredentialsHandleAsync
@ stub SspiGetAsyncCallStatus
@ stub SspiInitializeSecurityContextAsyncW
@ stub SspiLocalFree
@ stub SspiMarshalAuthIdentity
@ stub SspiReinitAsyncContext
@ stub SspiSetAsyncNotifyCallback
@ stub SspiUnmarshalAuthIdentity
@ stub SspiValidateAuthIdentity
@ stub SspiZeroAuthIdentity
@ stub TokenBindingGetKeyTypesServer
@ stub TokenBindingVerifyMessage
@ stub UnsealMessage
@ stub VerifySignature
