@ stub RevertToOldImplementation
@ stub D3D10CompileEffectFromMemory
@ stub D3D10CompileShader
@ stub D3D10CreateBlob
@ stdcall D3D10CreateDevice1(ptr long ptr long long long ptr)
@ stub D3D10CreateDeviceAndSwapChain1
@ stdcall D3D10CreateEffectFromMemory(ptr long long ptr ptr ptr) d3d10.D3D10CreateEffectFromMemory
@ stub D3D10CreateEffectPoolFromMemory
@ stub D3D10CreateStateBlock
@ stub D3D10DisassembleEffect
@ stub D3D10DisassembleShader
@ stub D3D10GetGeometryShaderProfile
@ stub D3D10GetInputAndOutputSignatureBlob
@ stub D3D10GetInputSignatureBlob
@ stub D3D10GetOutputSignatureBlob
@ stub D3D10GetPixelShaderProfile
@ stub D3D10GetShaderDebugInfo
@ stub D3D10GetVersion
@ stub D3D10GetVertexShaderProfile
@ stub D3D10PreprocessShader
@ stub D3D10ReflectShader
@ stub D3D10RegisterLayers
@ stub D3D10StateBlockMaskDifference
@ stub D3D10StateBlockMaskDisableAll
@ stub D3D10StateBlockMaskDisableCapture
@ stub D3D10StateBlockMaskEnableAll
@ stub D3D10StateBlockMaskEnableCapture
@ stub D3D10StateBlockMaskGetSetting
@ stub D3D10StateBlockMaskIntersect
@ stub D3D10StateBlockMaskUnion
