@ stub NetpAvoidNetlogonSpnSet
@ stub NetpChangeMachineName
@ stub NetpCheckOfflineLsaPolicyUpdate
@ stub NetpCompleteOfflineDomainJoin
@ stub NetpContinueProvisioningPackageInstall
@ stub NetpControlServices
@ stub NetpCrackNamesStatus2Win32Error
@ stub NetpDoDomainJoin
@ stub NetpDomainJoinLicensingCheck
@ stub NetpFreeLdapLsaDomainInfo
@ stub NetpGetJoinInformation
@ stub NetpGetListOfJoinableOUs
@ stub NetpGetLsaPrimaryDomain
@ stub NetpGetMachineAccountName
@ stub NetpGetNewMachineName
@ stub NetpIsSetupInProgress
@ stub NetpLogPrintHelper
@ stub NetpMachineValidToJoin
@ stub NetpManageIPCConnect
@ stub NetpQueryService
@ stub NetpSeparateUserAndDomain
@ stub NetpUnJoinDomain
@ stub NetpValidateName
@ stub NetSetuppCloseLog
@ stub NetSetuppOpenLog
