@ stub WMCheckURLExtension
@ stub WMCheckURLScheme
@ stub WMCreateBackupRestorerPrivate
@ stub WMCreateSyncReaderPriv
@ stub WMIsAvailableOffline
@ stub WMValidateData
@ stub DllRegisterServer
@ stub WMCreateBackupRestorer
@ stub WMCreateEditor
@ stub WMCreateIndexer
@ stub WMCreateProfileManager
@ stub WMCreateReader
@ stub WMCreateReaderPriv
@ stub WMCreateSyncReader
@ stub WMCreateWriter
@ stub WMCreateWriterFileSink
@ stub WMCreateWriterNetworkSink
@ stub WMCreateWriterPriv
@ stub WMCreateWriterPushSink
@ stub WMIsContentProtected
