@ stdcall EmptyWorkingSet(long)
@ stdcall EnumDeviceDrivers(ptr long ptr)
@ stdcall EnumPageFilesA(ptr ptr)
@ stdcall EnumPageFilesW(ptr ptr)
@ stdcall EnumProcessModules(long ptr long ptr)
@ stdcall EnumProcesses(ptr long ptr)
@ stdcall GetDeviceDriverBaseNameA(ptr str long)
@ stdcall GetDeviceDriverBaseNameW(ptr wstr long)
@ stdcall GetDeviceDriverFileNameA(ptr str long)
@ stdcall GetDeviceDriverFileNameW(ptr wstr long)
@ stdcall GetMappedFileNameA(long ptr str long)
@ stdcall GetMappedFileNameW(long ptr wstr long)
@ stdcall GetModuleBaseNameA(long long ptr long)
@ stdcall GetModuleBaseNameW(long long ptr long)
@ stdcall GetModuleFileNameExA(long long str long)
@ stdcall GetModuleFileNameExW(long long wstr long)
@ stdcall GetModuleInformation(long long ptr long)
@ stdcall GetPerformanceInfo(ptr long)
@ stdcall GetProcessImageFileNameA(long ptr long)
@ stdcall GetProcessImageFileNameW(long ptr long)
@ stdcall GetProcessMemoryInfo(long ptr long)
@ stdcall GetWsChanges(long ptr long)
@ stdcall InitializeProcessForWsWatch(long)
@ stdcall QueryWorkingSet(long ptr long)
@ stdcall QueryWorkingSetEx(long ptr long)
