@ stub AuthzAccessCheck
@ stub AuthzAddSidsToContext
@ stub AuthzCachedAccessCheck
@ stub AuthzEnumerateSecurityEventSources
@ stub AuthzEvaluateSacl
@ stub AuthzFreeAuditEvent
@ stub AuthzFreeContext
@ stub AuthzFreeHandle
@ stub AuthzFreeResourceManager
@ stub AuthzGetInformationFromContext
@ stub AuthzInitializeContextFromAuthzContext
@ stub AuthzInitializeContextFromSid
@ stub AuthzInitializeContextFromToken
@ stub AuthzInitializeObjectAccessAuditEvent
@ stub AuthzInitializeObjectAccessAuditEvent2
@ stdcall AuthzInitializeResourceManager(long ptr ptr ptr wstr ptr)
@ stdcall AuthzInstallSecurityEventSource(long ptr)
@ stub AuthzOpenObjectAudit
@ stub AuthzRegisterSecurityEventSource
@ stub AuthzReportSecurityEvent
@ stub AuthzReportSecurityEventFromParams
@ stub AuthzUninstallSecurityEventSource
@ stub AuthzUnregisterSecurityEventSource
@ stub AuthziAllocateAuditParams
@ stub AuthziCheckContextMembership
@ stub AuthziFreeAuditEventType
@ stub AuthziFreeAuditParams
@ stub AuthziFreeAuditQueue
@ stub AuthziGenerateAdminAlertAuditW
@ stub AuthziInitializeAuditEvent
@ stub AuthziInitializeAuditEventType
@ stub AuthziInitializeAuditParams
@ stub AuthziInitializeAuditParamsFromArray
@ stub AuthziInitializeAuditParamsWithRM
@ stub AuthziInitializeAuditQueue
@ stub AuthziInitializeContextFromSid
@ stub AuthziLogAuditEvent
@ stub AuthziModifyAuditEvent2
@ stub AuthziModifyAuditEvent
@ stub AuthziModifyAuditEventType
@ stub AuthziModifyAuditQueue
@ stub AuthziSourceAudit
