@ stdcall DIFXAPISetLogCallbackA(ptr ptr)
@ stdcall DIFXAPISetLogCallbackW(ptr ptr)
@ stdcall DriverPackageGetPathA(str ptr ptr)
@ stdcall DriverPackageGetPathW(wstr ptr ptr)
@ stdcall DriverPackageInstallA(str long ptr ptr)
@ stdcall DriverPackageInstallW(wstr long ptr ptr)
@ stdcall DriverPackagePreinstallA(str long)
@ stdcall DriverPackagePreinstallW(wstr long)
@ stdcall DriverPackageUninstallA(str long ptr ptr)
@ stdcall DriverPackageUninstallW(wstr long ptr ptr)
@ stdcall SetDifxLogCallbackA(ptr ptr)
@ stdcall SetDifxLogCallbackW(ptr ptr)
