@ stub GetCLRVersionForPSVersion
@ stub PerformWSManPluginReportCompletion
@ stub WSManPluginCommand
@ stub WSManPluginConnect
@ stub WSManPluginReceive
@ stub WSManPluginReleaseCommandContext
@ stub WSManPluginReleaseShellContext
@ stub WSManPluginSend
@ stub WSManPluginShell
@ stub WSManPluginShutdown
@ stub WSManPluginSignal
@ stub WSManPluginStartup
