@ stub TdhAggregatePayloadFilters
@ stub TdhApplyPayloadFilter
@ stub TdhCleanupPayloadEventFilterDescriptor
@ stub TdhCloseDecodingHandle
@ stub TdhCreatePayloadFilter
@ stub TdhDeletePayloadFilter
@ stub TdhEnumerateManifestProviderEvents
@ stub TdhEnumerateProviderFieldInformation
@ stub TdhEnumerateProviderFilters
@ stdcall TdhEnumerateProviders(ptr ptr)
@ stub TdhEnumerateRemoteWBEMProviderFieldInformation
@ stub TdhEnumerateRemoteWBEMProviders
@ stub TdhFormatProperty
@ stub TdhGetAllEventsInformation
@ stub TdhGetDecodingParameter
@ stub TdhGetEventInformation
@ stub TdhGetEventMapInformation
@ stub TdhGetManifestEventInformation
@ stub TdhGetProperty
@ stub TdhGetPropertyOffsetAndSize
@ stub TdhGetPropertySize
@ stub TdhGetWppMessage
@ stub TdhGetWppProperty
@ stdcall TdhLoadManifest(wstr)
@ stdcall TdhLoadManifestFromBinary(wstr)
@ stub TdhOpenDecodingHandle
@ stub TdhQueryProviderFieldInformation
@ stub TdhQueryRemoteWBEMProviderFieldInformation
@ stub TdhSetDecodingParameter
@ stub TdhUnloadManifest
@ stub TdhValidatePayloadFilter
@ stub TdhpFindMatchClassFromWBEM
@ stub TdhpGetBestTraceEventInfoWBEM
@ stub TdhpGetEventMapInfoWBEM
