@ stdcall CommandLineToArgvW(wstr ptr) shell32.CommandLineToArgvW
@ stub GetCurrentProcessExplicitAppUserModelID
@ stdcall SetCurrentProcessExplicitAppUserModelID(wstr) shell32.SetCurrentProcessExplicitAppUserModelID
