@ stub SnmpSvcAddrIsIpx
@ stub SnmpSvcAddrToSocket
@ stub SnmpSvcBufRevAndCpy
@ stub SnmpSvcBufRevInPlace
@ stub SnmpSvcDecodeMessage
@ stub SnmpSvcEncodeMessage
@ stub SnmpSvcGenerateAuthFailTrap
@ stub SnmpSvcGenerateColdStartTrap
@ stub SnmpSvcGenerateLinkDownTrap
@ stub SnmpSvcGenerateLinkUpTrap
@ stub SnmpSvcGenerateTrap
@ stub SnmpSvcGenerateWarmStartTrap
@ stub SnmpSvcGetEnterpriseOID
@ stub SnmpSvcGetUptime
@ stub SnmpSvcInitUptime
@ stub SnmpSvcReleaseMessage
@ stub SnmpSvcReportEvent
@ stub SnmpSvcSetLogLevel
@ stub SnmpSvcSetLogType
@ stub SnmpUtilAnsiToUnicode
@ stub SnmpUtilAsnAnyCpy
@ stub SnmpUtilAsnAnyFree
@ stub SnmpUtilDbgPrint
@ stub SnmpUtilIdsToA
@ stdcall SnmpUtilMemAlloc(long)
@ stdcall SnmpUtilMemFree(ptr)
@ stdcall SnmpUtilMemReAlloc(ptr long)
@ stub SnmpUtilOctetsCmp
@ stub SnmpUtilOctetsCpy
@ stub SnmpUtilOctetsFree
@ stub SnmpUtilOctetsNCmp
@ stub SnmpUtilOidAppend
@ stub SnmpUtilOidCmp
@ stdcall SnmpUtilOidCpy(ptr ptr)
@ stdcall SnmpUtilOidFree(ptr)
@ stub SnmpUtilOidNCmp
@ stub SnmpUtilOidToA
@ stub SnmpUtilPrintAsnAny
@ stub SnmpUtilPrintOid
@ stub SnmpUtilStrlenW
@ stub SnmpUtilUnicodeToAnsi
@ stub SnmpUtilVarBindCpy
@ stdcall SnmpUtilVarBindFree(ptr)
@ stub SnmpUtilVarBindListCpy
@ stub SnmpUtilVarBindListFree
