@ stub WofEnumEntries
@ stub WofFileEnumFiles
@ stub WofGetDriverVersion
@ stub WofIsExternalFile
@ stub WofSetFileDataLocation
@ stub WofShouldCompressBinaries
@ stub WofWimAddEntry
@ stub WofWimEnumFiles
@ stub WofWimRemoveEntry
@ stub WofWimSuspendEntry
@ stub WofWimUpdateEntry
