@ stub    DCIBeginAccess
@ stdcall DCICloseProvider(long)
@ stub    DCICreateOffscreen
@ stub    DCICreateOverlay
@ stub    DCICreatePrimary
@ stub    DCIDestroy
@ stub    DCIDraw
@ stub    DCIEndAccess
@ stub    DCIEnum
@ stdcall DCIOpenProvider()
@ stub    DCISetClipList
@ stub    DCISetDestination
@ stub    DCISetSrcDestClip
@ stdcall DllEntryPoint(long long ptr) DllMain
@ stub    GetDCRegionData
@ stub    GetWindowRegionData
@ stub    WinWatchClose
@ stub    WinWatchDidStatusChange
@ stub    WinWatchGetClipList
@ stub    WinWatchNotify
@ stub    WinWatchOpen
