@ stub IsVolumeSnapshotted
@ stub VssFreeSnapshotProperties
@ stub ShouldBlockRevert
@ stub -arch=arm ??0CVssJetWriter@@QAA@XZ
@ stub -arch=i386 ??0CVssJetWriter@@QAE@XZ
@ stub -arch=win64 ??0CVssJetWriter@@QEAA@XZ
@ cdecl -arch=arm ??0CVssWriter@@QAA@XZ(ptr) VSSAPI_CVssWriter_default_ctor
@ thiscall -arch=i386 ??0CVssWriter@@QAE@XZ(ptr) VSSAPI_CVssWriter_default_ctor
@ cdecl -arch=win64 ??0CVssWriter@@QEAA@XZ(ptr) VSSAPI_CVssWriter_default_ctor
@ stub -arch=arm ??1CVssJetWriter@@UAA@XZ
@ stub -arch=i386 ??1CVssJetWriter@@UAE@XZ
@ stub -arch=win64 ??1CVssJetWriter@@UEAA@XZ
@ cdecl -arch=arm ??1CVssWriter@@UAA@XZ(ptr) VSSAPI_CVssWriter_dtor
@ thiscall -arch=i386 ??1CVssWriter@@UAE@XZ(ptr) VSSAPI_CVssWriter_dtor
@ cdecl -arch=win64 ??1CVssWriter@@UEAA@XZ(ptr) VSSAPI_CVssWriter_dtor
@ stub -arch=arm ?AreComponentsSelected@CVssJetWriter@@IBA_NXZ
@ stub -arch=i386 ?AreComponentsSelected@CVssJetWriter@@IBG_NXZ
@ stub -arch=win64 ?AreComponentsSelected@CVssJetWriter@@IEBA_NXZ
@ stub -arch=arm ?AreComponentsSelected@CVssWriter@@IBA_NXZ
@ stub -arch=i386 ?AreComponentsSelected@CVssWriter@@IBG_NXZ
@ stub -arch=win64 ?AreComponentsSelected@CVssWriter@@IEBA_NXZ
@ stdcall -arch=win32 ?CreateVssBackupComponents@@YGJPAPAVIVssBackupComponents@@@Z(ptr) VSSAPI_CreateVssBackupComponents
@ stdcall -arch=win64 ?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z(ptr) VSSAPI_CreateVssBackupComponents
@ stub -arch=win32 ?CreateVssExamineWriterMetadata@@YGJPAGPAPAVIVssExamineWriterMetadata@@@Z
@ stub -arch=win64 ?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z
@ stub ?CreateVssSnapshotSetDescription@@YGJU_GUID@@JPAPAVIVssSnapshotSetDescription@@@Z
@ stub -arch=arm ?GetBackupType@CVssJetWriter@@IBA?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=i386 ?GetBackupType@CVssJetWriter@@IBG?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=win64 ?GetBackupType@CVssJetWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=arm ?GetBackupType@CVssWriter@@IBA?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=i386 ?GetBackupType@CVssWriter@@IBG?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=win64 ?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ
@ stub -arch=arm ?GetContext@CVssJetWriter@@IBAJXZ
@ stub -arch=i386 ?GetContext@CVssJetWriter@@IBGJXZ
@ stub -arch=win64 ?GetContext@CVssJetWriter@@IEBAJXZ
@ stub -arch=arm ?GetContext@CVssWriter@@IBAJXZ
@ stub -arch=i386 ?GetContext@CVssWriter@@IBGJXZ
@ stub -arch=win64 ?GetContext@CVssWriter@@IEBAJXZ
@ stub -arch=arm ?GetCurrentLevel@CVssJetWriter@@IBA?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=i386 ?GetCurrentLevel@CVssJetWriter@@IBG?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=win64 ?GetCurrentLevel@CVssJetWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=arm ?GetCurrentLevel@CVssWriter@@IBA?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=i386 ?GetCurrentLevel@CVssWriter@@IBG?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=win64 ?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ
@ stub -arch=arm ?GetCurrentSnapshotSetId@CVssJetWriter@@IBA?AU_GUID@@XZ
@ stub -arch=i386 ?GetCurrentSnapshotSetId@CVssJetWriter@@IBG?AU_GUID@@XZ
@ stub -arch=win64 ?GetCurrentSnapshotSetId@CVssJetWriter@@IEBA?AU_GUID@@XZ
@ stub -arch=arm ?GetCurrentSnapshotSetId@CVssWriter@@IBA?AU_GUID@@XZ
@ stub -arch=i386 ?GetCurrentSnapshotSetId@CVssWriter@@IBG?AU_GUID@@XZ
@ stub -arch=win64 ?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ
@ stub -arch=arm ?GetCurrentVolumeArray@CVssJetWriter@@IBAPAPBGXZ
@ stub -arch=i386 ?GetCurrentVolumeArray@CVssJetWriter@@IBGPAPBGXZ
@ stub -arch=win64 ?GetCurrentVolumeArray@CVssJetWriter@@IEBAPEAPEBGXZ
@ stub -arch=arm ?GetCurrentVolumeArray@CVssWriter@@IBAPAPBGXZ
@ stub -arch=i386 ?GetCurrentVolumeArray@CVssWriter@@IBGPAPBGXZ
@ stub -arch=win64 ?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ
@ stub -arch=arm ?GetCurrentVolumeCount@CVssJetWriter@@IBAIXZ
@ stub -arch=i386 ?GetCurrentVolumeCount@CVssJetWriter@@IBGIXZ
@ stub -arch=win64 ?GetCurrentVolumeCount@CVssJetWriter@@IEBAIXZ
@ stub -arch=arm ?GetCurrentVolumeCount@CVssWriter@@IBAIXZ
@ stub -arch=i386 ?GetCurrentVolumeCount@CVssWriter@@IBGIXZ
@ stub -arch=win64 ?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ
@ stub -arch=arm ?GetRestoreType@CVssJetWriter@@IBA?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=i386 ?GetRestoreType@CVssJetWriter@@IBG?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=win64 ?GetRestoreType@CVssJetWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=arm ?GetRestoreType@CVssWriter@@IBA?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=i386 ?GetRestoreType@CVssWriter@@IBG?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=win64 ?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ
@ stub -arch=arm ?GetSnapshotDeviceName@CVssJetWriter@@IBAJPBGPAPBG@Z
@ stub -arch=i386 ?GetSnapshotDeviceName@CVssJetWriter@@IBGJPBGPAPBG@Z
@ stub -arch=win64 ?GetSnapshotDeviceName@CVssJetWriter@@IEBAJPEBGPEAPEBG@Z
@ stub -arch=arm ?GetSnapshotDeviceName@CVssWriter@@IBAJPBGPAPBG@Z
@ stub -arch=i386 ?GetSnapshotDeviceName@CVssWriter@@IBGJPBGPAPBG@Z
@ stub -arch=win64 ?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z
@ stub -arch=arm ?Initialize@CVssJetWriter@@QAAJU_GUID@@PBG_N211K@Z
@ stub -arch=i386 ?Initialize@CVssJetWriter@@QAGJU_GUID@@PBG_N211K@Z
@ stub -arch=win64 ?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211K@Z
@ cdecl -arch=arm ?Initialize@CVssWriter@@QAAJU_GUID@@PBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z(ptr int128 wstr long long long long long long wstr) VSSAPI_CVssWriter_Initialize
@ thiscall -arch=i386 ?Initialize@CVssWriter@@QAGJU_GUID@@PBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z(ptr int128 wstr long long long long long long wstr) VSSAPI_CVssWriter_Initialize
@ cdecl -arch=win64 ?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z(ptr int128 wstr long long long long long long wstr) VSSAPI_CVssWriter_Initialize
@ stub -arch=arm ?InstallAlternateWriter@CVssWriter@@QAAJU_GUID@@0@Z
@ stub -arch=i386 ?InstallAlternateWriter@CVssWriter@@QAGJU_GUID@@0@Z
@ stub -arch=win64 ?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z
@ stub -arch=arm ?IsBootableSystemStateBackedUp@CVssJetWriter@@IBA_NXZ
@ stub -arch=i386 ?IsBootableSystemStateBackedUp@CVssJetWriter@@IBG_NXZ
@ stub -arch=win64 ?IsBootableSystemStateBackedUp@CVssJetWriter@@IEBA_NXZ
@ stub -arch=arm ?IsBootableSystemStateBackedUp@CVssWriter@@IBA_NXZ
@ stub -arch=i386 ?IsBootableSystemStateBackedUp@CVssWriter@@IBG_NXZ
@ stub -arch=win64 ?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ
@ stub -arch=arm ?IsPartialFileSupportEnabled@CVssJetWriter@@IBA_NXZ
@ stub -arch=i386 ?IsPartialFileSupportEnabled@CVssJetWriter@@IBG_NXZ
@ stub -arch=win64 ?IsPartialFileSupportEnabled@CVssJetWriter@@IEBA_NXZ
@ stub -arch=arm ?IsPartialFileSupportEnabled@CVssWriter@@IBA_NXZ
@ stub -arch=i386 ?IsPartialFileSupportEnabled@CVssWriter@@IBG_NXZ
@ stub -arch=win64 ?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ
@ stub -arch=arm ?IsPathAffected@CVssJetWriter@@IBA_NPBG@Z
@ stub -arch=i386 ?IsPathAffected@CVssJetWriter@@IBG_NPBG@Z
@ stub -arch=win64 ?IsPathAffected@CVssJetWriter@@IEBA_NPEBG@Z
@ stub -arch=arm ?IsPathAffected@CVssWriter@@IBA_NPBG@Z
@ stub -arch=i386 ?IsPathAffected@CVssWriter@@IBG_NPBG@Z
@ stub -arch=win64 ?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z
@ stub ?LoadVssSnapshotSetDescription@@YGJPBGPAPAVIVssSnapshotSetDescription@@U_GUID@@@Z
@ stub -arch=arm ?OnAbortBegin@CVssJetWriter@@UAAXXZ
@ stub -arch=i386 ?OnAbortBegin@CVssJetWriter@@UAGXXZ
@ stub -arch=win64 ?OnAbortBegin@CVssJetWriter@@UEAAXXZ
@ stub -arch=arm ?OnAbortEnd@CVssJetWriter@@UAAXXZ
@ stub -arch=i386 ?OnAbortEnd@CVssJetWriter@@UAGXXZ
@ stub -arch=win64 ?OnAbortEnd@CVssJetWriter@@UEAAXXZ
@ stub -arch=arm ?OnBackOffIOOnVolume@CVssWriter@@UAA_NPAGU_GUID@@1@Z
@ stub -arch=i386 ?OnBackOffIOOnVolume@CVssWriter@@UAG_NPAGU_GUID@@1@Z
@ stub -arch=win64 ?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z
@ stub -arch=arm ?OnBackupComplete@CVssWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnBackupComplete@CVssWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnBackupCompleteBegin@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnBackupCompleteBegin@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnBackupCompleteEnd@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=i386 ?OnBackupCompleteEnd@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=win64 ?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z
@ stub -arch=arm ?OnBackupShutdown@CVssWriter@@UAA_NU_GUID@@@Z
@ stub -arch=i386 ?OnBackupShutdown@CVssWriter@@UAG_NU_GUID@@@Z
@ stub -arch=win64 ?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z
@ stub -arch=arm ?OnContinueIOOnVolume@CVssWriter@@UAA_NPAGU_GUID@@1@Z
@ stub -arch=i386 ?OnContinueIOOnVolume@CVssWriter@@UAG_NPAGU_GUID@@1@Z
@ stub -arch=win64 ?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z
@ stub -arch=arm ?OnFreezeBegin@CVssJetWriter@@UAA_NXZ
@ stub -arch=i386 ?OnFreezeBegin@CVssJetWriter@@UAG_NXZ
@ stub -arch=win64 ?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ
@ stub -arch=arm ?OnFreezeEnd@CVssJetWriter@@UAA_N_N@Z
@ stub -arch=i386 ?OnFreezeEnd@CVssJetWriter@@UAG_N_N@Z
@ stub -arch=win64 ?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z
@ stub -arch=arm ?OnIdentify@CVssJetWriter@@UAA_NPAVIVssCreateWriterMetadata@@@Z
@ stub -arch=i386 ?OnIdentify@CVssJetWriter@@UAG_NPAVIVssCreateWriterMetadata@@@Z
@ stub -arch=win64 ?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z
@ stub -arch=arm ?OnIdentify@CVssWriter@@UAA_NPAVIVssCreateWriterMetadata@@@Z
@ stub -arch=i386 ?OnIdentify@CVssWriter@@UAG_NPAVIVssCreateWriterMetadata@@@Z
@ stub -arch=win64 ?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z
@ stub -arch=arm ?OnPostRestore@CVssWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPostRestore@CVssWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPostRestoreBegin@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPostRestoreBegin@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPostRestoreEnd@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=i386 ?OnPostRestoreEnd@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=win64 ?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z
@ stub -arch=arm ?OnPostSnapshot@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPostSnapshot@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPostSnapshot@CVssWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPostSnapshot@CVssWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPreRestore@CVssWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPreRestore@CVssWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPreRestoreBegin@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPreRestoreBegin@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPreRestoreEnd@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=i386 ?OnPreRestoreEnd@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=win64 ?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z
@ stub -arch=arm ?OnPrepareBackup@CVssWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPrepareBackup@CVssWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPrepareBackupBegin@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@@Z
@ stub -arch=i386 ?OnPrepareBackupBegin@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@@Z
@ stub -arch=win64 ?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z
@ stub -arch=arm ?OnPrepareBackupEnd@CVssJetWriter@@UAA_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=i386 ?OnPrepareBackupEnd@CVssJetWriter@@UAG_NPAVIVssWriterComponents@@_N@Z
@ stub -arch=win64 ?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z
@ stub -arch=arm ?OnPrepareSnapshotBegin@CVssJetWriter@@UAA_NXZ
@ stub -arch=i386 ?OnPrepareSnapshotBegin@CVssJetWriter@@UAG_NXZ
@ stub -arch=win64 ?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ
@ stub -arch=arm ?OnPrepareSnapshotEnd@CVssJetWriter@@UAA_N_N@Z
@ stub -arch=i386 ?OnPrepareSnapshotEnd@CVssJetWriter@@UAG_N_N@Z
@ stub -arch=win64 ?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z
@ stub -arch=arm ?OnThawBegin@CVssJetWriter@@UAA_NXZ
@ stub -arch=i386 ?OnThawBegin@CVssJetWriter@@UAG_NXZ
@ stub -arch=win64 ?OnThawBegin@CVssJetWriter@@UEAA_NXZ
@ stub -arch=arm ?OnThawEnd@CVssJetWriter@@UAA_N_N@Z
@ stub -arch=i386 ?OnThawEnd@CVssJetWriter@@UAG_N_N@Z
@ stub -arch=win64 ?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z
@ stub -arch=arm ?OnVSSApplicationStartup@CVssWriter@@UAA_NXZ
@ stub -arch=i386 ?OnVSSApplicationStartup@CVssWriter@@UAG_NXZ
@ stub -arch=win64 ?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ
@ stub -arch=arm ?OnVSSShutdown@CVssWriter@@UAA_NXZ
@ stub -arch=i386 ?OnVSSShutdown@CVssWriter@@UAG_NXZ
@ stub -arch=win64 ?OnVSSShutdown@CVssWriter@@UEAA_NXZ
@ stub -arch=arm ?SetWriterFailure@CVssJetWriter@@IAAJJ@Z
@ stub -arch=i386 ?SetWriterFailure@CVssJetWriter@@IAGJJ@Z
@ stub -arch=win64 ?SetWriterFailure@CVssJetWriter@@IEAAJJ@Z
@ stub -arch=arm ?SetWriterFailure@CVssWriter@@IAAJJ@Z
@ stub -arch=i386 ?SetWriterFailure@CVssWriter@@IAGJJ@Z
@ stub -arch=win64 ?SetWriterFailure@CVssWriter@@IEAAJJ@Z
@ cdecl -arch=arm ?Subscribe@CVssWriter@@QAAJK@Z(ptr long) VSSAPI_CVssWriter_Subscribe
@ thiscall -arch=i386 ?Subscribe@CVssWriter@@QAGJK@Z(ptr long) VSSAPI_CVssWriter_Subscribe
@ cdecl -arch=win64 ?Subscribe@CVssWriter@@QEAAJK@Z(ptr long) VSSAPI_CVssWriter_Subscribe
@ stub -arch=arm ?Uninitialize@CVssJetWriter@@QAAXXZ
@ stub -arch=i386 ?Uninitialize@CVssJetWriter@@QAGXXZ
@ stub -arch=win64 ?Uninitialize@CVssJetWriter@@QEAAXXZ
@ cdecl -arch=arm ?Unsubscribe@CVssWriter@@QAAJXZ(ptr) VSSAPI_CVssWriter_Unsubscribe
@ thiscall -arch=i386 ?Unsubscribe@CVssWriter@@QAGJXZ(ptr) VSSAPI_CVssWriter_Unsubscribe
@ cdecl -arch=win64 ?Unsubscribe@CVssWriter@@QEAAJXZ(ptr) VSSAPI_CVssWriter_Unsubscribe
@ stdcall CreateVssBackupComponentsInternal(ptr)
@ stub CreateVssExamineWriterMetadataInternal
@ stub CreateVssExpressWriterInternal
@ stub CreateWriter
@ stub CreateWriterEx
@ stdcall -private DllCanUnloadNow()
@ stub DllGetClassObject
@ stub GetProviderMgmtInterface
@ stub GetProviderMgmtInterfaceInternal
@ stub IsVolumeSnapshottedInternal
@ stub ShouldBlockRevertInternal
@ stub VssFreeSnapshotPropertiesInternal
