@ stub USBD_CreateConfigurationRequestEx
@ stub USBD_ParseConfigurationDescriptorEx
@ stub USBD_ParseDescriptors
@ stub USBD_AllocateDeviceName
@ stub USBD_CalculateUsbBandwidth
@ stub USBD_CompleteRequest
@ stub USBD_CreateConfigurationRequest
@ stub _USBD_CreateConfigurationRequestEx@8
@ stub USBD_CreateDevice
@ stub USBD_Debug_GetHeap
@ stub USBD_Debug_LogEntry
@ stub USBD_Debug_RetHeap
@ stub USBD_Dispatch
@ stub USBD_FreeDeviceMutex
@ stub USBD_FreeDeviceName
@ stub USBD_GetDeviceInformation
@ stub USBD_GetInterfaceLength
@ stub USBD_GetPdoRegistryParameter
@ stub USBD_GetSuspendPowerState
@ stub USBD_GetUSBDIVersion
@ stub USBD_InitializeDevice
@ stub USBD_MakePdoName
@ stub USBD_ParseConfigurationDescriptor
@ stub _USBD_ParseConfigurationDescriptorEx@28
@ stub _USBD_ParseDescriptors@16
@ stub USBD_QueryBusTime
@ stub USBD_RegisterHcDeviceCapabilities
@ stub USBD_RegisterHcFilter
@ stub USBD_RegisterHostController
@ stub USBD_RemoveDevice
@ stub USBD_RestoreDevice
@ stub USBD_SetSuspendPowerState
@ stub USBD_WaitDeviceMutex
