@ stub EvtArchiveExportedLog
@ stub EvtCancel
@ stub EvtClearLog
@ stub EvtClose
@ stub EvtCreateBookmark
@ stub EvtCreateRenderContext
@ stub EvtExportLog
@ stub EvtFormatMessage
@ stub EvtGetChannelConfigProperty
@ stub EvtGetEventInfo
@ stub EvtGetEventMetadataProperty
@ stub EvtGetExtendedStatus
@ stub EvtGetLogInfo
@ stub EvtGetObjectArrayProperty
@ stub EvtGetObjectArraySize
@ stub EvtGetPublisherMetadataProperty
@ stub EvtGetQueryInfo
@ stub EvtIntAssertConfig
@ stub EvtIntCreateBinXMLFromCustomXML
@ stub EvtIntCreateLocalLogfile
@ stub EvtIntGetClassicLogDisplayName
@ stub EvtIntRenderResourceEventTemplate
@ stub EvtIntReportAuthzEventAndSourceAsync
@ stub EvtIntReportEventAndSourceAsync
@ stub EvtIntRetractConfig
@ stub EvtIntSysprepCleanup
@ stub EvtIntWriteXmlEventToLocalLogfile
@ stub EvtNext
@ stub EvtNextChannelPath
@ stub EvtNextEventMetadata
@ stub EvtNextPublisherId
@ stub EvtOpenChannelConfig
@ stub EvtOpenChannelEnum
@ stub EvtOpenEventMetadataEnum
@ stub EvtOpenLog
@ stub EvtOpenPublisherEnum
@ stub EvtOpenPublisherMetadata
@ stub EvtOpenSession
@ stub EvtQuery
@ stub EvtRender
@ stub EvtSaveChannelConfig
@ stub EvtSeek
@ stub EvtSetChannelConfigProperty
@ stub EvtSetObjectArrayProperty
@ stub EvtSubscribe
@ stub EvtUpdateBookmark
