--- Test 1
Line1
"Line2"
--- Test 2
Test quotes "&" work
--- Test 3
"&"
--- Test 4
"<"
--- Test 5
">"
--- Test 6
"\"
--- Test 7
"|"
--- Test 8
"`"
--- Test 9
"""
--- Test 10
--- Test 11
--- Test 12
passed1
--- Test 13
passed2@space@
--- Test 14
foobar
--- Test 15
No whitespace
--- Test 16
--- Test 17
--- Test 18
No prompts or I would not get here1
No prompts or I would not get here2
%hello1%
%hello2
%hello3:h=t%
%hello4%%
one = %1
1
2
3
4
5
@todo_wine@var contents: 11
var=33@space@
99
