
@pwd@>echo Tests for cmd's builtin commands BAT@space@
Tests for cmd's builtin commands BAT
--- success/failure for basics
SUCCESS 0
FAILURE 33
foo@space@
SUCCESS 666
FAILURE 1
ERRORLEVEL 666
--- success/failure for IF/FOR blocks
SUCCESS 666
SUCCESS 666
FAILURE 33
FAILURE 34
SUCCESS 666
SUCCESS 666
SUCCESS 0
FAILURE 33
--- success/failure for external command
FAILURE 1
@todo_wine@ERRORLEVEL 3
FAILURE 1
ERRORLEVEL 9009
foo@space@
SUCCESS 0
foo@space@
FAILURE 1024
FAILURE 1
--- success/failure for CALL command
FAILURE 1
SUCCESS 0
FAILURE 1024
SUCCESS 0
SUCCESS 0
FAILURE 666
FAILURE 2
FAILURE 666
FAILURE 666
FAILURE 1
FAILURE 666
FAILURE 666
FAILURE 1
foo@space@
SUCCESS 0
foo@space@
FAILURE 1025
FAILURE 2
--- success/failure for pipes
b
SUCCESS 0
FAILURE 1
a
SUCCESS 0
FAILURE 3
a
SUCCESS 0
FAILURE 255
FAILURE 255
--- success/failure for START command
@todo_wine@FAILURE 1
foo@space@
SUCCESS 1024
@todo_wine@SUCCESS 666
--- success/failure for TYPE command
FAILURE 1
SUCCESS 0
FAILURE 1
@todo_wine@a@space@
@todo_wine@b@space@
@todo_wine@FAILURE 1
@todo_wine@---
FAILURE 1
--- success/failure for COPY command
FAILURE 1
SUCCESS 0
FAILURE 1
FAILURE 1
FAILURE 1
--- success/failure for MOVE command
FAILURE 1
SUCCESS 0
FAILURE 1
FAILURE 1
FAILURE 1
--- success/failure for RENAME command
FAILURE 1
FAILURE 1
FAILURE 1
FAILURE 1
SUCCESS 0
--- success/failure for ERASE command
FAILURE 1
SUCCESS 0
FAILURE 1
FAILURE 1
SUCCESS 0
--- success/failure for change drive command
SUCCESS 666
FAILURE 1
SUCCESS 0
FAILURE 1
--- success/failure for MKDIR,MD command
FAILURE 1
SUCCESS 0
FAILURE 1
FAILURE 1
SUCCESS 0
--- success/failure for CD command
SUCCESS 0
FAILURE 1
SUCCESS 0
SUCCESS 0
--- success/failure for PUSHD/POPD commands
SUCCESS 0
SUCCESS 0
FAILURE 1
SUCCESS 666
FAILURE 1
ERRORLEVEL 666
--- success/failure for DIR command
FAILURE 1
FAILURE 1
SUCCESS 0
SUCCESS 0
FAILURE 1
SUCCESS 0
--- success/failure for RMDIR/RD command
FAILURE 1
FAILURE 145
FAILURE 267
SUCCESS 666
FAILURE 2
FAILURE 3
ERRORLEVEL 666
ERRORLEVEL 666
ERRORLEVEL 666
ERRORLEVEL 666
ERRORLEVEL 666
ERRORLEVEL 666
--- success/failure for MKLINK command
FAILURE 1
FAILURE 1
FAILURE 1
FAILURE 1
FAILURE 1
SUCCESS 0
FAILURE 1
--- success/failure for SETLOCAL/ENDLOCAL commands
FAILURE 1
SUCCESS 0
SUCCESS 666
@todo_wine@SUCCESS@space@
SUCCESS 0
--- success/failure for DATE command
SUCCESS 0
FAILURE 1
--- success/failure for TIME command
SUCCESS 0
FAILURE 1
--- success/failure for BREAK command
@todo_wine@SUCCESS 666
@todo_wine@SUCCESS 666
--- success/failure for VER command
SUCCESS 0
SUCCESS 0
FAILURE 1
--- success/failure for VERIFY command
SUCCESS 0
SUCCESS 0
FAILURE 1
--- success/failure for VOL command
SUCCESS 0
SUCCESS 0
FAILURE 1
FAILURE 1
--- success/failure for LABEL command
FAILURE 1
--- success/failure for PATH command
SUCCESS 666
SUCCESS 666
PATH=@:\I\dont\Exist@space@
SUCCESS 666
PATH=(null)
SUCCESS 666
--- success/failure for SET command
SUCCESS 666
SUCCESS 666
FAILURE 1
SUCCESS 666
SUCCESS 666
FAILURE 1
FAILURE 1
--- success/failure for ASSOC command
SUCCESS 666
FAILURE 1
FAILURE 1
--- success/failure for FTYPE command
SUCCESS 666
FAILURE 2
FAILURE 2
--- success/failure for SHIFT command
FAILURE 1
SUCCESS 666
SUCCESS 666
--- success/failure for HELP command
FAILURE 1
FAILURE 1
SUCCESS 0
--- success/failure for PROMPT command
SUCCESS 666
--- success/failure for CLS command
@todo_wine@@formfeed@SUCCESS 666
@todo_wine@@formfeed@SUCCESS 666
FAILURE 1
--- success/failure for COLOR command
FAILURE 1
--- success/failure for TITLE command
SUCCESS 666
SUCCESS 666
--- success/failure for CHOICE command
FAILURE 1
FAILURE 1
FAILURE 2
FAILURE 1
--- success/failure for MORE command
SUCCESS 0
foo@space@

SUCCESS 0
@todo_wine@SUCCESS 0
@todo_wine@--- success/failure for PAUSE command
FAILURE 1
---
