# ordinal exports
1 stdcall WOWGetDescriptor(long ptr)

@ stdcall WOWCallback16(long long)
@ stdcall WOWCallback16Ex(long long long ptr ptr)
@ stdcall WOWDirectedYield16(long)
@ stdcall WOWGetVDMPointer(long long long)
@ stdcall WOWGetVDMPointerFix(long long long)
@ stdcall WOWGetVDMPointerUnfix(long)
@ stdcall WOWGlobalAlloc16(long long)
@ stdcall WOWGlobalAllocLock16(long long ptr)
@ stdcall WOWGlobalFree16(long)
@ stdcall WOWGlobalLock16(long)
@ stdcall WOWGlobalLockSize16(long ptr)
@ stdcall WOWGlobalUnlock16(long)
@ stdcall WOWGlobalUnlockFree16(long)
@ stdcall WOWHandle16(long long)
@ stdcall WOWHandle32(long long)
@ stdcall WOWYield16()
