/*
 * Copyright 2017 Fabian Maurer
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    helpstring("Enhanced Video Renderer"),
    threading(both),
    uuid(fa10746c-9b63-4b6c-bc49-fc300ea5f256)
]
coclass EnhancedVideoRenderer { interface IBaseFilter; }

[
    helpstring("MF Video Mixer"),
    threading(both),
    uuid(e474e05a-ab65-4f6a-827c-218b1baaf31f)
]
coclass MFVideoMixer9 { interface IMFTransform; }

[
    helpstring("MF Video Presenter"),
    threading(both),
    uuid(98455561-5136-4d28-ab08-4cee40ea2781)
]
coclass MFVideoPresenter9 { interface IMFVideoPresenter; }
