/*
 * COM classes for winegstreamer
 *
 * Copyright 2019 Nikolay Sivov
 * Copyright 2019 Zebediah Figura
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    helpstring("AVI Splitter"),
    threading(both),
    uuid(1b544c20-fd0b-11ce-8c63-00aa0044b51e)
]
coclass AviSplitter {}

[
    helpstring("MPEG Audio Decoder"),
    threading(both),
    uuid(4a2286e0-7bef-11ce-9bd9-0000e202599c)
]
coclass CMpegAudioCodec {}

[
    helpstring("MPEG Video Decoder"),
    threading(both),
    uuid(feb50740-7bef-11ce-9bd9-0000e202599c)
]
coclass CMpegVideoCodec {}

[
    helpstring("MPEG Layer-3 Decoder"),
    threading(both),
    uuid(38be3000-dbf4-11d0-860e-00a024cfef6d)
]
coclass mpeg_layer3_decoder {}

[
    helpstring("MPEG-I Stream Splitter"),
    threading(both),
    uuid(336475d0-942a-11ce-a870-00aa002feab5)
]
coclass MPEG1Splitter {}

[
    helpstring("Wave Parser"),
    threading(both),
    uuid(d51bd5a1-7548-11cf-a520-0080c77ef58a)
]
coclass WAVEParser {}

[
    helpstring("GStreamer parser using decodebin"),
    threading(both),
    uuid(f9d8d64e-a144-47dc-8ee0-f53498372c29)
]
coclass decodebin_parser {}

[
    threading(both),
    uuid(88753b26-5b24-49bd-b2e7-0c445c78c982)
]
coclass VideoProcessorMFT {}

[
    helpstring("Generic Decodebin Byte Stream Handler"),
    threading(both),
    uuid(317df618-5e5a-468a-9f15-d827a9a08162)
]
coclass GStreamerByteStreamHandler {}

[
    threading(both),
    uuid(2eeb4adf-4578-4d10-bca7-bb955f56320a)
]
coclass CWMADecMediaObject {};

[
    threading(both),
    uuid(32d186a7-218f-4c75-8876-dd77273a8999)
]
coclass CMSAACDecMFT {}

[
    threading(both),
    uuid(82d353df-90bd-4382-8bc2-3f6192b76e34)
]
coclass CWMVDecMediaObject {}

[
    threading(both),
    uuid(62ce7e72-4c71-4d20-b15d-452831a87d9d)
]
coclass CMSH264DecoderMFT {}

[
    threading(both),
    uuid(f447b69e-1884-4a7e-8055-346f74d6edb3)
]
coclass CResamplerMediaObject {}

[
    threading(both),
    uuid(98230571-0087-4204-b020-3282538e57d3)
]
coclass CColorConvertDMO {}

[
    threading(both),
    uuid(11275a82-5e5a-47fd-a01c-3683c12fb196)
]
coclass MFMP3SinkClassFactory {}

[
    helpstring("MF MPEG4 Sink Class Factory"),
    threading(both),
    uuid(a22c4fc7-6e91-4e1d-89e9-53b2667b72ba)
]
coclass MFMPEG4SinkClassFactory {}
