@ stub WdsGetPointer
#@ extern g_Kernel32
#@ extern g_bEnableDiagnosticMode
@ stub ConstructPartialMsgIfA
@ stub ConstructPartialMsgIfW
@ stub ConstructPartialMsgVA
@ stub ConstructPartialMsgVW
@ stub CurrentIP
@ stub EndMajorTask
@ stub EndMinorTask
@ stub GetMajorTask
@ stub GetMajorTaskA
@ stub GetMinorTask
@ stub GetMinorTaskA
@ stub StartMajorTask
@ stub StartMinorTask
@ stub WdsAbortBlackboardItemEnum
@ stub WdsAddModule
@ stub WdsAddUsmtLogStack
@ stub WdsAllocCollection
@ stub WdsCollectionAddValue
@ stub WdsCollectionGetValue
@ stub WdsCopyBlackboardItems
@ stub WdsCopyBlackboardItemsEx
@ stub WdsCreateBlackboard
@ stub WdsDeleteBlackboardValue
@ stub WdsDeleteEvent
@ stub WdsDestroyBlackboard
@ stub WdsDuplicateData
@ stub WdsEnableDiagnosticMode
@ stub WdsEnableExit
@ stub WdsEnableExitEx
@ stub WdsEnumFirstBlackboardItem
@ stub WdsEnumFirstCollectionValue
@ stub WdsEnumNextBlackboardItem
@ stub WdsEnumNextCollectionValue
@ stub WdsExecuteWorkQueue
@ stub WdsExecuteWorkQueue2
@ stub WdsExecuteWorkQueueEx
@ stub WdsExitImmediately
@ stub WdsExitImmediatelyEx
@ stub WdsFreeCollection
@ stub WdsFreeData
@ stub WdsGenericSetupLogInit
@ stub WdsGetAssertFlags
@ stub WdsGetBlackboardBinaryData
@ stub WdsGetBlackboardStringA
@ stub WdsGetBlackboardStringW
@ stub WdsGetBlackboardUintPtr
@ stub WdsGetBlackboardValue
@ stub WdsGetCurrentExecutionGroup
@ stub WdsGetSetupLog
@ stub WdsTempDir
@ stub WdsInitialize
@ stub WdsInitializeCallbackArray
@ stub WdsInitializeDataBinary
@ stub WdsInitializeDataStringA
@ stub WdsInitializeDataStringW
@ stub WdsInitializeDataUInt32
@ stub WdsInitializeDataUInt64
@ stub WdsIsDiagnosticModeEnabled
@ stub WdsIterateOfflineQueue
@ stub WdsIterateQueue
@ stub WdsLockBlackboardValue
@ stub WdsLockExecutionGroup
@ stub WdsLogCreate
@ stub WdsLogDestroy
@ stub WdsLogRegStockProviders
@ stub WdsLogRegisterProvider
@ stub WdsLogStructuredException
@ stub WdsLogUnRegStockProviders
@ stub WdsLogUnRegisterProvider
@ stub WdsPackCollection
@ stub WdsPublish
@ stub WdsPublishEx
@ stub WdsPublishImmediateAsynch
@ stub WdsPublishImmediateEx
@ stub WdsPublishOffline
@ stub WdsSeqAlloc
@ stub WdsSeqFree
@ stub WdsSetAssertFlags
@ stub WdsSetBlackboardValue
@ stub WdsSetNextExecutionGroup
@ stub WdsSetUILanguage
@ stub WdsSetupLogDestroy
@ stub WdsSetupLogInit
@ stub WdsSetLogMessageA
@ stub WdsSetLogMessageW
@ stub WdsSubscribeEx
@ stub WdsTerminate
@ stub WdsUnlockExecutionGroup
@ stub WdsUnpackCollection
@ stub WdsUnsubscribe
@ stub WdsUnsubscribeEx
@ stub WdsValidBlackboard
