1 stdcall EnumPropPages(ptr ptr long)
2 stdcall drvCommConfigDialogW(ptr long ptr)
3 stdcall drvCommConfigDialogA(ptr long ptr)
4 stdcall drvSetDefaultCommConfigW(wstr ptr long)
5 stdcall drvSetDefaultCommConfigA(str ptr long)
6 stdcall drvGetDefaultCommConfigW(wstr ptr ptr)
7 stdcall drvGetDefaultCommConfigA(str ptr ptr)
