@ cdecl winedmo_demuxer_check(str)
@ cdecl winedmo_demuxer_create(wstr ptr int64 ptr ptr ptr ptr)
@ cdecl winedmo_demuxer_destroy(ptr)
@ cdecl winedmo_demuxer_read(int64 ptr ptr ptr)
@ cdecl winedmo_demuxer_seek(int64 int64)
@ cdecl winedmo_demuxer_stream_lang(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_name(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_type(int64 long ptr ptr)
