1 stub GenericChainCertificateTrust
2 stub GenericChainFinalProv
3 stub HTTPSCertificateTrust
4 stub SoftpubDefCertInit
5 stub SoftpubFreeDefUsageCallData
6 stub SoftpubLoadDefUsageCallData
7 stub AddPersonalTrustDBPages
8 stub DllRegisterServer
9 stub DllUnregisterServer
10 stub DriverCleanupPolicy
11 stub DriverFinalPolicy
12 stub DriverInitializePolicy
13 stub FindCertsByIssuer
14 stub HTTPSFinalProv
15 stub OfficeCleanupPolicy
16 stub OfficeInitializePolicy
17 stub OpenPersonalTrustDBDialog
18 stub SoftpubAuthenticode
19 stub SoftpubCheckCert
20 stub SoftpubCleanup
21 stub SoftpubDumpStructure
22 stub SoftpubInitialize
23 stub SoftpubLoadMessage
24 stub SoftpubLoadSignature
