@ stub ExAcquireFastMutex
@ stub ExReleaseFastMutex
@ stub ExTryToAcquireFastMutex
@ stub HalClearSoftwareInterrupt
@ stub HalRequestSoftwareInterrupt
@ stub HalSystemVectorDispatchEntry
@ stub KeAcquireInStackQueuedSpinLock
@ stub KeAcquireInStackQueuedSpinLockRaiseToSynch
@ stub KeAcquireQueuedSpinLock
@ stub KeAcquireQueuedSpinLockRaiseToSynch
@ stub KeAcquireSpinLockRaiseToSynch
@ stub KeReleaseInStackQueuedSpinLock
@ stub KeReleaseQueuedSpinLock
@ stub KeTryToAcquireQueuedSpinLock
@ stub KeTryToAcquireQueuedSpinLockRaiseToSynch
@ stub KfAcquireSpinLock
@ stub KfLowerIrql
@ stub KfRaiseIrql
@ stub KfReleaseSpinLock
@ stub HalAcquireDisplayOwnership
@ stub HalAdjustResourceList
@ stub HalAllProcessorsStarted
@ stub HalAllocateAdapterChannel
@ stub HalAllocateCommonBuffer
@ stub HalAllocateCrashDumpRegisters
@ stub HalAssignSlotResources
@ stub HalBeginSystemInterrupt
@ stub HalCalibratePerformanceCounter
@ stub HalDisableSystemInterrupt
@ stub HalDisplayString
@ stub HalEnableSystemInterrupt
@ stub HalEndSystemInterrupt
@ stub HalFlushCommonBuffer
@ stub HalFreeCommonBuffer
@ stub HalGetAdapter
@ stub HalGetBusData
@ stub HalGetBusDataByOffset
@ stub HalGetEnvironmentVariable
@ stub HalGetInterruptVector
@ stub HalHandleNMI
@ stub HalInitSystem
@ stub HalInitializeProcessor
@ stub HalMakeBeep
@ stub HalProcessorIdle
@ stub HalQueryDisplayParameters
@ stub HalQueryRealTimeClock
@ stub HalReadDmaCounter
@ stub HalReportResourceUsage
@ stub HalRequestIpi
@ stub HalReturnToFirmware
@ stub HalSetBusData
@ stub HalSetBusDataByOffset
@ stub HalSetDisplayParameters
@ stub HalSetEnvironmentVariable
@ stub HalSetProfileInterval
@ stub HalSetRealTimeClock
@ stub HalSetTimeIncrement
@ stub HalStartNextProcessor
@ stub HalStartProfileInterrupt
@ stub HalStopProfileInterrupt
@ stub HalTranslateBusAddress
@ stub IoAssignDriveLetters
@ stub IoFlushAdapterBuffers
@ stub IoFreeAdapterChannel
@ stub IoFreeMapRegisters
@ stub IoMapTransfer
@ stub IoReadPartitionTable
@ stub IoSetPartitionInformation
@ stub IoWritePartitionTable
@ stub KdComPortInUse
@ stub KeAcquireSpinLock
@ stub KeFlushWriteBuffer
@ stub KeGetCurrentIrql
@ stub KeLowerIrql
@ stub KeQueryPerformanceCounter
@ stub KeRaiseIrql
@ stub KeRaiseIrqlToDpcLevel
@ stub KeRaiseIrqlToSynchLevel
@ stub KeReleaseSpinLock
@ stub KeStallExecutionProcessor
@ stub READ_PORT_BUFFER_UCHAR
@ stub READ_PORT_BUFFER_ULONG
@ stub READ_PORT_BUFFER_USHORT
@ stub READ_PORT_UCHAR
@ stub READ_PORT_ULONG
@ stub READ_PORT_USHORT
@ stub WRITE_PORT_BUFFER_UCHAR
@ stub WRITE_PORT_BUFFER_ULONG
@ stub WRITE_PORT_BUFFER_USHORT
@ stub WRITE_PORT_UCHAR
@ stub WRITE_PORT_ULONG
@ stub WRITE_PORT_USHORT
