/*
 * CE coredll.dll
 *
 * Copyright 2010, 2014 André Hentschel
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#include "config.h"

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>

#include "ntstatus.h"
#define WIN32_NO_STATUS
#include "windows.h"
#include "winternl.h"
#include "wine/debug.h"
#include "wine/ce.h"

WINE_DEFAULT_DEBUG_CHANNEL(coredll);

static HMODULE hcomctl32, hcrypt32, hgdi32, himm32, hkernel32, hmsvcrt, hshell32, hshlwapi, hunicows, huser32, hversion;

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    switch (fdwReason)
    {
        case DLL_PROCESS_ATTACH:
            hcomctl32 = LoadLibraryA("comctl32.dll");
            hcrypt32 = LoadLibraryA("crypt32.dll");
            hgdi32 = LoadLibraryA("gdi32.dll");
            himm32 = LoadLibraryA("imm32.dll");
            hkernel32 = LoadLibraryA("kernel32.dll");
            hmsvcrt = LoadLibraryA("msvcrt.dll");
            hshell32 = LoadLibraryA("shell32.dll");
            hshlwapi = LoadLibraryA("shlwapi.dll");
            hunicows = LoadLibraryA("unicows.dll");
            huser32 = LoadLibraryA("user32.dll");
            hversion = LoadLibraryA("version.dll");
            DisableThreadLibraryCalls(hinstDLL);
            break;
        case DLL_PROCESS_DETACH:
            break;
    }

    return TRUE;
}

#define EVENT_PULSE 1
#define EVENT_RESET 2
#define EVENT_SET   3

BOOL WINAPI myEventModify( HMODULE hmod, unsigned int e )
{
    TRACE("%p %u\n", hmod, e);
    if (e==EVENT_PULSE) return PulseEvent(hmod);
    if (e==EVENT_RESET) return ResetEvent(hmod);
    if (e==EVENT_SET) return SetEvent(hmod);
    return FALSE;
}

BOOL WINAPI COREDLL_EventModify( HMODULE hmod, unsigned int e )
{
    return wrap2((long)hmod,e,myEventModify);
}

/***********************************************************************
 *           GetProcAddressW    (COREDLL.530)
 *
 * Find the address of an exported symbol in a loaded dll.
 *
 * PARAMS
 *  hModule  [I] Handle to the dll returned by LoadLibraryW().
 *  function [I] Name of the symbol, or an integer ordinal number < 16384
 *
 * RETURNS
 *  Success: A pointer to the symbol in the process address space.
 *  Failure: NULL. Use GetLastError() to determine the cause.
 */
FARPROC WINAPI COREDLL_GetProcAddressW( HMODULE hModule, LPCWSTR function )
{
    NTSTATUS    nts;
    FARPROC     fp;

    if (!hModule) hModule = NtCurrentTeb()->Peb->ImageBaseAddress;

    /* FIXME: untested hack */

    if ((ULONG_PTR)function >> 16)
    {
        ANSI_STRING     str;
        char functionA[MAX_PATH];

        WideCharToMultiByte(CP_ACP, 0, function, -1, functionA, MAX_PATH, NULL, NULL);

        RtlInitAnsiString( &str, functionA );
        nts = LdrGetProcedureAddress( hModule, &str, 0, (void**)&fp );
    }
    else
        nts = LdrGetProcedureAddress( hModule, NULL, LOWORD(function), (void**)&fp );

    if (nts != STATUS_SUCCESS)
    {
        SetLastError( RtlNtStatusToDosError( nts ) );
        fp = NULL;
    }

    return fp;
}

/***********************************************************************
 *           rt_udiv
 *
 * integer divide function (arm)
 *
 * PARAMS
 *  divisor
 *  dividend
 *
 * RETURNS (registers)
 *  r0 = result
 *  r1 = remainer
 */
void WINAPI COREDLL_rt_udiv( unsigned int divisor, unsigned int dividend )
{
    unsigned int x1=0,y1=0;
    div_t result;

    if(dividend != 0) {
/*
    	x1 = divisor / dividend;
    	y1 = divisor % dividend;
*/
        result = div (dividend, divisor);
	x1 = result.quot; y1 = result.rem;
    }
TRACE("%d/%d = %d:%d\n", dividend, divisor, x1,y1);

    asm volatile ( "mov r0,%[res]\n"
    	  "mov r1,%[rmm]\n"
	: /* no output */
        : [res] "r" (x1), [rmm] "r" (y1)
	: /* no clobbers */
    );
    return;
}
/***********************************************************************
 *           rt_sdiv
 *
 * integer divide function (arm)
 *
 * PARAMS
 *  divisor
 *  dividend
 *
 * RETURNS (registers)
 *  r0 = result
 *  r1 = remainer
 */
void WINAPI COREDLL_rt_sdiv( int divisor, int dividend )
{
    int x1=0,y1=0;

    if(dividend != 0) {
    	x1 = divisor / dividend;
    	y1 = divisor % dividend;
    }
TRACE("%d/%d = %d:%d\n", dividend, divisor, x1,y1);

    asm volatile ( "mov r0,%[res]\n"
    	  "mov r1,%[rmm]\n"
	: /* no output */
        : [res] "r" (x1), [rmm] "r" (y1)
	: /* no clobbers */
    );
    return;
}
/***********************************************************************
 *           _getstdfilex
 *
 * retrurn standard file descriptors
 *
 * PARAMS
 *  file descriptor int
 *
 * RETURNS
 *  file *
 *//*
FILE * COREDLL_getstdfilex( int n )
{
   switch (n) {
	case 0: return (FILE *)stdin;
	case 1: return (FILE *)stdout;
	case 2: return (FILE *)stderr;
	default: return (FILE *)NULL;
   }
}
*/


FIXFUNC1(kernel32, InitializeCriticalSection, InitializeCriticalSection)
FIXFUNC1(kernel32, DeleteCriticalSection, DeleteCriticalSection)
FIXFUNC1(kernel32, EnterCriticalSection, EnterCriticalSection)
FIXFUNC1(kernel32, LeaveCriticalSection, LeaveCriticalSection)
FIXFUNC1(kernel32, ExitThread, ExitThread)
FIXFUNC1(kernel32, InterlockedIncrement, InterlockedIncrement)
FIXFUNC1(kernel32, InterlockedDecrement, InterlockedDecrement)
FIXFUNC2(kernel32, InterlockedExchange, InterlockedExchange)
FIXFUNC1(kernel32, TlsGetValue, TlsGetValue)
FIXFUNC2(kernel32, TlsSetValue, TlsSetValue)
FIXFUNC2(kernel32, CompareFileTime, CompareFileTime)
FIXFUNC2(kernel32, SystemTimeToFileTime, SystemTimeToFileTime)
FIXFUNC2(kernel32, FileTimeToSystemTime, FileTimeToSystemTime)
FIXFUNC2(kernel32, FileTimeToLocalFileTime, FileTimeToLocalFileTime)
FIXFUNC2(kernel32, LocalFileTimeToFileTime, LocalFileTimeToFileTime)
FIXFUNC1(kernel32, GetLocalTime, GetLocalTime)
FIXFUNC1(kernel32, SetLocalTime, SetLocalTime)
FIXFUNC1(kernel32, GetSystemTime, GetSystemTime)
FIXFUNC1(kernel32, SetSystemTime, SetSystemTime)
FIXFUNC1(kernel32, GetTimeZoneInformation, GetTimeZoneInformation)
FIXFUNC1(kernel32, SetTimeZoneInformation, SetTimeZoneInformation)
FIXFUNC3(msvcrt, memchr, memchr)
FIXFUNC2(kernel32, LocalAlloc, LocalAlloc)
FIXFUNC3(kernel32, LocalReAlloc, LocalReAlloc)
FIXFUNC1(kernel32, LocalSize, LocalSize)
FIXFUNC1(kernel32, LocalFree, LocalFree)
FIXFUNC3(kernel32, HeapCreate, HeapCreate)
FIXFUNC1(kernel32, HeapDestroy, HeapDestroy)
FIXFUNC3(kernel32, HeapAlloc, HeapAlloc)
FIXFUNC4(kernel32, HeapReAlloc, HeapReAlloc)
FIXFUNC3(kernel32, HeapSize, HeapSize)
FIXFUNC3(kernel32, HeapFree, HeapFree)
FIXFUNC0(kernel32, GetProcessHeap, GetProcessHeap)
FIXFUNC3(kernel32, HeapValidate, HeapValidate)
FIXFUNC3(user32, wvsprintfW, wvsprintfW)
FIXFUNC2(msvcrt, wcscat, wcscat)
FIXFUNC2(msvcrt, wcschr, wcschr)
FIXFUNC2(msvcrt, wcscmp, wcscmp)
FIXFUNC2(msvcrt, wcscpy, wcscpy)
FIXFUNC2(msvcrt, wcscspn, wcscspn)
FIXFUNC1(msvcrt, wcslen, wcslen)
FIXFUNC3(msvcrt, wcsncat, wcsncat)
FIXFUNC3(msvcrt, wcsncmp, wcsncmp)
FIXFUNC3(msvcrt, wcsncpy, wcsncpy)
FIXFUNC3(msvcrt, _wcsnset, _wcsnset)
FIXFUNC2(msvcrt, wcspbrk, wcspbrk)
FIXFUNC2(msvcrt, wcsrchr, wcsrchr)
FIXFUNC1(msvcrt, _wcsrev, _wcsrev)
FIXFUNC2(msvcrt, _wcsset, _wcsset)
FIXFUNC2(msvcrt, wcsspn, wcsspn)
FIXFUNC2(msvcrt, wcsstr, wcsstr)
FIXFUNC1(msvcrt, _wcsdup, _wcsdup)
FIXFUNC3(msvcrt, wcstombs, wcstombs)
FIXFUNC3(msvcrt, mbstowcs, mbstowcs)
FIXFUNC2(msvcrt, wcstok, wcstok)
FIXFUNC1(msvcrt, _wtol, _wtol)
FIXFUNC1(kernel32, GlobalMemoryStatus, GlobalMemoryStatus)
FIXFUNC4(user32, SystemParametersInfoW, SystemParametersInfoW)
FIXFUNC6(gdi32, CreateDIBSection, CreateDIBSection)
FIXFUNC2(gdi32, EqualRgn, EqualRgn)
FIXFUNC2(user32, CreateAcceleratorTableW, CreateAcceleratorTableW)
FIXFUNC1(user32, DestroyAcceleratorTable, DestroyAcceleratorTable)
FIXFUNC2(user32, LoadAcceleratorsW, LoadAcceleratorsW)
FIXFUNC1(user32, RegisterClassW, RegisterClassW)
FIXFUNC2(user32, CopyRect, CopyRect)
FIXFUNC2(user32, EqualRect, EqualRect)
FIXFUNC3(user32, InflateRect, InflateRect)
FIXFUNC3(user32, IntersectRect, IntersectRect)
FIXFUNC1(user32, IsRectEmpty, IsRectEmpty)
FIXFUNC3(user32, OffsetRect, OffsetRect)
FIXFUNC2(user32, PtInRect, PtInRect)
FIXFUNC5(user32, SetRect, SetRect)
FIXFUNC1(user32, SetRectEmpty, SetRectEmpty)
FIXFUNC3(user32, SubtractRect, SubtractRect)
FIXFUNC3(user32, UnionRect, UnionRect)
FIXFUNC1(kernel32, ClearCommBreak, ClearCommBreak)
FIXFUNC3(kernel32, ClearCommError, ClearCommError)
FIXFUNC2(kernel32, EscapeCommFunction, EscapeCommFunction)
FIXFUNC2(kernel32, GetCommMask, GetCommMask)
FIXFUNC2(kernel32, GetCommModemStatus, GetCommModemStatus)
FIXFUNC2(kernel32, GetCommProperties, GetCommProperties)
FIXFUNC2(kernel32, GetCommState, GetCommState)
FIXFUNC2(kernel32, GetCommTimeouts, GetCommTimeouts)
FIXFUNC2(kernel32, PurgeComm, PurgeComm)
FIXFUNC1(kernel32, SetCommBreak, SetCommBreak)
FIXFUNC2(kernel32, SetCommMask, SetCommMask)
FIXFUNC2(kernel32, SetCommState, SetCommState)
FIXFUNC2(kernel32, SetCommTimeouts, SetCommTimeouts)
FIXFUNC3(kernel32, SetupComm, SetupComm)
FIXFUNC2(kernel32, TransmitCommChar, TransmitCommChar)
FIXFUNC3(kernel32, WaitCommEvent, WaitCommEvent)
FIXFUNC5(unicows, CryptAcquireContextW, CryptAcquireContextW)
FIXFUNC6(unicows, CryptSignHashW, CryptSignHashW)
FIXFUNC6(unicows, CryptVerifySignatureW, CryptVerifySignatureW)
FIXFUNC2(unicows, CryptSetProviderW, CryptSetProviderW)
FIXFUNC4(unicows, CryptSetProviderExW, CryptSetProviderExW)
FIXFUNC5(unicows, CryptGetDefaultProviderW, CryptGetDefaultProviderW)
FIXFUNC6(unicows, CryptEnumProviderTypesW, CryptEnumProviderTypesW)
FIXFUNC6(unicows, CryptEnumProvidersW, CryptEnumProvidersW)
FIXFUNC2(kernel32, CreateDirectoryW, CreateDirectoryW)
FIXFUNC1(kernel32, RemoveDirectoryW, RemoveDirectoryW)
FIXFUNC2(kernel32, GetTempPathW, GetTempPathW)
FIXFUNC2(kernel32, MoveFileW, MoveFileW)
FIXFUNC3(kernel32, CopyFileW, CopyFileW)
FIXFUNC1(kernel32, DeleteFileW, DeleteFileW)
FIXFUNC1(kernel32, GetFileAttributesW, GetFileAttributesW)
FIXFUNC2(kernel32, FindFirstFileW, FindFirstFileW)
FIXFUNC7(kernel32, CreateFileW, CreateFileW)
FIXFUNC2(kernel32, SetFileAttributesW, SetFileAttributesW)
FIXFUNC5(kernel32, ReadFile, ReadFile)
FIXFUNC5(kernel32, WriteFile, WriteFile)
FIXFUNC2(kernel32, GetFileSize, GetFileSize)
FIXFUNC4(kernel32, SetFilePointer, SetFilePointer)
FIXFUNC2(kernel32, GetFileInformationByHandle, GetFileInformationByHandle)
FIXFUNC1(kernel32, FlushFileBuffers, FlushFileBuffers)
FIXFUNC4(kernel32, GetFileTime, GetFileTime)
FIXFUNC4(kernel32, SetFileTime, SetFileTime)
FIXFUNC1(kernel32, SetEndOfFile, SetEndOfFile)
FIXFUNC8(kernel32, DeviceIoControl, DeviceIoControl)
FIXFUNC1(kernel32, FindClose, FindClose)
FIXFUNC2(kernel32, FindNextFileW, FindNextFileW)
FIXFUNC4(kernel32, GetDiskFreeSpaceExW, GetDiskFreeSpaceExW)
FIXFUNC1(kernel32, IsValidCodePage, IsValidCodePage)
FIXFUNC0(kernel32, GetACP, GetACP)
FIXFUNC0(kernel32, GetOEMCP, GetOEMCP)
FIXFUNC2(kernel32, GetCPInfo, GetCPInfo)
FIXFUNC1(kernel32, IsDBCSLeadByte, IsDBCSLeadByte)
FIXFUNC2(kernel32, IsDBCSLeadByteEx, IsDBCSLeadByteEx)
FIXFUNC2(msvcrt, iswctype, iswctype)
FIXFUNC1(msvcrt, towlower, towlower)
FIXFUNC1(msvcrt, towupper, towupper)
FIXFUNC6(kernel32, MultiByteToWideChar, MultiByteToWideChar)
FIXFUNC8(kernel32, WideCharToMultiByte, WideCharToMultiByte)
FIXFUNC6(kernel32, CompareStringW, CompareStringW)
FIXFUNC6(kernel32, LCMapStringW, LCMapStringW)
FIXFUNC4(kernel32, GetLocaleInfoW, GetLocaleInfoW)
FIXFUNC3(kernel32, SetLocaleInfoW, SetLocaleInfoW)
FIXFUNC6(kernel32, GetTimeFormatW, GetTimeFormatW)
FIXFUNC6(kernel32, GetDateFormatW, GetDateFormatW)
FIXFUNC6(kernel32, GetNumberFormatW, GetNumberFormatW)
FIXFUNC6(kernel32, GetCurrencyFormatW, GetCurrencyFormatW)
FIXFUNC4(kernel32, EnumCalendarInfoW, EnumCalendarInfoW)
FIXFUNC3(kernel32, EnumTimeFormatsW, EnumTimeFormatsW)
FIXFUNC3(kernel32, EnumDateFormatsW, EnumDateFormatsW)
FIXFUNC2(kernel32, IsValidLocale, IsValidLocale)
FIXFUNC1(kernel32, ConvertDefaultLocale, ConvertDefaultLocale)
FIXFUNC0(kernel32, GetSystemDefaultLangID, GetSystemDefaultLangID)
FIXFUNC0(kernel32, GetUserDefaultLangID, GetUserDefaultLangID)
FIXFUNC0(kernel32, GetSystemDefaultLCID, GetSystemDefaultLCID)
FIXFUNC0(kernel32, GetUserDefaultLCID, GetUserDefaultLCID)
FIXFUNC4(kernel32, GetStringTypeW, GetStringTypeW)
FIXFUNC5(kernel32, GetStringTypeExW, GetStringTypeExW)
FIXFUNC5(kernel32, FoldStringW, FoldStringW)
FIXFUNC2(kernel32, EnumSystemLocalesW, EnumSystemLocalesW)
FIXFUNC2(kernel32, EnumSystemCodePagesW, EnumSystemCodePagesW)
FIXFUNC1(user32, CharLowerW, CharLowerW)
FIXFUNC2(user32, CharLowerBuffW, CharLowerBuffW)
FIXFUNC2(user32, CharUpperBuffW, CharUpperBuffW)
FIXFUNC1(user32, CharUpperW, CharUpperW)
FIXFUNC2(user32, CharPrevW, CharPrevW)
FIXFUNC1(user32, CharNextW, CharNextW)
FIXFUNC2(kernel32, lstrcmpW, lstrcmpW)
FIXFUNC2(kernel32, lstrcmpiW, lstrcmpiW)
FIXFUNC3(msvcrt, _wcsnicmp, _wcsnicmp)
FIXFUNC2(msvcrt, _wcsicmp, _wcsicmp)
FIXFUNC1(msvcrt, _wcslwr, _wcslwr)
FIXFUNC1(msvcrt, _wcsupr, _wcsupr)
FIXFUNC7(kernel32, FormatMessageW, FormatMessageW)
FIXFUNC12(user32, CreateWindowExW, CreateWindowExW)
FIXFUNC7(user32, SetWindowPos, SetWindowPos)
FIXFUNC2(user32, GetWindowRect, GetWindowRect)
FIXFUNC2(user32, GetClientRect, GetClientRect)
FIXFUNC3(user32, InvalidateRect, InvalidateRect)
FIXFUNC2(user32, GetWindow, GetWindow)
FIXFUNC1(user32, WindowFromPoint, WindowFromPoint)
FIXFUNC2(user32, ChildWindowFromPoint, ChildWindowFromPoint)
FIXFUNC2(user32, ClientToScreen, ClientToScreen)
FIXFUNC2(user32, ScreenToClient, ScreenToClient)
FIXFUNC2(user32, SetWindowTextW, SetWindowTextW)
FIXFUNC3(user32, GetWindowTextW, GetWindowTextW)
FIXFUNC3(user32, SetWindowLongW, SetWindowLongW)
FIXFUNC2(user32, GetWindowLongW, GetWindowLongW)
FIXFUNC2(user32, BeginPaint, BeginPaint)
FIXFUNC2(user32, EndPaint, EndPaint)
FIXFUNC1(user32, GetDC, GetDC)
FIXFUNC2(user32, ReleaseDC, ReleaseDC)
FIXFUNC4(user32, DefWindowProcW, DefWindowProcW)
FIXFUNC1(user32, DestroyWindow, DestroyWindow)
FIXFUNC2(user32, ShowWindow, ShowWindow)
FIXFUNC1(user32, UpdateWindow, UpdateWindow)
FIXFUNC2(user32, SetParent, SetParent)
FIXFUNC1(user32, GetParent, GetParent)
FIXFUNC1(user32, GetWindowDC, GetWindowDC)
FIXFUNC1(user32, IsWindow, IsWindow)
FIXFUNC6(user32, MoveWindow, MoveWindow)
FIXFUNC3(user32, GetUpdateRgn, GetUpdateRgn)
FIXFUNC3(user32, GetUpdateRect, GetUpdateRect)
FIXFUNC1(user32, BringWindowToTop, BringWindowToTop)
FIXFUNC1(user32, GetWindowTextLengthW, GetWindowTextLengthW)
FIXFUNC2(user32, IsChild, IsChild)
FIXFUNC2(user32, ValidateRect, ValidateRect)
FIXFUNC4(user32, SetScrollInfo, SetScrollInfo)
FIXFUNC4(user32, SetScrollPos, SetScrollPos)
FIXFUNC5(user32, SetScrollRange, SetScrollRange)
FIXFUNC3(user32, GetScrollInfo, GetScrollInfo)
FIXFUNC3(user32, GetClassNameW, GetClassNameW)
FIXFUNC4(user32, MapWindowPoints, MapWindowPoints)
FIXFUNC5(user32, CallWindowProcW, CallWindowProcW)
FIXFUNC2(user32, FindWindowW, FindWindowW)
FIXFUNC2(user32, EnableWindow, EnableWindow)
FIXFUNC1(user32, IsWindowEnabled, IsWindowEnabled)
FIXFUNC8(user32, ScrollWindowEx, ScrollWindowEx)
FIXFUNC4(user32, PostThreadMessageW, PostThreadMessageW)
FIXFUNC2(user32, EnumWindows, EnumWindows)
FIXFUNC2(user32, GetWindowThreadProcessId, GetWindowThreadProcessId)
FIXFUNC2(unicows, sndPlaySoundW, sndPlaySoundW)
FIXFUNC3(unicows, PlaySoundW, PlaySoundW)
FIXFUNC5(unicows, WNetAddConnection3W, WNetAddConnection3W)
FIXFUNC3(unicows, WNetCancelConnection2W, WNetCancelConnection2W)
FIXFUNC1(unicows, WNetConnectionDialog1W, WNetConnectionDialog1W)
FIXFUNC1(unicows, WNetDisconnectDialog1W, WNetDisconnectDialog1W)
FIXFUNC3(unicows, WNetGetConnectionW, WNetGetConnectionW)
FIXFUNC4(unicows, WNetGetUniversalNameW, WNetGetUniversalNameW)
FIXFUNC3(unicows, WNetGetUserW, WNetGetUserW)
FIXFUNC5(unicows, WNetOpenEnumW, WNetOpenEnumW)
FIXFUNC4(unicows, WNetEnumResourceW, WNetEnumResourceW)
FIXFUNC1(kernel32, RegCloseKey, RegCloseKey)
FIXFUNC9(kernel32, RegCreateKeyExW, RegCreateKeyExW)
FIXFUNC2(unicows, RegDeleteKeyW, RegDeleteKeyW)
FIXFUNC2(kernel32, RegDeleteValueW, RegDeleteValueW)
FIXFUNC8(kernel32, RegEnumValueW, RegEnumValueW)
FIXFUNC8(kernel32, RegEnumKeyExW, RegEnumKeyExW)
FIXFUNC5(kernel32, RegOpenKeyExW, RegOpenKeyExW)
FIXFUNC12(kernel32, RegQueryInfoKeyW, RegQueryInfoKeyW)
FIXFUNC6(kernel32, RegQueryValueExW, RegQueryValueExW)
FIXFUNC6(kernel32, RegSetValueExW, RegSetValueExW)
FIXFUNC1(unicows, GetOpenFileNameW, GetOpenFileNameW)
FIXFUNC1(unicows, GetSaveFileNameW, GetSaveFileNameW)
FIXFUNC2(kernel32, TerminateThread, TerminateThread)
FIXFUNC6(kernel32, CreateThread, CreateThread)
FIXFUNC10(kernel32, CreateProcessW, CreateProcessW)
FIXFUNC4(kernel32, CreateEventW, CreateEventW)
FIXFUNC1(kernel32, Sleep, Sleep)
FIXFUNC2(kernel32, WaitForSingleObject, WaitForSingleObject)
FIXFUNC4(kernel32, WaitForMultipleObjects, WaitForMultipleObjects)
FIXFUNC1(kernel32, SuspendThread, SuspendThread)
FIXFUNC1(kernel32, ResumeThread, ResumeThread)
FIXFUNC2(kernel32, SetThreadContext, SetThreadContext)
FIXFUNC2(kernel32, WaitForDebugEvent, WaitForDebugEvent)
FIXFUNC3(kernel32, ContinueDebugEvent, ContinueDebugEvent)
FIXFUNC1(kernel32, DebugActiveProcess, DebugActiveProcess)
FIXFUNC5(kernel32, ReadProcessMemory, ReadProcessMemory)
FIXFUNC5(kernel32, WriteProcessMemory, WriteProcessMemory)
FIXFUNC3(kernel32, FlushInstructionCache, FlushInstructionCache)
FIXFUNC3(kernel32, OpenProcess, OpenProcess)
FIXFUNC2(kernel32, SetThreadPriority, SetThreadPriority)
FIXFUNC1(kernel32, GetThreadPriority, GetThreadPriority)
FIXFUNC0(kernel32, GetLastError, GetLastError)
FIXFUNC1(kernel32, SetLastError, SetLastError)
FIXFUNC2(kernel32, GetExitCodeThread, GetExitCodeThread)
FIXFUNC2(kernel32, GetExitCodeProcess, GetExitCodeProcess)
FIXFUNC1(kernel32, IsBadCodePtr, IsBadCodePtr)
FIXFUNC2(kernel32, IsBadReadPtr, IsBadReadPtr)
FIXFUNC2(kernel32, IsBadWritePtr, IsBadWritePtr)
FIXFUNC4(kernel32, VirtualAlloc, VirtualAlloc)
FIXFUNC3(kernel32, VirtualFree, VirtualFree)
FIXFUNC4(kernel32, VirtualProtect, VirtualProtect)
FIXFUNC3(kernel32, VirtualQuery, VirtualQuery)
FIXFUNC1(kernel32, LoadLibraryW, LoadLibraryW)
FIXFUNC1(kernel32, FreeLibrary, FreeLibrary)
FIXFUNC3(kernel32, FindResourceW, FindResourceW)
FIXFUNC2(kernel32, LoadResource, LoadResource)
FIXFUNC2(kernel32, SizeofResource, SizeofResource)
FIXFUNC0(kernel32, GetTickCount, GetTickCount)
FIXFUNC1(kernel32, GetProcessVersion, GetProcessVersion)
FIXFUNC3(kernel32, GetModuleFileNameW, GetModuleFileNameW)
FIXFUNC1(kernel32, QueryPerformanceCounter, QueryPerformanceCounter)
FIXFUNC1(kernel32, QueryPerformanceFrequency, QueryPerformanceFrequency)
FIXFUNC1(kernel32, OutputDebugStringW, OutputDebugStringW)
FIXFUNC1(kernel32, GetSystemInfo, GetSystemInfo)
FIXFUNC4(kernel32, RaiseException, RaiseException)
FIXFUNC2(kernel32, TerminateProcess, TerminateProcess)
FIXFUNC6(kernel32, CreateFileMappingW, CreateFileMappingW)
FIXFUNC5(kernel32, MapViewOfFile, MapViewOfFile)
FIXFUNC1(kernel32, UnmapViewOfFile, UnmapViewOfFile)
FIXFUNC2(kernel32, FlushViewOfFile, FlushViewOfFile)
FIXFUNC1(kernel32, CloseHandle, CloseHandle)
FIXFUNC3(kernel32, CreateMutexW, CreateMutexW)
FIXFUNC1(kernel32, ReleaseMutex, ReleaseMutex)
FIXFUNC4(user32, CreateCaret, CreateCaret)
FIXFUNC0(user32, DestroyCaret, DestroyCaret)
FIXFUNC1(user32, HideCaret, HideCaret)
FIXFUNC1(user32, ShowCaret, ShowCaret)
FIXFUNC2(user32, SetCaretPos, SetCaretPos)
FIXFUNC1(user32, GetCaretPos, GetCaretPos)
FIXFUNC1(user32, SetCaretBlinkTime, SetCaretBlinkTime)
FIXFUNC0(user32, GetCaretBlinkTime, GetCaretBlinkTime)
FIXFUNC1(user32, OpenClipboard, OpenClipboard)
FIXFUNC0(user32, CloseClipboard, CloseClipboard)
FIXFUNC0(user32, GetClipboardOwner, GetClipboardOwner)
FIXFUNC2(user32, SetClipboardData, SetClipboardData)
FIXFUNC1(user32, GetClipboardData, GetClipboardData)
FIXFUNC1(user32, RegisterClipboardFormatW, RegisterClipboardFormatW)
FIXFUNC0(user32, CountClipboardFormats, CountClipboardFormats)
FIXFUNC1(user32, EnumClipboardFormats, EnumClipboardFormats)
FIXFUNC3(user32, GetClipboardFormatNameW, GetClipboardFormatNameW)
FIXFUNC0(user32, EmptyClipboard, EmptyClipboard)
FIXFUNC1(user32, IsClipboardFormatAvailable, IsClipboardFormatAvailable)
FIXFUNC2(user32, GetPriorityClipboardFormat, GetPriorityClipboardFormat)
FIXFUNC0(user32, GetOpenClipboardWindow, GetOpenClipboardWindow)
FIXFUNC1(user32, SetCursor, SetCursor)
FIXFUNC2(user32, LoadCursorW, LoadCursorW)
FIXFUNC4(user32, CheckRadioButton, CheckRadioButton)
FIXFUNC5(user32, SendDlgItemMessageW, SendDlgItemMessageW)
FIXFUNC3(user32, SetDlgItemTextW, SetDlgItemTextW)
FIXFUNC4(user32, GetDlgItemTextW, GetDlgItemTextW)
FIXFUNC5(user32, CreateDialogIndirectParamW, CreateDialogIndirectParamW)
FIXFUNC4(user32, DefDlgProcW, DefDlgProcW)
FIXFUNC5(user32, DialogBoxIndirectParamW, DialogBoxIndirectParamW)
FIXFUNC2(user32, EndDialog, EndDialog)
FIXFUNC2(user32, GetDlgItem, GetDlgItem)
FIXFUNC1(user32, GetDlgCtrlID, GetDlgCtrlID)
FIXFUNC0(user32, GetDialogBaseUnits, GetDialogBaseUnits)
FIXFUNC4(user32, GetDlgItemInt, GetDlgItemInt)
FIXFUNC3(user32, GetNextDlgTabItem, GetNextDlgTabItem)
FIXFUNC3(user32, GetNextDlgGroupItem, GetNextDlgGroupItem)
FIXFUNC2(user32, IsDialogMessageW, IsDialogMessageW)
FIXFUNC2(user32, MapDialogRect, MapDialogRect)
FIXFUNC4(user32, SetDlgItemInt, SetDlgItemInt)
FIXFUNC0(user32, GetForegroundWindow, GetForegroundWindow)
FIXFUNC1(user32, SetForegroundWindow, SetForegroundWindow)
FIXFUNC1(user32, SetActiveWindow, SetActiveWindow)
FIXFUNC1(user32, SetFocus, SetFocus)
FIXFUNC0(user32, GetFocus, GetFocus)
FIXFUNC0(user32, GetActiveWindow, GetActiveWindow)
FIXFUNC0(user32, GetCapture, GetCapture)
FIXFUNC1(user32, SetCapture, SetCapture)
FIXFUNC0(user32, ReleaseCapture, ReleaseCapture)
FIXFUNC1(kernel32, GetVersionExW, GetVersionExW)
FIXFUNC3(msvcrt, vfwprintf, vfwprintf)
FIXFUNC1(user32, CreateIconIndirect, CreateIconIndirect)
FIXFUNC1(user32, DestroyIcon, DestroyIcon)
FIXFUNC9(user32, DrawIconEx, DrawIconEx)
FIXFUNC5(unicows, ExtractIconExW, ExtractIconExW)
FIXFUNC2(user32, LoadIconW, LoadIconW)
FIXFUNC6(user32, LoadImageW, LoadImageW)
FIXFUNC1(user32, ClipCursor, ClipCursor)
FIXFUNC1(user32, GetClipCursor, GetClipCursor)
FIXFUNC0(user32, GetCursor, GetCursor)
FIXFUNC1(user32, GetCursorPos, GetCursorPos)
FIXFUNC2(user32, SetCursorPos, SetCursorPos)
FIXFUNC1(user32, ShowCursor, ShowCursor)
FIXFUNC3(comctl32, ImageList_Add, ImageList_Add)
FIXFUNC3(comctl32, ImageList_AddMasked, ImageList_AddMasked)
FIXFUNC4(comctl32, ImageList_BeginDrag, ImageList_BeginDrag)
FIXFUNC5(comctl32, ImageList_Create, ImageList_Create)
FIXFUNC1(comctl32, ImageList_Destroy, ImageList_Destroy)
FIXFUNC3(comctl32, ImageList_DragEnter, ImageList_DragEnter)
FIXFUNC1(comctl32, ImageList_DragLeave, ImageList_DragLeave)
FIXFUNC2(comctl32, ImageList_DragMove, ImageList_DragMove)
FIXFUNC1(comctl32, ImageList_DragShowNolock, ImageList_DragShowNolock)
FIXFUNC6(comctl32, ImageList_Draw, ImageList_Draw)
FIXFUNC10(comctl32, ImageList_DrawEx, ImageList_DrawEx)
FIXFUNC1(comctl32, ImageList_DrawIndirect, ImageList_DrawIndirect)
FIXFUNC0(comctl32, ImageList_EndDrag, ImageList_EndDrag)
FIXFUNC1(comctl32, ImageList_GetBkColor, ImageList_GetBkColor)
FIXFUNC2(comctl32, ImageList_GetDragImage, ImageList_GetDragImage)
FIXFUNC3(comctl32, ImageList_GetIcon, ImageList_GetIcon)
FIXFUNC3(comctl32, ImageList_GetIconSize, ImageList_GetIconSize)
FIXFUNC1(comctl32, ImageList_GetImageCount, ImageList_GetImageCount)
FIXFUNC3(comctl32, ImageList_GetImageInfo, ImageList_GetImageInfo)
FIXFUNC7(comctl32, ImageList_LoadImage, ImageList_LoadImage)
FIXFUNC6(comctl32, ImageList_Merge, ImageList_Merge)
FIXFUNC2(comctl32, ImageList_Remove, ImageList_Remove)
FIXFUNC4(comctl32, ImageList_Replace, ImageList_Replace)
FIXFUNC3(comctl32, ImageList_ReplaceIcon, ImageList_ReplaceIcon)
FIXFUNC2(comctl32, ImageList_SetBkColor, ImageList_SetBkColor)
FIXFUNC4(comctl32, ImageList_SetDragCursorImage, ImageList_SetDragCursorImage)
FIXFUNC3(comctl32, ImageList_SetIconSize, ImageList_SetIconSize)
FIXFUNC3(comctl32, ImageList_SetOverlayImage, ImageList_SetOverlayImage)
FIXFUNC5(comctl32, ImageList_Copy, ImageList_Copy)
FIXFUNC1(comctl32, ImageList_Duplicate, ImageList_Duplicate)
FIXFUNC2(comctl32, ImageList_SetImageCount, ImageList_SetImageCount)
FIXFUNC2(imm32, ImmAssociateContext, ImmAssociateContext)
FIXFUNC4(imm32, ImmConfigureIMEW, ImmConfigureIMEW)
FIXFUNC1(imm32, ImmCreateIMCC, ImmCreateIMCC)
FIXFUNC1(imm32, ImmDestroyIMCC, ImmDestroyIMCC)
FIXFUNC6(imm32, ImmEnumRegisterWordW, ImmEnumRegisterWordW)
FIXFUNC4(imm32, ImmEscapeW, ImmEscapeW)
FIXFUNC1(imm32, ImmGenerateMessage, ImmGenerateMessage)
FIXFUNC4(imm32, ImmGetCandidateListW, ImmGetCandidateListW)
FIXFUNC2(imm32, ImmGetCandidateListCountW, ImmGetCandidateListCountW)
FIXFUNC3(imm32, ImmGetCandidateWindow, ImmGetCandidateWindow)
FIXFUNC2(imm32, ImmGetCompositionFontW, ImmGetCompositionFontW)
FIXFUNC4(imm32, ImmGetCompositionStringW, ImmGetCompositionStringW)
FIXFUNC2(imm32, ImmGetCompositionWindow, ImmGetCompositionWindow)
FIXFUNC1(imm32, ImmGetContext, ImmGetContext)
FIXFUNC6(imm32, ImmGetConversionListW, ImmGetConversionListW)
FIXFUNC3(imm32, ImmGetConversionStatus, ImmGetConversionStatus)
FIXFUNC1(imm32, ImmGetDefaultIMEWnd, ImmGetDefaultIMEWnd)
FIXFUNC3(imm32, ImmGetDescriptionW, ImmGetDescriptionW)
FIXFUNC4(imm32, ImmGetGuideLineW, ImmGetGuideLineW)
FIXFUNC1(imm32, ImmGetIMCCLockCount, ImmGetIMCCLockCount)
FIXFUNC1(imm32, ImmGetIMCCSize, ImmGetIMCCSize)
FIXFUNC1(imm32, ImmGetIMCLockCount, ImmGetIMCLockCount)
FIXFUNC1(imm32, ImmGetOpenStatus, ImmGetOpenStatus)
FIXFUNC2(imm32, ImmGetProperty, ImmGetProperty)
FIXFUNC3(imm32, ImmGetRegisterWordStyleW, ImmGetRegisterWordStyleW)
FIXFUNC4(imm32, ImmIsUIMessageW, ImmIsUIMessageW)
FIXFUNC1(imm32, ImmLockIMC, ImmLockIMC)
FIXFUNC1(imm32, ImmLockIMCC, ImmLockIMCC)
FIXFUNC4(imm32, ImmNotifyIME, ImmNotifyIME)
FIXFUNC2(imm32, ImmReSizeIMCC, ImmReSizeIMCC)
FIXFUNC4(imm32, ImmRegisterWordW, ImmRegisterWordW)
FIXFUNC2(imm32, ImmReleaseContext, ImmReleaseContext)
FIXFUNC2(imm32, ImmSetCandidateWindow, ImmSetCandidateWindow)
FIXFUNC2(imm32, ImmSetCompositionFontW, ImmSetCompositionFontW)
FIXFUNC6(imm32, ImmSetCompositionStringW, ImmSetCompositionStringW)
FIXFUNC2(imm32, ImmSetCompositionWindow, ImmSetCompositionWindow)
FIXFUNC3(imm32, ImmSetConversionStatus, ImmSetConversionStatus)
FIXFUNC4(imm32, ImmGetHotKey, ImmGetHotKey)
FIXFUNC2(imm32, ImmSetOpenStatus, ImmSetOpenStatus)
FIXFUNC2(imm32, ImmSetStatusWindowPos, ImmSetStatusWindowPos)
FIXFUNC2(imm32, ImmSimulateHotKey, ImmSimulateHotKey)
FIXFUNC1(imm32, ImmUnlockIMC, ImmUnlockIMC)
FIXFUNC1(imm32, ImmUnlockIMCC, ImmUnlockIMCC)
FIXFUNC4(imm32, ImmUnregisterWordW, ImmUnregisterWordW)
FIXFUNC3(user32, SendInput, SendInput)
FIXFUNC5(user32, mouse_event, mouse_event)
FIXFUNC1(user32, GetAsyncKeyState, GetAsyncKeyState)
FIXFUNC2(user32, MapVirtualKeyW, MapVirtualKeyW)
FIXFUNC4(user32, keybd_event, keybd_event)
FIXFUNC4(user32, RegisterHotKey, RegisterHotKey)
FIXFUNC2(user32, UnregisterHotKey, UnregisterHotKey)
FIXFUNC3(user32, TranslateAcceleratorW, TranslateAcceleratorW)
FIXFUNC5(user32, InsertMenuW, InsertMenuW)
FIXFUNC4(user32, AppendMenuW, AppendMenuW)
FIXFUNC3(user32, RemoveMenu, RemoveMenu)
FIXFUNC1(user32, DestroyMenu, DestroyMenu)
FIXFUNC6(user32, TrackPopupMenuEx, TrackPopupMenuEx)
FIXFUNC2(user32, LoadMenuW, LoadMenuW)
FIXFUNC3(user32, EnableMenuItem, EnableMenuItem)
FIXFUNC3(user32, CheckMenuItem, CheckMenuItem)
FIXFUNC5(user32, CheckMenuRadioItem, CheckMenuRadioItem)
FIXFUNC3(user32, DeleteMenu, DeleteMenu)
FIXFUNC0(user32, CreateMenu, CreateMenu)
FIXFUNC0(user32, CreatePopupMenu, CreatePopupMenu)
FIXFUNC4(user32, SetMenuItemInfoW, SetMenuItemInfoW)
FIXFUNC4(user32, GetMenuItemInfoW, GetMenuItemInfoW)
FIXFUNC2(user32, GetSubMenu, GetSubMenu)
FIXFUNC1(user32, DrawMenuBar, DrawMenuBar)
FIXFUNC1(user32, MessageBeep, MessageBeep)
FIXFUNC4(user32, MessageBoxW, MessageBoxW)
FIXFUNC1(user32, DispatchMessageW, DispatchMessageW)
FIXFUNC1(user32, GetKeyState, GetKeyState)
FIXFUNC4(user32, GetMessageW, GetMessageW)
FIXFUNC0(user32, GetMessagePos, GetMessagePos)
FIXFUNC5(user32, PeekMessageW, PeekMessageW)
FIXFUNC4(user32, PostMessageW, PostMessageW)
FIXFUNC1(user32, PostQuitMessage, PostQuitMessage)
FIXFUNC4(user32, SendMessageW, SendMessageW)
FIXFUNC4(user32, SendNotifyMessageW, SendNotifyMessageW)
FIXFUNC1(user32, TranslateMessage, TranslateMessage)
FIXFUNC5(user32, MsgWaitForMultipleObjectsEx, MsgWaitForMultipleObjectsEx)
FIXFUNC2(user32, LoadBitmapW, LoadBitmapW)
FIXFUNC4(user32, LoadStringW, LoadStringW)
FIXFUNC4(user32, SetTimer, SetTimer)
FIXFUNC2(user32, KillTimer, KillTimer)
FIXFUNC3(user32, GetClassInfoW, GetClassInfoW)
FIXFUNC2(user32, GetClassLongW, GetClassLongW)
FIXFUNC3(user32, SetClassLongW, SetClassLongW)
FIXFUNC2(user32, UnregisterClassW, UnregisterClassW)
FIXFUNC1(user32, GetSystemMetrics, GetSystemMetrics)
FIXFUNC1(user32, IsWindowVisible, IsWindowVisible)
FIXFUNC4(user32, AdjustWindowRectEx, AdjustWindowRectEx)
FIXFUNC0(user32, GetDoubleClickTime, GetDoubleClickTime)
FIXFUNC1(user32, GetSysColor, GetSysColor)
FIXFUNC3(user32, SetSysColors, SetSysColors)
FIXFUNC1(user32, RegisterWindowMessageW, RegisterWindowMessageW)
FIXFUNC1(gdi32, AddFontResourceW, AddFontResourceW)
FIXFUNC1(gdi32, CreateFontIndirectW, CreateFontIndirectW)
FIXFUNC8(gdi32, ExtTextOutW, ExtTextOutW)
FIXFUNC7(gdi32, GetTextExtentExPointW, GetTextExtentExPointW)
FIXFUNC2(gdi32, GetTextMetricsW, GetTextMetricsW)
FIXFUNC1(gdi32, RemoveFontResourceW, RemoveFontResourceW)
FIXFUNC5(gdi32, CreateBitmap, CreateBitmap)
FIXFUNC3(gdi32, CreateCompatibleBitmap, CreateCompatibleBitmap)
FIXFUNC9(gdi32, BitBlt, BitBlt)
FIXFUNC12(gdi32, MaskBlt, MaskBlt)
FIXFUNC11(gdi32, StretchBlt, StretchBlt)
FIXFUNC2(gdi32, RestoreDC, RestoreDC)
FIXFUNC1(gdi32, SaveDC, SaveDC)
FIXFUNC4(gdi32, CreateDCW, CreateDCW)
FIXFUNC1(gdi32, CreateCompatibleDC, CreateCompatibleDC)
FIXFUNC1(gdi32, DeleteDC, DeleteDC)
FIXFUNC1(gdi32, DeleteObject, DeleteObject)
FIXFUNC1(gdi32, GetBkColor, GetBkColor)
FIXFUNC1(gdi32, GetBkMode, GetBkMode)
FIXFUNC2(gdi32, GetCurrentObject, GetCurrentObject)
FIXFUNC2(gdi32, GetDeviceCaps, GetDeviceCaps)
FIXFUNC1(gdi32, GetObjectType, GetObjectType)
FIXFUNC3(gdi32, GetObjectW, GetObjectW)
FIXFUNC1(gdi32, GetStockObject, GetStockObject)
FIXFUNC1(gdi32, GetTextColor, GetTextColor)
FIXFUNC2(gdi32, SelectObject, SelectObject)
FIXFUNC2(gdi32, SetBkColor, SetBkColor)
FIXFUNC2(gdi32, SetBkMode, SetBkMode)
FIXFUNC2(gdi32, SetTextColor, SetTextColor)
FIXFUNC1(gdi32, CreatePatternBrush, CreatePatternBrush)
FIXFUNC3(gdi32, CreatePen, CreatePen)
FIXFUNC3(gdi32, FillRgn, FillRgn)
FIXFUNC2(gdi32, SetROP2, SetROP2)
FIXFUNC2(gdi32, CreateDIBPatternBrushPt, CreateDIBPatternBrushPt)
FIXFUNC1(gdi32, CreatePenIndirect, CreatePenIndirect)
FIXFUNC1(gdi32, CreateSolidBrush, CreateSolidBrush)
FIXFUNC4(user32, DrawEdge, DrawEdge)
FIXFUNC2(user32, DrawFocusRect, DrawFocusRect)
FIXFUNC5(gdi32, Ellipse, Ellipse)
FIXFUNC3(user32, FillRect, FillRect)
FIXFUNC3(gdi32, GetPixel, GetPixel)
FIXFUNC1(user32, GetSysColorBrush, GetSysColorBrush)
FIXFUNC6(gdi32, PatBlt, PatBlt)
FIXFUNC3(gdi32, Polygon, Polygon)
FIXFUNC3(gdi32, Polyline, Polyline)
FIXFUNC5(gdi32, Rectangle, Rectangle)
FIXFUNC7(gdi32, RoundRect, RoundRect)
FIXFUNC4(gdi32, SetBrushOrgEx, SetBrushOrgEx)
FIXFUNC4(gdi32, SetPixel, SetPixel)
FIXFUNC5(user32, DrawTextW, DrawTextW)
FIXFUNC1(gdi32, CreatePalette, CreatePalette)
FIXFUNC2(gdi32, GetNearestPaletteIndex, GetNearestPaletteIndex)
FIXFUNC4(gdi32, GetPaletteEntries, GetPaletteEntries)
FIXFUNC4(gdi32, GetSystemPaletteEntries, GetSystemPaletteEntries)
FIXFUNC4(gdi32, SetPaletteEntries, SetPaletteEntries)
FIXFUNC2(gdi32, GetNearestColor, GetNearestColor)
FIXFUNC1(gdi32, RealizePalette, RealizePalette)
FIXFUNC3(gdi32, SelectPalette, SelectPalette)
FIXFUNC1(gdi32, AbortDoc, AbortDoc)
FIXFUNC1(gdi32, EndDoc, EndDoc)
FIXFUNC1(gdi32, EndPage, EndPage)
FIXFUNC2(gdi32, SetAbortProc, SetAbortProc)
FIXFUNC2(gdi32, StartDocW, StartDocW)
FIXFUNC1(gdi32, StartPage, StartPage)
FIXFUNC4(gdi32, EnumFontFamiliesW, EnumFontFamiliesW)
FIXFUNC4(gdi32, EnumFontsW, EnumFontsW)
FIXFUNC3(gdi32, GetTextFaceW, GetTextFaceW)
FIXFUNC4(gdi32, CombineRgn, CombineRgn)
FIXFUNC1(gdi32, CreateRectRgnIndirect, CreateRectRgnIndirect)
FIXFUNC5(gdi32, ExcludeClipRect, ExcludeClipRect)
FIXFUNC2(gdi32, GetClipBox, GetClipBox)
FIXFUNC2(gdi32, GetClipRgn, GetClipRgn)
FIXFUNC3(gdi32, GetRegionData, GetRegionData)
FIXFUNC2(gdi32, GetRgnBox, GetRgnBox)
FIXFUNC5(gdi32, IntersectClipRect, IntersectClipRect)
FIXFUNC3(gdi32, OffsetRgn, OffsetRgn)
FIXFUNC3(gdi32, PtInRegion, PtInRegion)
FIXFUNC2(gdi32, RectInRegion, RectInRegion)
FIXFUNC2(gdi32, SelectClipRgn, SelectClipRgn)
FIXFUNC4(gdi32, CreateRectRgn, CreateRectRgn)
FIXFUNC2(gdi32, RectVisible, RectVisible)
FIXFUNC5(gdi32, SetRectRgn, SetRectRgn)
FIXFUNC4(gdi32, SetViewportOrgEx, SetViewportOrgEx)
FIXFUNC7(user32, ScrollDC, ScrollDC)
FIXFUNC1(gdi32, EnableEUDC, EnableEUDC)
FIXFUNC4(user32, DrawFrameControl, DrawFrameControl)
FIXFUNC1(msvcrt, abs, abs)
FIXFUNC1(msvcrt, acos, acos)
FIXFUNC1(msvcrt, asin, asin)
FIXFUNC1(msvcrt, atan, atan)
FIXFUNC2(msvcrt, atan2, atan2)
FIXFUNC1(msvcrt, atoi, atoi)
FIXFUNC1(msvcrt, atol, atol)
FIXFUNC1(msvcrt, atof, atof)
FIXFUNC2(msvcrt, _atodbl, _atodbl)
FIXFUNC1(msvcrt, _cabs, _cabs)
FIXFUNC1(msvcrt, ceil, ceil)
FIXFUNC1(msvcrt, _chgsign, _chgsign)
FIXFUNC0(msvcrt, _clearfp, _clearfp)
FIXFUNC2(msvcrt, _controlfp, _controlfp)
FIXFUNC2(msvcrt, _copysign, _copysign)
FIXFUNC1(msvcrt, cos, cos)
FIXFUNC1(msvcrt, cosh, cosh)
FIXFUNC2(msvcrt, difftime, difftime)
FIXFUNC2(msvcrt, div, div)
FIXFUNC4(msvcrt, _ecvt, _ecvt)
FIXFUNC1(msvcrt, exp, exp)
FIXFUNC1(msvcrt, fabs, fabs)
FIXFUNC4(msvcrt, _fcvt, _fcvt)
FIXFUNC1(msvcrt, _finite, _finite)
FIXFUNC1(msvcrt, floor, floor)
FIXFUNC2(msvcrt, fmod, fmod)
FIXFUNC1(msvcrt, _fpclass, _fpclass)
FIXFUNC3(msvcrt, _fpieee_flt, _fpieee_flt)
FIXFUNC0(msvcrt, _fpreset, _fpreset)
FIXFUNC1(msvcrt, free, free)
FIXFUNC2(msvcrt, frexp, frexp)
FIXFUNC3(msvcrt, _gcvt, _gcvt)
FIXFUNC2(msvcrt, _hypot, _hypot)
FIXFUNC1(msvcrt, _isnan, _isnan)
FIXFUNC3(msvcrt, _itoa, _itoa)
FIXFUNC3(msvcrt, _itow, _itow)
FIXFUNC1(msvcrt, _j0, _j0)
FIXFUNC1(msvcrt, _j1, _j1)
FIXFUNC2(msvcrt, _jn, _jn)
FIXFUNC1(msvcrt, labs, labs)
FIXFUNC2(msvcrt, ldexp, ldexp)
FIXFUNC2(msvcrt, ldiv, ldiv)
FIXFUNC1(msvcrt, log, log)
FIXFUNC1(msvcrt, log10, log10)
FIXFUNC1(msvcrt, _logb, _logb)
FIXFUNC2(msvcrt, longjmp, longjmp)
FIXFUNC2(msvcrt, _lrotl, _lrotl)
FIXFUNC2(msvcrt, _lrotr, _lrotr)
FIXFUNC3(msvcrt, _ltoa, _ltoa)
FIXFUNC3(msvcrt, _ltow, _ltow)
FIXFUNC1(msvcrt, malloc, malloc)
FIXFUNC4(msvcrt, _memccpy, _memccpy)
FIXFUNC3(msvcrt, memcmp, memcmp)
FIXFUNC3(msvcrt, memcpy, memcpy)
FIXFUNC3(msvcrt, _memicmp, _memicmp)
FIXFUNC3(msvcrt, memmove, memmove)
FIXFUNC3(msvcrt, memset, memset)
FIXFUNC2(msvcrt, modf, modf)
FIXFUNC1(msvcrt, _msize, _msize)
FIXFUNC2(msvcrt, _nextafter, _nextafter)
FIXFUNC2(msvcrt, pow, pow)
FIXFUNC4(msvcrt, qsort, qsort)
FIXFUNC0(msvcrt, rand, rand)
FIXFUNC2(msvcrt, realloc, realloc)
FIXFUNC2(msvcrt, _rotl, _rotl)
FIXFUNC2(msvcrt, _rotr, _rotr)
FIXFUNC2(msvcrt, _scalb, _scalb)
FIXFUNC1(msvcrt, sin, sin)
FIXFUNC1(msvcrt, sinh, sinh)
FIXFUNC1(msvcrt, sqrt, sqrt)
FIXFUNC1(msvcrt, srand, srand)
FIXFUNC0(msvcrt, _statusfp, _statusfp)
FIXFUNC2(msvcrt, strcat, strcat)
FIXFUNC2(msvcrt, strchr, strchr)
FIXFUNC2(msvcrt, strcmp, strcmp)
FIXFUNC2(msvcrt, strcpy, strcpy)
FIXFUNC2(msvcrt, strcspn, strcspn)
FIXFUNC1(msvcrt, strlen, strlen)
FIXFUNC3(msvcrt, strncat, strncat)
FIXFUNC3(msvcrt, strncmp, strncmp)
FIXFUNC3(msvcrt, strncpy, strncpy)
FIXFUNC2(msvcrt, strstr, strstr)
FIXFUNC2(msvcrt, strtok, strtok)
FIXFUNC3(msvcrt, _swab, _swab)
FIXFUNC1(msvcrt, tan, tan)
FIXFUNC1(msvcrt, tanh, tanh)
FIXFUNC3(msvcrt, _ultoa, _ultoa)
FIXFUNC3(msvcrt, _ultow, _ultow)
FIXFUNC2(msvcrt, wcstod, wcstod)
FIXFUNC3(msvcrt, wcstol, wcstol)
FIXFUNC3(msvcrt, wcstoul, wcstoul)
FIXFUNC1(msvcrt, _y0, _y0)
FIXFUNC1(msvcrt, _y1, _y1)
FIXFUNC2(msvcrt, _yn, _yn)
FIXFUNC1(msvcrt, tolower, tolower)
FIXFUNC1(msvcrt, toupper, toupper)
FIXFUNC0(msvcrt, _purecall, _purecall)
FIXFUNC3(msvcrt, vswprintf, vswprintf)
FIXFUNC2(msvcrt, vprintf, vprintf)
FIXFUNC0(msvcrt, getchar, getchar)
FIXFUNC1(msvcrt, putchar, putchar)
FIXFUNC1(msvcrt, gets, gets)
FIXFUNC1(msvcrt, puts, puts)
FIXFUNC1(msvcrt, fgetc, fgetc)
FIXFUNC3(msvcrt, fgets, fgets)
FIXFUNC2(msvcrt, fputc, fputc)
FIXFUNC2(msvcrt, fputs, fputs)
FIXFUNC2(msvcrt, ungetc, ungetc)
FIXFUNC2(msvcrt, fopen, fopen)
FIXFUNC3(msvcrt, vfprintf, vfprintf)
FIXFUNC2(msvcrt, _wfdopen, _wfdopen)
FIXFUNC1(msvcrt, fclose, fclose)
FIXFUNC0(msvcrt, _fcloseall, _fcloseall)
FIXFUNC4(msvcrt, fread, fread)
FIXFUNC4(msvcrt, fwrite, fwrite)
FIXFUNC1(msvcrt, fflush, fflush)
FIXFUNC0(msvcrt, _flushall, _flushall)
FIXFUNC1(msvcrt, _fileno, _fileno)
FIXFUNC1(msvcrt, feof, feof)
FIXFUNC1(msvcrt, ferror, ferror)
FIXFUNC1(msvcrt, clearerr, clearerr)
FIXFUNC2(msvcrt, fgetpos, fgetpos)
FIXFUNC2(msvcrt, fsetpos, fsetpos)
FIXFUNC3(msvcrt, fseek, fseek)
FIXFUNC1(msvcrt, ftell, ftell)
FIXFUNC4(msvcrt, _vsnwprintf, _vsnwprintf)
FIXFUNC2(msvcrt, vwprintf, vwprintf)
FIXFUNC0(msvcrt, getwchar, getwchar)
FIXFUNC1(msvcrt, putwchar, putwchar)
FIXFUNC1(msvcrt, _getws, _getws)
FIXFUNC1(msvcrt, _putws, _putws)
FIXFUNC1(msvcrt, fgetwc, fgetwc)
FIXFUNC2(msvcrt, fputwc, fputwc)
FIXFUNC2(msvcrt, ungetwc, ungetwc)
FIXFUNC3(msvcrt, fgetws, fgetws)
FIXFUNC2(msvcrt, fputws, fputws)
FIXFUNC2(msvcrt, _wfopen, _wfopen)
FIXFUNC3(msvcrt, vsprintf, vsprintf)
FIXFUNC4(msvcrt, _vsnprintf, _vsnprintf)
FIXFUNC2(kernel32, GetThreadContext, GetThreadContext)
FIXFUNC1(kernel32, RegFlushKey, RegFlushKey)
FIXFUNC1(user32, BeginDeferWindowPos, BeginDeferWindowPos)
FIXFUNC8(user32, DeferWindowPos, DeferWindowPos)
FIXFUNC1(user32, EndDeferWindowPos, EndDeferWindowPos)
FIXFUNC1(user32, GetKeyboardLayoutNameW, GetKeyboardLayoutNameW)
FIXFUNC3(gdi32, TranslateCharsetInfo, TranslateCharsetInfo)
FIXFUNC1(kernel32, GetModuleHandleW, GetModuleHandleW)
FIXFUNC6(gdi32, ExtEscape, ExtEscape)
FIXFUNC3(user32, GetDCEx, GetDCEx)
FIXFUNC5(kernel32, GetThreadTimes, GetThreadTimes)
FIXFUNC2(msvcrt, _setmode, _setmode)
FIXFUNC0(imm32, ImmCreateContext, ImmCreateContext)
FIXFUNC1(imm32, ImmDestroyContext, ImmDestroyContext)
FIXFUNC2(imm32, ImmGetStatusWindowPos, ImmGetStatusWindowPos)
FIXFUNC3(msvcrt, _wfreopen, _wfreopen)
FIXFUNC4(user32, SetWindowsHookExW, SetWindowsHookExW)
FIXFUNC1(user32, UnhookWindowsHookEx, UnhookWindowsHookEx)
FIXFUNC4(user32, CallNextHookEx, CallNextHookEx)
FIXFUNC3(imm32, ImmAssociateContextEx, ImmAssociateContextEx)
FIXFUNC1(imm32, ImmDisableIME, ImmDisableIME)
FIXFUNC3(imm32, ImmGetIMEFileNameW, ImmGetIMEFileNameW)
FIXFUNC1(imm32, ImmIsIME, ImmIsIME)
FIXFUNC1(imm32, ImmGetVirtualKey, ImmGetVirtualKey)
FIXFUNC6(imm32, ImmGetImeMenuItemsW, ImmGetImeMenuItemsW)
FIXFUNC2(kernel32, FreeLibraryAndExitThread, FreeLibraryAndExitThread)
FIXFUNC1(user32, GetKeyboardLayout, GetKeyboardLayout)

FIXFUNC0(kernel32, GetCommandLineW, GetCommandLineW)

FIXFUNC1(kernel32, DisableThreadLibraryCalls, DisableThreadLibraryCalls)
FIXFUNC1(kernel32, TryEnterCriticalSection, TryEnterCriticalSection)
FIXFUNC4(kernel32, GetTempFileNameW, GetTempFileNameW)
FIXFUNC6(kernel32, FindFirstFileExW, FindFirstFileExW)
FIXFUNC3(kernel32, GetFileAttributesExW, GetFileAttributesExW)
FIXFUNC4(kernel32, CreateSemaphoreW, CreateSemaphoreW)
FIXFUNC3(kernel32, ReleaseSemaphore, ReleaseSemaphore)
FIXFUNC3(kernel32, LoadLibraryExW, LoadLibraryExW)
FIXFUNC3(imm32, ImmRequestMessageW, ImmRequestMessageW)
FIXFUNC0(kernel32, GetSystemDefaultUILanguage, GetSystemDefaultUILanguage)
FIXFUNC0(kernel32, GetUserDefaultUILanguage, GetUserDefaultUILanguage)
FIXFUNC3(kernel32, EnumUILanguagesW, EnumUILanguagesW)
FIXFUNC2(msvcrt, calloc, calloc)
FIXFUNC0(user32, GetDesktopWindow, GetDesktopWindow)
FIXFUNC3(user32, SetWindowRgn, SetWindowRgn)
FIXFUNC2(user32, GetWindowRgn, GetWindowRgn)
FIXFUNC2(msvcrt, strtod, strtod)
FIXFUNC3(msvcrt, strtol, strtol)
FIXFUNC3(msvcrt, strtoul, strtoul)
FIXFUNC2(msvcrt, strpbrk, strpbrk)
FIXFUNC2(msvcrt, strrchr, strrchr)
FIXFUNC2(msvcrt, strspn, strspn)
FIXFUNC1(msvcrt, _strdup, _strdup)
FIXFUNC2(msvcrt, _stricmp, _stricmp)
FIXFUNC3(msvcrt, _strnicmp, _strnicmp)
FIXFUNC3(msvcrt, _strnset, _strnset)
FIXFUNC1(msvcrt, _strrev, _strrev)
FIXFUNC2(msvcrt, _strset, _strset)
FIXFUNC1(msvcrt, _strlwr, _strlwr)
FIXFUNC1(msvcrt, _strupr, _strupr)
FIXFUNC2(msvcrt, _isctype, _isctype)
FIXFUNC1(msvcrt, _atoi64, _atoi64)
FIXFUNC0(user32, InSendMessage, InSendMessage)
FIXFUNC1(user32, GetQueueStatus, GetQueueStatus)
FIXFUNC3(unicows, RasEnumDevicesW, RasEnumDevicesW)
FIXFUNC4(unicows, RasGetProjectionInfoW, RasGetProjectionInfoW)
FIXFUNC4(version, VerQueryValueW, VerQueryValueW)
FIXFUNC4(version, GetFileVersionInfoW, GetFileVersionInfoW)
FIXFUNC2(version, GetFileVersionInfoSizeW, GetFileVersionInfoSizeW)
FIXFUNC3(kernel32, InterlockedExchangeAdd, InterlockedExchangeAdd)
FIXFUNC3(kernel32, InterlockedCompareExchange, InterlockedCompareExchange)
FIXFUNC3(kernel32, OpenEventW, OpenEventW)
FIXFUNC1(kernel32, GlobalAddAtomW, GlobalAddAtomW)
FIXFUNC1(kernel32, GlobalDeleteAtom, GlobalDeleteAtom)
FIXFUNC1(kernel32, GlobalFindAtomW, GlobalFindAtomW)
FIXFUNC2(user32, MonitorFromPoint, MonitorFromPoint)
FIXFUNC2(user32, MonitorFromRect, MonitorFromRect)
FIXFUNC2(user32, MonitorFromWindow, MonitorFromWindow)
FIXFUNC4(user32, EnumDisplayMonitors, EnumDisplayMonitors)
FIXFUNC7(kernel32, DuplicateHandle, DuplicateHandle)
FIXFUNC4(msvcrt, __CxxFrameHandler, __CxxFrameHandler)
FIXFUNC1(msvcrt, __RTCastToVoid, __RTCastToVoid)
FIXFUNC1(msvcrt, __RTtypeid, __RTtypeid)
FIXFUNC5(msvcrt, __RTDynamicCast, __RTDynamicCast)
FIXFUNC2(kernel32, SetSystemPowerState, SetSystemPowerState)
FIXFUNC7(crypt32, CryptProtectData, CryptProtectData)
FIXFUNC7(crypt32, CryptUnprotectData, CryptUnprotectData)
FIXFUNC4(msvcrt, setvbuf, setvbuf)
FIXFUNC3(user32, InvalidateRgn, InvalidateRgn)
FIXFUNC2(user32, ValidateRgn, ValidateRgn)
FIXFUNC3(gdi32, ExtCreateRegion, ExtCreateRegion)
FIXFUNC1(msvcrt, _abs64, _abs64)
FIXFUNC2(msvcrt, _rotl64, _rotl64)
FIXFUNC2(msvcrt, _rotr64, _rotr64)
FIXFUNC2(msvcrt, _XcptFilter, _XcptFilter)
FIXFUNC4(gdi32, MoveToEx, MoveToEx)
FIXFUNC3(gdi32, LineTo, LineTo)
FIXFUNC2(gdi32, GetCurrentPositionEx, GetCurrentPositionEx)
FIXFUNC2(gdi32, SetTextAlign, SetTextAlign)
FIXFUNC1(gdi32, GetTextAlign, GetTextAlign)
FIXFUNC4(gdi32, GetCharWidth32, GetCharWidth32W)
FIXFUNC4(gdi32, GetDIBColorTable, GetDIBColorTable)
FIXFUNC4(gdi32, SetDIBColorTable, SetDIBColorTable)
FIXFUNC13(gdi32, StretchDIBits, StretchDIBits)
FIXFUNC4(user32, RedrawWindow, RedrawWindow)
FIXFUNC3(kernel32, FindFirstChangeNotificationW, FindFirstChangeNotificationW)
FIXFUNC1(kernel32, FindNextChangeNotification, FindNextChangeNotification)
FIXFUNC1(kernel32, FindCloseChangeNotification, FindCloseChangeNotification)
FIXFUNC3(gdi32, SetBitmapBits, SetBitmapBits)
FIXFUNC12(gdi32, SetDIBitsToDevice, SetDIBitsToDevice)
FIXFUNC1(kernel32, IsProcessorFeaturePresent, IsProcessorFeaturePresent)
FIXFUNC2(user32, ActivateKeyboardLayout, ActivateKeyboardLayout)
FIXFUNC2(user32, GetKeyboardLayoutList, GetKeyboardLayoutList)
FIXFUNC2(user32, LoadKeyboardLayoutW, LoadKeyboardLayoutW)
FIXFUNC2(user32, InvertRect, InvertRect)
FIXFUNC1(user32, GetKeyboardType, GetKeyboardType)
FIXFUNC2(user32, GetIconInfo, GetIconInfo)
FIXFUNC1(gdi32, GetStretchBltMode, GetStretchBltMode)
FIXFUNC2(gdi32, SetStretchBltMode, SetStretchBltMode)
FIXFUNC5(kernel32, ReadFileScatter, ReadFileScatter)
FIXFUNC5(kernel32, WriteFileGather, WriteFileGather)
FIXFUNC1(comctl32, DPA_Create, DPA_Create)
FIXFUNC2(comctl32, DPA_CreateEx, DPA_CreateEx)
FIXFUNC2(comctl32, DPA_Clone, DPA_Clone)
FIXFUNC1(comctl32, DPA_DeleteAllPtrs, DPA_DeleteAllPtrs)
FIXFUNC2(comctl32, DPA_DeletePtr, DPA_DeletePtr)
FIXFUNC1(comctl32, DPA_Destroy, DPA_Destroy)
FIXFUNC3(comctl32, DPA_DestroyCallback, DPA_DestroyCallback)
FIXFUNC3(comctl32, DPA_EnumCallback, DPA_EnumCallback)
FIXFUNC2(comctl32, DPA_GetPtr, DPA_GetPtr)
FIXFUNC2(comctl32, DPA_GetPtrIndex, DPA_GetPtrIndex)
FIXFUNC2(comctl32, DPA_Grow, DPA_Grow)
FIXFUNC3(comctl32, DPA_InsertPtr, DPA_InsertPtr)
FIXFUNC6(comctl32, DPA_Search, DPA_Search)
FIXFUNC3(comctl32, DPA_SetPtr, DPA_SetPtr)
FIXFUNC3(comctl32, DPA_Sort, DPA_Sort)
FIXFUNC2(comctl32, DSA_Create, DSA_Create)
FIXFUNC1(comctl32, DSA_DeleteAllItems, DSA_DeleteAllItems)
FIXFUNC2(comctl32, DSA_DeleteItem, DSA_DeleteItem)
FIXFUNC1(comctl32, DSA_Destroy, DSA_Destroy)
FIXFUNC3(comctl32, DSA_DestroyCallback, DSA_DestroyCallback)
FIXFUNC3(comctl32, DSA_EnumCallback, DSA_EnumCallback)
FIXFUNC3(comctl32, DSA_GetItem, DSA_GetItem)
FIXFUNC2(comctl32, DSA_GetItemPtr, DSA_GetItemPtr)
FIXFUNC3(comctl32, DSA_InsertItem, DSA_InsertItem)
FIXFUNC3(comctl32, DSA_SetItem, DSA_SetItem)
FIXFUNC3(kernel32, MulDiv, MulDiv)
FIXFUNC2(kernel32, HeapCompact, HeapCompact)
FIXFUNC5(gdi32, EnumFontFamiliesExW, EnumFontFamiliesExW)
FIXFUNC5(gdi32, GetCharABCWidthsI, GetCharABCWidthsI)
FIXFUNC5(gdi32, GetFontData, GetFontData)
FIXFUNC3(gdi32, GetOutlineTextMetricsW, GetOutlineTextMetricsW)
FIXFUNC2(gdi32, SetLayout, SetLayout)
FIXFUNC1(gdi32, GetLayout, GetLayout)
FIXFUNC6(kernel32, CopyFileExW, CopyFileExW)
FIXFUNC2(gdi32, SetTextCharacterExtra, SetTextCharacterExtra)
FIXFUNC1(gdi32, GetTextCharacterExtra, GetTextCharacterExtra)
FIXFUNC6(kernel32, LockFileEx, LockFileEx)
FIXFUNC5(kernel32, UnlockFileEx, UnlockFileEx)
FIXFUNC1(shell32, ShellExecuteEx, ShellExecuteExW)
FIXFUNC4(shell32, SHGetFileInfo, SHGetFileInfoW)
FIXFUNC4(shlwapi, SHLoadIndirectString, SHLoadIndirectString)
FIXFUNC4(gdi32, SetWindowOrgEx, SetWindowOrgEx)
FIXFUNC2(gdi32, GetWindowOrgEx, GetWindowOrgEx)
FIXFUNC2(gdi32, GetWindowExtEx, GetWindowExtEx)
FIXFUNC4(gdi32, OffsetViewportOrgEx, OffsetViewportOrgEx)
FIXFUNC2(gdi32, GetViewportOrgEx, GetViewportOrgEx)
FIXFUNC2(gdi32, GetViewportExtEx, GetViewportExtEx)
FIXFUNC1(gdi32, GetROP2, GetROP2)
FIXFUNC1(kernel32, DebugActiveProcessStop, DebugActiveProcessStop)
FIXFUNC1(kernel32, DebugSetProcessKillOnExit, DebugSetProcessKillOnExit)
FIXFUNC2(kernel32, CheckRemoteDebuggerPresent, CheckRemoteDebuggerPresent)
