@ stub CreateWaitEvent
@ stub CreateWaitEventBinding
@ stub CreateWaitTimer
@ stub DeRegisterWaitEventBinding
@ stub DeRegisterWaitEventBindingSelf
@ stub DeRegisterWaitEventsTimers
@ stub DeRegisterWaitEventsTimersSelf
@ stub DebugPrintWaitWorkerThreads
@ stub LogErrorA
@ stub LogErrorW
@ stub LogEventA
@ stub LogEventW
@ stub MprSetupProtocolEnum
@ stub MprSetupProtocolFree
@ stub QueueWorkItem
@ stub RegisterWaitEventBinding
@ stub RegisterWaitEventsTimers
@ stub RouterAssert
@ stub RouterGetErrorStringA
@ stub RouterGetErrorStringW
@ stub RouterLogDeregisterA
@ stub RouterLogDeregisterW
@ stub RouterLogEventA
@ stub RouterLogEventDataA
@ stub RouterLogEventDataW
@ stub RouterLogEventExA
@ stub RouterLogEventExW
@ stub RouterLogEventStringA
@ stub RouterLogEventStringW
@ stub RouterLogEventValistExA
@ stub RouterLogEventValistExW
@ stub RouterLogEventW
@ stub RouterLogRegisterA
@ stub RouterLogRegisterW
@ stub SetIoCompletionProc
@ stub TraceDeregisterA
@ stub TraceDeregisterExA
@ stub TraceDeregisterExW
@ stub TraceDeregisterW
@ stub TraceDumpExA
@ stub TraceDumpExW
@ stub TraceGetConsoleA
@ stub TraceGetConsoleW
@ stub TracePrintfA
@ stub TracePrintfExA
@ stub TracePrintfExW
@ stub TracePrintfW
@ stub TracePutsExA
@ stub TracePutsExW
@ stdcall TraceRegisterExA(str long)
@ stdcall TraceRegisterExW(wstr long)
@ stub TraceVprintfExA
@ stub TraceVprintfExW
@ stub UpdateWaitTimer
@ stub WTFreeEvent
@ stub WTFreeTimer
