#ifndef __WINE_WINE_SHELL16_H
#define __WINE_WINE_SHELL16_H

#include "windef.h"

BOOL16      WINAPI AboutDlgProc16(HWND16,UINT16,WPARAM16,LPARAM);
BOOL      WINAPI AboutDlgProc(HWND,UINT,WPARAM,LPARAM);


#endif /* __WINE_WINE_SHELL16_H */
