name	comctl32
base	2

00 stub MenuHelp
01 stub ShowHideMenuCtl
02 stub GetEffectiveClientRect
03 stub DrawStatusTextA
04 stub CreateStatusWindowA
05 stub CreateToolbar
06 stub CreateMappedBitmap
07 stub CreatePropertySheetPage
08 stub CreatePropertySheetPageA
09 stub CreatePropertySheetPageW
10 stub CreateStatusWindow
11 stub MakeDragList
12 stub LBItemFromPt
13 stub DrawInsert
14 stub CreateUpDownControl
15 stub InitCommonControls
16 stub CreateStatusWindowW
17 stub CreateToolbarEx
18 stub DestroyPropertySheetPage
19 stub DrawStatusText
20 stub DrawStatusTextW
21 stub ImageList_Add
22 stub ImageList_AddIcon
23 stub ImageList_AddMasked
24 stub ImageList_BeginDrag
25 stub ImageList_Create
26 stub ImageList_Destroy
27 stub ImageList_DragEnter
28 stub ImageList_DragLeave
29 stub ImageList_DragMove
30 stub ImageList_DragShowNolock
31 stub ImageList_Draw
32 stub ImageList_DrawEx
33 stub ImageList_EndDrag
34 stub ImageList_GetBkColor
35 stub ImageList_GetDragImage
36 stub ImageList_GetIcon
37 stub ImageList_GetIconSize
38 stub ImageList_GetImageCount
39 stub ImageList_GetImageInfo
40 stub ImageList_GetImageRect
41 stub ImageList_LoadImage
42 stub ImageList_LoadImageA
43 stub ImageList_LoadImageW
44 stub ImageList_Merge
45 stub ImageList_Read
46 stub ImageList_Remove
47 stub ImageList_Replace
48 stub ImageList_ReplaceIcon
49 stub ImageList_SetBkColor
50 stub ImageList_SetDragCursorImage
51 stub ImageList_SetIconSize
52 stub ImageList_SetOverlayImage
53 stub ImageList_Write
54 stub PropertySheet
55 stub PropertySheetA
56 stub PropertySheetW
