10 stub AtlAdvise
11 stub AtlUnadvise
12 stub AtlFreeMarshalStream
13 stub AtlMarshalPtrInProc
14 stub AtlUnmarshalPtr
15 stub AtlComModuleGetClassObject
17 stub AtlComModuleRegisterClassObjects
20 stub AtlComModuleRevokeClassObjects
22 stub AtlComModuleUnregisterServer
23 stub AtlUpdateRegistryFromResourceD
24 stub AtlWaitWithMessageLoop
25 stub AtlSetErrorInfo
26 stub AtlCreateTargetDC
27 stub AtlHiMetricToPixel
28 stub AtlPixelToHiMetric
29 stub AtlDevModeW2A
30 stub AtlComPtrAssign
31 stub AtlComQIPtrAssign
32 stub AtlInternalQueryInterface
34 stdcall AtlGetVersion(ptr)
35 stub AtlAxDialogBoxW
36 stub AtlAxDialogBoxA
37 stub AtlAxCreateDialogW
38 stub AtlAxCreateDialogA
39 stub AtlAxCreateControl
40 stub AtlAxCreateControlEx
41 stub AtlAxAttachControl
42 stub AtlAxWinInit
43 stub AtlWinModuleAddCreateWndData
44 stub AtlWinModuleExtractCreateWndData
45 stub AtlWinModuleRegisterWndClassInfoW
46 stub AtlWinModuleRegisterWndClassInfoA
47 stub AtlAxGetControl
48 stub AtlAxGetHost
49 stub AtlRegisterClassCategoriesHelper
50 stub AtlIPersistStreamInit_Load
51 stub AtlIPersistStreamInit_Save
52 stub AtlIPersistPropertyBag_Load
53 stub AtlIPersistPropertyBag_Save
54 stub AtlGetObjectSourceInterface
56 stub AtlLoadTypeLib
58 stub AtlModuleAddTermFunc
59 stub AtlAxCreateControlLic
60 stub AtlAxCreateControlLicEx
61 stub AtlCreateRegistrar
62 stub AtlWinModuleRegisterClassExW
63 stub AtlWinModuleRegisterClassExA
64 stub AtlCallTermFunc
65 stub AtlWinModuleInit
66 stub AtlWinModuleTerm
67 stub AtlSetPerUserRegistration
68 stub AtlGetPerUserRegistration
