5 stub MsiSIPIsMyTypeOfFile
6 stub MsiSIPGetSignedDataMsg
7 stub MsiSIPPutSignedDataMsg
8 stub MsiSIPRemoveSignedDataMsg
9 stub MsiSIPCreateIndirectData
10 stub MsiSIPVerifyIndirectData
11 stub DllRegisterServer
12 stub DllUnregisterServer
