@ stub WldpIsAppApprovedByPolicy
@ stub WldpIsProductionConfiguration
@ stub WldpIsWcosProductionConfiguration
@ stub WldpQueryPolicySettingEnabled2
@ stub WldpQueryPolicySettingEnabled
@ stub WldpQueryPolicySettingEnabledInternal
@ stdcall WldpQueryWindowsLockdownMode(ptr)
@ stub WldpQueryWindowsLockdownRestriction
@ stub WldpResetProductionConfiguration
@ stub WldpResetWcosProductionConfiguration
@ stub WldpSetWindowsLockdownRestriction
@ stub WldpTraceLoggingWDACBlockDialogShown
@ stub WldpAddDeveloperCertificateForDynamicCodeTrust
@ stub WldpCheckDeviceEncryptionNotStarted
@ stub WldpCheckRetailConfiguration
@ stub WldpCheckWcosDeviceEncryptionSecure
@ stub WldpDisableDeveloperMode
@ stub WldpEnableDeveloperMode
@ stdcall WldpGetLockdownPolicy(ptr ptr long)
@ stub WldpIsAllowedEntryPoint
@ stub WldpIsClassInApprovedList
@ stub WldpIsDebugAllowed
@ stdcall WldpIsDynamicCodePolicyEnabled(ptr)
@ stub WldpIsProductionConfigurationInProc
@ stub WldpQueryDeviceSecurityInformation
@ stub WldpQueryDynamicCodeTrust
@ stub WldpQuerySecurityPolicy
@ stub WldpSetDynamicCodeTrust
@ stub WldpSetDynamicCodeTrust2
