@ stub NetApiBufferAllocate
@ stub NetApiBufferFree
@ stub NetApiBufferReallocate
@ stub NetApiBufferSize
@ stub NetRemoteComputerSupports
@ stub NetapipBufferAllocate
@ stub NetpIsComputerNameValid
@ stub NetpIsDomainNameValid
@ stub NetpIsGroupNameValid
@ stub NetpIsRemote
@ stub NetpIsRemoteNameValid
@ stub NetpIsShareNameValid
@ stub NetpIsUncComputerNameValid
@ stub NetpIsUserNameValid
@ stub NetpwListCanonicalize
@ stub NetpwListTraverse
@ stub NetpwNameCanonicalize
@ stub NetpwNameCompare
@ stub NetpwNameValidate
@ stub NetpwPathCanonicalize
@ stub NetpwPathCompare
@ stub NetpwPathType
