@ stdcall AcceptEx(long long ptr long long long ptr ptr)
@ stub EnumProtocolsA
@ stub EnumProtocolsW
@ stub GetAcceptExSockaddrs
@ stub GetAddressByNameA
@ stub GetAddressByNameW
@ stub GetNameByTypeA
@ stub GetNameByTypeW
@ stub GetServiceA
@ stub GetServiceW
@ stub GetTypeByNameA
@ stub GetTypeByNameW
@ stub MigrateWinsockConfiguration
@ stub NPLoadNameSpaces
@ stub NSPStartup
@ stub ServiceMain
@ stub SetServiceA
@ stub SetServiceW
@ stub StartWsdpService
@ stub StopWsdpService
@ stub SvchostPushServiceGlobals
@ stdcall TransmitFile(long long long long ptr ptr long)
@ stub WSARecvEx
@ stub WSPStartup
@ stub dn_expand
@ stub getnetbyname
@ stub inet_network
@ stub rcmd
@ stub rexec
@ stub rresvport
@ stub s_perror
@ stub sethostname
