@ stub NsiAllocateAndGetPersistentDataWithMaskTable
@ stub NsiAllocateAndGetTable
@ stub NsiCancelChangeNotification
@ stub NsiDeregisterChangeNotification
@ stub NsiDeregisterChangeNotificationEx
@ stub NsiEnumerateObjectsAllParameters
@ stub NsiEnumerateObjectsAllParametersEx
@ stub NsiEnumerateObjectsAllPersistentParametersWithMask
@ stub NsiFreePersistentDataWithMaskTable
@ stub NsiFreeTable
@ stub NsiGetAllParameters
@ stub NsiGetAllParametersEx
@ stub NsiGetAllPersistentParametersWithMask
@ stub NsiObjectSecurity
@ stub NsiGetParameter
@ stub NsiGetParameterEx
@ stub NsiRegisterChangeNotification
@ stub NsiRegisterChangeNotificationEx
@ stub NsiRequestChangeNotification
@ stub NsiRequestChangeNotificationEx
@ stub NsiSetAllParameters
@ stub NsiSetAllParametersEx
@ stub NsiSetAllPersistentParametersWithMask
@ stub NsiSetObjectSecurity
@ stub NsiSetParameter
@ stub NsiSetParameterEx
