@ stdcall init_funcs(ptr)

@ stdcall SQLAllocHandle(long long ptr)
@ stdcall SQLBindCol(long long long ptr long ptr)
@ stdcall SQLBindParameter(long long long long long long long ptr long ptr)
@ stdcall SQLBrowseConnect(long str long ptr long ptr)
@ stdcall SQLConnect(long str long str long str long)
@ stdcall SQLDescribeCol(long long ptr long ptr ptr ptr ptr ptr)
@ stdcall SQLDisconnect(long)
@ stdcall SQLDriverConnect(long long str long ptr long ptr long)
@ stdcall SQLExecDirect(long str long)
@ stdcall SQLExecute(long)
@ stdcall SQLFetch(long)
@ stdcall SQLFreeHandle(long long)
@ stdcall SQLFreeStmt(long long )
@ stdcall SQLGetConnectAttr(long long ptr long ptr)
@ stdcall SQLGetData(long long long ptr long ptr)
@ stdcall SQLGetDiagField(long long long long ptr long ptr)
@ stdcall SQLGetDiagRec(long long long ptr ptr ptr long ptr)
@ stdcall SQLGetEnvAttr(long long ptr long ptr)
@ stdcall SQLGetInfo(long long ptr long ptr)
@ stdcall SQLGetStmtAttr(long long ptr long ptr)
@ stdcall SQLPrepare(long str long)
@ stdcall SQLRowCount(long ptr)
@ stdcall SQLSetConnectAttr(long long ptr long)
@ stdcall SQLSetDescField(long long long ptr long)
@ stdcall SQLSetEnvAttr(long long ptr long)
@ stdcall SQLSetStmtAttr(long long ptr long)
