/*
 * COM Classes for xactengine
 *
 * Copyright 2018 Ethan Lee for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    threading(both),
#if XACT3_VER == 0x0200
    uuid(0aa000aa-f404-11d9-bd7a-0010dc4f8f81)
#elif XACT3_VER == 0x0204
    uuid(bc3e0fc6-2e0d-4c45-bc61-d9c328319bd8)
#elif XACT3_VER == 0x0207
    uuid(cd0d66ec-8057-43f5-acbd-66dfb36fd78c)
#elif XACT3_VER == 0x0209
    uuid(343e68e6-8f82-4a8d-a2da-6e9a944b378c)
#elif XACT3_VER == 0x0300
    uuid(3b80ee2a-b0f5-4780-9e30-90cb39685b03)
#elif XACT3_VER == 0x0301
    uuid(962f5027-99be-4692-a468-85802cf8de61)
#elif XACT3_VER == 0x0302
    uuid(d3332f02-3dd0-4de9-9aec-20d85c4111b6)
#elif XACT3_VER == 0x0303
    uuid(94c1affa-66e7-4961-9521-cfdef3128d4f)
#elif XACT3_VER == 0x0304
    uuid(0977d092-2d95-4e43-8d42-9ddcc2545ed5)
#elif XACT3_VER == 0x0305
    uuid(074b110f-7f58-4743-aea5-12f15b5074ed)
#elif XACT3_VER == 0x0306
    uuid(248d8a3b-6256-44d3-a018-2ac96c459f47)
#else /* XACT3_VER == 0x0307 or not defined */
    uuid(bcc782bc-6492-4c22-8c35-f5d72fe73c6e)
#endif
]
coclass XACTEngine {}
