/*
 * COM Classes for xactengine
 *
 * Copyright 2018 Ethan Lee for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

#if XACT3_VER == 0x0305
[
    helpstring("XACT3.5 Class"),
    threading(both),
    uuid(074b110f-7f58-4743-aea5-12f15b5074ed)
]
coclass XACTEngine35 { interface IXACT37Engine; }
#elif XACT3_VER == 0x0306
[
    helpstring("XACT3.6 Class"),
    threading(both),
    uuid(248d8a3b-6256-44d3-a018-2ac96c459f47)
]
coclass XACTEngine36 { interface IXACT37Engine; }
#else /* XACT3_VER == 0x0307 or not defined */
[
    helpstring("XACT3.7 Class"),
    threading(both),
    uuid(bcc782bc-6492-4c22-8c35-f5d72fe73c6e)
]
coclass XACTEngine37 { interface IXACT37Engine; }
#endif
