@ stub FilterAttach
@ stub FilterAttachAtAltitude
@ stub FilterClose
@ stdcall FilterConnectCommunicationPort(wstr long ptr long ptr ptr)
@ stub FilterCreate
@ stub FilterDetach
@ stub FilterFindClose
@ stub FilterFindFirst
@ stub FilterFindNext
@ stub FilterGetDosName
@ stub FilterGetInformation
@ stub FilterGetMessage
@ stub FilterInstanceClose
@ stub FilterInstanceCreate
@ stub FilterInstanceFindClose
@ stub FilterInstanceFindFirst
@ stub FilterInstanceFindNext
@ stub FilterInstanceGetInformation
@ stub FilterLoad
@ stub FilterReplyMessage
@ stub FilterSendMessage
@ stub FilterUnload
@ stub FilterVolumeClose
@ stub FilterVolumeFindClose
@ stub FilterVolumeFindFirst
@ stub FilterVolumeFindNext
@ stub FilterVolumeInstanceFindClose
@ stub FilterVolumeInstanceFindFirst
@ stub FilterVolumeInstanceFindNext
