@ stdcall -private DllMain(long long ptr)
@ stdcall GetConsoleType()
@ stdcall GetSystemOSVersion(ptr)
@ stdcall QueryProcessorSchedulingStatistics(ptr)
@ stdcall SetThreadpoolAffinityMask(ptr long)
@ stdcall SetThreadName(long wstr)
@ stdcall GetThreadName(long ptr long ptr)
@ stdcall TitleMemoryStatus(ptr)
@ stdcall JobTitleMemoryStatus(ptr)
@ stdcall ToolingMemoryStatus(ptr)
@ stdcall AllocateTitlePhysicalPages(long long ptr ptr)
@ stdcall FreeTitlePhysicalPages(long long ptr)
@ stdcall MapTitlePhysicalPages(ptr long long long ptr)
@ stdcall MapTitleEsramPages(ptr long long ptr)
@ stdcall EraVirtualAllocEx(long ptr long long long)
@ stdcall EraVirtualAlloc(ptr long long long)
@ stdcall EraVirtualFreeEx(long ptr long long)
@ stdcall EraVirtualFree(ptr long long)
@ stdcall EraVirtualQueryEx(long ptr ptr long)
@ stdcall EraVirtualQuery(ptr ptr long)
@ stdcall EraVirtualProtectEx(long ptr long long ptr)
@ stdcall EraVirtualProtect(ptr long long ptr)
@ stdcall XMemAllocDefault(long int64)
@ stdcall XMemFreeDefault(ptr int64)
@ stdcall XMemAlloc(long int64)
@ stdcall XMemFree(ptr int64)
@ stdcall XMemSetAllocationHooks(ptr ptr)
@ stdcall XMemCheckDefaultHeaps()
@ stdcall XMemSetAllocationHysteresis()
@ stdcall XMemGetAllocationHysteresis()
@ stdcall XMemPreallocateFreeSpace()
@ stdcall XMemGetAllocationStatistics()
@ stdcall XMemGetAuxiliaryTitleMemory()
@ stdcall XMemReleaseAuxiliaryTitleMemory(long)
@ stdcall EraCreateFileW(wstr long long ptr long long long)
@ stdcall EraCreateFileA(str long long ptr long long long)
@ stdcall EraCreateFile2(wstr long long long ptr)
@ stdcall EraCreateDirectoryA(str ptr)
@ stdcall EraCreateDirectoryW(wstr ptr)
@ stdcall EraLoadLibraryExA(str long long)
@ stdcall EraLoadLibraryW(wstr)
@ stdcall EraLoadLibraryExW(wstr long long)
@ stdcall EraGetFileAttributesW(wstr)
@ stdcall EraGetFileAttributesExW(wstr long ptr)
@ stdcall EraGetFileAttributesA(str)
@ stdcall EraFindFirstFileW(wstr ptr)
@ stdcall EraFindFirstFileA(str ptr)
@ stdcall EraFindNextFileW(long ptr)
@ stdcall EraFindNextFileA(long ptr)
@ stdcall EraDeleteFileW(wstr)
@ stdcall EraSetFileAttributesA(str long)
@ stdcall EraGetFileInformationByHandleEx(long long ptr long)
@ stdcall EraReadFile(long ptr long ptr ptr)
@ stdcall EraWriteFile(long ptr long ptr ptr)
@ stdcall NtEnable32BitProcess(long long ptr long)
@ stdcall EraGetProcAddress(long str)
@ stdcall EraGetVersionExW(ptr) EraGetVersionExW
@ stdcall GetVersionExW(ptr) EraGetVersionExW
