@ stub ??0CLexer@@QAE@XZ
@ stub ??1CLexer@@QAE@XZ
@ stub ADSIPrint
@ stub ADsAbandonSearch
@ stub ADsCloseSearchHandle
@ stub ADsCreateAttributeDefinition
@ stub ADsCreateClassDefinition
@ stub ADsCreateDSObject
@ stub ADsCreateDSObjectExt
@ stub ADsDeleteAttributeDefinition
@ stub ADsDeleteClassDefinition
@ stub ADsDeleteDSObject
@ stub ADsEnumAttributes
@ stub ADsEnumClasses
@ stub ADsExecuteSearch
@ stub ADsFreeColumn
@ stub ADsGetColumn
@ stub ADsGetFirstRow
@ stub ADsGetNextColumnName
@ stub ADsGetNextRow
@ stub ADsGetObjectAttributes
@ stub ADsGetPreviousRow
@ stub ADsHelperGetCurrentRowMessage
@ stub ADsObject
@ stub ADsSetObjectAttributes
@ stub ADsSetSearchPreference
@ stub ADsWriteAttributeDefinition
@ stub ADsWriteClassDefinition
@ stub AdsTypeToLdapTypeCopyConstruct
@ stub AdsTypeToLdapTypeCopyDNWithBinary
@ stub AdsTypeToLdapTypeCopyDNWithString
@ stub AdsTypeToLdapTypeCopyGeneralizedTime
@ stub AdsTypeToLdapTypeCopyTime
@ stub BerBvFree
@ stub BerEncodingQuotaControl
@ stub BuildADsParentPath
@ stub BuildADsParentPathFromObjectInfo2
@ stub BuildADsParentPathFromObjectInfo
@ stub BuildADsPathFromLDAPPath2
@ stub BuildADsPathFromLDAPPath
@ stub BuildADsPathFromParent
@ stub BuildLDAPPathFromADsPath2
@ stub BuildLDAPPathFromADsPath
@ stub ChangeSeparator
@ stub Component
@ stub ConvertSidToString
@ stub ConvertSidToU2Trustee
@ stub ConvertU2TrusteeToSid
@ stub FindEntryInSearchTable
@ stub FindSearchTableIndex
@ stub FreeObjectInfo
@ stub GetDefaultServer
@ stub GetDisplayName
@ stub GetDomainDNSNameForDomain
@ stub GetLDAPTypeName
@ stub ?GetNextToken@CLexer@@QAEJPAGPAK@Z
@ stub GetServerAndPort
@ stub GetSyntaxOfAttribute
@ stub InitObjectInfo
@ stub ?InitializePath@CLexer@@QAEJPAG@Z
@ stub IsGCNamespace
@ stub LdapAddExtS
@ stub LdapAddS
@ stub LdapAttributeFree
@ stub LdapCacheAddRef
@ stub LdapCloseObject
@ stub LdapCompareExt
@ stub LdapControlFree
@ stub LdapControlsFree
@ stub LdapCountEntries
@ stub LdapCrackUserDNtoNTLMUser2
@ stub LdapCreatePageControl
@ stub LdapDeleteExtS
@ stub LdapDeleteS
@ stub LdapFirstAttribute
@ stub LdapFirstEntry
@ stub LdapGetDn
@ stub LdapGetNextPageS
@ stub LdapGetSchemaObjectCount
@ stub LdapGetSubSchemaSubEntryPath
@ stub LdapGetSyntaxIdOfAttribute
@ stub LdapGetSyntaxOfAttributeOnServer
@ stub LdapGetValues
@ stub LdapGetValuesLen
@ stub LdapInitializeSearchPreferences
@ stub LdapIsClassNameValidOnServer
@ stub LdapMakeSchemaCacheObsolete
@ stub LdapMemFree
@ stub LdapModDnS
@ stub LdapModifyExtS
@ stub LdapModifyS
@ stub LdapMsgFree
@ stub LdapNextAttribute
@ stub LdapNextEntry
@ stub LdapOpenObject2
@ stub LdapOpenObject
@ stub LdapParsePageControl
@ stub LdapParseResult
@ stub LdapReadAttribute2
@ stub LdapReadAttribute
@ stub LdapReadAttributeFast
@ stub LdapRenameExtS
@ stub LdapResult
@ stub LdapSearch
@ stub LdapSearchAbandonPage
@ stub LdapSearchExtS
@ stub LdapSearchInitPage
@ stub LdapSearchS
@ stub LdapSearchST
@ stub LdapTypeBinaryToString
@ stub LdapTypeCopyConstruct
@ stub LdapTypeFreeLdapModList
@ stub LdapTypeFreeLdapModObject
@ stub LdapTypeFreeLdapObjects
@ stub LdapTypeToAdsTypeDNWithBinary
@ stub LdapTypeToAdsTypeDNWithString
@ stub LdapTypeToAdsTypeGeneralizedTime
@ stub LdapTypeToAdsTypeUTCTime
@ stub LdapValueFree
@ stub LdapValueFreeLen
@ stub LdapcKeepHandleAround
@ stub LdapcSetStickyServer
@ stub PathName
@ stub ReadPagingSupportedAttr
@ stub ReadSecurityDescriptorControlType
@ stub ReadServerSupportsIsADAMControl
@ stub ReadServerSupportsIsADControl
@ stub SchemaAddRef
@ stub SchemaClose
@ stub SchemaGetClassInfo
@ stub SchemaGetClassInfoByIndex
@ stub SchemaGetObjectCount
@ stub SchemaGetPropertyInfo
@ stub SchemaGetPropertyInfoByIndex
@ stub SchemaGetStringsFromStringTable
@ stub SchemaGetSyntaxOfAttribute
@ stub SchemaIsClassAContainer
@ stub SchemaOpen
@ stub ?SetAtDisabler@CLexer@@QAEXH@Z
@ stub ?SetExclaimnationDisabler@CLexer@@QAEXH@Z
@ stub ?SetFSlashDisabler@CLexer@@QAEXH@Z
@ stub SortAndRemoveDuplicateOIDs
@ stub UnMarshallLDAPToLDAPSynID
@ stub intcmp
@ stub ADSIAbandonSearch
@ stub ADSICloseDSObject
@ stub ADSICloseSearchHandle
@ stub ADSICreateDSObject
@ stub ADSIDeleteDSObject
@ stub ADSIExecuteSearch
@ stub ADSIFreeColumn
@ stub ADSIGetColumn
@ stub ADSIGetFirstRow
@ stub ADSIGetNextColumnName
@ stub ADSIGetNextRow
@ stub ADSIGetObjectAttributes
@ stub ADSIGetPreviousRow
@ stub ADSIModifyRdn
@ stub ADSIOpenDSObject
@ stub ADSISetObjectAttributes
@ stub ADSISetSearchPreference
@ stub ADsDecodeBinaryData
@ stub ADsEncodeBinaryData
@ stub ADsGetLastError
@ stub ADsSetLastError
@ stub AdsTypeFreeAdsObjects
@ stub AllocADsMem
@ stub AllocADsStr
@ stub FreeADsMem
@ stub FreeADsStr
@ stub LdapTypeToAdsTypeCopyConstruct
@ stub MapADSTypeToLDAPType
@ stub MapLDAPTypeToADSType
@ stub ReallocADsMem
@ stub ReallocADsStr
