@ cdecl _Aligned_get_default_resource()
@ cdecl _Aligned_new_delete_resource()
@ cdecl _Aligned_set_default_resource(ptr)
@ cdecl _Unaligned_get_default_resource()
@ cdecl _Unaligned_new_delete_resource()
@ cdecl _Unaligned_set_default_resource(ptr)
@ cdecl null_memory_resource()
