@ stub DwTerminalDlg
@ stub GetRasDialOutProtocols
@ stub RasAutodialDisableDlgA
@ stub RasAutodialDisableDlgW
@ stub RasAutodialQueryDlgA
@ stub RasAutodialQueryDlgW
@ stub RasDialDlgA
@ stub RasDialDlgW
@ stub RasEntryDlgA
@ stdcall RasEntryDlgW(wstr wstr ptr)
@ stub RasMonitorDlgA
@ stub RasMonitorDlgW
@ stub RasPhonebookDlgA
@ stub RasPhonebookDlgW
@ stub RasSrvAddPropPages
@ stub RasSrvAddWizPages
@ stub RasSrvAllowConnectionsConfig
@ stub RasSrvCleanupService
@ stub RasSrvEnumConnections
@ stub RasSrvHangupConnection
@ stub RasSrvInitializeService
@ stub RasSrvIsConnectionConnected
@ stub RasSrvIsServiceRunning
@ stub RasSrvQueryShowIcon
@ stub RasUserEnableManualDial
@ stub RasUserGetManualDial
@ stub RasUserPrefsDlg
@ stub RasWizCreateNewEntry
@ stub RasWizGetNCCFlags
@ stub RasWizGetSuggestedEntryName
@ stub RasWizGetUserInputConnectionName
@ stub RasWizIsEntryRenamable
@ stub RasWizQueryMaxPageCount
@ stub RasWizSetEntryName
@ stub RouterEntryDlgA
@ stub RouterEntryDlgW
