@ stdcall -private ServiceMain(long ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ stub wiasCreateChildAppItem
@ stub wiasCreateDrvItem
@ stub wiasCreateLogInstance
@ stub wiasCreatePropContext
@ stub wiasDebugError
@ stub wiasDebugTrace
@ stub wiasDownSampleBuffer
@ stub wiasFormatArgs
@ stub wiasFreePropContext
@ stub wiasGetChangedValueFloat
@ stub wiasGetChangedValueGuid
@ stub wiasGetChangedValueLong
@ stub wiasGetChangedValueStr
@ stub wiasGetChildrenContexts
@ stub wiasGetContextFromName
@ stub wiasGetDrvItem
@ stub wiasGetImageInformation
@ stub wiasGetItemType
@ stub wiasGetPropertyAttributes
@ stub wiasGetRootItem
@ stub wiasIsPropChanged
@ stub wiasParseEndorserString
@ stub wiasPrintDebugHResult
@ stub wiasQueueEvent
@ stub wiasReadMultiple
@ stub wiasReadPropBin
@ stub wiasReadPropFloat
@ stub wiasReadPropGuid
@ stub wiasReadPropLong
@ stub wiasReadPropStr
@ stub wiasSendEndOfPage
@ stub wiasSetItemPropAttribs
@ stub wiasSetItemPropNames
@ stub wiasSetPropChanged
@ stub wiasSetPropertyAttributes
@ stub wiasSetValidFlag
@ stub wiasSetValidListFloat
@ stub wiasSetValidListGuid
@ stub wiasSetValidListLong
@ stub wiasSetValidListStr
@ stub wiasSetValidRangeFloat
@ stub wiasSetValidRangeLong
@ stub wiasUpdateScanRect
@ stub wiasUpdateValidFormat
@ stub wiasValidateItemProperties
@ stub wiasWriteBufToFile
@ stub wiasWriteMultiple
@ stub wiasWritePageBufToFile
@ stub wiasWritePageBufToStream
@ stub wiasWritePropBin
@ stub wiasWritePropFloat
@ stub wiasWritePropGuid
@ stub wiasWritePropLong
@ stub wiasWritePropStr
