@ stub CloseDefaultICUGroupingLetters
@ stub GetDefaultICUGroupingLetters
@ stub GetICUGroupingLetter
@ stub SortCloseHandle
@ stub SortGetHandle
@ stub SortGetSearchKey
@ stub UCNV_FROM_U_CALLBACK_ESCAPE(ptr ptr ptr long long long ptr)
@ stub UCNV_FROM_U_CALLBACK_SKIP(ptr ptr ptr long long long ptr)
@ stub UCNV_FROM_U_CALLBACK_STOP(ptr ptr ptr long long long ptr)
@ stub UCNV_FROM_U_CALLBACK_SUBSTITUTE(ptr ptr ptr long long long ptr)
@ stub UCNV_TO_U_CALLBACK_ESCAPE(ptr ptr str long long ptr)
@ stub UCNV_TO_U_CALLBACK_SKIP(ptr ptr str long long ptr)
@ stub UCNV_TO_U_CALLBACK_STOP(ptr ptr str long long ptr)
@ stub UCNV_TO_U_CALLBACK_SUBSTITUTE(ptr ptr str long long ptr)
@ stub u_UCharsToChars(ptr str long)
@ stub u_austrcpy(str ptr)
@ stub u_austrncpy(str ptr long)
@ stub u_catclose(long)
@ stub u_catgets(long long long ptr ptr ptr)
@ stub u_catopen(str str ptr)
@ stub u_charAge(long long)
@ stub u_charDigitValue(long)
@ stub u_charDirection(long)
@ stub u_charFromName(long str ptr)
@ stub u_charMirror(long)
@ stub u_charName(long long str long ptr)
@ stub u_charType(long)
@ stub u_charsToUChars(str ptr long)
@ stub u_cleanup()
@ stub u_countChar32(ptr long)
@ stub u_digit(long long)
@ stub u_enumCharNames(long long ptr ptr long ptr)
@ stub u_enumCharTypes(ptr ptr)
@ stub u_errorName(long)
@ stub u_foldCase(long long)
@ stub u_forDigit(long long)
@ stub u_formatMessage(str ptr long ptr long ptr)
@ stub u_formatMessageWithError(str ptr long ptr long ptr ptr)
@ stub u_getBidiPairedBracket(long)
@ stub u_getBinaryPropertySet
@ stub u_getCombiningClass(long)
@ stub u_getDataVersion(long ptr)
@ stub u_getFC_NFKC_Closure(long ptr long ptr)
@ stub u_getIntPropertyMap
@ stub u_getIntPropertyMaxValue(long)
@ stub u_getIntPropertyMinValue(long)
@ stub u_getIntPropertyValue(long long)
@ stub u_getNumericValue(long)
@ stub u_getPropertyEnum(str)
@ stub u_getPropertyName(long long)
@ stub u_getPropertyValueEnum(long str)
@ stub u_getPropertyValueName(long long long)
@ stub u_getUnicodeVersion(long)
@ stub u_getVersion(long)
@ stub u_hasBinaryProperty(long long)
@ stub u_init(ptr)
@ stub u_isIDIgnorable(long)
@ stub u_isIDPart(long)
@ stub u_isIDStart(long)
@ stub u_isISOControl(long)
@ stub u_isJavaIDPart(long)
@ stub u_isJavaIDStart(long)
@ stub u_isJavaSpaceChar(long)
@ stub u_isMirrored(long)
@ stub u_isUAlphabetic(long)
@ stub u_isULowercase(long)
@ stub u_isUUppercase(long)
@ stub u_isUWhiteSpace(long)
@ stub u_isWhitespace(long)
@ stub u_isalnum(long)
@ stub u_isalpha(long)
@ stub u_isbase(long)
@ stub u_isblank(long)
@ stub u_iscntrl(long)
@ stub u_isdefined(long)
@ stub u_isdigit(long)
@ stub u_isgraph(long)
@ stub u_islower(long)
@ stub u_isprint(long)
@ stub u_ispunct(long)
@ stub u_isspace(long)
@ stub u_istitle(long)
@ stub u_isupper(long)
@ stub u_isxdigit(long)
@ stub u_memcasecmp(ptr ptr long long)
@ stub u_memchr(ptr long long)
@ stub u_memchr32(ptr long long)
@ stub u_memcmp(ptr ptr long)
@ stub u_memcmpCodePointOrder(ptr ptr long)
@ stub u_memcpy(ptr ptr long)
@ stub u_memmove(ptr ptr long)
@ stub u_memrchr(ptr long long)
@ stub u_memrchr32(ptr long long)
@ stub u_memset(ptr long long)
@ stub u_parseMessage(str ptr long ptr long ptr)
@ stub u_parseMessageWithError(str ptr long ptr long ptr ptr)
@ stub u_setMemoryFunctions(ptr ptr ptr ptr ptr)
@ stub u_shapeArabic(ptr long ptr long long ptr)
@ stub u_strCaseCompare(ptr long ptr long long ptr)
@ stub u_strCompare(ptr long ptr long long)
@ stub u_strCompareIter(ptr ptr long)
@ stub u_strFindFirst(ptr long ptr long)
@ stub u_strFindLast(ptr long ptr long)
@ stub u_strFoldCase(ptr long ptr long long ptr)
@ stub u_strFromJavaModifiedUTF8WithSub(ptr long ptr str long long ptr ptr)
@ stub u_strFromUTF32(ptr long ptr ptr long ptr)
@ stub u_strFromUTF32WithSub(ptr long ptr ptr long long ptr ptr)
@ stub u_strFromUTF8(ptr long ptr str long ptr)
@ stub u_strFromUTF8Lenient(ptr long ptr str long ptr)
@ stub u_strFromUTF8WithSub(ptr long ptr str long long ptr ptr)
@ stub u_strFromWCS(ptr long ptr wstr long ptr)
@ stub u_strHasMoreChar32Than(ptr long long)
@ stub u_strToJavaModifiedUTF8(str long ptr ptr long ptr)
@ stub u_strToLower(ptr long ptr long str ptr)
@ stub u_strToTitle(ptr long ptr long ptr str ptr)
@ stub u_strToUTF32(ptr long ptr ptr long ptr)
@ stub u_strToUTF32WithSub(ptr long ptr ptr long long ptr ptr)
@ stub u_strToUTF8(str long ptr ptr long ptr)
@ stub u_strToUTF8WithSub(str long ptr ptr long long ptr ptr)
@ stub u_strToUpper(ptr long ptr long str ptr)
@ stub u_strToWCS(wstr long ptr ptr long ptr)
@ stub u_strcasecmp(ptr ptr long)
@ stub u_strcat(ptr ptr)
@ stub u_strchr(ptr long)
@ stub u_strchr32(ptr long)
@ stub u_strcmp(ptr ptr)
@ stub u_strcmpCodePointOrder(ptr ptr)
@ stub u_strcpy(ptr ptr)
@ stub u_strcspn(ptr ptr)
@ stub u_stringHasBinaryProperty
@ stub u_strlen(ptr)
@ stub u_strncasecmp(ptr ptr long long)
@ stub u_strncat(ptr ptr long)
@ stub u_strncmp(ptr ptr long)
@ stub u_strncmpCodePointOrder(ptr ptr long)
@ stub u_strncpy(ptr ptr long)
@ stub u_strpbrk(ptr ptr)
@ stub u_strrchr(ptr long)
@ stub u_strrchr32(ptr long)
@ stub u_strrstr(ptr ptr)
@ stub u_strspn(ptr ptr)
@ stub u_strstr(ptr ptr)
@ stub u_strtok_r(ptr ptr ptr)
@ stub u_tolower(long)
@ stub u_totitle(long)
@ stub u_toupper(long)
@ stub u_uastrcpy(ptr str)
@ stub u_uastrncpy(ptr str long)
@ stub u_unescape(str ptr long)
@ stub u_unescapeAt(long ptr long ptr)
@ stub u_versionFromString(long str)
@ stub u_versionFromUString(long ptr)
@ stub u_versionToString(long str)
@ stub u_vformatMessage(str ptr long ptr long long ptr)
@ stub u_vformatMessageWithError(str ptr long ptr long ptr long ptr)
@ stub u_vparseMessage(str ptr long ptr long long ptr)
@ stub u_vparseMessageWithError(str ptr long ptr long long ptr ptr)
@ stub ubidi_close(ptr)
@ stub ubidi_countParagraphs(ptr)
@ stub ubidi_countRuns(ptr ptr)
@ stub ubidi_getBaseDirection(ptr long)
@ stub ubidi_getClassCallback(ptr ptr ptr)
@ stub ubidi_getCustomizedClass(ptr long)
@ stub ubidi_getDirection(ptr)
@ stub ubidi_getLength(ptr)
@ stub ubidi_getLevelAt(ptr long)
@ stub ubidi_getLevels(ptr ptr)
@ stub ubidi_getLogicalIndex(ptr long ptr)
@ stub ubidi_getLogicalMap(ptr ptr ptr)
@ stub ubidi_getLogicalRun(ptr long ptr ptr)
@ stub ubidi_getParaLevel(ptr)
@ stub ubidi_getParagraph(ptr long ptr ptr ptr ptr)
@ stub ubidi_getParagraphByIndex(ptr long ptr ptr ptr ptr)
@ stub ubidi_getProcessedLength(ptr)
@ stub ubidi_getReorderingMode(ptr)
@ stub ubidi_getReorderingOptions(ptr)
@ stub ubidi_getResultLength(ptr)
@ stub ubidi_getText(ptr)
@ stub ubidi_getVisualIndex(ptr long ptr)
@ stub ubidi_getVisualMap(ptr ptr ptr)
@ stub ubidi_getVisualRun(ptr long ptr ptr)
@ stub ubidi_invertMap(ptr ptr long)
@ stub ubidi_isInverse(ptr)
@ stub ubidi_isOrderParagraphsLTR(ptr)
@ stub ubidi_open()
@ stub ubidi_openSized(long long ptr)
@ stub ubidi_orderParagraphsLTR(ptr long)
@ stub ubidi_reorderLogical(ptr long ptr)
@ stub ubidi_reorderVisual(ptr long ptr)
@ stub ubidi_setClassCallback(ptr ptr ptr ptr ptr ptr)
@ stub ubidi_setContext(ptr ptr long ptr long ptr)
@ stub ubidi_setInverse(ptr long)
@ stub ubidi_setLine(ptr long long ptr ptr)
@ stub ubidi_setPara(ptr ptr long long ptr ptr)
@ stub ubidi_setReorderingMode(ptr long)
@ stub ubidi_setReorderingOptions(ptr long)
@ stub ubidi_writeReordered(ptr ptr long long ptr)
@ stub ubidi_writeReverse(ptr long ptr long long ptr)
@ stub ubiditransform_close(ptr)
@ stub ubiditransform_open(ptr)
@ stub ubiditransform_transform(ptr ptr long ptr long long long long long long long ptr)
@ stub ublock_getCode(long)
@ stub ubrk_clone
@ stub ubrk_close(ptr)
@ stub ubrk_countAvailable()
@ stub ubrk_current(ptr)
@ stub ubrk_first(ptr)
@ stub ubrk_following(ptr long)
@ stub ubrk_getAvailable(long)
@ stub ubrk_getBinaryRules(ptr ptr long ptr)
@ stub ubrk_getLocaleByType(ptr long ptr)
@ stub ubrk_getRuleStatus(ptr)
@ stub ubrk_getRuleStatusVec(ptr ptr long ptr)
@ stub ubrk_isBoundary(ptr long)
@ stub ubrk_last(ptr)
@ stub ubrk_next(ptr)
@ stub ubrk_open(long str ptr long ptr)
@ stub ubrk_openBinaryRules(ptr long ptr long ptr)
@ stub ubrk_openRules(ptr long ptr long ptr ptr)
@ stub ubrk_preceding(ptr long)
@ stub ubrk_previous(ptr)
@ stub ubrk_refreshUText(ptr ptr ptr)
@ stub ubrk_safeClone(ptr ptr ptr ptr)
@ stub ubrk_setText(ptr ptr long ptr)
@ stub ubrk_setUText(ptr ptr ptr)
@ stub ucal_add(ptr long long ptr)
@ stub ucal_clear(ptr)
@ stub ucal_clearField(ptr long)
@ stub ucal_clone(ptr ptr)
@ stub ucal_close(ptr)
@ stub ucal_countAvailable()
@ stub ucal_equivalentTo(ptr ptr)
@ stub ucal_get(ptr long ptr)
@ stub ucal_getAttribute(ptr long)
@ stub ucal_getAvailable(long)
@ stub ucal_getCanonicalTimeZoneID(ptr long ptr long ptr ptr)
@ stub ucal_getDSTSavings(ptr ptr)
@ stub ucal_getDayOfWeekType(ptr long ptr)
@ stub ucal_getDefaultTimeZone(ptr long ptr)
@ stub ucal_getFieldDifference(ptr long long ptr)
@ stub ucal_getGregorianChange(ptr ptr)
@ stub ucal_getHostTimeZone
@ stub ucal_getKeywordValuesForLocale(str str long ptr)
@ stub ucal_getLimit(ptr long long ptr)
@ stub ucal_getLocaleByType(ptr long ptr)
@ stub ucal_getMillis(ptr ptr)
@ stub ucal_getNow()
@ stub ucal_getTZDataVersion(ptr)
@ stub ucal_getTimeZoneDisplayName(ptr long str ptr long ptr)
@ stub ucal_getTimeZoneID(ptr ptr long ptr)
@ stub ucal_getTimeZoneIDForWindowsID(ptr long str ptr long ptr)
@ stub ucal_getTimeZoneOffsetFromLocal
@ stub ucal_getTimeZoneTransitionDate(ptr long ptr ptr)
@ stub ucal_getType(ptr ptr)
@ stub ucal_getWeekendTransition(ptr long ptr)
@ stub ucal_getWindowsTimeZoneID(ptr long ptr long ptr)
@ stub ucal_inDaylightTime(ptr ptr)
@ stub ucal_isSet(ptr long)
@ stub ucal_isWeekend(ptr long ptr)
@ stub ucal_open(ptr long str long ptr)
@ stub ucal_openCountryTimeZones(str ptr)
@ stub ucal_openTimeZoneIDEnumeration(long str ptr ptr)
@ stub ucal_openTimeZones(ptr)
@ stub ucal_roll(ptr long long ptr)
@ stub ucal_set(ptr long long)
@ stub ucal_setAttribute(ptr long long)
@ stub ucal_setDate(ptr long long long ptr)
@ stub ucal_setDateTime(ptr long long long long long long ptr)
@ stub ucal_setDefaultTimeZone(ptr ptr)
@ stub ucal_setGregorianChange(ptr long ptr)
@ stub ucal_setMillis(ptr long ptr)
@ stub ucal_setTimeZone(ptr ptr long ptr)
@ stub ucasemap_close(ptr)
@ stub ucasemap_getBreakIterator(ptr)
@ stub ucasemap_getLocale(ptr)
@ stub ucasemap_getOptions(ptr)
@ stub ucasemap_open(str long ptr)
@ stub ucasemap_setBreakIterator(ptr ptr ptr)
@ stub ucasemap_setLocale(ptr str ptr)
@ stub ucasemap_setOptions(ptr long ptr)
@ stub ucasemap_toTitle(ptr ptr long ptr long ptr)
@ stub ucasemap_utf8FoldCase(ptr str long str long ptr)
@ stub ucasemap_utf8ToLower(ptr str long str long ptr)
@ stub ucasemap_utf8ToTitle(ptr str long str long ptr)
@ stub ucasemap_utf8ToUpper(ptr str long str long ptr)
@ stub ucfpos_close
@ stub ucfpos_constrainCategory
@ stub ucfpos_constrainField
@ stub ucfpos_getCategory
@ stub ucfpos_getField
@ stub ucfpos_getIndexes
@ stub ucfpos_getInt64IterationContext
@ stub ucfpos_matchesField
@ stub ucfpos_open
@ stub ucfpos_reset
@ stub ucfpos_setInt64IterationContext
@ stub ucfpos_setState
@ stub ucnv_cbFromUWriteBytes(ptr str long long ptr)
@ stub ucnv_cbFromUWriteSub(ptr long ptr)
@ stub ucnv_cbFromUWriteUChars(ptr ptr ptr long ptr)
@ stub ucnv_cbToUWriteSub(ptr long ptr)
@ stub ucnv_cbToUWriteUChars(ptr ptr long long ptr)
@ stub ucnv_clone
@ stub ucnv_close(ptr)
@ stub ucnv_compareNames(str str)
@ stub ucnv_convert(str str str long str long ptr)
@ stub ucnv_convertEx(ptr ptr ptr str ptr str ptr ptr ptr ptr long long ptr)
@ stub ucnv_countAliases(str ptr)
@ stub ucnv_countAvailable()
@ stub ucnv_countStandards()
@ stub ucnv_detectUnicodeSignature(str long ptr ptr)
@ stub ucnv_fixFileSeparator(ptr ptr long)
@ stub ucnv_flushCache()
@ stub ucnv_fromAlgorithmic(ptr long str long str long ptr)
@ stub ucnv_fromUChars(ptr str long ptr long ptr)
@ stub ucnv_fromUCountPending(ptr ptr)
@ stub ucnv_fromUnicode(ptr ptr str ptr ptr ptr long ptr)
@ stub ucnv_getAlias(str long ptr)
@ stub ucnv_getAliases(str ptr ptr)
@ stub ucnv_getAvailableName(long)
@ stub ucnv_getCCSID(ptr ptr)
@ stub ucnv_getCanonicalName(str str ptr)
@ stub ucnv_getDefaultName()
@ stub ucnv_getDisplayName(ptr str ptr long ptr)
@ stub ucnv_getFromUCallBack(ptr ptr ptr)
@ stub ucnv_getInvalidChars(ptr str ptr ptr)
@ stub ucnv_getInvalidUChars(ptr ptr ptr ptr)
@ stub ucnv_getMaxCharSize(ptr)
@ stub ucnv_getMinCharSize(ptr)
@ stub ucnv_getName(ptr ptr)
@ stub ucnv_getNextUChar(ptr ptr str ptr)
@ stub ucnv_getPlatform(ptr ptr)
@ stub ucnv_getStandard(long ptr)
@ stub ucnv_getStandardName(str str ptr)
@ stub ucnv_getStarters(ptr long ptr)
@ stub ucnv_getSubstChars(ptr str ptr ptr)
@ stub ucnv_getToUCallBack(ptr ptr ptr)
@ stub ucnv_getType(ptr)
@ stub ucnv_getUnicodeSet(ptr ptr long ptr)
@ stub ucnv_isAmbiguous(ptr)
@ stub ucnv_isFixedWidth(ptr ptr)
@ stub ucnv_open(str ptr)
@ stub ucnv_openAllNames(ptr)
@ stub ucnv_openCCSID(long long ptr)
@ stub ucnv_openPackage(str str ptr)
@ stub ucnv_openStandardNames(str str ptr)
@ stub ucnv_openU(ptr ptr)
@ stub ucnv_reset(ptr)
@ stub ucnv_resetFromUnicode(ptr)
@ stub ucnv_resetToUnicode(ptr)
@ stub ucnv_safeClone(ptr ptr ptr ptr)
@ stub ucnv_setDefaultName(str)
@ stub ucnv_setFallback(ptr long)
@ stub ucnv_setFromUCallBack(ptr long ptr ptr ptr ptr)
@ stub ucnv_setSubstChars(ptr str long ptr)
@ stub ucnv_setSubstString(ptr ptr long ptr)
@ stub ucnv_setToUCallBack(ptr long ptr ptr ptr ptr)
@ stub ucnv_toAlgorithmic(long ptr str long str long ptr)
@ stub ucnv_toUChars(ptr ptr long str long ptr)
@ stub ucnv_toUCountPending(ptr ptr)
@ stub ucnv_toUnicode(ptr ptr ptr ptr str ptr long ptr)
@ stub ucnv_usesFallback(ptr)
@ stub ucnvsel_close(ptr)
@ stub ucnvsel_open(str long ptr long ptr)
@ stub ucnvsel_openFromSerialized(ptr long ptr)
@ stub ucnvsel_selectForString(ptr ptr long ptr)
@ stub ucnvsel_selectForUTF8(ptr str long ptr)
@ stub ucnvsel_serialize(ptr ptr long ptr)
@ stub ucol_clone
@ stub ucol_cloneBinary(ptr ptr long ptr)
@ stub ucol_close(ptr)
@ stub ucol_closeElements(ptr)
@ stub ucol_countAvailable()
@ stub ucol_equal(ptr ptr long ptr long)
@ stub ucol_getAttribute(ptr long ptr)
@ stub ucol_getAvailable(long)
@ stub ucol_getBound(ptr long long long ptr long ptr)
@ stub ucol_getContractionsAndExpansions(ptr ptr ptr long ptr)
@ stub ucol_getDisplayName(str str ptr long ptr)
@ stub ucol_getEquivalentReorderCodes(long ptr long ptr)
@ stub ucol_getFunctionalEquivalent(str long str str ptr ptr)
@ stub ucol_getKeywordValues(str ptr)
@ stub ucol_getKeywordValuesForLocale(str str long ptr)
@ stub ucol_getKeywords(ptr)
@ stub ucol_getLocaleByType(ptr long ptr)
@ stub ucol_getMaxExpansion(ptr long)
@ stub ucol_getMaxVariable(ptr)
@ stub ucol_getOffset(ptr)
@ stub ucol_getReorderCodes(ptr ptr long ptr)
@ stub ucol_getRules(ptr ptr)
@ stub ucol_getRulesEx(ptr long ptr long)
@ stub ucol_getSortKey(ptr ptr long ptr long)
@ stub ucol_getStrength(ptr)
@ stub ucol_getTailoredSet(ptr ptr)
@ stub ucol_getUCAVersion(ptr long)
@ stub ucol_getVariableTop(ptr ptr)
@ stub ucol_getVersion(ptr long)
@ stub ucol_greater(ptr ptr long ptr long)
@ stub ucol_greaterOrEqual(ptr ptr long ptr long)
@ stub ucol_keyHashCode(ptr long)
@ stub ucol_mergeSortkeys(ptr long ptr long ptr long)
@ stub ucol_next(ptr ptr)
@ stub ucol_nextSortKeyPart(ptr ptr long ptr long ptr)
@ stub ucol_open(str ptr)
@ stub ucol_openAvailableLocales(ptr)
@ stub ucol_openBinary(ptr long ptr ptr)
@ stub ucol_openElements(ptr ptr long ptr)
@ stub ucol_openRules(ptr long long long ptr ptr)
@ stub ucol_previous(ptr ptr)
@ stub ucol_primaryOrder(long)
@ stub ucol_reset(ptr)
@ stub ucol_safeClone(ptr ptr ptr ptr)
@ stub ucol_secondaryOrder(long)
@ stub ucol_setAttribute(ptr long long ptr)
@ stub ucol_setMaxVariable(ptr long ptr)
@ stub ucol_setOffset(ptr long ptr)
@ stub ucol_setReorderCodes(ptr ptr long ptr)
@ stub ucol_setStrength(ptr long)
@ stub ucol_setText(ptr ptr long ptr)
@ stub ucol_strcoll(ptr ptr long ptr long)
@ stub ucol_strcollIter(ptr ptr ptr ptr)
@ stub ucol_strcollUTF8(ptr str long str long ptr)
@ stub ucol_tertiaryOrder(long)
@ stub ucpmap_get
@ stub ucpmap_getRange
@ stub ucptrie_close
@ stub ucptrie_get
@ stub ucptrie_getRange
@ stub ucptrie_getType
@ stub ucptrie_getValueWidth
@ stub ucptrie_internalSmallIndex
@ stub ucptrie_internalSmallU8Index
@ stub ucptrie_internalU8PrevIndex
@ stub ucptrie_openFromBinary
@ stub ucptrie_toBinary
@ stub ucsdet_close(ptr)
@ stub ucsdet_detect(ptr ptr)
@ stub ucsdet_detectAll(ptr ptr ptr)
@ stub ucsdet_enableInputFilter(ptr long)
@ stub ucsdet_getAllDetectableCharsets(ptr ptr)
@ stub ucsdet_getConfidence(ptr ptr)
@ stub ucsdet_getLanguage(ptr ptr)
@ stub ucsdet_getName(ptr ptr)
@ stub ucsdet_getUChars(ptr ptr long ptr)
@ stub ucsdet_isInputFilterEnabled(ptr)
@ stub ucsdet_open(ptr)
@ stub ucsdet_setDeclaredEncoding(ptr str long ptr)
@ stub ucsdet_setText(ptr str long ptr)
@ stub ucurr_countCurrencies(str long ptr)
@ stub ucurr_forLocale(str ptr long ptr)
@ stub ucurr_forLocaleAndDate(str long long ptr long ptr)
@ stub ucurr_getDefaultFractionDigits(ptr ptr)
@ stub ucurr_getDefaultFractionDigitsForUsage(ptr long ptr)
@ stub ucurr_getKeywordValuesForLocale(str str long ptr)
@ stub ucurr_getName(ptr str long ptr ptr ptr)
@ stub ucurr_getNumericCode(ptr)
@ stub ucurr_getPluralName(ptr str ptr str ptr ptr)
@ stub ucurr_getRoundingIncrement(ptr ptr)
@ stub ucurr_getRoundingIncrementForUsage(ptr long ptr)
@ stub ucurr_isAvailable(ptr long long ptr)
@ stub ucurr_openISOCurrencies(long ptr)
@ stub ucurr_register(ptr str ptr)
@ stub ucurr_unregister(long ptr)
@ stub udat_adoptNumberFormat(ptr ptr)
@ stub udat_adoptNumberFormatForFields(ptr ptr ptr ptr)
@ stub udat_applyPattern(ptr long ptr long)
@ stub udat_clone(ptr ptr)
@ stub udat_close(ptr)
@ stub udat_countAvailable()
@ stub udat_countSymbols(ptr long)
@ stub udat_format(ptr long ptr long ptr ptr)
@ stub udat_formatCalendar(ptr ptr ptr long ptr ptr)
@ stub udat_formatCalendarForFields(ptr ptr ptr long ptr ptr)
@ stub udat_formatForFields(ptr long ptr long ptr ptr)
@ stub udat_get2DigitYearStart(ptr ptr)
@ stub udat_getAvailable(long)
@ stub udat_getBooleanAttribute(ptr long ptr)
@ stub udat_getCalendar(ptr)
@ stub udat_getContext(ptr long ptr)
@ stub udat_getLocaleByType(ptr long ptr)
@ stub udat_getNumberFormat(ptr)
@ stub udat_getNumberFormatForField(ptr long)
@ stub udat_getSymbols(ptr long long ptr long ptr)
@ stub udat_isLenient(ptr)
@ stub udat_open(long long str ptr long ptr long ptr)
@ stub udat_parse(ptr ptr long ptr ptr)
@ stub udat_parseCalendar(ptr ptr ptr long ptr ptr)
@ stub udat_set2DigitYearStart(ptr long ptr)
@ stub udat_setBooleanAttribute(ptr long long ptr)
@ stub udat_setCalendar(ptr ptr)
@ stub udat_setContext(ptr long ptr)
@ stub udat_setLenient(ptr long)
@ stub udat_setNumberFormat(ptr ptr)
@ stub udat_setSymbols(ptr long long ptr long ptr)
@ stub udat_toCalendarDateField(long)
@ stub udat_toPattern(ptr long ptr long ptr)
@ stub udatpg_addPattern(ptr ptr long long ptr long ptr ptr)
@ stub udatpg_clone(ptr ptr)
@ stub udatpg_close(ptr)
@ stub udatpg_getAppendItemFormat(ptr long ptr)
@ stub udatpg_getAppendItemName(ptr long ptr)
@ stub udatpg_getBaseSkeleton(ptr ptr long ptr long ptr)
@ stub udatpg_getBestPattern(ptr ptr long ptr long ptr)
@ stub udatpg_getBestPatternWithOptions(ptr ptr long long ptr long ptr)
@ stub udatpg_getDateTimeFormat(ptr ptr)
@ stub udatpg_getDecimal(ptr ptr)
@ stub udatpg_getDefaultHourCycle
@ stub udatpg_getFieldDisplayName
@ stub udatpg_getPatternForSkeleton(ptr ptr long ptr)
@ stub udatpg_getSkeleton(ptr ptr long ptr long ptr)
@ stub udatpg_open(str ptr)
@ stub udatpg_openBaseSkeletons(ptr ptr)
@ stub udatpg_openEmpty(ptr)
@ stub udatpg_openSkeletons(ptr ptr)
@ stub udatpg_replaceFieldTypes(ptr ptr long ptr long ptr long ptr)
@ stub udatpg_replaceFieldTypesWithOptions(ptr ptr long ptr long long ptr long ptr)
@ stub udatpg_setAppendItemFormat(ptr long ptr long)
@ stub udatpg_setAppendItemName(ptr long ptr long)
@ stub udatpg_setDateTimeFormat(ptr ptr long)
@ stub udatpg_setDecimal(ptr ptr long)
@ stub udtitvfmt_close(ptr)
@ stub udtitvfmt_closeResult
@ stub udtitvfmt_format(ptr long long ptr long ptr ptr)
@ stub udtitvfmt_formatToResult
@ stub udtitvfmt_getContext
@ stub udtitvfmt_open(str ptr long ptr long ptr)
@ stub udtitvfmt_openResult
@ stub udtitvfmt_resultAsValue
@ stub udtitvfmt_setContext
@ stub uenum_close(ptr)
@ stub uenum_count(ptr ptr)
@ stub uenum_next(ptr ptr ptr)
@ stub uenum_openCharStringsEnumeration(str long ptr)
@ stub uenum_openUCharStringsEnumeration(ptr long ptr)
@ stub uenum_reset(ptr ptr)
@ stub uenum_unext(ptr ptr ptr)
@ stub ufieldpositer_close(ptr)
@ stub ufieldpositer_next(ptr ptr ptr)
@ stub ufieldpositer_open(ptr)
@ stub ufmt_close(ptr)
@ stub ufmt_getArrayItemByIndex(ptr long ptr)
@ stub ufmt_getArrayLength(ptr ptr)
@ stub ufmt_getDate(ptr ptr)
@ stub ufmt_getDecNumChars(ptr ptr ptr)
@ stub ufmt_getDouble(ptr ptr)
@ stub ufmt_getInt64(ptr ptr)
@ stub ufmt_getLong(ptr ptr)
@ stub ufmt_getObject(ptr ptr)
@ stub ufmt_getType(ptr ptr)
@ stub ufmt_getUChars(ptr ptr ptr)
@ stub ufmt_isNumeric(ptr)
@ stub ufmt_open(ptr)
@ stub ufmtval_getString
@ stub ufmtval_nextPosition
@ stub ugender_getInstance(str ptr)
@ stub ugender_getListGender(ptr ptr long ptr)
@ stub uidna_close(ptr)
@ stub uidna_labelToASCII(ptr ptr long ptr long ptr ptr)
@ stub uidna_labelToASCII_UTF8(ptr str long str long ptr ptr)
@ stub uidna_labelToUnicode(ptr ptr long ptr long ptr ptr)
@ stub uidna_labelToUnicodeUTF8(ptr str long str long ptr ptr)
@ stub uidna_nameToASCII(ptr ptr long ptr long ptr ptr)
@ stub uidna_nameToASCII_UTF8(ptr str long str long ptr ptr)
@ stub uidna_nameToUnicode(ptr ptr long ptr long ptr ptr)
@ stub uidna_nameToUnicodeUTF8(ptr str long str long ptr ptr)
@ stub uidna_openUTS46(long ptr)
@ stub uiter_current32(ptr)
@ stub uiter_getState(ptr)
@ stub uiter_next32(ptr)
@ stub uiter_previous32(ptr)
@ stub uiter_setState(ptr long ptr)
@ stub uiter_setString(ptr ptr long)
@ stub uiter_setUTF16BE(ptr str long)
@ stub uiter_setUTF8(ptr str long)
@ stub uldn_close(ptr)
@ stub uldn_getContext(ptr long ptr)
@ stub uldn_getDialectHandling(ptr)
@ stub uldn_getLocale(ptr)
@ stub uldn_keyDisplayName(ptr str ptr long ptr)
@ stub uldn_keyValueDisplayName(ptr str str ptr long ptr)
@ stub uldn_languageDisplayName(ptr str ptr long ptr)
@ stub uldn_localeDisplayName(ptr str ptr long ptr)
@ stub uldn_open(str long ptr)
@ stub uldn_openForContext(str ptr long ptr)
@ stub uldn_regionDisplayName(ptr str ptr long ptr)
@ stub uldn_scriptCodeDisplayName(ptr long ptr long ptr)
@ stub uldn_scriptDisplayName(ptr str ptr long ptr)
@ stub uldn_variantDisplayName(ptr str ptr long ptr)
@ stub ulistfmt_close(ptr)
@ stub ulistfmt_closeResult
@ stub ulistfmt_format(ptr ptr ptr long ptr long ptr)
@ stub ulistfmt_formatStringsToResult
@ stub ulistfmt_open(str ptr)
@ stub ulistfmt_openForType
@ stub ulistfmt_openResult
@ stub ulistfmt_resultAsValue
@ stub uloc_acceptLanguage(str long ptr ptr long ptr ptr)
@ stub uloc_acceptLanguageFromHTTP(str long ptr str ptr ptr)
@ stub uloc_addLikelySubtags(str str long ptr)
@ stub uloc_canonicalize(str str long ptr)
@ stub uloc_countAvailable()
@ stub uloc_forLanguageTag(str str long ptr ptr)
@ stub uloc_getAvailable(long)
@ stub uloc_getBaseName(str str long ptr)
@ stub uloc_getCharacterOrientation(str ptr)
@ stub uloc_getCountry(str str long ptr)
@ stub uloc_getDefault()
@ stub uloc_getDisplayCountry(str str ptr long ptr)
@ stub uloc_getDisplayKeyword(str str ptr long ptr)
@ stub uloc_getDisplayKeywordValue(str str str ptr long ptr)
@ stub uloc_getDisplayLanguage(str str ptr long ptr)
@ stub uloc_getDisplayName(str str ptr long ptr)
@ stub uloc_getDisplayScript(str str ptr long ptr)
@ stub uloc_getDisplayVariant(str str ptr long ptr)
@ stub uloc_getISO3Country(str)
@ stub uloc_getISO3Language(str)
@ stub uloc_getISOCountries()
@ stub uloc_getISOLanguages()
@ stub uloc_getKeywordValue(str str str long ptr)
@ stub uloc_getLCID(str)
@ stub uloc_getLanguage(str str long ptr)
@ stub uloc_getLineOrientation(str ptr)
@ stub uloc_getLocaleForLCID(long str long ptr)
@ stub uloc_getName(str str long ptr)
@ stub uloc_getParent(str str long ptr)
@ stub uloc_getScript(str str long ptr)
@ stub uloc_getVariant(str str long ptr)
@ stub uloc_isRightToLeft(str)
@ stub uloc_minimizeSubtags(str str long ptr)
@ stub uloc_openAvailableByType
@ stub uloc_openKeywords(str ptr)
@ stub uloc_setDefault(str ptr)
@ stub uloc_setKeywordValue(str str str long ptr)
@ stub uloc_toLanguageTag(str str long long ptr)
@ stub uloc_toLegacyKey(str)
@ stub uloc_toLegacyType(str str)
@ stub uloc_toUnicodeLocaleKey(str)
@ stub uloc_toUnicodeLocaleType(str str)
@ stub ulocdata_close(ptr)
@ stub ulocdata_getCLDRVersion(long ptr)
@ stub ulocdata_getDelimiter(ptr long ptr long ptr)
@ stub ulocdata_getExemplarSet(ptr ptr long long ptr)
@ stub ulocdata_getLocaleDisplayPattern(ptr ptr long ptr)
@ stub ulocdata_getLocaleSeparator(ptr ptr long ptr)
@ stub ulocdata_getMeasurementSystem(str ptr)
@ stub ulocdata_getNoSubstitute(ptr)
@ stub ulocdata_getPaperSize(str ptr ptr ptr)
@ stub ulocdata_open(str ptr)
@ stub ulocdata_setNoSubstitute(ptr long)
@ stub umsg_applyPattern(ptr ptr long ptr ptr)
@ stub umsg_autoQuoteApostrophe(ptr long ptr long ptr)
@ stub umsg_clone(ptr ptr)
@ stub umsg_close(ptr)
@ stub umsg_format(ptr ptr long ptr)
@ stub umsg_getLocale(ptr)
@ stub umsg_open(ptr long str ptr ptr)
@ stub umsg_parse(ptr ptr long ptr ptr)
@ stub umsg_setLocale(ptr str)
@ stub umsg_toPattern(ptr ptr long ptr)
@ stub umsg_vformat(ptr ptr long long ptr)
@ stub umsg_vparse(ptr ptr long ptr long ptr)
@ stub umutablecptrie_buildImmutable
@ stub umutablecptrie_clone
@ stub umutablecptrie_close
@ stub umutablecptrie_fromUCPMap
@ stub umutablecptrie_fromUCPTrie
@ stub umutablecptrie_get
@ stub umutablecptrie_getRange
@ stub umutablecptrie_open
@ stub umutablecptrie_set
@ stub umutablecptrie_setRange
@ stub unorm2_append(ptr ptr long long ptr long ptr)
@ stub unorm2_close(ptr)
@ stub unorm2_composePair(ptr long long)
@ stub unorm2_getCombiningClass(ptr long)
@ stub unorm2_getDecomposition(ptr long ptr long ptr)
@ stub unorm2_getInstance(str str long ptr)
@ stub unorm2_getNFCInstance(ptr)
@ stub unorm2_getNFDInstance(ptr)
@ stub unorm2_getNFKCCasefoldInstance(ptr)
@ stub unorm2_getNFKCInstance(ptr)
@ stub unorm2_getNFKDInstance(ptr)
@ stub unorm2_getRawDecomposition(ptr long ptr long ptr)
@ stub unorm2_hasBoundaryAfter(ptr long)
@ stub unorm2_hasBoundaryBefore(ptr long)
@ stub unorm2_isInert(ptr long)
@ stub unorm2_isNormalized(ptr ptr long ptr)
@ stub unorm2_normalize(ptr ptr long ptr long ptr)
@ stub unorm2_normalizeSecondAndAppend(ptr ptr long long ptr long ptr)
@ stub unorm2_openFiltered(ptr ptr ptr)
@ stub unorm2_quickCheck(ptr ptr long ptr)
@ stub unorm2_spanQuickCheckYes(ptr ptr long ptr)
@ stub unorm_compare(ptr long ptr long long ptr)
@ stub unum_applyPattern(ptr long ptr long ptr ptr)
@ stub unum_clone(ptr ptr)
@ stub unum_close(ptr)
@ stub unum_countAvailable()
@ stub unum_format(ptr long ptr long ptr ptr)
@ stub unum_formatDecimal(ptr str long ptr long ptr ptr)
@ stub unum_formatDouble(ptr double ptr long ptr ptr)
@ stub unum_formatDoubleCurrency(ptr double ptr ptr long ptr ptr)
@ stub unum_formatDoubleForFields(ptr double ptr long ptr ptr)
@ stub unum_formatInt64(ptr long ptr long ptr ptr)
@ stub unum_formatUFormattable(ptr ptr ptr long ptr ptr)
@ stub unum_getAttribute(ptr long)
@ stub unum_getAvailable(long)
@ stub unum_getContext(ptr long ptr)
@ stub unum_getDoubleAttribute(ptr long)
@ stub unum_getLocaleByType(ptr long ptr)
@ stub unum_getSymbol(ptr long ptr long ptr)
@ stub unum_getTextAttribute(ptr long ptr long ptr)
@ stub unum_open(long ptr long str ptr ptr)
@ stub unum_parse(ptr ptr long ptr ptr)
@ stub unum_parseDecimal(ptr ptr long ptr str long ptr)
@ stub unum_parseDouble(ptr ptr long ptr ptr)
@ stub unum_parseDoubleCurrency(ptr ptr long ptr ptr ptr)
@ stub unum_parseInt64(ptr ptr long ptr ptr)
@ stub unum_parseToUFormattable(ptr ptr ptr long ptr ptr)
@ stub unum_setAttribute(ptr long long)
@ stub unum_setContext(ptr long ptr)
@ stub unum_setDoubleAttribute(ptr long double)
@ stub unum_setSymbol(ptr long ptr long ptr)
@ stub unum_setTextAttribute(ptr long ptr long ptr)
@ stub unum_toPattern(ptr long ptr long ptr)
@ stub unumf_close
@ stub unumf_closeResult
@ stub unumf_formatDecimal
@ stub unumf_formatDouble
@ stub unumf_formatInt
@ stub unumf_openForSkeletonAndLocale
@ stub unumf_openForSkeletonAndLocaleWithError
@ stub unumf_openResult
@ stub unumf_resultAsValue
@ stub unumf_resultGetAllFieldPositions
@ stub unumf_resultNextFieldPosition
@ stub unumf_resultToDecimalNumber
@ stub unumf_resultToString
@ stub unumrf_close
@ stub unumrf_closeResult
@ stub unumrf_formatDecimalRange
@ stub unumrf_formatDoubleRange
@ stub unumrf_openForSkeletonWithCollapseAndIdentityFallback
@ stub unumrf_openResult
@ stub unumrf_resultAsValue
@ stub unumrf_resultGetFirstDecimalNumber
@ stub unumrf_resultGetIdentityResult
@ stub unumrf_resultGetSecondDecimalNumber
@ stub unumsys_close(ptr)
@ stub unumsys_getDescription(ptr ptr long ptr)
@ stub unumsys_getName(ptr)
@ stub unumsys_getRadix(ptr)
@ stub unumsys_isAlgorithmic(ptr)
@ stub unumsys_open(str ptr)
@ stub unumsys_openAvailableNames(ptr)
@ stub unumsys_openByName(str ptr)
@ stub uplrules_close(ptr)
@ stub uplrules_getKeywords(ptr ptr)
@ stub uplrules_open(str ptr)
@ stub uplrules_openForType(str long ptr)
@ stub uplrules_select(ptr double ptr long ptr)
@ stub uplrules_selectFormatted
@ stub uregex_appendReplacement(ptr ptr long ptr ptr ptr)
@ stub uregex_appendReplacementUText(ptr ptr ptr ptr)
@ stub uregex_appendTail(ptr ptr ptr ptr)
@ stub uregex_appendTailUText(ptr ptr ptr)
@ stub uregex_clone(ptr ptr)
@ stub uregex_close(ptr)
@ stub uregex_end(ptr long ptr)
@ stub uregex_end64(ptr long ptr)
@ stub uregex_find(ptr long ptr)
@ stub uregex_find64(ptr long ptr)
@ stub uregex_findNext(ptr ptr)
@ stub uregex_flags(ptr ptr)
@ stub uregex_getFindProgressCallback(ptr ptr ptr ptr)
@ stub uregex_getMatchCallback(ptr ptr ptr ptr)
@ stub uregex_getStackLimit(ptr ptr)
@ stub uregex_getText(ptr ptr ptr)
@ stub uregex_getTimeLimit(ptr ptr)
@ stub uregex_getUText(ptr ptr ptr)
@ stub uregex_group(ptr long ptr long ptr)
@ stub uregex_groupCount(ptr ptr)
@ stub uregex_groupNumberFromCName(ptr str long ptr)
@ stub uregex_groupNumberFromName(ptr ptr long ptr)
@ stub uregex_groupUText(ptr long ptr ptr ptr)
@ stub uregex_hasAnchoringBounds(ptr ptr)
@ stub uregex_hasTransparentBounds(ptr ptr)
@ stub uregex_hitEnd(ptr ptr)
@ stub uregex_lookingAt(ptr long ptr)
@ stub uregex_lookingAt64(ptr long ptr)
@ stub uregex_matches(ptr long ptr)
@ stub uregex_matches64(ptr long ptr)
@ stub uregex_open(ptr long long ptr ptr)
@ stub uregex_openC(str long ptr ptr)
@ stub uregex_openUText(ptr long ptr ptr)
@ stub uregex_pattern(ptr ptr ptr)
@ stub uregex_patternUText(ptr ptr)
@ stub uregex_refreshUText(ptr ptr ptr)
@ stub uregex_regionEnd(ptr ptr)
@ stub uregex_regionEnd64(ptr ptr)
@ stub uregex_regionStart(ptr ptr)
@ stub uregex_regionStart64(ptr ptr)
@ stub uregex_replaceAll(ptr ptr long ptr long ptr)
@ stub uregex_replaceAllUText(ptr ptr ptr ptr)
@ stub uregex_replaceFirst(ptr ptr long ptr long ptr)
@ stub uregex_replaceFirstUText(ptr ptr ptr ptr)
@ stub uregex_requireEnd(ptr ptr)
@ stub uregex_reset(ptr long ptr)
@ stub uregex_reset64(ptr long ptr)
@ stub uregex_setFindProgressCallback(ptr ptr ptr ptr)
@ stub uregex_setMatchCallback(ptr ptr ptr ptr)
@ stub uregex_setRegion(ptr long long ptr)
@ stub uregex_setRegion64(ptr long long ptr)
@ stub uregex_setRegionAndStart(ptr long long long ptr)
@ stub uregex_setStackLimit(ptr long ptr)
@ stub uregex_setText(ptr ptr long ptr)
@ stub uregex_setTimeLimit(ptr long ptr)
@ stub uregex_setUText(ptr ptr ptr)
@ stub uregex_split(ptr ptr long ptr ptr long ptr)
@ stub uregex_splitUText(ptr ptr long ptr)
@ stub uregex_start(ptr long ptr)
@ stub uregex_start64(ptr long ptr)
@ stub uregex_useAnchoringBounds(ptr long ptr)
@ stub uregex_useTransparentBounds(ptr long ptr)
@ stub uregion_areEqual(ptr ptr)
@ stub uregion_contains(ptr ptr)
@ stub uregion_getAvailable(long ptr)
@ stub uregion_getContainedRegions(ptr ptr)
@ stub uregion_getContainedRegionsOfType(ptr long ptr)
@ stub uregion_getContainingRegion(ptr)
@ stub uregion_getContainingRegionOfType(ptr long)
@ stub uregion_getNumericCode(ptr)
@ stub uregion_getPreferredValues(ptr ptr)
@ stub uregion_getRegionCode(ptr)
@ stub uregion_getRegionFromCode(str ptr)
@ stub uregion_getRegionFromNumericCode(long ptr)
@ stub uregion_getType(ptr)
@ stub ureldatefmt_close(ptr)
@ stub ureldatefmt_closeResult
@ stub ureldatefmt_combineDateAndTime(ptr ptr long ptr long ptr long ptr)
@ stub ureldatefmt_format(ptr double long ptr long ptr)
@ stub ureldatefmt_formatNumeric(ptr double long ptr long ptr)
@ stub ureldatefmt_formatNumericToResult
@ stub ureldatefmt_formatToResult
@ stub ureldatefmt_open(str ptr long long ptr)
@ stub ureldatefmt_openResult
@ stub ureldatefmt_resultAsValue
@ stub ures_close(ptr)
@ stub ures_getBinary(ptr ptr ptr)
@ stub ures_getByIndex(ptr long ptr ptr)
@ stub ures_getByKey(ptr str ptr ptr)
@ stub ures_getInt(ptr ptr)
@ stub ures_getIntVector(ptr ptr ptr)
@ stub ures_getKey(ptr)
@ stub ures_getLocaleByType(ptr long ptr)
@ stub ures_getNextResource(ptr ptr ptr)
@ stub ures_getNextString(ptr ptr ptr ptr)
@ stub ures_getSize(ptr)
@ stub ures_getString(ptr ptr ptr)
@ stub ures_getStringByIndex(ptr long ptr ptr)
@ stub ures_getStringByKey(ptr str ptr ptr)
@ stub ures_getType(ptr)
@ stub ures_getUInt(ptr ptr)
@ stub ures_getUTF8String(ptr str ptr long ptr)
@ stub ures_getUTF8StringByIndex(ptr long str ptr long ptr)
@ stub ures_getUTF8StringByKey(ptr str str ptr long ptr)
@ stub ures_getVersion(ptr long)
@ stub ures_hasNext(ptr)
@ stub ures_open(str str ptr)
@ stub ures_openAvailableLocales(str ptr)
@ stub ures_openDirect(str str ptr)
@ stub ures_openU(ptr str ptr)
@ stub ures_resetIterator(ptr)
@ stub uscript_breaksBetweenLetters(long)
@ stub uscript_getCode(str ptr long ptr)
@ stub uscript_getName(long)
@ stub uscript_getSampleString(long ptr long ptr)
@ stub uscript_getScript(long ptr)
@ stub uscript_getScriptExtensions(long ptr long ptr)
@ stub uscript_getShortName(long)
@ stub uscript_getUsage(long)
@ stub uscript_hasScript(long long)
@ stub uscript_isCased(long)
@ stub uscript_isRightToLeft(long)
@ stub usearch_close(ptr)
@ stub usearch_first(ptr ptr)
@ stub usearch_following(ptr long ptr)
@ stub usearch_getAttribute(ptr long)
@ stub usearch_getBreakIterator(ptr)
@ stub usearch_getCollator(ptr)
@ stub usearch_getMatchedLength(ptr)
@ stub usearch_getMatchedStart(ptr)
@ stub usearch_getMatchedText(ptr ptr long ptr)
@ stub usearch_getOffset(ptr)
@ stub usearch_getPattern(ptr ptr)
@ stub usearch_getText(ptr ptr)
@ stub usearch_last(ptr ptr)
@ stub usearch_next(ptr ptr)
@ stub usearch_open(ptr long ptr long str ptr ptr)
@ stub usearch_openFromCollator(ptr long ptr long ptr ptr ptr)
@ stub usearch_preceding(ptr long ptr)
@ stub usearch_previous(ptr ptr)
@ stub usearch_reset(ptr)
@ stub usearch_setAttribute(ptr long long ptr)
@ stub usearch_setBreakIterator(ptr ptr ptr)
@ stub usearch_setCollator(ptr ptr ptr)
@ stub usearch_setOffset(ptr long ptr)
@ stub usearch_setPattern(ptr ptr long ptr)
@ stub usearch_setText(ptr ptr long ptr)
@ stub uset_add(ptr long)
@ stub uset_addAll(ptr ptr)
@ stub uset_addAllCodePoints(ptr ptr long)
@ stub uset_addRange(ptr long long)
@ stub uset_addString(ptr ptr long)
@ stub uset_applyIntPropertyValue(ptr long long ptr)
@ stub uset_applyPattern(ptr ptr long long ptr)
@ stub uset_applyPropertyAlias(ptr ptr long ptr long ptr)
@ stub uset_charAt(ptr long)
@ stub uset_clear(ptr)
@ stub uset_clone(ptr)
@ stub uset_cloneAsThawed(ptr)
@ stub uset_close(ptr)
@ stub uset_closeOver(ptr long)
@ stub uset_compact(ptr)
@ stub uset_complement(ptr)
@ stub uset_complementAll(ptr ptr)
@ stub uset_complementAllCodePoints
@ stub uset_complementRange
@ stub uset_complementString
@ stub uset_contains(ptr long)
@ stub uset_containsAll(ptr ptr)
@ stub uset_containsAllCodePoints(ptr ptr long)
@ stub uset_containsNone(ptr ptr)
@ stub uset_containsRange(ptr long long)
@ stub uset_containsSome(ptr ptr)
@ stub uset_containsString(ptr ptr long)
@ stub uset_equals(ptr ptr)
@ stub uset_freeze(ptr)
@ stub uset_getItem(ptr long ptr ptr ptr long ptr)
@ stub uset_getItemCount(ptr)
@ stub uset_getRangeCount
@ stub uset_getSerializedRange(ptr long ptr ptr)
@ stub uset_getSerializedRangeCount(ptr)
@ stub uset_getSerializedSet(ptr ptr long)
@ stub uset_hasStrings
@ stub uset_indexOf(ptr long)
@ stub uset_isEmpty(ptr)
@ stub uset_isFrozen(ptr)
@ stub uset_open(long long)
@ stub uset_openEmpty()
@ stub uset_openPattern(ptr long ptr)
@ stub uset_openPatternOptions(ptr long long ptr)
@ stub uset_remove(ptr long)
@ stub uset_removeAll(ptr ptr)
@ stub uset_removeAllCodePoints
@ stub uset_removeAllStrings(ptr)
@ stub uset_removeRange(ptr long long)
@ stub uset_removeString(ptr ptr long)
@ stub uset_resemblesPattern(ptr long long)
@ stub uset_retain(ptr long long)
@ stub uset_retainAll(ptr ptr)
@ stub uset_retainAllCodePoints
@ stub uset_retainString
@ stub uset_serialize(ptr ptr long ptr)
@ stub uset_serializedContains(ptr long)
@ stub uset_set(ptr long long)
@ stub uset_setSerializedToOne(ptr long)
@ stub uset_size(ptr)
@ stub uset_span(ptr ptr long long)
@ stub uset_spanBack(ptr ptr long long)
@ stub uset_spanBackUTF8(ptr str long long)
@ stub uset_spanUTF8(ptr str long long)
@ stub uset_toPattern(ptr ptr long long ptr)
@ stub uspoof_areConfusable(ptr ptr long ptr long ptr)
@ stub uspoof_areConfusableUTF8(ptr str long str long ptr)
@ stub uspoof_check(ptr ptr long ptr ptr)
@ stub uspoof_check2(ptr ptr long ptr ptr)
@ stub uspoof_check2UTF8(ptr str long ptr ptr)
@ stub uspoof_checkUTF8(ptr str long ptr ptr)
@ stub uspoof_clone(ptr ptr)
@ stub uspoof_close(ptr)
@ stub uspoof_closeCheckResult(ptr)
@ stub uspoof_getAllowedChars(ptr ptr)
@ stub uspoof_getAllowedLocales(ptr ptr)
@ stub uspoof_getCheckResultChecks(ptr ptr)
@ stub uspoof_getCheckResultNumerics(ptr ptr)
@ stub uspoof_getCheckResultRestrictionLevel(ptr ptr)
@ stub uspoof_getChecks(ptr ptr)
@ stub uspoof_getInclusionSet(ptr)
@ stub uspoof_getRecommendedSet(ptr)
@ stub uspoof_getRestrictionLevel(ptr)
@ stub uspoof_getSkeleton(ptr long ptr long ptr long ptr)
@ stub uspoof_getSkeletonUTF8(ptr long str long str long ptr)
@ stub uspoof_open(ptr)
@ stub uspoof_openCheckResult(ptr)
@ stub uspoof_openFromSerialized(ptr long ptr ptr)
@ stub uspoof_openFromSource(str long str long ptr ptr ptr)
@ stub uspoof_serialize(ptr ptr long ptr)
@ stub uspoof_setAllowedChars(ptr ptr ptr)
@ stub uspoof_setAllowedLocales(ptr str ptr)
@ stub uspoof_setChecks(ptr long ptr)
@ stub uspoof_setRestrictionLevel(ptr long)
@ stub usprep_close(ptr)
@ stub usprep_open(str str ptr)
@ stub usprep_openByType(long ptr)
@ stub usprep_prepare(ptr ptr long ptr long long ptr ptr)
@ stub utext_char32At(ptr long)
@ stub utext_clone(ptr ptr long long ptr)
@ stub utext_close(ptr)
@ stub utext_copy(ptr long long long long ptr)
@ stub utext_current32(ptr)
@ stub utext_equals(ptr ptr)
@ stub utext_extract(ptr long long ptr long ptr)
@ stub utext_freeze(ptr)
@ stub utext_getNativeIndex(ptr)
@ stub utext_getPreviousNativeIndex(ptr)
@ stub utext_hasMetaData(ptr)
@ stub utext_isLengthExpensive(ptr)
@ stub utext_isWritable(ptr)
@ stub utext_moveIndex32(ptr long)
@ stub utext_nativeLength(ptr)
@ stub utext_next32(ptr)
@ stub utext_next32From(ptr long)
@ stub utext_openUChars(ptr ptr long ptr)
@ stub utext_openUTF8(ptr str long ptr)
@ stub utext_previous32(ptr)
@ stub utext_previous32From(ptr long)
@ stub utext_replace(ptr long long ptr long ptr)
@ stub utext_setNativeIndex(ptr long)
@ stub utext_setup(ptr long ptr)
@ stub utf8_appendCharSafeBody(ptr long long long ptr)
@ stub utf8_back1SafeBody(ptr long long)
@ stub utf8_nextCharSafeBody(ptr ptr long long long)
@ stub utf8_prevCharSafeBody(ptr long ptr long long)
@ stub utmscale_fromInt64(long long ptr)
@ stub utmscale_getTimeScaleValue(long long ptr)
@ stub utmscale_toInt64(long long ptr)
@ stub utrace_format(str long long str)
@ stub utrace_functionName(long)
@ stub utrace_getFunctions(ptr ptr ptr ptr)
@ stub utrace_getLevel()
@ stub utrace_setFunctions(ptr ptr ptr ptr)
@ stub utrace_setLevel(long)
@ stub utrace_vformat(str long long str long)
@ stub utrans_clone(ptr ptr)
@ stub utrans_close(ptr)
@ stub utrans_countAvailableIDs()
@ stub utrans_getSourceSet(ptr long ptr ptr)
@ stub utrans_getUnicodeID(ptr ptr)
@ stub utrans_openIDs(ptr)
@ stub utrans_openInverse(ptr ptr)
@ stub utrans_openU(ptr long long ptr long ptr ptr)
@ stub utrans_register(ptr ptr)
@ stub utrans_setFilter(ptr ptr long ptr)
@ stub utrans_toRules(ptr long ptr long ptr)
@ stub utrans_trans(ptr ptr ptr long ptr ptr)
@ stub utrans_transIncremental(ptr ptr ptr ptr ptr)
@ stub utrans_transIncrementalUChars(ptr ptr ptr long ptr ptr)
@ stub utrans_transUChars(ptr ptr ptr long long ptr ptr)
@ stub utrans_unregisterID(ptr long)
