@ stub CloseDefaultICUGroupingLetters
@ stub GetDefaultICUGroupingLetters
@ stub GetICUGroupingLetter
@ stub SortCloseHandle
@ stub SortGetHandle
@ stub SortGetSearchKey
@ cdecl UCNV_FROM_U_CALLBACK_ESCAPE(ptr ptr ptr long long long ptr)
@ cdecl UCNV_FROM_U_CALLBACK_SKIP(ptr ptr ptr long long long ptr)
@ cdecl UCNV_FROM_U_CALLBACK_STOP(ptr ptr ptr long long long ptr)
@ cdecl UCNV_FROM_U_CALLBACK_SUBSTITUTE(ptr ptr ptr long long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_ESCAPE(ptr ptr str long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_SKIP(ptr ptr str long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_STOP(ptr ptr str long long ptr)
@ cdecl UCNV_TO_U_CALLBACK_SUBSTITUTE(ptr ptr str long long ptr)
@ cdecl u_UCharsToChars(ptr str long)
@ cdecl u_austrcpy(str ptr)
@ cdecl u_austrncpy(str ptr long)
@ cdecl u_catclose(long)
@ cdecl u_catgets(long long long ptr ptr ptr)
@ cdecl u_catopen(str str ptr)
@ cdecl u_charAge(long long)
@ cdecl u_charDigitValue(long)
@ cdecl u_charDirection(long)
@ cdecl u_charFromName(long str ptr)
@ cdecl u_charMirror(long)
@ cdecl u_charName(long long str long ptr)
@ cdecl u_charType(long)
@ cdecl u_charsToUChars(str ptr long)
@ cdecl u_cleanup()
@ cdecl u_countChar32(ptr long)
@ cdecl u_digit(long long)
@ cdecl u_enumCharNames(long long ptr ptr long ptr)
@ cdecl u_enumCharTypes(ptr ptr)
@ cdecl u_errorName(long)
@ cdecl u_foldCase(long long)
@ cdecl u_forDigit(long long)
@ varargs u_formatMessage(str ptr long ptr long ptr)
@ varargs u_formatMessageWithError(str ptr long ptr long ptr ptr)
@ cdecl u_getBidiPairedBracket(long)
@ cdecl u_getBinaryPropertySet(long ptr)
@ cdecl u_getCombiningClass(long)
@ cdecl u_getDataVersion(long ptr)
@ cdecl u_getFC_NFKC_Closure(long ptr long ptr)
@ cdecl u_getIntPropertyMap(long ptr)
@ cdecl u_getIntPropertyMaxValue(long)
@ cdecl u_getIntPropertyMinValue(long)
@ cdecl u_getIntPropertyValue(long long)
@ cdecl u_getNumericValue(long)
@ cdecl u_getPropertyEnum(str)
@ cdecl u_getPropertyName(long long)
@ cdecl u_getPropertyValueEnum(long str)
@ cdecl u_getPropertyValueName(long long long)
@ cdecl u_getUnicodeVersion(long)
@ cdecl u_getVersion(long)
@ cdecl u_hasBinaryProperty(long long)
@ cdecl u_init(ptr)
@ cdecl u_isIDIgnorable(long)
@ cdecl u_isIDPart(long)
@ cdecl u_isIDStart(long)
@ cdecl u_isISOControl(long)
@ cdecl u_isJavaIDPart(long)
@ cdecl u_isJavaIDStart(long)
@ cdecl u_isJavaSpaceChar(long)
@ cdecl u_isMirrored(long)
@ cdecl u_isUAlphabetic(long)
@ cdecl u_isULowercase(long)
@ cdecl u_isUUppercase(long)
@ cdecl u_isUWhiteSpace(long)
@ cdecl u_isWhitespace(long)
@ cdecl u_isalnum(long)
@ cdecl u_isalpha(long)
@ cdecl u_isbase(long)
@ cdecl u_isblank(long)
@ cdecl u_iscntrl(long)
@ cdecl u_isdefined(long)
@ cdecl u_isdigit(long)
@ cdecl u_isgraph(long)
@ cdecl u_islower(long)
@ cdecl u_isprint(long)
@ cdecl u_ispunct(long)
@ cdecl u_isspace(long)
@ cdecl u_istitle(long)
@ cdecl u_isupper(long)
@ cdecl u_isxdigit(long)
@ cdecl u_memcasecmp(ptr ptr long long)
@ cdecl u_memchr(ptr long long)
@ cdecl u_memchr32(ptr long long)
@ cdecl u_memcmp(ptr ptr long)
@ cdecl u_memcmpCodePointOrder(ptr ptr long)
@ cdecl u_memcpy(ptr ptr long)
@ cdecl u_memmove(ptr ptr long)
@ cdecl u_memrchr(ptr long long)
@ cdecl u_memrchr32(ptr long long)
@ cdecl u_memset(ptr long long)
@ varargs u_parseMessage(str ptr long ptr long ptr)
@ varargs u_parseMessageWithError(str ptr long ptr long ptr ptr)
@ cdecl u_setMemoryFunctions(ptr ptr ptr ptr ptr)
@ cdecl u_shapeArabic(ptr long ptr long long ptr)
@ cdecl u_strCaseCompare(ptr long ptr long long ptr)
@ cdecl u_strCompare(ptr long ptr long long)
@ cdecl u_strCompareIter(ptr ptr long)
@ cdecl u_strFindFirst(ptr long ptr long)
@ cdecl u_strFindLast(ptr long ptr long)
@ cdecl u_strFoldCase(ptr long ptr long long ptr)
@ cdecl u_strFromJavaModifiedUTF8WithSub(ptr long ptr str long long ptr ptr)
@ cdecl u_strFromUTF32(ptr long ptr ptr long ptr)
@ cdecl u_strFromUTF32WithSub(ptr long ptr ptr long long ptr ptr)
@ cdecl u_strFromUTF8(ptr long ptr str long ptr)
@ cdecl u_strFromUTF8Lenient(ptr long ptr str long ptr)
@ cdecl u_strFromUTF8WithSub(ptr long ptr str long long ptr ptr)
@ cdecl u_strFromWCS(ptr long ptr wstr long ptr)
@ cdecl u_strHasMoreChar32Than(ptr long long)
@ cdecl u_strToJavaModifiedUTF8(str long ptr ptr long ptr)
@ cdecl u_strToLower(ptr long ptr long str ptr)
@ cdecl u_strToTitle(ptr long ptr long ptr str ptr)
@ cdecl u_strToUTF32(ptr long ptr ptr long ptr)
@ cdecl u_strToUTF32WithSub(ptr long ptr ptr long long ptr ptr)
@ cdecl u_strToUTF8(str long ptr ptr long ptr)
@ cdecl u_strToUTF8WithSub(str long ptr ptr long long ptr ptr)
@ cdecl u_strToUpper(ptr long ptr long str ptr)
@ cdecl u_strToWCS(wstr long ptr ptr long ptr)
@ cdecl u_strcasecmp(ptr ptr long)
@ cdecl u_strcat(ptr ptr)
@ cdecl u_strchr(ptr long)
@ cdecl u_strchr32(ptr long)
@ cdecl u_strcmp(ptr ptr)
@ cdecl u_strcmpCodePointOrder(ptr ptr)
@ cdecl u_strcpy(ptr ptr)
@ cdecl u_strcspn(ptr ptr)
@ cdecl u_stringHasBinaryProperty(ptr long long)
@ cdecl u_strlen(ptr)
@ cdecl u_strncasecmp(ptr ptr long long)
@ cdecl u_strncat(ptr ptr long)
@ cdecl u_strncmp(ptr ptr long)
@ cdecl u_strncmpCodePointOrder(ptr ptr long)
@ cdecl u_strncpy(ptr ptr long)
@ cdecl u_strpbrk(ptr ptr)
@ cdecl u_strrchr(ptr long)
@ cdecl u_strrchr32(ptr long)
@ cdecl u_strrstr(ptr ptr)
@ cdecl u_strspn(ptr ptr)
@ cdecl u_strstr(ptr ptr)
@ cdecl u_strtok_r(ptr ptr ptr)
@ cdecl u_tolower(long)
@ cdecl u_totitle(long)
@ cdecl u_toupper(long)
@ cdecl u_uastrcpy(ptr str)
@ cdecl u_uastrncpy(ptr str long)
@ cdecl u_unescape(str ptr long)
@ cdecl u_unescapeAt(long ptr long ptr)
@ cdecl u_versionFromString(long str)
@ cdecl u_versionFromUString(long ptr)
@ cdecl u_versionToString(long str)
@ cdecl u_vformatMessage(str ptr long ptr long long ptr)
@ cdecl u_vformatMessageWithError(str ptr long ptr long ptr long ptr)
@ cdecl u_vparseMessage(str ptr long ptr long long ptr)
@ cdecl u_vparseMessageWithError(str ptr long ptr long long ptr ptr)
@ cdecl ubidi_close(ptr)
@ cdecl ubidi_countParagraphs(ptr)
@ cdecl ubidi_countRuns(ptr ptr)
@ cdecl ubidi_getBaseDirection(ptr long)
@ cdecl ubidi_getClassCallback(ptr ptr ptr)
@ cdecl ubidi_getCustomizedClass(ptr long)
@ cdecl ubidi_getDirection(ptr)
@ cdecl ubidi_getLength(ptr)
@ cdecl ubidi_getLevelAt(ptr long)
@ cdecl ubidi_getLevels(ptr ptr)
@ cdecl ubidi_getLogicalIndex(ptr long ptr)
@ cdecl ubidi_getLogicalMap(ptr ptr ptr)
@ cdecl ubidi_getLogicalRun(ptr long ptr ptr)
@ cdecl ubidi_getParaLevel(ptr)
@ cdecl ubidi_getParagraph(ptr long ptr ptr ptr ptr)
@ cdecl ubidi_getParagraphByIndex(ptr long ptr ptr ptr ptr)
@ cdecl ubidi_getProcessedLength(ptr)
@ cdecl ubidi_getReorderingMode(ptr)
@ cdecl ubidi_getReorderingOptions(ptr)
@ cdecl ubidi_getResultLength(ptr)
@ cdecl ubidi_getText(ptr)
@ cdecl ubidi_getVisualIndex(ptr long ptr)
@ cdecl ubidi_getVisualMap(ptr ptr ptr)
@ cdecl ubidi_getVisualRun(ptr long ptr ptr)
@ cdecl ubidi_invertMap(ptr ptr long)
@ cdecl ubidi_isInverse(ptr)
@ cdecl ubidi_isOrderParagraphsLTR(ptr)
@ cdecl ubidi_open()
@ cdecl ubidi_openSized(long long ptr)
@ cdecl ubidi_orderParagraphsLTR(ptr long)
@ cdecl ubidi_reorderLogical(ptr long ptr)
@ cdecl ubidi_reorderVisual(ptr long ptr)
@ cdecl ubidi_setClassCallback(ptr ptr ptr ptr ptr ptr)
@ cdecl ubidi_setContext(ptr ptr long ptr long ptr)
@ cdecl ubidi_setInverse(ptr long)
@ cdecl ubidi_setLine(ptr long long ptr ptr)
@ cdecl ubidi_setPara(ptr ptr long long ptr ptr)
@ cdecl ubidi_setReorderingMode(ptr long)
@ cdecl ubidi_setReorderingOptions(ptr long)
@ cdecl ubidi_writeReordered(ptr ptr long long ptr)
@ cdecl ubidi_writeReverse(ptr long ptr long long ptr)
@ cdecl ubiditransform_close(ptr)
@ cdecl ubiditransform_open(ptr)
@ cdecl ubiditransform_transform(ptr ptr long ptr long long long long long long long ptr)
@ cdecl ublock_getCode(long)
@ cdecl ubrk_clone(ptr ptr)
@ cdecl ubrk_close(ptr)
@ cdecl ubrk_countAvailable()
@ cdecl ubrk_current(ptr)
@ cdecl ubrk_first(ptr)
@ cdecl ubrk_following(ptr long)
@ cdecl ubrk_getAvailable(long)
@ cdecl ubrk_getBinaryRules(ptr ptr long ptr)
@ cdecl ubrk_getLocaleByType(ptr long ptr)
@ cdecl ubrk_getRuleStatus(ptr)
@ cdecl ubrk_getRuleStatusVec(ptr ptr long ptr)
@ cdecl ubrk_isBoundary(ptr long)
@ cdecl ubrk_last(ptr)
@ cdecl ubrk_next(ptr)
@ cdecl ubrk_open(long str ptr long ptr)
@ cdecl ubrk_openBinaryRules(ptr long ptr long ptr)
@ cdecl ubrk_openRules(ptr long ptr long ptr ptr)
@ cdecl ubrk_preceding(ptr long)
@ cdecl ubrk_previous(ptr)
@ cdecl ubrk_refreshUText(ptr ptr ptr)
@ cdecl ubrk_safeClone(ptr ptr ptr ptr)
@ cdecl ubrk_setText(ptr ptr long ptr)
@ cdecl ubrk_setUText(ptr ptr ptr)
@ cdecl ucal_add(ptr long long ptr)
@ cdecl ucal_clear(ptr)
@ cdecl ucal_clearField(ptr long)
@ cdecl ucal_clone(ptr ptr)
@ cdecl ucal_close(ptr)
@ cdecl ucal_countAvailable()
@ cdecl ucal_equivalentTo(ptr ptr)
@ cdecl ucal_get(ptr long ptr)
@ cdecl ucal_getAttribute(ptr long)
@ cdecl ucal_getAvailable(long)
@ cdecl ucal_getCanonicalTimeZoneID(ptr long ptr long ptr ptr)
@ cdecl ucal_getDSTSavings(ptr ptr)
@ cdecl ucal_getDayOfWeekType(ptr long ptr)
@ cdecl ucal_getDefaultTimeZone(ptr long ptr)
@ cdecl ucal_getFieldDifference(ptr long long ptr)
@ cdecl ucal_getGregorianChange(ptr ptr)
@ cdecl ucal_getHostTimeZone(ptr long ptr)
@ cdecl ucal_getKeywordValuesForLocale(str str long ptr)
@ cdecl ucal_getLimit(ptr long long ptr)
@ cdecl ucal_getLocaleByType(ptr long ptr)
@ cdecl ucal_getMillis(ptr ptr)
@ cdecl ucal_getNow()
@ cdecl ucal_getTZDataVersion(ptr)
@ cdecl ucal_getTimeZoneDisplayName(ptr long str ptr long ptr)
@ cdecl ucal_getTimeZoneID(ptr ptr long ptr)
@ cdecl ucal_getTimeZoneIDForWindowsID(ptr long str ptr long ptr)
@ cdecl ucal_getTimeZoneOffsetFromLocal(ptr long long ptr ptr ptr)
@ cdecl ucal_getTimeZoneTransitionDate(ptr long ptr ptr)
@ cdecl ucal_getType(ptr ptr)
@ cdecl ucal_getWeekendTransition(ptr long ptr)
@ cdecl ucal_getWindowsTimeZoneID(ptr long ptr long ptr)
@ cdecl ucal_inDaylightTime(ptr ptr)
@ cdecl ucal_isSet(ptr long)
@ cdecl ucal_isWeekend(ptr long ptr)
@ cdecl ucal_open(ptr long str long ptr)
@ cdecl ucal_openCountryTimeZones(str ptr)
@ cdecl ucal_openTimeZoneIDEnumeration(long str ptr ptr)
@ cdecl ucal_openTimeZones(ptr)
@ cdecl ucal_roll(ptr long long ptr)
@ cdecl ucal_set(ptr long long)
@ cdecl ucal_setAttribute(ptr long long)
@ cdecl ucal_setDate(ptr long long long ptr)
@ cdecl ucal_setDateTime(ptr long long long long long long ptr)
@ cdecl ucal_setDefaultTimeZone(ptr ptr)
@ cdecl ucal_setGregorianChange(ptr long ptr)
@ cdecl ucal_setMillis(ptr long ptr)
@ cdecl ucal_setTimeZone(ptr ptr long ptr)
@ cdecl ucasemap_close(ptr)
@ cdecl ucasemap_getBreakIterator(ptr)
@ cdecl ucasemap_getLocale(ptr)
@ cdecl ucasemap_getOptions(ptr)
@ cdecl ucasemap_open(str long ptr)
@ cdecl ucasemap_setBreakIterator(ptr ptr ptr)
@ cdecl ucasemap_setLocale(ptr str ptr)
@ cdecl ucasemap_setOptions(ptr long ptr)
@ cdecl ucasemap_toTitle(ptr ptr long ptr long ptr)
@ cdecl ucasemap_utf8FoldCase(ptr str long str long ptr)
@ cdecl ucasemap_utf8ToLower(ptr str long str long ptr)
@ cdecl ucasemap_utf8ToTitle(ptr str long str long ptr)
@ cdecl ucasemap_utf8ToUpper(ptr str long str long ptr)
@ cdecl ucfpos_close(ptr)
@ cdecl ucfpos_constrainCategory(ptr long ptr)
@ cdecl ucfpos_constrainField(ptr long long ptr)
@ cdecl ucfpos_getCategory(ptr ptr)
@ cdecl ucfpos_getField(ptr ptr)
@ cdecl ucfpos_getIndexes(ptr ptr ptr ptr)
@ cdecl ucfpos_getInt64IterationContext(ptr ptr)
@ cdecl ucfpos_matchesField(ptr long long ptr)
@ cdecl ucfpos_open(ptr)
@ cdecl ucfpos_reset(ptr ptr)
@ cdecl ucfpos_setInt64IterationContext(ptr int64 ptr)
@ cdecl ucfpos_setState(ptr long long long long ptr)
@ cdecl ucnv_cbFromUWriteBytes(ptr str long long ptr)
@ cdecl ucnv_cbFromUWriteSub(ptr long ptr)
@ cdecl ucnv_cbFromUWriteUChars(ptr ptr ptr long ptr)
@ cdecl ucnv_cbToUWriteSub(ptr long ptr)
@ cdecl ucnv_cbToUWriteUChars(ptr ptr long long ptr)
@ cdecl ucnv_clone(ptr ptr)
@ cdecl ucnv_close(ptr)
@ cdecl ucnv_compareNames(str str)
@ cdecl ucnv_convert(str str str long str long ptr)
@ cdecl ucnv_convertEx(ptr ptr ptr str ptr str ptr ptr ptr ptr long long ptr)
@ cdecl ucnv_countAliases(str ptr)
@ cdecl ucnv_countAvailable()
@ cdecl ucnv_countStandards()
@ cdecl ucnv_detectUnicodeSignature(str long ptr ptr)
@ cdecl ucnv_fixFileSeparator(ptr ptr long)
@ cdecl ucnv_flushCache()
@ cdecl ucnv_fromAlgorithmic(ptr long str long str long ptr)
@ cdecl ucnv_fromUChars(ptr str long ptr long ptr)
@ cdecl ucnv_fromUCountPending(ptr ptr)
@ cdecl ucnv_fromUnicode(ptr ptr str ptr ptr ptr long ptr)
@ cdecl ucnv_getAlias(str long ptr)
@ cdecl ucnv_getAliases(str ptr ptr)
@ cdecl ucnv_getAvailableName(long)
@ cdecl ucnv_getCCSID(ptr ptr)
@ cdecl ucnv_getCanonicalName(str str ptr)
@ cdecl ucnv_getDefaultName()
@ cdecl ucnv_getDisplayName(ptr str ptr long ptr)
@ cdecl ucnv_getFromUCallBack(ptr ptr ptr)
@ cdecl ucnv_getInvalidChars(ptr str ptr ptr)
@ cdecl ucnv_getInvalidUChars(ptr ptr ptr ptr)
@ cdecl ucnv_getMaxCharSize(ptr)
@ cdecl ucnv_getMinCharSize(ptr)
@ cdecl ucnv_getName(ptr ptr)
@ cdecl ucnv_getNextUChar(ptr ptr str ptr)
@ cdecl ucnv_getPlatform(ptr ptr)
@ cdecl ucnv_getStandard(long ptr)
@ cdecl ucnv_getStandardName(str str ptr)
@ cdecl ucnv_getStarters(ptr long ptr)
@ cdecl ucnv_getSubstChars(ptr str ptr ptr)
@ cdecl ucnv_getToUCallBack(ptr ptr ptr)
@ cdecl ucnv_getType(ptr)
@ cdecl ucnv_getUnicodeSet(ptr ptr long ptr)
@ cdecl ucnv_isAmbiguous(ptr)
@ cdecl ucnv_isFixedWidth(ptr ptr)
@ cdecl ucnv_open(str ptr)
@ cdecl ucnv_openAllNames(ptr)
@ cdecl ucnv_openCCSID(long long ptr)
@ cdecl ucnv_openPackage(str str ptr)
@ cdecl ucnv_openStandardNames(str str ptr)
@ cdecl ucnv_openU(ptr ptr)
@ cdecl ucnv_reset(ptr)
@ cdecl ucnv_resetFromUnicode(ptr)
@ cdecl ucnv_resetToUnicode(ptr)
@ cdecl ucnv_safeClone(ptr ptr ptr ptr)
@ cdecl ucnv_setDefaultName(str)
@ cdecl ucnv_setFallback(ptr long)
@ cdecl ucnv_setFromUCallBack(ptr long ptr ptr ptr ptr)
@ cdecl ucnv_setSubstChars(ptr str long ptr)
@ cdecl ucnv_setSubstString(ptr ptr long ptr)
@ cdecl ucnv_setToUCallBack(ptr long ptr ptr ptr ptr)
@ cdecl ucnv_toAlgorithmic(long ptr str long str long ptr)
@ cdecl ucnv_toUChars(ptr ptr long str long ptr)
@ cdecl ucnv_toUCountPending(ptr ptr)
@ cdecl ucnv_toUnicode(ptr ptr ptr ptr str ptr long ptr)
@ cdecl ucnv_usesFallback(ptr)
@ cdecl ucnvsel_close(ptr)
@ cdecl ucnvsel_open(str long ptr long ptr)
@ cdecl ucnvsel_openFromSerialized(ptr long ptr)
@ cdecl ucnvsel_selectForString(ptr ptr long ptr)
@ cdecl ucnvsel_selectForUTF8(ptr str long ptr)
@ cdecl ucnvsel_serialize(ptr ptr long ptr)
@ cdecl ucol_clone(ptr ptr)
@ cdecl ucol_cloneBinary(ptr ptr long ptr)
@ cdecl ucol_close(ptr)
@ cdecl ucol_closeElements(ptr)
@ cdecl ucol_countAvailable()
@ cdecl ucol_equal(ptr ptr long ptr long)
@ cdecl ucol_getAttribute(ptr long ptr)
@ cdecl ucol_getAvailable(long)
@ cdecl ucol_getBound(ptr long long long ptr long ptr)
@ cdecl ucol_getContractionsAndExpansions(ptr ptr ptr long ptr)
@ cdecl ucol_getDisplayName(str str ptr long ptr)
@ cdecl ucol_getEquivalentReorderCodes(long ptr long ptr)
@ cdecl ucol_getFunctionalEquivalent(str long str str ptr ptr)
@ cdecl ucol_getKeywordValues(str ptr)
@ cdecl ucol_getKeywordValuesForLocale(str str long ptr)
@ cdecl ucol_getKeywords(ptr)
@ cdecl ucol_getLocaleByType(ptr long ptr)
@ cdecl ucol_getMaxExpansion(ptr long)
@ cdecl ucol_getMaxVariable(ptr)
@ cdecl ucol_getOffset(ptr)
@ cdecl ucol_getReorderCodes(ptr ptr long ptr)
@ cdecl ucol_getRules(ptr ptr)
@ cdecl ucol_getRulesEx(ptr long ptr long)
@ cdecl ucol_getSortKey(ptr ptr long ptr long)
@ cdecl ucol_getStrength(ptr)
@ cdecl ucol_getTailoredSet(ptr ptr)
@ cdecl ucol_getUCAVersion(ptr long)
@ cdecl ucol_getVariableTop(ptr ptr)
@ cdecl ucol_getVersion(ptr long)
@ cdecl ucol_greater(ptr ptr long ptr long)
@ cdecl ucol_greaterOrEqual(ptr ptr long ptr long)
@ cdecl ucol_keyHashCode(ptr long)
@ cdecl ucol_mergeSortkeys(ptr long ptr long ptr long)
@ cdecl ucol_next(ptr ptr)
@ cdecl ucol_nextSortKeyPart(ptr ptr long ptr long ptr)
@ cdecl ucol_open(str ptr)
@ cdecl ucol_openAvailableLocales(ptr)
@ cdecl ucol_openBinary(ptr long ptr ptr)
@ cdecl ucol_openElements(ptr ptr long ptr)
@ cdecl ucol_openRules(ptr long long long ptr ptr)
@ cdecl ucol_previous(ptr ptr)
@ cdecl ucol_primaryOrder(long)
@ cdecl ucol_reset(ptr)
@ cdecl ucol_safeClone(ptr ptr ptr ptr)
@ cdecl ucol_secondaryOrder(long)
@ cdecl ucol_setAttribute(ptr long long ptr)
@ cdecl ucol_setMaxVariable(ptr long ptr)
@ cdecl ucol_setOffset(ptr long ptr)
@ cdecl ucol_setReorderCodes(ptr ptr long ptr)
@ cdecl ucol_setStrength(ptr long)
@ cdecl ucol_setText(ptr ptr long ptr)
@ cdecl ucol_strcoll(ptr ptr long ptr long)
@ cdecl ucol_strcollIter(ptr ptr ptr ptr)
@ cdecl ucol_strcollUTF8(ptr str long str long ptr)
@ cdecl ucol_tertiaryOrder(long)
@ cdecl ucpmap_get(ptr long)
@ cdecl ucpmap_getRange(ptr long long long ptr ptr ptr)
@ cdecl ucptrie_close(ptr)
@ cdecl ucptrie_get(ptr long)
@ cdecl ucptrie_getRange(ptr long long long ptr ptr ptr)
@ cdecl ucptrie_getType(ptr)
@ cdecl ucptrie_getValueWidth(ptr)
@ cdecl ucptrie_internalSmallIndex(ptr long)
@ cdecl ucptrie_internalSmallU8Index(ptr long long long)
@ cdecl ucptrie_internalU8PrevIndex(ptr long ptr ptr)
@ cdecl ucptrie_openFromBinary(long long ptr long ptr ptr)
@ cdecl ucptrie_toBinary(ptr ptr long ptr)
@ cdecl ucsdet_close(ptr)
@ cdecl ucsdet_detect(ptr ptr)
@ cdecl ucsdet_detectAll(ptr ptr ptr)
@ cdecl ucsdet_enableInputFilter(ptr long)
@ cdecl ucsdet_getAllDetectableCharsets(ptr ptr)
@ cdecl ucsdet_getConfidence(ptr ptr)
@ cdecl ucsdet_getLanguage(ptr ptr)
@ cdecl ucsdet_getName(ptr ptr)
@ cdecl ucsdet_getUChars(ptr ptr long ptr)
@ cdecl ucsdet_isInputFilterEnabled(ptr)
@ cdecl ucsdet_open(ptr)
@ cdecl ucsdet_setDeclaredEncoding(ptr str long ptr)
@ cdecl ucsdet_setText(ptr str long ptr)
@ cdecl ucurr_countCurrencies(str long ptr)
@ cdecl ucurr_forLocale(str ptr long ptr)
@ cdecl ucurr_forLocaleAndDate(str long long ptr long ptr)
@ cdecl ucurr_getDefaultFractionDigits(ptr ptr)
@ cdecl ucurr_getDefaultFractionDigitsForUsage(ptr long ptr)
@ cdecl ucurr_getKeywordValuesForLocale(str str long ptr)
@ cdecl ucurr_getName(ptr str long ptr ptr ptr)
@ cdecl ucurr_getNumericCode(ptr)
@ cdecl ucurr_getPluralName(ptr str ptr str ptr ptr)
@ cdecl ucurr_getRoundingIncrement(ptr ptr)
@ cdecl ucurr_getRoundingIncrementForUsage(ptr long ptr)
@ cdecl ucurr_isAvailable(ptr long long ptr)
@ cdecl ucurr_openISOCurrencies(long ptr)
@ cdecl ucurr_register(ptr str ptr)
@ cdecl ucurr_unregister(long ptr)
@ cdecl udat_adoptNumberFormat(ptr ptr)
@ cdecl udat_adoptNumberFormatForFields(ptr ptr ptr ptr)
@ cdecl udat_applyPattern(ptr long ptr long)
@ cdecl udat_clone(ptr ptr)
@ cdecl udat_close(ptr)
@ cdecl udat_countAvailable()
@ cdecl udat_countSymbols(ptr long)
@ cdecl udat_format(ptr long ptr long ptr ptr)
@ cdecl udat_formatCalendar(ptr ptr ptr long ptr ptr)
@ cdecl udat_formatCalendarForFields(ptr ptr ptr long ptr ptr)
@ cdecl udat_formatForFields(ptr long ptr long ptr ptr)
@ cdecl udat_get2DigitYearStart(ptr ptr)
@ cdecl udat_getAvailable(long)
@ cdecl udat_getBooleanAttribute(ptr long ptr)
@ cdecl udat_getCalendar(ptr)
@ cdecl udat_getContext(ptr long ptr)
@ cdecl udat_getLocaleByType(ptr long ptr)
@ cdecl udat_getNumberFormat(ptr)
@ cdecl udat_getNumberFormatForField(ptr long)
@ cdecl udat_getSymbols(ptr long long ptr long ptr)
@ cdecl udat_isLenient(ptr)
@ cdecl udat_open(long long str ptr long ptr long ptr)
@ cdecl udat_parse(ptr ptr long ptr ptr)
@ cdecl udat_parseCalendar(ptr ptr ptr long ptr ptr)
@ cdecl udat_set2DigitYearStart(ptr long ptr)
@ cdecl udat_setBooleanAttribute(ptr long long ptr)
@ cdecl udat_setCalendar(ptr ptr)
@ cdecl udat_setContext(ptr long ptr)
@ cdecl udat_setLenient(ptr long)
@ cdecl udat_setNumberFormat(ptr ptr)
@ cdecl udat_setSymbols(ptr long long ptr long ptr)
@ cdecl udat_toCalendarDateField(long)
@ cdecl udat_toPattern(ptr long ptr long ptr)
@ cdecl udatpg_addPattern(ptr ptr long long ptr long ptr ptr)
@ cdecl udatpg_clone(ptr ptr)
@ cdecl udatpg_close(ptr)
@ cdecl udatpg_getAppendItemFormat(ptr long ptr)
@ cdecl udatpg_getAppendItemName(ptr long ptr)
@ cdecl udatpg_getBaseSkeleton(ptr ptr long ptr long ptr)
@ cdecl udatpg_getBestPattern(ptr ptr long ptr long ptr)
@ cdecl udatpg_getBestPatternWithOptions(ptr ptr long long ptr long ptr)
@ cdecl udatpg_getDateTimeFormat(ptr ptr)
@ cdecl udatpg_getDecimal(ptr ptr)
@ cdecl udatpg_getDefaultHourCycle(ptr ptr)
@ cdecl udatpg_getFieldDisplayName(ptr long long ptr long ptr)
@ cdecl udatpg_getPatternForSkeleton(ptr ptr long ptr)
@ cdecl udatpg_getSkeleton(ptr ptr long ptr long ptr)
@ cdecl udatpg_open(str ptr)
@ cdecl udatpg_openBaseSkeletons(ptr ptr)
@ cdecl udatpg_openEmpty(ptr)
@ cdecl udatpg_openSkeletons(ptr ptr)
@ cdecl udatpg_replaceFieldTypes(ptr ptr long ptr long ptr long ptr)
@ cdecl udatpg_replaceFieldTypesWithOptions(ptr ptr long ptr long long ptr long ptr)
@ cdecl udatpg_setAppendItemFormat(ptr long ptr long)
@ cdecl udatpg_setAppendItemName(ptr long ptr long)
@ cdecl udatpg_setDateTimeFormat(ptr ptr long)
@ cdecl udatpg_setDecimal(ptr ptr long)
@ cdecl udtitvfmt_close(ptr)
@ cdecl udtitvfmt_closeResult(ptr)
@ cdecl udtitvfmt_format(ptr long long ptr long ptr ptr)
@ cdecl udtitvfmt_formatToResult(ptr long long ptr ptr)
@ cdecl udtitvfmt_getContext(ptr long ptr)
@ cdecl udtitvfmt_open(str ptr long ptr long ptr)
@ cdecl udtitvfmt_openResult(ptr)
@ cdecl udtitvfmt_resultAsValue(ptr ptr)
@ cdecl udtitvfmt_setContext(ptr long ptr)
@ cdecl uenum_close(ptr)
@ cdecl uenum_count(ptr ptr)
@ cdecl uenum_next(ptr ptr ptr)
@ cdecl uenum_openCharStringsEnumeration(str long ptr)
@ cdecl uenum_openUCharStringsEnumeration(ptr long ptr)
@ cdecl uenum_reset(ptr ptr)
@ cdecl uenum_unext(ptr ptr ptr)
@ cdecl ufieldpositer_close(ptr)
@ cdecl ufieldpositer_next(ptr ptr ptr)
@ cdecl ufieldpositer_open(ptr)
@ cdecl ufmt_close(ptr)
@ cdecl ufmt_getArrayItemByIndex(ptr long ptr)
@ cdecl ufmt_getArrayLength(ptr ptr)
@ cdecl ufmt_getDate(ptr ptr)
@ cdecl ufmt_getDecNumChars(ptr ptr ptr)
@ cdecl ufmt_getDouble(ptr ptr)
@ cdecl ufmt_getInt64(ptr ptr)
@ cdecl ufmt_getLong(ptr ptr)
@ cdecl ufmt_getObject(ptr ptr)
@ cdecl ufmt_getType(ptr ptr)
@ cdecl ufmt_getUChars(ptr ptr ptr)
@ cdecl ufmt_isNumeric(ptr)
@ cdecl ufmt_open(ptr)
@ cdecl ufmtval_getString(ptr ptr ptr)
@ cdecl ufmtval_nextPosition(ptr ptr ptr)
@ cdecl ugender_getInstance(str ptr)
@ cdecl ugender_getListGender(ptr ptr long ptr)
@ cdecl uidna_close(ptr)
@ cdecl uidna_labelToASCII(ptr ptr long ptr long ptr ptr)
@ cdecl uidna_labelToASCII_UTF8(ptr str long str long ptr ptr)
@ cdecl uidna_labelToUnicode(ptr ptr long ptr long ptr ptr)
@ cdecl uidna_labelToUnicodeUTF8(ptr str long str long ptr ptr)
@ cdecl uidna_nameToASCII(ptr ptr long ptr long ptr ptr)
@ cdecl uidna_nameToASCII_UTF8(ptr str long str long ptr ptr)
@ cdecl uidna_nameToUnicode(ptr ptr long ptr long ptr ptr)
@ cdecl uidna_nameToUnicodeUTF8(ptr str long str long ptr ptr)
@ cdecl uidna_openUTS46(long ptr)
@ cdecl uiter_current32(ptr)
@ cdecl uiter_getState(ptr)
@ cdecl uiter_next32(ptr)
@ cdecl uiter_previous32(ptr)
@ cdecl uiter_setState(ptr long ptr)
@ cdecl uiter_setString(ptr ptr long)
@ cdecl uiter_setUTF16BE(ptr str long)
@ cdecl uiter_setUTF8(ptr str long)
@ cdecl uldn_close(ptr)
@ cdecl uldn_getContext(ptr long ptr)
@ cdecl uldn_getDialectHandling(ptr)
@ cdecl uldn_getLocale(ptr)
@ cdecl uldn_keyDisplayName(ptr str ptr long ptr)
@ cdecl uldn_keyValueDisplayName(ptr str str ptr long ptr)
@ cdecl uldn_languageDisplayName(ptr str ptr long ptr)
@ cdecl uldn_localeDisplayName(ptr str ptr long ptr)
@ cdecl uldn_open(str long ptr)
@ cdecl uldn_openForContext(str ptr long ptr)
@ cdecl uldn_regionDisplayName(ptr str ptr long ptr)
@ cdecl uldn_scriptCodeDisplayName(ptr long ptr long ptr)
@ cdecl uldn_scriptDisplayName(ptr str ptr long ptr)
@ cdecl uldn_variantDisplayName(ptr str ptr long ptr)
@ cdecl ulistfmt_close(ptr)
@ cdecl ulistfmt_closeResult(ptr)
@ cdecl ulistfmt_format(ptr ptr ptr long ptr long ptr)
@ cdecl ulistfmt_formatStringsToResult(ptr ptr ptr long ptr ptr)
@ cdecl ulistfmt_open(str ptr)
@ cdecl ulistfmt_openForType(ptr long long ptr)
@ cdecl ulistfmt_openResult(ptr)
@ cdecl ulistfmt_resultAsValue(ptr ptr)
@ cdecl uloc_acceptLanguage(str long ptr ptr long ptr ptr)
@ cdecl uloc_acceptLanguageFromHTTP(str long ptr str ptr ptr)
@ cdecl uloc_addLikelySubtags(str str long ptr)
@ cdecl uloc_canonicalize(str str long ptr)
@ cdecl uloc_countAvailable()
@ cdecl uloc_forLanguageTag(str str long ptr ptr)
@ cdecl uloc_getAvailable(long)
@ cdecl uloc_getBaseName(str str long ptr)
@ cdecl uloc_getCharacterOrientation(str ptr)
@ cdecl uloc_getCountry(str str long ptr)
@ cdecl uloc_getDefault()
@ cdecl uloc_getDisplayCountry(str str ptr long ptr)
@ cdecl uloc_getDisplayKeyword(str str ptr long ptr)
@ cdecl uloc_getDisplayKeywordValue(str str str ptr long ptr)
@ cdecl uloc_getDisplayLanguage(str str ptr long ptr)
@ cdecl uloc_getDisplayName(str str ptr long ptr)
@ cdecl uloc_getDisplayScript(str str ptr long ptr)
@ cdecl uloc_getDisplayVariant(str str ptr long ptr)
@ cdecl uloc_getISO3Country(str)
@ cdecl uloc_getISO3Language(str)
@ cdecl uloc_getISOCountries()
@ cdecl uloc_getISOLanguages()
@ cdecl uloc_getKeywordValue(str str str long ptr)
@ cdecl uloc_getLCID(str)
@ cdecl uloc_getLanguage(str str long ptr)
@ cdecl uloc_getLineOrientation(str ptr)
@ cdecl uloc_getLocaleForLCID(long str long ptr)
@ cdecl uloc_getName(str str long ptr)
@ cdecl uloc_getParent(str str long ptr)
@ cdecl uloc_getScript(str str long ptr)
@ cdecl uloc_getVariant(str str long ptr)
@ cdecl uloc_isRightToLeft(str)
@ cdecl uloc_minimizeSubtags(str str long ptr)
@ cdecl uloc_openAvailableByType(long ptr)
@ cdecl uloc_openKeywords(str ptr)
@ cdecl uloc_setDefault(str ptr)
@ cdecl uloc_setKeywordValue(str str str long ptr)
@ cdecl uloc_toLanguageTag(str str long long ptr)
@ cdecl uloc_toLegacyKey(str)
@ cdecl uloc_toLegacyType(str str)
@ cdecl uloc_toUnicodeLocaleKey(str)
@ cdecl uloc_toUnicodeLocaleType(str str)
@ cdecl ulocdata_close(ptr)
@ cdecl ulocdata_getCLDRVersion(long ptr)
@ cdecl ulocdata_getDelimiter(ptr long ptr long ptr)
@ cdecl ulocdata_getExemplarSet(ptr ptr long long ptr)
@ cdecl ulocdata_getLocaleDisplayPattern(ptr ptr long ptr)
@ cdecl ulocdata_getLocaleSeparator(ptr ptr long ptr)
@ cdecl ulocdata_getMeasurementSystem(str ptr)
@ cdecl ulocdata_getNoSubstitute(ptr)
@ cdecl ulocdata_getPaperSize(str ptr ptr ptr)
@ cdecl ulocdata_open(str ptr)
@ cdecl ulocdata_setNoSubstitute(ptr long)
@ cdecl umsg_applyPattern(ptr ptr long ptr ptr)
@ cdecl umsg_autoQuoteApostrophe(ptr long ptr long ptr)
@ cdecl umsg_clone(ptr ptr)
@ cdecl umsg_close(ptr)
@ varargs umsg_format(ptr ptr long ptr)
@ cdecl umsg_getLocale(ptr)
@ cdecl umsg_open(ptr long str ptr ptr)
@ varargs umsg_parse(ptr ptr long ptr ptr)
@ cdecl umsg_setLocale(ptr str)
@ cdecl umsg_toPattern(ptr ptr long ptr)
@ cdecl umsg_vformat(ptr ptr long long ptr)
@ cdecl umsg_vparse(ptr ptr long ptr long ptr)
@ cdecl umutablecptrie_buildImmutable(ptr long long ptr)
@ cdecl umutablecptrie_clone(ptr ptr)
@ cdecl umutablecptrie_close(ptr)
@ cdecl umutablecptrie_fromUCPMap(ptr ptr)
@ cdecl umutablecptrie_fromUCPTrie(ptr ptr)
@ cdecl umutablecptrie_get(ptr long)
@ cdecl umutablecptrie_getRange(ptr long long long ptr ptr ptr)
@ cdecl umutablecptrie_open(long long ptr)
@ cdecl umutablecptrie_set(ptr long long ptr)
@ cdecl umutablecptrie_setRange(ptr long long long ptr)
@ cdecl unorm2_append(ptr ptr long long ptr long ptr)
@ cdecl unorm2_close(ptr)
@ cdecl unorm2_composePair(ptr long long)
@ cdecl unorm2_getCombiningClass(ptr long)
@ cdecl unorm2_getDecomposition(ptr long ptr long ptr)
@ cdecl unorm2_getInstance(str str long ptr)
@ cdecl unorm2_getNFCInstance(ptr)
@ cdecl unorm2_getNFDInstance(ptr)
@ cdecl unorm2_getNFKCCasefoldInstance(ptr)
@ cdecl unorm2_getNFKCInstance(ptr)
@ cdecl unorm2_getNFKDInstance(ptr)
@ cdecl unorm2_getRawDecomposition(ptr long ptr long ptr)
@ cdecl unorm2_hasBoundaryAfter(ptr long)
@ cdecl unorm2_hasBoundaryBefore(ptr long)
@ cdecl unorm2_isInert(ptr long)
@ cdecl unorm2_isNormalized(ptr ptr long ptr)
@ cdecl unorm2_normalize(ptr ptr long ptr long ptr)
@ cdecl unorm2_normalizeSecondAndAppend(ptr ptr long long ptr long ptr)
@ cdecl unorm2_openFiltered(ptr ptr ptr)
@ cdecl unorm2_quickCheck(ptr ptr long ptr)
@ cdecl unorm2_spanQuickCheckYes(ptr ptr long ptr)
@ cdecl unorm_compare(ptr long ptr long long ptr)
@ cdecl unum_applyPattern(ptr long ptr long ptr ptr)
@ cdecl unum_clone(ptr ptr)
@ cdecl unum_close(ptr)
@ cdecl unum_countAvailable()
@ cdecl unum_format(ptr long ptr long ptr ptr)
@ cdecl unum_formatDecimal(ptr str long ptr long ptr ptr)
@ cdecl unum_formatDouble(ptr double ptr long ptr ptr)
@ cdecl unum_formatDoubleCurrency(ptr double ptr ptr long ptr ptr)
@ cdecl unum_formatDoubleForFields(ptr double ptr long ptr ptr)
@ cdecl unum_formatInt64(ptr long ptr long ptr ptr)
@ cdecl unum_formatUFormattable(ptr ptr ptr long ptr ptr)
@ cdecl unum_getAttribute(ptr long)
@ cdecl unum_getAvailable(long)
@ cdecl unum_getContext(ptr long ptr)
@ cdecl unum_getDoubleAttribute(ptr long)
@ cdecl unum_getLocaleByType(ptr long ptr)
@ cdecl unum_getSymbol(ptr long ptr long ptr)
@ cdecl unum_getTextAttribute(ptr long ptr long ptr)
@ cdecl unum_open(long ptr long str ptr ptr)
@ cdecl unum_parse(ptr ptr long ptr ptr)
@ cdecl unum_parseDecimal(ptr ptr long ptr str long ptr)
@ cdecl unum_parseDouble(ptr ptr long ptr ptr)
@ cdecl unum_parseDoubleCurrency(ptr ptr long ptr ptr ptr)
@ cdecl unum_parseInt64(ptr ptr long ptr ptr)
@ cdecl unum_parseToUFormattable(ptr ptr ptr long ptr ptr)
@ cdecl unum_setAttribute(ptr long long)
@ cdecl unum_setContext(ptr long ptr)
@ cdecl unum_setDoubleAttribute(ptr long double)
@ cdecl unum_setSymbol(ptr long ptr long ptr)
@ cdecl unum_setTextAttribute(ptr long ptr long ptr)
@ cdecl unum_toPattern(ptr long ptr long ptr)
@ cdecl unumf_close(ptr)
@ cdecl unumf_closeResult(ptr)
@ cdecl unumf_formatDecimal(ptr ptr long ptr ptr)
@ cdecl unumf_formatDouble(ptr double ptr ptr)
@ cdecl unumf_formatInt(ptr int64 ptr ptr)
@ cdecl unumf_openForSkeletonAndLocale(ptr long str ptr)
@ cdecl unumf_openForSkeletonAndLocaleWithError(ptr long str ptr ptr)
@ cdecl unumf_openResult(ptr)
@ cdecl unumf_resultAsValue(ptr ptr)
@ cdecl unumf_resultGetAllFieldPositions(ptr ptr ptr)
@ cdecl unumf_resultNextFieldPosition(ptr ptr ptr)
@ cdecl unumf_resultToDecimalNumber(ptr ptr long ptr)
@ cdecl unumf_resultToString(ptr ptr long ptr)
@ cdecl unumrf_close(ptr)
@ cdecl unumrf_closeResult(ptr)
@ cdecl unumrf_formatDecimalRange(ptr ptr long ptr long ptr ptr)
@ cdecl unumrf_formatDoubleRange(ptr double double ptr ptr)
@ cdecl unumrf_openForSkeletonWithCollapseAndIdentityFallback(ptr long long long str ptr ptr)
@ cdecl unumrf_openResult(ptr)
@ cdecl unumrf_resultAsValue(ptr ptr)
@ cdecl unumrf_resultGetFirstDecimalNumber(ptr ptr long ptr)
@ cdecl unumrf_resultGetIdentityResult(ptr ptr)
@ cdecl unumrf_resultGetSecondDecimalNumber(ptr ptr long ptr)
@ cdecl unumsys_close(ptr)
@ cdecl unumsys_getDescription(ptr ptr long ptr)
@ cdecl unumsys_getName(ptr)
@ cdecl unumsys_getRadix(ptr)
@ cdecl unumsys_isAlgorithmic(ptr)
@ cdecl unumsys_open(str ptr)
@ cdecl unumsys_openAvailableNames(ptr)
@ cdecl unumsys_openByName(str ptr)
@ cdecl uplrules_close(ptr)
@ cdecl uplrules_getKeywords(ptr ptr)
@ cdecl uplrules_open(str ptr)
@ cdecl uplrules_openForType(str long ptr)
@ cdecl uplrules_select(ptr double ptr long ptr)
@ cdecl uplrules_selectFormatted(ptr ptr ptr long ptr)
@ cdecl uregex_appendReplacement(ptr ptr long ptr ptr ptr)
@ cdecl uregex_appendReplacementUText(ptr ptr ptr ptr)
@ cdecl uregex_appendTail(ptr ptr ptr ptr)
@ cdecl uregex_appendTailUText(ptr ptr ptr)
@ cdecl uregex_clone(ptr ptr)
@ cdecl uregex_close(ptr)
@ cdecl uregex_end(ptr long ptr)
@ cdecl uregex_end64(ptr long ptr)
@ cdecl uregex_find(ptr long ptr)
@ cdecl uregex_find64(ptr long ptr)
@ cdecl uregex_findNext(ptr ptr)
@ cdecl uregex_flags(ptr ptr)
@ cdecl uregex_getFindProgressCallback(ptr ptr ptr ptr)
@ cdecl uregex_getMatchCallback(ptr ptr ptr ptr)
@ cdecl uregex_getStackLimit(ptr ptr)
@ cdecl uregex_getText(ptr ptr ptr)
@ cdecl uregex_getTimeLimit(ptr ptr)
@ cdecl uregex_getUText(ptr ptr ptr)
@ cdecl uregex_group(ptr long ptr long ptr)
@ cdecl uregex_groupCount(ptr ptr)
@ cdecl uregex_groupNumberFromCName(ptr str long ptr)
@ cdecl uregex_groupNumberFromName(ptr ptr long ptr)
@ cdecl uregex_groupUText(ptr long ptr ptr ptr)
@ cdecl uregex_hasAnchoringBounds(ptr ptr)
@ cdecl uregex_hasTransparentBounds(ptr ptr)
@ cdecl uregex_hitEnd(ptr ptr)
@ cdecl uregex_lookingAt(ptr long ptr)
@ cdecl uregex_lookingAt64(ptr long ptr)
@ cdecl uregex_matches(ptr long ptr)
@ cdecl uregex_matches64(ptr long ptr)
@ cdecl uregex_open(ptr long long ptr ptr)
@ cdecl uregex_openC(str long ptr ptr)
@ cdecl uregex_openUText(ptr long ptr ptr)
@ cdecl uregex_pattern(ptr ptr ptr)
@ cdecl uregex_patternUText(ptr ptr)
@ cdecl uregex_refreshUText(ptr ptr ptr)
@ cdecl uregex_regionEnd(ptr ptr)
@ cdecl uregex_regionEnd64(ptr ptr)
@ cdecl uregex_regionStart(ptr ptr)
@ cdecl uregex_regionStart64(ptr ptr)
@ cdecl uregex_replaceAll(ptr ptr long ptr long ptr)
@ cdecl uregex_replaceAllUText(ptr ptr ptr ptr)
@ cdecl uregex_replaceFirst(ptr ptr long ptr long ptr)
@ cdecl uregex_replaceFirstUText(ptr ptr ptr ptr)
@ cdecl uregex_requireEnd(ptr ptr)
@ cdecl uregex_reset(ptr long ptr)
@ cdecl uregex_reset64(ptr long ptr)
@ cdecl uregex_setFindProgressCallback(ptr ptr ptr ptr)
@ cdecl uregex_setMatchCallback(ptr ptr ptr ptr)
@ cdecl uregex_setRegion(ptr long long ptr)
@ cdecl uregex_setRegion64(ptr long long ptr)
@ cdecl uregex_setRegionAndStart(ptr long long long ptr)
@ cdecl uregex_setStackLimit(ptr long ptr)
@ cdecl uregex_setText(ptr ptr long ptr)
@ cdecl uregex_setTimeLimit(ptr long ptr)
@ cdecl uregex_setUText(ptr ptr ptr)
@ cdecl uregex_split(ptr ptr long ptr ptr long ptr)
@ cdecl uregex_splitUText(ptr ptr long ptr)
@ cdecl uregex_start(ptr long ptr)
@ cdecl uregex_start64(ptr long ptr)
@ cdecl uregex_useAnchoringBounds(ptr long ptr)
@ cdecl uregex_useTransparentBounds(ptr long ptr)
@ cdecl uregion_areEqual(ptr ptr)
@ cdecl uregion_contains(ptr ptr)
@ cdecl uregion_getAvailable(long ptr)
@ cdecl uregion_getContainedRegions(ptr ptr)
@ cdecl uregion_getContainedRegionsOfType(ptr long ptr)
@ cdecl uregion_getContainingRegion(ptr)
@ cdecl uregion_getContainingRegionOfType(ptr long)
@ cdecl uregion_getNumericCode(ptr)
@ cdecl uregion_getPreferredValues(ptr ptr)
@ cdecl uregion_getRegionCode(ptr)
@ cdecl uregion_getRegionFromCode(str ptr)
@ cdecl uregion_getRegionFromNumericCode(long ptr)
@ cdecl uregion_getType(ptr)
@ cdecl ureldatefmt_close(ptr)
@ cdecl ureldatefmt_closeResult(ptr)
@ cdecl ureldatefmt_combineDateAndTime(ptr ptr long ptr long ptr long ptr)
@ cdecl ureldatefmt_format(ptr double long ptr long ptr)
@ cdecl ureldatefmt_formatNumeric(ptr double long ptr long ptr)
@ cdecl ureldatefmt_formatNumericToResult(ptr double long ptr ptr)
@ cdecl ureldatefmt_formatToResult(ptr double long ptr ptr)
@ cdecl ureldatefmt_open(str ptr long long ptr)
@ cdecl ureldatefmt_openResult(ptr)
@ cdecl ureldatefmt_resultAsValue(ptr ptr)
@ cdecl ures_close(ptr)
@ cdecl ures_getBinary(ptr ptr ptr)
@ cdecl ures_getByIndex(ptr long ptr ptr)
@ cdecl ures_getByKey(ptr str ptr ptr)
@ cdecl ures_getInt(ptr ptr)
@ cdecl ures_getIntVector(ptr ptr ptr)
@ cdecl ures_getKey(ptr)
@ cdecl ures_getLocaleByType(ptr long ptr)
@ cdecl ures_getNextResource(ptr ptr ptr)
@ cdecl ures_getNextString(ptr ptr ptr ptr)
@ cdecl ures_getSize(ptr)
@ cdecl ures_getString(ptr ptr ptr)
@ cdecl ures_getStringByIndex(ptr long ptr ptr)
@ cdecl ures_getStringByKey(ptr str ptr ptr)
@ cdecl ures_getType(ptr)
@ cdecl ures_getUInt(ptr ptr)
@ cdecl ures_getUTF8String(ptr str ptr long ptr)
@ cdecl ures_getUTF8StringByIndex(ptr long str ptr long ptr)
@ cdecl ures_getUTF8StringByKey(ptr str str ptr long ptr)
@ cdecl ures_getVersion(ptr long)
@ cdecl ures_hasNext(ptr)
@ cdecl ures_open(str str ptr)
@ cdecl ures_openAvailableLocales(str ptr)
@ cdecl ures_openDirect(str str ptr)
@ cdecl ures_openU(ptr str ptr)
@ cdecl ures_resetIterator(ptr)
@ cdecl uscript_breaksBetweenLetters(long)
@ cdecl uscript_getCode(str ptr long ptr)
@ cdecl uscript_getName(long)
@ cdecl uscript_getSampleString(long ptr long ptr)
@ cdecl uscript_getScript(long ptr)
@ cdecl uscript_getScriptExtensions(long ptr long ptr)
@ cdecl uscript_getShortName(long)
@ cdecl uscript_getUsage(long)
@ cdecl uscript_hasScript(long long)
@ cdecl uscript_isCased(long)
@ cdecl uscript_isRightToLeft(long)
@ cdecl usearch_close(ptr)
@ cdecl usearch_first(ptr ptr)
@ cdecl usearch_following(ptr long ptr)
@ cdecl usearch_getAttribute(ptr long)
@ cdecl usearch_getBreakIterator(ptr)
@ cdecl usearch_getCollator(ptr)
@ cdecl usearch_getMatchedLength(ptr)
@ cdecl usearch_getMatchedStart(ptr)
@ cdecl usearch_getMatchedText(ptr ptr long ptr)
@ cdecl usearch_getOffset(ptr)
@ cdecl usearch_getPattern(ptr ptr)
@ cdecl usearch_getText(ptr ptr)
@ cdecl usearch_last(ptr ptr)
@ cdecl usearch_next(ptr ptr)
@ cdecl usearch_open(ptr long ptr long str ptr ptr)
@ cdecl usearch_openFromCollator(ptr long ptr long ptr ptr ptr)
@ cdecl usearch_preceding(ptr long ptr)
@ cdecl usearch_previous(ptr ptr)
@ cdecl usearch_reset(ptr)
@ cdecl usearch_setAttribute(ptr long long ptr)
@ cdecl usearch_setBreakIterator(ptr ptr ptr)
@ cdecl usearch_setCollator(ptr ptr ptr)
@ cdecl usearch_setOffset(ptr long ptr)
@ cdecl usearch_setPattern(ptr ptr long ptr)
@ cdecl usearch_setText(ptr ptr long ptr)
@ cdecl uset_add(ptr long)
@ cdecl uset_addAll(ptr ptr)
@ cdecl uset_addAllCodePoints(ptr ptr long)
@ cdecl uset_addRange(ptr long long)
@ cdecl uset_addString(ptr ptr long)
@ cdecl uset_applyIntPropertyValue(ptr long long ptr)
@ cdecl uset_applyPattern(ptr ptr long long ptr)
@ cdecl uset_applyPropertyAlias(ptr ptr long ptr long ptr)
@ cdecl uset_charAt(ptr long)
@ cdecl uset_clear(ptr)
@ cdecl uset_clone(ptr)
@ cdecl uset_cloneAsThawed(ptr)
@ cdecl uset_close(ptr)
@ cdecl uset_closeOver(ptr long)
@ cdecl uset_compact(ptr)
@ cdecl uset_complement(ptr)
@ cdecl uset_complementAll(ptr ptr)
@ cdecl uset_complementAllCodePoints(ptr ptr long)
@ cdecl uset_complementRange(ptr long long)
@ cdecl uset_complementString(ptr ptr long)
@ cdecl uset_contains(ptr long)
@ cdecl uset_containsAll(ptr ptr)
@ cdecl uset_containsAllCodePoints(ptr ptr long)
@ cdecl uset_containsNone(ptr ptr)
@ cdecl uset_containsRange(ptr long long)
@ cdecl uset_containsSome(ptr ptr)
@ cdecl uset_containsString(ptr ptr long)
@ cdecl uset_equals(ptr ptr)
@ cdecl uset_freeze(ptr)
@ cdecl uset_getItem(ptr long ptr ptr ptr long ptr)
@ cdecl uset_getItemCount(ptr)
@ cdecl uset_getRangeCount(ptr)
@ cdecl uset_getSerializedRange(ptr long ptr ptr)
@ cdecl uset_getSerializedRangeCount(ptr)
@ cdecl uset_getSerializedSet(ptr ptr long)
@ cdecl uset_hasStrings(ptr)
@ cdecl uset_indexOf(ptr long)
@ cdecl uset_isEmpty(ptr)
@ cdecl uset_isFrozen(ptr)
@ cdecl uset_open(long long)
@ cdecl uset_openEmpty()
@ cdecl uset_openPattern(ptr long ptr)
@ cdecl uset_openPatternOptions(ptr long long ptr)
@ cdecl uset_remove(ptr long)
@ cdecl uset_removeAll(ptr ptr)
@ cdecl uset_removeAllCodePoints(ptr ptr long)
@ cdecl uset_removeAllStrings(ptr)
@ cdecl uset_removeRange(ptr long long)
@ cdecl uset_removeString(ptr ptr long)
@ cdecl uset_resemblesPattern(ptr long long)
@ cdecl uset_retain(ptr long long)
@ cdecl uset_retainAll(ptr ptr)
@ cdecl uset_retainAllCodePoints(ptr ptr long)
@ cdecl uset_retainString(ptr ptr long)
@ cdecl uset_serialize(ptr ptr long ptr)
@ cdecl uset_serializedContains(ptr long)
@ cdecl uset_set(ptr long long)
@ cdecl uset_setSerializedToOne(ptr long)
@ cdecl uset_size(ptr)
@ cdecl uset_span(ptr ptr long long)
@ cdecl uset_spanBack(ptr ptr long long)
@ cdecl uset_spanBackUTF8(ptr str long long)
@ cdecl uset_spanUTF8(ptr str long long)
@ cdecl uset_toPattern(ptr ptr long long ptr)
@ cdecl uspoof_areConfusable(ptr ptr long ptr long ptr)
@ cdecl uspoof_areConfusableUTF8(ptr str long str long ptr)
@ cdecl uspoof_check(ptr ptr long ptr ptr)
@ cdecl uspoof_check2(ptr ptr long ptr ptr)
@ cdecl uspoof_check2UTF8(ptr str long ptr ptr)
@ cdecl uspoof_checkUTF8(ptr str long ptr ptr)
@ cdecl uspoof_clone(ptr ptr)
@ cdecl uspoof_close(ptr)
@ cdecl uspoof_closeCheckResult(ptr)
@ cdecl uspoof_getAllowedChars(ptr ptr)
@ cdecl uspoof_getAllowedLocales(ptr ptr)
@ cdecl uspoof_getCheckResultChecks(ptr ptr)
@ cdecl uspoof_getCheckResultNumerics(ptr ptr)
@ cdecl uspoof_getCheckResultRestrictionLevel(ptr ptr)
@ cdecl uspoof_getChecks(ptr ptr)
@ cdecl uspoof_getInclusionSet(ptr)
@ cdecl uspoof_getRecommendedSet(ptr)
@ cdecl uspoof_getRestrictionLevel(ptr)
@ cdecl uspoof_getSkeleton(ptr long ptr long ptr long ptr)
@ cdecl uspoof_getSkeletonUTF8(ptr long str long str long ptr)
@ cdecl uspoof_open(ptr)
@ cdecl uspoof_openCheckResult(ptr)
@ cdecl uspoof_openFromSerialized(ptr long ptr ptr)
@ cdecl uspoof_openFromSource(str long str long ptr ptr ptr)
@ cdecl uspoof_serialize(ptr ptr long ptr)
@ cdecl uspoof_setAllowedChars(ptr ptr ptr)
@ cdecl uspoof_setAllowedLocales(ptr str ptr)
@ cdecl uspoof_setChecks(ptr long ptr)
@ cdecl uspoof_setRestrictionLevel(ptr long)
@ cdecl usprep_close(ptr)
@ cdecl usprep_open(str str ptr)
@ cdecl usprep_openByType(long ptr)
@ cdecl usprep_prepare(ptr ptr long ptr long long ptr ptr)
@ cdecl utext_char32At(ptr long)
@ cdecl utext_clone(ptr ptr long long ptr)
@ cdecl utext_close(ptr)
@ cdecl utext_copy(ptr long long long long ptr)
@ cdecl utext_current32(ptr)
@ cdecl utext_equals(ptr ptr)
@ cdecl utext_extract(ptr long long ptr long ptr)
@ cdecl utext_freeze(ptr)
@ cdecl utext_getNativeIndex(ptr)
@ cdecl utext_getPreviousNativeIndex(ptr)
@ cdecl utext_hasMetaData(ptr)
@ cdecl utext_isLengthExpensive(ptr)
@ cdecl utext_isWritable(ptr)
@ cdecl utext_moveIndex32(ptr long)
@ cdecl utext_nativeLength(ptr)
@ cdecl utext_next32(ptr)
@ cdecl utext_next32From(ptr long)
@ cdecl utext_openUChars(ptr ptr long ptr)
@ cdecl utext_openUTF8(ptr str long ptr)
@ cdecl utext_previous32(ptr)
@ cdecl utext_previous32From(ptr long)
@ cdecl utext_replace(ptr long long ptr long ptr)
@ cdecl utext_setNativeIndex(ptr long)
@ cdecl utext_setup(ptr long ptr)
@ cdecl utf8_appendCharSafeBody(ptr long long long ptr)
@ cdecl utf8_back1SafeBody(ptr long long)
@ cdecl utf8_nextCharSafeBody(ptr ptr long long long)
@ cdecl utf8_prevCharSafeBody(ptr long ptr long long)
@ cdecl utmscale_fromInt64(long long ptr)
@ cdecl utmscale_getTimeScaleValue(long long ptr)
@ cdecl utmscale_toInt64(long long ptr)
@ varargs utrace_format(str long long str)
@ cdecl utrace_functionName(long)
@ cdecl utrace_getFunctions(ptr ptr ptr ptr)
@ cdecl utrace_getLevel()
@ cdecl utrace_setFunctions(ptr ptr ptr ptr)
@ cdecl utrace_setLevel(long)
@ cdecl utrace_vformat(str long long str long)
@ cdecl utrans_clone(ptr ptr)
@ cdecl utrans_close(ptr)
@ cdecl utrans_countAvailableIDs()
@ cdecl utrans_getSourceSet(ptr long ptr ptr)
@ cdecl utrans_getUnicodeID(ptr ptr)
@ cdecl utrans_openIDs(ptr)
@ cdecl utrans_openInverse(ptr ptr)
@ cdecl utrans_openU(ptr long long ptr long ptr ptr)
@ cdecl utrans_register(ptr ptr)
@ cdecl utrans_setFilter(ptr ptr long ptr)
@ cdecl utrans_toRules(ptr long ptr long ptr)
@ cdecl utrans_trans(ptr ptr ptr long ptr ptr)
@ cdecl utrans_transIncremental(ptr ptr ptr ptr ptr)
@ cdecl utrans_transIncrementalUChars(ptr ptr ptr long ptr ptr)
@ cdecl utrans_transUChars(ptr ptr ptr long long ptr ptr)
@ cdecl utrans_unregisterID(ptr long)
