@ stub ArcFilterDprIndicateReceive
@ stub ArcFilterDprIndicateReceiveComplete
@ stub EthFilterDprIndicateReceive
@ stub EthFilterDprIndicateReceiveComplete
@ stub FddiFilterDprIndicateReceive
@ stub FddiFilterDprIndicateReceiveComplete
@ stub NDIS_BUFFER_TO_SPAN_PAGES
@ stub NdisAcquireReadWriteLock
@ stub NdisAcquireSpinLock
@ stub NdisAdjustBufferLength
@ stub NdisAllocateBuffer
@ stub NdisAllocateBufferPool
@ stub NdisAllocateFromBlockPool
@ stub NdisAllocateMemory
@ stdcall NdisAllocateMemoryWithTag(ptr long long)
@ stub NdisAllocatePacket
@ stub NdisAllocatePacketPool
@ stub NdisAllocatePacketPoolEx
@ stdcall NdisAllocateSpinLock(ptr)
@ stub NdisAnsiStringToUnicodeString
@ stub NdisBufferLength
@ stub NdisBufferVirtualAddress
@ stub NdisCancelSendPackets
@ stub NdisCancelTimer
@ stub NdisClAddParty
@ stub NdisClCloseAddressFamily
@ stub NdisClCloseCall
@ stub NdisClDeregisterSap
@ stub NdisClDropParty
@ stub NdisClGetProtocolVcContextFromTapiCallId
@ stub NdisClIncomingCallComplete
@ stub NdisClMakeCall
@ stub NdisClModifyCallQoS
@ stub NdisClOpenAddressFamily
@ stub NdisClRegisterSap
@ stub NdisCloseAdapter
@ stub NdisCloseConfiguration
@ stub NdisCloseFile
@ stub NdisCmActivateVc
@ stub NdisCmAddPartyComplete
@ stub NdisCmCloseAddressFamilyComplete
@ stub NdisCmCloseCallComplete
@ stub NdisCmDeactivateVc
@ stub NdisCmDeregisterSapComplete
@ stub NdisCmDispatchCallConnected
@ stub NdisCmDispatchIncomingCall
@ stub NdisCmDispatchIncomingCallQoSChange
@ stub NdisCmDispatchIncomingCloseCall
@ stub NdisCmDispatchIncomingDropParty
@ stub NdisCmDropPartyComplete
@ stub NdisCmMakeCallComplete
@ stub NdisCmModifyCallQoSComplete
@ stub NdisCmOpenAddressFamilyComplete
@ stub NdisCmRegisterAddressFamily
@ stub NdisCmRegisterSapComplete
@ stub NdisCoAssignInstanceName
@ stub NdisCoCreateVc
@ stub NdisCoDeleteVc
@ stub NdisCoGetTapiCallId
@ stub NdisCoRequest
@ stub NdisCoRequestComplete
@ stub NdisCoSendPackets
@ stub NdisCompareAnsiString
@ stub NdisCompareUnicodeString
@ stub NdisCompleteBindAdapter
@ stub NdisCompleteDmaTransfer
@ stub NdisCompletePnPEvent
@ stub NdisCompleteUnbindAdapter
@ stub NdisConvertStringToAtmAddress
@ stub NdisCopyBuffer
@ stub NdisCopyFromPacketToPacket
@ stub NdisCopyFromPacketToPacketSafe
@ stub NdisCreateBlockPool
@ stub NdisDeregisterProtocol
@ stub NdisDeregisterTdiCallBack
@ stub NdisDestroyBlockPool
@ stub NdisDprAcquireSpinLock
@ stub NdisDprAllocatePacket
@ stub NdisDprAllocatePacketNonInterlocked
@ stub NdisDprFreePacket
@ stub NdisDprFreePacketNonInterlocked
@ stub NdisDprReleaseSpinLock
@ stub NdisEqualString
@ stub NdisFreeBuffer
@ stub NdisFreeBufferPool
@ stub NdisFreeMemory
@ stub NdisFreePacket
@ stub NdisFreePacketPool
@ stub NdisFreeSpinLock
@ stub NdisFreeToBlockPool
@ stub NdisGeneratePartialCancelId
@ stub NdisGetBufferPhysicalArraySize
@ stub NdisGetCurrentProcessorCounts
@ stub NdisGetCurrentProcessorCpuUsage
@ stub NdisGetCurrentSystemTime
@ stub NdisGetDriverHandle
@ stub NdisGetFirstBufferFromPacket
@ stub NdisGetFirstBufferFromPacketSafe
@ stub NdisGetPacketCancelId
@ stub NdisGetPoolFromPacket
@ stub NdisGetReceivedPacket
@ stub NdisGetRoutineAddress
@ stub NdisGetSharedDataAlignment
@ stub NdisGetSystemUpTime
@ stub NdisGetVersion
@ stub NdisIMAssociateMiniport
@ stub NdisIMCancelInitializeDeviceInstance
@ stub NdisIMCopySendCompletePerPacketInfo
@ stub NdisIMCopySendPerPacketInfo
@ stub NdisIMDeInitializeDeviceInstance
@ stub NdisIMDeregisterLayeredMiniport
@ stub NdisIMGetBindingContext
@ stub NdisIMGetCurrentPacketStack
@ stub NdisIMGetDeviceContext
@ stub NdisIMInitializeDeviceInstance
@ stub NdisIMInitializeDeviceInstanceEx
@ stub NdisIMNotifyPnPEvent
@ stub NdisIMQueueMiniportCallback
@ stub NdisIMRegisterLayeredMiniport
@ stub NdisIMRevertBack
@ stub NdisIMSwitchToMiniport
@ stub NdisImmediateReadPciSlotInformation
@ stub NdisImmediateReadPortUchar
@ stub NdisImmediateReadPortUlong
@ stub NdisImmediateReadPortUshort
@ stub NdisImmediateReadSharedMemory
@ stub NdisImmediateWritePciSlotInformation
@ stub NdisImmediateWritePortUchar
@ stub NdisImmediateWritePortUlong
@ stub NdisImmediateWritePortUshort
@ stub NdisImmediateWriteSharedMemory
@ stub NdisInitAnsiString
@ stdcall NdisInitUnicodeString(ptr wstr) ntdll.RtlInitUnicodeString
@ stub NdisInitializeEvent
@ stub NdisInitializeReadWriteLock
@ stub NdisInitializeString
@ stub NdisInitializeTimer
@ stub NdisInitializeWrapper
@ stub NdisInterlockedAddLargeInterger
@ stub NdisInterlockedAddUlong
@ stub NdisInterlockedDecrement
@ stub NdisInterlockedIncrement
@ stub NdisInterlockedInsertHeadList
@ stub NdisInterlockedInsertTailList
@ stub NdisInterlockedPopEntryList
@ stub NdisInterlockedPushEntryList
@ stub NdisInterlockedRemoveHeadList
@ stub NdisMAllocateMapRegisters
@ stub NdisMAllocateSharedMemory
@ stub NdisMAllocateSharedMemoryAsync
@ stub NdisMCancelTimer
@ stub NdisMCloseLog
@ stub NdisMCmActivateVc
@ stub NdisMCmCreateVc
@ stub NdisMCmDeactivateVc
@ stub NdisMCmDeleteVc
@ stub NdisMCmRegisterAddressFamily
@ stub NdisMCmRequest
@ stub NdisMCoActivateVcComplete
@ stub NdisMCoDeactivateVcComplete
@ stub NdisMCoIndicateReceivePacket
@ stub NdisMCoIndicateStatus
@ stub NdisMCoReceiveComplete
@ stub NdisMCoRequestComplete
@ stub NdisMCoSendComplete
@ stub NdisMCompleteBufferPhysicalMapping
@ stub NdisMCreateLog
@ stub NdisMDeregisterAdapterShutdownHandler
@ stub NdisMDeregisterDevice
@ stub NdisMDeregisterDmaChannel
@ stub NdisMDeregisterInterrupt
@ stub NdisMDeregisterIoPortRange
@ stub NdisMFlushLog
@ stub NdisMFreeMapRegisters
@ stub NdisMFreeSharedMemory
@ stub NdisMGetDeviceProperty
@ stub NdisMGetDmaAlignment
@ stub NdisMIndicateStatus
@ stub NdisMIndicateStatusComplete
@ stub NdisMInitializeScatterGatherDma
@ stub NdisMInitializeTimer
@ stub NdisMMapIoSpace
@ stub NdisMPciAssignResources
@ stub NdisMPromoteMiniport
@ stub NdisMQueryAdapterInstanceName
@ stub NdisMQueryAdapterResources
@ stub NdisMQueryInformationComplete
@ stub NdisMReadDmaCounter
@ stub NdisMRegisterAdapterShutdownHandler
@ stub NdisMRegisterDevice
@ stub NdisMRegisterDmaChannel
@ stub NdisMRegisterInterrupt
@ stub NdisMRegisterIoPortRange
@ stub NdisMRegisterMiniport
@ stub NdisMRegisterUnloadHandler
@ stub NdisMRemoveMiniport
@ stub NdisMResetComplete
@ stub NdisMSendComplete
@ stub NdisMSendResourcesAvailable
@ stub NdisMSetAttributes
@ stub NdisMSetAttributesEx
@ stub NdisMSetInformationComplete
@ stub NdisMSetMiniportSecondary
@ stub NdisMSetPeriodicTimer
@ stub NdisMSetTimer
@ stub NdisMSleep
@ stub NdisMStartBufferPhysicalMapping
@ stub NdisMSynchronizeWithInterrupt
@ stub NdisMTransferDataComplete
@ stub NdisMUnmapIoSpace
@ stub NdisMWanIndicateReceive
@ stub NdisMWanIndicateReceiveComplete
@ stub NdisMWanSendComplete
@ stub NdisMWriteLogData
@ stub NdisMapFile
@ stub NdisMatchPdoWithPacket
@ stub NdisOpenAdapter
@ stub NdisOpenConfiguration
@ stub NdisOpenConfigurationKeyByIndex
@ stub NdisOpenConfigurationKeyByName
@ stub NdisOpenFile
@ stub NdisOpenProtocolConfiguration
@ stub NdisOverrideBusNumber
@ stub NdisPacketPoolUsage
@ stub NdisPacketSize
@ stub NdisQueryAdapterInstanceName
@ stub NdisQueryBindInstanceName
@ stub NdisQueryBuffer
@ stub NdisQueryBufferOffset
@ stub NdisQueryBufferSafe
@ stub NdisQueryMapRegisterCount
@ stub NdisQueryPendingIOCount
@ stub NdisReEnumerateProtocolBindings
@ stub NdisReadConfiguration
@ stub NdisReadEisaSlotInformation
@ stub NdisReadEisaSlotInformationEx
@ stub NdisReadMcaPosInformation
@ stub NdisReadNetworkAddress
@ stub NdisReadPciSlotInformation
@ stub NdisReadPcmciaAttributeMemory
@ stdcall NdisRegisterProtocol(ptr ptr ptr long)
@ stub NdisRegisterTdiCallBack
@ stub NdisReleaseReadWriteLock
@ stub NdisReleaseSpinLock
@ stub NdisRequest
@ stub NdisReset
@ stub NdisResetEvent
@ stub NdisReturnPackets
@ stub NdisScheduleWorkItem
@ stub NdisSend
@ stub NdisSendPackets
@ stub NdisSetEvent
@ stub NdisSetPacketCancelId
@ stub NdisSetPacketPoolProtocolId
@ stub NdisSetPacketStatus
@ stub NdisSetProtocolFilter
@ stub NdisSetTimer
@ stub NdisSetTimerEx
@ stub NdisSetupDmaTransfer
@ stdcall NdisSystemProcessorCount()
@ stub NdisTerminateWrapper
@ stub NdisTransferData
@ stub NdisUnchainBufferAtBack
@ stub NdisUnchainBufferAtFront
@ stub NdisUnicodeStringToAnsiString
@ stub NdisUnmapFile
@ stub NdisUpcaseUnicodeString
@ stub NdisUpdateSharedMemory
@ stub NdisWaitEvent
@ stub NdisWriteConfiguration
@ stub NdisWriteErrorLogEntry
@ stub NdisWriteEventLogEntry
@ stub NdisWritePciSlotInformation
@ stub NdisWritePcmciaAttributeMemory
@ stub TrFilterDprIndicateReceive
@ stub TrFilterDprIndicateReceiveComplete
