1017 stub @
1019 stub @
1028 stub @
1031 stub @
1033 stub @
1038 stub @
1039 stub @
1040 stub @
1041 stub @
1042 stub @

@ stub CompileEffectDescription
@ stub CreateEffectDescription
@ stub DCompositionAttachMouseDragToHwnd
@ stub DCompositionAttachMouseWheelToHwnd
@ stub DCompositionCreateDevice2
@ stub DCompositionCreateDevice3
@ stub DCompositionCreateDevice
@ stub DCompositionCreateSurfaceHandle
@ stub DeserializeEffectDescription
@ stub DllCanUnloadNow
@ stub DllGetActivationFactory
@ stub DllGetClassObject
@ stub DwmEnableMMCSS
@ stub DwmFlush
@ stub DwmpEnableDDASupport
@ stub SerializeEffectDescription
