/*
 * Copyright (C) the Wine project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep header

import "unknwn.idl";
import "xtaskqueue.h";

typedef void __stdcall XGameInviteEventCallback( void *context, const char *inviteUri );

cpp_quote("#ifdef __WINESRC__")

[
    local,
    object,
    uuid(0651aae2-4012-4077-bf84-8b9097090e2c)
]
interface IXGameInviteImpl : IUnknown
{
    HRESULT XGameInviteRegisterForEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XGameInviteEventCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XGameInviteUnregisterForEvent( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
}

[
    local,
    object,
    uuid(014d1cc3-bcfe-41ff-b2f0-e1ef07155828)
]
interface IXGameInviteImpl2 : IXGameInviteImpl
{
    HRESULT XGameInviteRegisterForPendingEvent( [in, optional] XTaskQueueHandle queue, [in, optional] void *context, [in] XGameInviteEventCallback *callback, [out] XTaskQueueRegistrationToken *token );
    BOOLEAN XGameInviteUnregisterForPendingEvent( [in] XTaskQueueRegistrationToken token, [in] BOOLEAN wait );
    HRESULT XGameInviteAcceptPendingInvite( [in, string] const char *inviteUri );
}

[
    uuid(0651aae2-4012-4077-bf84-8b9097090e2c)
]
coclass XGameInviteImpl
{
    [default] interface IXGameInviteImpl2;
}

cpp_quote("#endif")
