  1 stub INICOM
  2 stub SETCOM
  3 stub SETQUE
  4 stub RECCOM
  5 stub SNDCOM
  6 stub CTX
  7 stub TRMCOM
  8 stub STACOM
  9 stub CEXTFCN
 10 stub CFLUSH
 11 stub CEVT
 12 stub CEVTGET
 13 stub CSETBRK
 14 stub CCLRBRK
 15 stub GETDCB
#16 stub WEP
 17 stub SUSPENDOPENCOMMPORTS # win3.1
 18 stub REACTIVATEOPENCOMMPORTS # win3.1
 19 stub COMMWRITESTRING
 20 stub READCOMMSTRING
100 stub ENABLENOTIFICATION
101 stub ordinal_only__win31
