 1 stdcall CAPI_REGISTER(long long long long ptr)
 2 stdcall CAPI_RELEASE(long)
 3 stdcall CAPI_PUT_MESSAGE(long ptr)
 4 stdcall CAPI_GET_MESSAGE(long ptr)
 5 stdcall CAPI_WAIT_FOR_SIGNAL(long)
 6 stdcall CAPI_GET_MANUFACTURER(ptr)
 7 stdcall CAPI_GET_VERSION(ptr ptr ptr ptr)
 8 stdcall CAPI_GET_SERIAL_NUMBER(ptr)
 9 stdcall CAPI_GET_PROFILE(ptr long)
10 stdcall CAPI_INSTALLED()
99 stdcall CAPI_MANUFACTURER(long long long ptr long)
