@ stub CommitComplete
@ stub CommitEnlistment
@ stdcall CommitTransaction(ptr)
@ stub CommitTransactionAsync
@ stub CreateEnlistment
@ stub CreateResourceManager
@ stdcall CreateTransaction(ptr ptr long long long long wstr)
@ stub CreateTransactionManager
@ stub GetCurrentClockTransactionManager
@ stub GetEnlistmentId
@ stub GetEnlistmentRecoveryInformation
@ stub GetNotificationResourceManager
@ stub GetNotificationResourceManagerAsync
@ stub GetTransactionId
@ stub GetTransactionInformation
@ stub GetTransactionManagerId
@ stub OpenEnlistment
@ stub OpenResourceManager
@ stub OpenTransaction
@ stub OpenTransactionManager
@ stub OpenTransactionManagerById
@ stub PrePrepareComplete
@ stub PrePrepareEnlistment
@ stub PrepareComplete
@ stub PrepareEnlistment
@ stub PrivCreateTransaction
@ stub PrivIsLogWritableTransactionManager
@ stub PrivPropagationComplete
@ stub PrivPropagationFailed
@ stub PrivRegisterProtocolAddressInformation
@ stub ReadOnlyEnlistment
@ stub RecoverEnlistment
@ stub RecoverResourceManager
@ stub RecoverTransactionManager
@ stub RenameTransactionManager
@ stub RollbackComplete
@ stub RollbackEnlistment
@ stdcall RollbackTransaction(ptr)
@ stub RollbackTransactionAsync
@ stub RollforwardTransactionManager
@ stub SetEnlistmentRecoveryInformation
@ stub SetResourceManagerCompletionPort
@ stub SetTransactionInformation
@ stub SinglePhaseReject
