/*
 * Copyright 2019 Alistair Leslie-Hughes
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */
#pragma makedep register

[
    uuid(54e211b6-3650-4f75-8334-fa359598e1c5),
    threading(both)
]
coclass DirectManipulationManager
{
    interface IDirectManipulationManager2;
    [default] interface IDirectManipulationManager;
}

[
    uuid(99793286-77cc-4b57-96db-3b354f6f9fb5),
    threading(both)
]
coclass DirectManipulationSharedManager
{
    interface IDirectManipulationManager2;
    [default] interface IDirectManipulationManager;
}

[
    uuid(79dea627-a08a-43ac-8ef5-6900b9299126),
    threading(both)
]
coclass DCompManipulationCompositor
{
    [default] interface IDirectManipulationCompositor;
    interface IDirectManipulationCompositor2;
    interface IDirectManipulationFrameInfoProvider;
}
