@ stub ValidateSystemShutdown
@ stub BiActivateWorkItemForUser
@ stub BiChangeApplicationStateForPackageName
@ stub BiChangeApplicationStateForPackageNameForUser
@ stub BiChangeApplicationStateForPsmKey
@ stub BiChangeApplicationStateForPsmKeyForUser
@ stub BiChangeSessionState
@ stub BiChangeUserState
@ stub BiEnumerateWorkItemsForPackageNameAndUser
@ stub BiGetActiveBackgroundTasksEvent
@ stub BiGetActiveBackgroundTasksEventForUser
@ stub BiGetCancellationTimeoutInMs
@ stub BiIsApplicationTerminateSensitive
@ stub BiIsApplicationTerminateSensitiveForUser
@ stub BiNotifyNewSession
@ stub BiNotifyNewSessionComplete
@ stub BiNotifyNewUser
@ stub BiPlmFreeMemory
@ stub BiPtActivateDeferredWorkItem
@ stub BiPtActivateInBackground
@ stub BiPtActivateInBackgroundEx
@ stub BiPtActivateWorkItem
@ stub BiPtAssociateActivationProxy
@ stub BiPtAssociateApplicationEntryPoint
@ stub BiPtAssociateApplicationExtensionClass
@ stub BiPtCancelWorkItem
@ stub BiPtCancelWorkItemEx
@ stub BiPtCreateEvent
@ stub BiPtCreateEventForApp
@ stub BiPtCreateEventForPackageName
@ stub BiPtDeleteEvent
@ stub BiPtDisableWorkItem
@ stub BiPtDisassociateWorkItem
@ stub BiPtDisassociateWorkItemEx
@ stub BiPtEnableWorkItem
@ stub BiPtEnumerateBrokeredEvents
@ stub BiPtEnumerateBrokeredEventsEx
@ stub BiPtEnumerateWorkItemsForPackageName
@ stub BiPtEnumerateWorkItemsForPackageNameEx
@ stub BiPtFreeMemory
@ stub BiPtGetStatusStateNameFromBrokerEventId
@ stub BiPtQueryBrokerEventId
@ stub BiPtQueryBrokeredEvent
@ stub BiPtQuerySystemStateBroadcastChannels
@ stub BiPtQueryWorkItem
@ stub BiPtQueryWorkItemEx
@ stub BiPtQueryWorkItemStatusStateName
@ stub BiPtSignalEvent
@ stub BiPtSignalEventEx
@ stub BiPtSignalMultipleEvents
@ stub BiPtSignalTriggerEvent
@ stub BiPtSignalTriggerEventEx
@ stub BiQueryWorkItemForUser
@ stub BiResetActiveSessionForPackage
@ stub BiResetActiveUserForPackage
@ stub BiSetActiveSessionForPackage
@ stub BiSetActiveUserForPackage
@ stub BiTerminateApplicationHost
@ stub BiTerminateApplicationHost2
@ stub BiTerminateApplicationHostForUser
@ stub BiUpdateBackgroundAccessApplicationsForUser
@ stub BiUpdateLockScreenApplications
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetActivationFactory(ptr ptr)
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stub PsmApplyTaskCompletion
@ stub PsmBlockAppStateChangeCompletion
@ stub PsmDisconnect
@ stub PsmGetSessionInfo
@ stub PsmInitializeExtension
@ stub PsmIsProcessInApplication
@ stub PsmIsProcessInApplication2
@ stub PsmQueryApplicationInformation
@ stub PsmQueryApplicationInformation2
@ stub PsmQueryApplicationInterferenceCount
@ stub PsmQueryApplicationInterferenceCount2
@ stub PsmQueryApplicationList
@ stub PsmQueryApplicationList2
@ stub PsmQueryApplicationProperties
@ stub PsmQueryApplicationProperties2
@ stub PsmQueryApplicationProperties3
@ stub PsmQueryApplicationPropertiesByUser
@ stub PsmQueryApplicationResourceUsage
@ stub PsmQueryApplicationResourceUsage2
@ stub PsmQueryApplicationResourceUsageForTimer
@ stub PsmQueryCurrentAppState
@ stub PsmQueryMaxMemoryUsage
@ stub PsmQueryMaxMemoryUsage2
@ stub PsmQueryMemoryUsage
@ stub PsmQueryMemoryUsage2
@ stub PsmQueryMemoryUsageByUser
@ stub PsmQueryProcessList
@ stub PsmQueryProcessList2
@ stub PsmQuerySharedCommitByUser
@ stub PsmQueryTaskCompletionInformation
@ stub PsmQueryTaskCompletionInformation2
@ stub PsmRegisterAppPriorityNotification
@ stub PsmRegisterAppStateChangeNotification
@ stub PsmRegisterApplicationNotification
@ stub PsmRegisterApplicationNotification2
@ stub PsmRegisterDynamicProcess
@ stub PsmRegisterKeyNotification
@ stub PsmRegisterManagerType
@ stub PsmResetMaxMemoryUsage
@ stub PsmResetMaxMemoryUsage2
@ stub PsmResetMaxMemoryUsageByUser
@ stub PsmSetApplicationPriority
@ stub PsmSetApplicationPriority2
@ stub PsmSetApplicationProperties
@ stub PsmSetApplicationProperties2
@ stub PsmSetApplicationProperties3
@ stub PsmSetApplicationPropertiesByUser
@ stub PsmSetApplicationState
@ stub PsmSetApplicationState2
@ stub PsmShutdownApplication
@ stub PsmTimerCleanup
@ stub PsmTimerElapsedResourceTimeGet
@ stub PsmTimerInitialize
@ stub PsmTimerRemainingResourceTimeGet
@ stub PsmTimerStart
@ stub PsmUnblockAppStateChangeCompletion
@ stub PsmUnregisterAppStateChangeNotification
@ stub PsmWaitForAppResume
@ stdcall RegisterAppConstrainedChangeNotification(ptr ptr ptr)
@ stdcall RegisterAppStateChangeNotification(ptr ptr ptr)
@ stdcall UnregisterAppConstrainedChangeNotification(ptr)
@ stdcall UnregisterAppStateChangeNotification(ptr)
