@ stdcall D3DX11CheckVersion(long long)
@ stub D3DX11CompileFromFileA
@ stub D3DX11CompileFromFileW
@ stub D3DX11CompileFromMemory
@ stub D3DX11CompileFromResourceA
@ stub D3DX11CompileFromResourceW
@ stub D3DX11ComputeNormalMap
@ stub D3DX11CreateAsyncCompilerProcessor
@ stub D3DX11CreateAsyncFileLoaderA
@ stub D3DX11CreateAsyncFileLoaderW
@ stub D3DX11CreateAsyncMemoryLoader
@ stub D3DX11CreateAsyncResourceLoaderA
@ stub D3DX11CreateAsyncResourceLoaderW
@ stub D3DX11CreateAsyncShaderPreprocessProcessor
@ stub D3DX11CreateAsyncShaderResourceViewProcessor
@ stub D3DX11CreateAsyncTextureInfoProcessor
@ stub D3DX11CreateAsyncTextureProcessor
@ stub D3DX11CreateShaderResourceViewFromFileA
@ stub D3DX11CreateShaderResourceViewFromFileW
@ stub D3DX11CreateShaderResourceViewFromMemory
@ stub D3DX11CreateShaderResourceViewFromResourceA
@ stub D3DX11CreateShaderResourceViewFromResourceW
@ stub D3DX11CreateTextureFromFileA
@ stub D3DX11CreateTextureFromFileW
@ stub D3DX11CreateTextureFromMemory
@ stub D3DX11CreateTextureFromResourceA
@ stub D3DX11CreateTextureFromResourceW
@ stub D3DX11CreateThreadPump
@ stub D3DX11FilterTexture
@ stub D3DX11GetImageInfoFromFileA
@ stub D3DX11GetImageInfoFromFileW
@ stub D3DX11GetImageInfoFromMemory
@ stub D3DX11GetImageInfoFromResourceA
@ stub D3DX11GetImageInfoFromResourceW
@ stub D3DX11LoadTextureFromTexture
@ stub D3DX11PreprocessShaderFromFileA
@ stub D3DX11PreprocessShaderFromFileW
@ stub D3DX11PreprocessShaderFromMemory
@ stub D3DX11PreprocessShaderFromResourceA
@ stub D3DX11PreprocessShaderFromResourceW
@ stub D3DX11SHProjectCubeMap
@ stub D3DX11SaveTextureToFileA
@ stub D3DX11SaveTextureToFileW
@ stub D3DX11SaveTextureToMemory
