@ stub NetAccessAdd
@ stub NetAccessCheck
@ stub NetAccessDel
@ stub NetAccessEnum
@ stub NetAccessGetInfo
@ stub NetAccessGetUserPerms
@ stub NetAccessSetInfo
@ stub NetConnectionEnum
@ stub NetFileClose
@ stub NetFileEnum
@ stub NetSecurityGetInfo
@ stub NetServerGetInfo
@ stub NetSessionDel
@ stub NetSessionEnum
@ stub NetSessionGetInfo
@ stub NetShareAdd
@ stub NetShareDel
@ stub NetShareEnum
@ stub NetShareGetInfo
@ stub NetShareSetInfo
