# Generated with make_sqlite.py
@ stdcall sqlite3_aggregate_count(ptr)
@ stdcall sqlite3_auto_extension(ptr)
@ stdcall sqlite3_autovacuum_pages(ptr ptr ptr ptr)
@ stdcall sqlite3_backup_finish(ptr)
@ stdcall sqlite3_backup_init(ptr ptr ptr ptr)
@ stdcall sqlite3_backup_pagecount(ptr)
@ stdcall sqlite3_backup_remaining(ptr)
@ stdcall sqlite3_backup_step(ptr long)
@ stdcall sqlite3_bind_blob(ptr long ptr long ptr)
@ stdcall sqlite3_bind_blob64(ptr long ptr int64 ptr)
@ stdcall sqlite3_bind_double(ptr long double)
@ stdcall sqlite3_bind_int(ptr long long)
@ stdcall sqlite3_bind_int64(ptr long int64)
@ stdcall sqlite3_bind_null(ptr long)
@ stdcall sqlite3_bind_parameter_count(ptr)
@ stdcall sqlite3_bind_parameter_index(ptr ptr)
@ stdcall sqlite3_bind_parameter_name(ptr long)
@ stdcall sqlite3_bind_pointer(ptr long ptr ptr ptr)
@ stdcall sqlite3_bind_text(ptr long ptr long ptr)
@ stdcall sqlite3_bind_text16(ptr long ptr long ptr)
@ stdcall sqlite3_bind_text64(ptr long ptr int64 ptr long)
@ stdcall sqlite3_bind_value(ptr long ptr)
@ stdcall sqlite3_bind_zeroblob(ptr long long)
@ stdcall sqlite3_bind_zeroblob64(ptr long int64)
@ stdcall sqlite3_blob_bytes(ptr)
@ stdcall sqlite3_blob_close(ptr)
@ stdcall sqlite3_blob_open(ptr ptr ptr ptr int64 long ptr)
@ stdcall sqlite3_blob_read(ptr ptr long long)
@ stdcall sqlite3_blob_reopen(ptr int64)
@ stdcall sqlite3_blob_write(ptr ptr long long)
@ stdcall sqlite3_busy_handler(ptr ptr ptr)
@ stdcall sqlite3_busy_timeout(ptr long)
@ stdcall sqlite3_cancel_auto_extension(ptr)
@ stdcall sqlite3_changes(ptr)
@ stdcall sqlite3_changes64(ptr)
@ stdcall sqlite3_clear_bindings(ptr)
@ stdcall sqlite3_close(ptr)
@ stdcall sqlite3_close_v2(ptr)
@ stdcall sqlite3_collation_needed(ptr ptr ptr)
@ stdcall sqlite3_collation_needed16(ptr ptr ptr)
@ stdcall sqlite3_column_blob(ptr long)
@ stdcall sqlite3_column_bytes(ptr long)
@ stdcall sqlite3_column_bytes16(ptr long)
@ stdcall sqlite3_column_count(ptr)
@ stdcall sqlite3_column_database_name(ptr long)
@ stdcall sqlite3_column_database_name16(ptr long)
@ stdcall sqlite3_column_decltype(ptr long)
@ stdcall sqlite3_column_decltype16(ptr long)
@ stdcall sqlite3_column_double(ptr long)
@ stdcall sqlite3_column_int(ptr long)
@ stdcall sqlite3_column_int64(ptr long)
@ stdcall sqlite3_column_name(ptr long)
@ stdcall sqlite3_column_name16(ptr long)
@ stdcall sqlite3_column_origin_name(ptr long)
@ stdcall sqlite3_column_origin_name16(ptr long)
@ stdcall sqlite3_column_table_name(ptr long)
@ stdcall sqlite3_column_table_name16(ptr long)
@ stdcall sqlite3_column_text(ptr long)
@ stdcall sqlite3_column_text16(ptr long)
@ stdcall sqlite3_column_type(ptr long)
@ stdcall sqlite3_column_value(ptr long)
@ stdcall sqlite3_commit_hook(ptr ptr ptr)
@ stdcall sqlite3_compileoption_get(long)
@ stdcall sqlite3_compileoption_used(ptr)
@ stdcall sqlite3_complete(ptr)
@ stdcall sqlite3_complete16(ptr)
@ varargs sqlite3_config(long)
@ stdcall sqlite3_context_db_handle(ptr)
@ stdcall sqlite3_create_collation(ptr ptr long ptr ptr)
@ stdcall sqlite3_create_collation16(ptr ptr long ptr ptr)
@ stdcall sqlite3_create_collation_v2(ptr ptr long ptr ptr ptr)
@ stdcall sqlite3_create_filename(ptr ptr ptr long ptr)
@ stdcall sqlite3_create_function(ptr ptr long long ptr ptr ptr ptr)
@ stdcall sqlite3_create_function16(ptr ptr long long ptr ptr ptr ptr)
@ stdcall sqlite3_create_function_v2(ptr ptr long long ptr ptr ptr ptr ptr)
@ stdcall sqlite3_create_module(ptr ptr ptr ptr)
@ stdcall sqlite3_create_module_v2(ptr ptr ptr ptr ptr)
@ stdcall sqlite3_create_window_function(ptr ptr long long ptr ptr ptr ptr ptr ptr)
@ stdcall sqlite3_data_count(ptr)
@ extern sqlite3_data_directory
@ stdcall sqlite3_database_file_object(ptr)
@ stdcall sqlite3_db_cacheflush(ptr)
@ varargs sqlite3_db_config(ptr long)
@ stdcall sqlite3_db_filename(ptr ptr)
@ stdcall sqlite3_db_handle(ptr)
@ stdcall sqlite3_db_mutex(ptr)
@ stdcall sqlite3_db_name(ptr long)
@ stdcall sqlite3_db_readonly(ptr ptr)
@ stdcall sqlite3_db_release_memory(ptr)
@ stdcall sqlite3_db_status(ptr long ptr ptr long)
@ stdcall sqlite3_db_status64(ptr long ptr ptr long)
@ stdcall sqlite3_declare_vtab(ptr ptr)
@ stdcall sqlite3_deserialize(ptr ptr ptr int64 int64 long)
@ stdcall sqlite3_drop_modules(ptr ptr)
@ stdcall sqlite3_enable_load_extension(ptr long)
@ stdcall sqlite3_enable_shared_cache(long)
@ stdcall sqlite3_errcode(ptr)
@ stdcall sqlite3_errmsg(ptr)
@ stdcall sqlite3_errmsg16(ptr)
@ stdcall sqlite3_error_offset(ptr)
@ stdcall sqlite3_errstr(long)
@ stdcall sqlite3_exec(ptr ptr ptr ptr ptr)
@ stdcall sqlite3_expanded_sql(ptr)
@ stdcall sqlite3_expired(ptr)
@ stdcall sqlite3_extended_errcode(ptr)
@ stdcall sqlite3_extended_result_codes(ptr long)
@ stdcall sqlite3_file_control(ptr ptr long ptr)
@ stdcall sqlite3_filename_database(ptr)
@ stdcall sqlite3_filename_journal(ptr)
@ stdcall sqlite3_filename_wal(ptr)
@ stdcall sqlite3_finalize(ptr)
@ stdcall sqlite3_free(ptr)
@ stdcall sqlite3_free_filename(ptr)
@ stdcall sqlite3_free_table(ptr)
@ extern sqlite3_fts3_may_be_corrupt
@ stdcall sqlite3_get_autocommit(ptr)
@ stdcall sqlite3_get_auxdata(ptr long)
@ stdcall sqlite3_get_clientdata(ptr ptr)
@ stdcall sqlite3_get_table(ptr ptr ptr ptr ptr ptr)
@ stdcall sqlite3_global_recover()
@ stdcall sqlite3_hard_heap_limit64(int64)
@ stdcall sqlite3_initialize()
@ stdcall sqlite3_interrupt(ptr)
@ stdcall sqlite3_is_interrupted(ptr)
@ stdcall sqlite3_keyword_check(ptr long)
@ stdcall sqlite3_keyword_count()
@ stdcall sqlite3_keyword_name(long ptr ptr)
@ stdcall sqlite3_last_insert_rowid(ptr)
@ stdcall sqlite3_libversion()
@ stdcall sqlite3_libversion_number()
@ stdcall sqlite3_limit(ptr long long)
@ stdcall sqlite3_load_extension(ptr ptr ptr ptr)
@ varargs sqlite3_log(long ptr)
@ stdcall sqlite3_malloc(long)
@ stdcall sqlite3_malloc64(int64)
@ stdcall sqlite3_memory_alarm(ptr ptr int64)
@ stdcall sqlite3_memory_highwater(long)
@ stdcall sqlite3_memory_used()
@ varargs sqlite3_mprintf(ptr)
@ stdcall sqlite3_msize(ptr)
@ stdcall sqlite3_mutex_alloc(long)
@ stdcall sqlite3_mutex_enter(ptr)
@ stdcall sqlite3_mutex_free(ptr)
@ stdcall sqlite3_mutex_leave(ptr)
@ stdcall sqlite3_mutex_try(ptr)
@ stdcall sqlite3_next_stmt(ptr ptr)
@ stdcall sqlite3_open(ptr ptr)
@ stdcall sqlite3_open16(ptr ptr)
@ stdcall sqlite3_open_v2(ptr ptr long ptr)
@ stdcall sqlite3_os_end()
@ stdcall sqlite3_os_init()
@ stdcall sqlite3_overload_function(ptr ptr long)
@ stdcall sqlite3_prepare(ptr ptr long ptr ptr)
@ stdcall sqlite3_prepare16(ptr ptr long ptr ptr)
@ stdcall sqlite3_prepare16_v2(ptr ptr long ptr ptr)
@ stdcall sqlite3_prepare16_v3(ptr ptr long long ptr ptr)
@ stdcall sqlite3_prepare_v2(ptr ptr long ptr ptr)
@ stdcall sqlite3_prepare_v3(ptr ptr long long ptr ptr)
@ stdcall sqlite3_profile(ptr ptr ptr)
@ stdcall sqlite3_progress_handler(ptr long ptr ptr)
@ stdcall sqlite3_randomness(long ptr)
@ stdcall sqlite3_realloc(ptr long)
@ stdcall sqlite3_realloc64(ptr int64)
@ stdcall sqlite3_release_memory(long)
@ stdcall sqlite3_reset(ptr)
@ stdcall sqlite3_reset_auto_extension()
@ stdcall sqlite3_result_blob(ptr ptr long ptr)
@ stdcall sqlite3_result_blob64(ptr ptr int64 ptr)
@ stdcall sqlite3_result_double(ptr double)
@ stdcall sqlite3_result_error(ptr ptr long)
@ stdcall sqlite3_result_error16(ptr ptr long)
@ stdcall sqlite3_result_error_code(ptr long)
@ stdcall sqlite3_result_error_nomem(ptr)
@ stdcall sqlite3_result_error_toobig(ptr)
@ stdcall sqlite3_result_int(ptr long)
@ stdcall sqlite3_result_int64(ptr int64)
@ stdcall sqlite3_result_null(ptr)
@ stdcall sqlite3_result_pointer(ptr ptr ptr ptr)
@ stdcall sqlite3_result_subtype(ptr long)
@ stdcall sqlite3_result_text(ptr ptr long ptr)
@ stdcall sqlite3_result_text16(ptr ptr long ptr)
@ stdcall sqlite3_result_text16be(ptr ptr long ptr)
@ stdcall sqlite3_result_text16le(ptr ptr long ptr)
@ stdcall sqlite3_result_text64(ptr ptr int64 ptr long)
@ stdcall sqlite3_result_value(ptr ptr)
@ stdcall sqlite3_result_zeroblob(ptr long)
@ stdcall sqlite3_result_zeroblob64(ptr int64)
@ stdcall sqlite3_rollback_hook(ptr ptr ptr)
@ stdcall sqlite3_rtree_geometry_callback(ptr ptr ptr ptr)
@ stdcall sqlite3_rtree_query_callback(ptr ptr ptr ptr ptr)
@ stdcall sqlite3_serialize(ptr ptr ptr long)
@ stdcall sqlite3_set_authorizer(ptr ptr ptr)
@ stdcall sqlite3_set_auxdata(ptr long ptr ptr)
@ stdcall sqlite3_set_clientdata(ptr ptr ptr ptr)
@ stdcall sqlite3_set_errmsg(ptr long ptr)
@ stdcall sqlite3_set_last_insert_rowid(ptr int64)
@ stdcall sqlite3_setlk_timeout(ptr long long)
@ stdcall sqlite3_shutdown()
@ stdcall sqlite3_sleep(long)
@ varargs sqlite3_snprintf(long ptr ptr)
@ stdcall sqlite3_soft_heap_limit(long)
@ stdcall sqlite3_soft_heap_limit64(int64)
@ stdcall sqlite3_sourceid()
@ stdcall sqlite3_sql(ptr)
@ stdcall sqlite3_status(long ptr ptr long)
@ stdcall sqlite3_status64(long ptr ptr long)
@ stdcall sqlite3_step(ptr)
@ stdcall sqlite3_stmt_busy(ptr)
@ stdcall sqlite3_stmt_explain(ptr long)
@ stdcall sqlite3_stmt_isexplain(ptr)
@ stdcall sqlite3_stmt_readonly(ptr)
@ stdcall sqlite3_stmt_status(ptr long long)
@ stdcall sqlite3_str_append(ptr ptr long)
@ stdcall sqlite3_str_appendall(ptr ptr)
@ stdcall sqlite3_str_appendchar(ptr long long)
@ varargs sqlite3_str_appendf(ptr ptr)
@ stdcall sqlite3_str_errcode(ptr)
@ stdcall sqlite3_str_finish(ptr)
@ stdcall sqlite3_str_length(ptr)
@ stdcall sqlite3_str_new(ptr)
@ stdcall sqlite3_str_reset(ptr)
@ stdcall sqlite3_str_value(ptr)
@ stdcall sqlite3_str_vappendf(ptr ptr ptr)
@ stdcall sqlite3_strglob(ptr ptr)
@ stdcall sqlite3_stricmp(ptr ptr)
@ stdcall sqlite3_strlike(ptr ptr long)
@ stdcall sqlite3_strnicmp(ptr ptr long)
@ stdcall sqlite3_system_errno(ptr)
@ stdcall sqlite3_table_column_metadata(ptr ptr ptr ptr ptr ptr ptr ptr ptr)
@ extern sqlite3_temp_directory
@ varargs sqlite3_test_control(long)
@ stdcall sqlite3_thread_cleanup()
@ stdcall sqlite3_threadsafe()
@ stdcall sqlite3_total_changes(ptr)
@ stdcall sqlite3_total_changes64(ptr)
@ stdcall sqlite3_trace(ptr ptr ptr)
@ stdcall sqlite3_trace_v2(ptr long ptr ptr)
@ stdcall sqlite3_transfer_bindings(ptr ptr)
@ stdcall sqlite3_txn_state(ptr ptr)
@ stub sqlite3_unsupported_selecttrace
@ stdcall sqlite3_update_hook(ptr ptr ptr)
@ stdcall sqlite3_uri_boolean(ptr ptr long)
@ stdcall sqlite3_uri_int64(ptr ptr int64)
@ stdcall sqlite3_uri_key(ptr long)
@ stdcall sqlite3_uri_parameter(ptr ptr)
@ stdcall sqlite3_user_data(ptr)
@ stdcall sqlite3_value_blob(ptr)
@ stdcall sqlite3_value_bytes(ptr)
@ stdcall sqlite3_value_bytes16(ptr)
@ stdcall sqlite3_value_double(ptr)
@ stdcall sqlite3_value_dup(ptr)
@ stdcall sqlite3_value_encoding(ptr)
@ stdcall sqlite3_value_free(ptr)
@ stdcall sqlite3_value_frombind(ptr)
@ stdcall sqlite3_value_int(ptr)
@ stdcall sqlite3_value_int64(ptr)
@ stdcall sqlite3_value_nochange(ptr)
@ stdcall sqlite3_value_numeric_type(ptr)
@ stdcall sqlite3_value_pointer(ptr ptr)
@ stdcall sqlite3_value_subtype(ptr)
@ stdcall sqlite3_value_text(ptr)
@ stdcall sqlite3_value_text16(ptr)
@ stdcall sqlite3_value_text16be(ptr)
@ stdcall sqlite3_value_text16le(ptr)
@ stdcall sqlite3_value_type(ptr)
@ extern sqlite3_version
@ stdcall sqlite3_vfs_find(ptr)
@ stdcall sqlite3_vfs_register(ptr long)
@ stdcall sqlite3_vfs_unregister(ptr)
@ stdcall sqlite3_vmprintf(ptr ptr)
@ stdcall sqlite3_vsnprintf(long ptr ptr ptr)
@ stdcall sqlite3_vtab_collation(ptr long)
@ varargs sqlite3_vtab_config(ptr long)
@ stdcall sqlite3_vtab_distinct(ptr)
@ stdcall sqlite3_vtab_in(ptr long long)
@ stdcall sqlite3_vtab_in_first(ptr ptr)
@ stdcall sqlite3_vtab_in_next(ptr ptr)
@ stdcall sqlite3_vtab_nochange(ptr)
@ stdcall sqlite3_vtab_on_conflict(ptr)
@ stdcall sqlite3_vtab_rhs_value(ptr long ptr)
@ stdcall sqlite3_wal_autocheckpoint(ptr long)
@ stdcall sqlite3_wal_checkpoint(ptr ptr)
@ stdcall sqlite3_wal_checkpoint_v2(ptr ptr long ptr ptr)
@ stdcall sqlite3_wal_hook(ptr ptr ptr)
@ stdcall sqlite3_win32_is_nt()
@ stdcall sqlite3_win32_mbcs_to_utf8(ptr)
@ stdcall sqlite3_win32_mbcs_to_utf8_v2(ptr long)
@ stdcall sqlite3_win32_set_directory(long ptr)
@ stdcall sqlite3_win32_set_directory16(long ptr)
@ stdcall sqlite3_win32_set_directory8(long ptr)
@ stdcall sqlite3_win32_sleep(long)
@ stdcall sqlite3_win32_unicode_to_utf8(ptr)
@ stdcall sqlite3_win32_utf8_to_mbcs(ptr)
@ stdcall sqlite3_win32_utf8_to_mbcs_v2(ptr long)
@ stdcall sqlite3_win32_utf8_to_unicode(ptr)
@ stdcall sqlite3_win32_write_debug(ptr long)
