@ stdcall D3D9GetSWInfo()
@ stdcall DebugSetMute()
@ stdcall Direct3DCreate9(long)
@ stdcall ValidatePixelShader(ptr long long ptr)
@ stdcall ValidateVertexShader(ptr long long ptr)
@ stdcall D3DPERF_SetOptions(long)
