@ stub DRMAcquireAdvisories
@ stub DRMAcquireIssuanceLicenseTemplate
@ stub DRMAcquireLicense
@ stub DRMActivate
@ stub DRMAddLicense
@ stub DRMAddRightWithUser
@ stub DRMAttest
@ stub DRMCheckSecurity
@ stub DRMClearAllRights
@ stub DRMCloseEnvironmentHandle
@ stub DRMCloseHandle
@ stub DRMClosePubHandle
@ stub DRMCloseQueryHandle
@ stub DRMCloseSession
@ stub DRMConstructCertificateChain
@ stub DRMCreateBoundLicense
@ stub DRMCreateClientSession
@ stub DRMCreateEnablingBitsDecryptor
@ stub DRMCreateEnablingBitsEncryptor
@ stub DRMCreateEnablingPrincipal
@ stub DRMCreateIssuanceLicense
@ stub DRMCreateLicenseStorageSession
@ stub DRMCreateRight
@ stub DRMCreateUser
@ stub DRMDecode
@ stub DRMDeconstructCertificateChain
@ stub DRMDecrypt
@ stub DRMDeleteLicense
@ stub DRMDuplicateEnvironmentHandle
@ stub DRMDuplicateHandle
@ stub DRMDuplicatePubHandle
@ stub DRMDuplicateSession
@ stub DRMEncode
@ stub DRMEncrypt
@ stub DRMEnumerateLicense
@ stub DRMGetApplicationSpecificData
@ stub DRMGetBoundLicenseAttribute
@ stub DRMGetBoundLicenseAttributeCount
@ stub DRMGetBoundLicenseObject
@ stub DRMGetBoundLicenseObjectCount
@ stub DRMGetCertificateChainCount
@ stub DRMGetClientVersion
@ stub DRMGetEnvironmentInfo
@ stub DRMGetInfo
@ stub DRMGetIntervalTime
@ stub DRMGetIssuanceLicenseInfo
@ stub DRMGetIssuanceLicenseTemplate
@ stub DRMGetMetaData
@ stub DRMGetNameAndDescription
@ stub DRMGetOwnerLicense
@ stub DRMGetProcAddress
@ stub DRMGetRevocationPoint
@ stub DRMGetRightExtendedInfo
@ stub DRMGetRightInfo
@ stub DRMGetSecurityProvider
@ stub DRMGetServiceLocation
@ stub DRMGetSignedIssuanceLicense
@ stub DRMGetSignedIssuanceLicenseEx
@ stub DRMGetTime
@ stub DRMGetUnboundLicenseAttribute
@ stub DRMGetUnboundLicenseAttributeCount
@ stub DRMGetUnboundLicenseObject
@ stub DRMGetUnboundLicenseObjectCount
@ stub DRMGetUsagePolicy
@ stub DRMGetUserInfo
@ stub DRMGetUserRights
@ stub DRMGetUsers
@ stub DRMInitEnvironment
@ stub DRMIsActivated
@ stub DRMIsWindowProtected
@ stub DRMLoadLibrary
@ stub DRMParseUnboundLicense
@ stdcall DRMRegisterContent(long)
@ stub DRMRegisterProtectedWindow
@ stub DRMRegisterRevocationList
@ stub DRMRepair
@ stub DRMSetApplicationSpecificData
@ stub DRMSetGlobalOptions
@ stub DRMSetIntervalTime
@ stub DRMSetMetaData
@ stub DRMSetNameAndDescription
@ stub DRMSetRevocationPoint
@ stub DRMSetUsagePolicy
@ stub DRMVerify
@ stdcall -private DllCanUnloadNow()
@ stub DllGetClassObject
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ stub __AddMachineCertToLicenseStore
