@ stdcall CreateIUriBuilder(ptr long long ptr)
@ stdcall CreateUri(wstr long long ptr)
@ stdcall CreateUriWithFragment(wstr wstr long long ptr)
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetActivationFactory(ptr ptr)
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall PrivateCoInternetCombineIUri(ptr ptr long ptr long)
@ stdcall PrivateCoInternetParseIUri(ptr long long ptr long ptr long)
@ stdcall wine_get_canonicalized_uri(ptr)
