@ stub -private DllCanUnloadNow
@ stdcall -private DllMain(long long ptr)
@ stub WIMApplyImage
@ stub WIMCaptureImage
@ stub WIMCloseHandle
@ stub WIMCommitImageHandle
@ stub WIMCopyFile
@ stub WIMCreateFile
@ stub WIMCreateImageFile
@ stub WIMDeleteImage
@ stub WIMDeleteImageMounts
@ stub WIMEnumImageFiles
@ stub WIMExportImage
@ stub WIMExtractImagePath
@ stub WIMFindFirstImageFile
@ stub WIMFindNextImageFile
@ stub WIMGetAttributes
@ stub WIMGetImageCount
@ stub WIMGetImageInformation
@ stub WIMGetMessageCallbackCount
@ stub WIMGetMountedImageHandle
@ stub WIMGetMountedImageInfo
@ stub WIMGetMountedImageInfoFromFile
@ stub WIMGetMountedImages
@ stub WIMInitFileIOCallbacks
@ stub WIMLoadImage
@ stub WIMMountImage
@ stub WIMMountImageHandle
@ stub WIMReadImageFile
@ stub WIMRegisterLogFile
@ stub WIMRegisterMessageCallback
@ stub WIMRemountImage
@ stub WIMSetBootImage
@ stub WIMSetFileIOCallbackTemporaryPath
@ stub WIMSetImageInformation
@ stub WIMSetReferenceFile
@ stub WIMSetTemporaryFile
@ stub WIMSplitFile
@ stub WIMUmountImage
@ stub WIMUmountImageHandle
@ stub WIMUnregisterLogFile
@ stub WIMUnregisterMessageCallback
