2 stub -noname SHGetAppKeyAssoc
3 stub -noname SHSetAppKeyWndAssoc
4 stub -noname SHSipInfo
5 stub -noname IsPhoneAppWindow
8 stub -noname SHImListPopup
9 stdcall SHInitExtraControls()
10 stub -noname SHCloseApps
11 stub -noname GetRegisteredAppInfo
12 stub -noname SetRegisteredAppInfo
13 stub -noname FreeRegisteredAppInfo
14 stub -noname Shell_HeapCreate
15 stub -noname Shell_Alloc
16 stub -noname Shell_Free
17 stub -noname Shell_AllocString
18 stub -noname Shell_CatStrAlloc
19 stub -noname Shell_LoadStringAlloc
20 stub -noname Shell_RegAllocString
21 stub -noname SHSipPreference
22 stub -noname SHAppNotifyDone
23 stub -noname ?PathFindExtension@@YAPAGPBG@Z
24 stdcall -noname PathAddBackslash(ptr) shell32.PathAddBackslash
25 stub -noname PathRemoveBackslash
26 stdcall -noname PathCombine(ptr ptr ptr) shell32.PathCombine
27 stdcall -noname PathFindFileName(ptr) shell32.PathFindFileName
28 stdcall -noname PathIsRelative(ptr) shell32.PathIsRelative
29 stub -noname ComboEditAutoComplete
30 stub -noname SHHandleSipChange
31 stub -noname SHHandleActivate
32 stub -noname SHMessageBox
33 stub -noname SHForceBaseState
34 stdcall  SHCreateMenuBar(ptr)
35 stub -noname SHCreateWorkerWindow
36 stub -noname SHCommandBar_GetCommandBarByID
37 stub -noname SHCommandBar_EnableCommand
38 stub -noname SHCommandBar_GetClientRect
39 stub -noname SHInputDialog
40 stdcall SHRecognizeGesture(ptr)
41 stub -noname SHCreateContextMenu
42 stdcall -noname PathRemoveBlanks(ptr) shell32.PathRemoveBlanks
43 stub -noname SHCreateMainWindow
44 stub -noname EditSubProc
45 stub -noname ComboSubProc
46 stub -noname ComboBoxEditSubProc
47 stub -noname SubClassThisWindow
48 stub -noname SHCheckForContextMenu
49 stub -noname SHEnableEditMenu
50 stub -noname SHRunCpl
51 stub -noname StrStrI
52 stub -noname CancelSIPUp
53 stub -noname SHCreateSystemFont
54 stdcall -noname SHFillRectClr(long ptr long) shlwapi.SHFillRectClr
55 stub -noname SHColorDisplay
56 stdcall SHInitDialog(ptr)
57 stub -noname SHTrackPopupMenu
58 stub -noname SHDrawUnderline
59 stdcall -noname SHSetWindowBits(long long long long) shlwapi.SHSetWindowBits
62 stub -noname IsSANMessage
63 stub -noname ?MinPowerOff@@YAHXZ
64 stub -noname SHLoadImageResource
65 stdcall SHFullScreen(ptr long)
66 stub -noname ?SHMenuBar_GetMenu@@YAPAUHMENU__@@PAUHWND__@@H@Z
67 stub -noname SHShowContextMenu
68 stub -noname SHAnimationSequenceIsAnimating
69 stub -noname SHDoneButton
70 stub -noname LFHeightForPoint
71 stub -noname SHFontMgrCreate
72 stub -noname SHFontMgrManageFonts
73 stub -noname SHFontMgrDestroy
74 stub -noname SHCreateMenuBarInternal
75 stub -noname SHLoadImageFile
76 stub -noname SHHdrGrpSepLineDraw
79 stub -noname SHSignalDone
80 stub -noname SHNewProfileObj
81 stub -noname SHEndProfileObj
82 stub -noname SHRunFontManager
83 stdcall SHHandleWMSettingChange(ptr long long ptr)
84 stub -noname SHHandleWMActivate
85 stub -noname SHStartIfNeeded
86 stub -noname SHClearStartedBit
87 stub -noname SHStartProfile
88 stub -noname SHSetNavBarText
89 stub -noname SHLoadFormattedImageFile
90 stub -noname SHGetAutoRunPath
91 stdcall -noname SHLoadMenuPopup(ptr wstr) shlwapi.SHLoadMenuPopup
92 stub -noname IsFullScreenWindow
93 stub -noname SHStartAndBlock
94 stub -noname SHIsPreRapierApp
95 stub -noname SHSavePWWarning
96 stub -noname SHGetDeviceFeatureLevel
97 stub -noname SHSendBackToFocusWindow
98 stub -noname SHEnumPropSheetHandlers
99 stub -noname SHForceBaseStateEx
100 stub -noname SHLoadContextMenuExtensions
101 stub -noname SHInvokeContextMenuCommand
102 stub -noname SHFreeContextMenuExtensions
103 stub -noname SHBoxEx
104 stub -noname SHBox
105 stub -noname SHTextBox
106 stub -noname PhoneGetCallPropertyBag
107 stub -noname PhoneGetCallProperties
108 stub -noname SHCreateNewItem
109 stub -noname SHDocManagerCreate
110 stub -noname SHDocManagerRegister
111 stub -noname SHDocManagerQuery
112 stub -noname SHDocManagerDestroy
113 stdcall -ordinal SHChangeNotifyRegister(long long long long long ptr) shell32.SHChangeNotifyRegister
114 stdcall -ordinal SHChangeNotifyDeregister(long) shell32.SHChangeNotifyDeregister
115 stub -noname SHChangeNotifyFree
116 stub -noname PathIsPrefix
117 stub -noname SHAnimateRects
118 stub -noname SHScanBuffer
119 stub -noname SHScanFile
120 stub -noname SHFreeScanners
121 stub -noname SHLock
122 stub -noname SHUnlock
123 stub -noname SHIsLocked
124 stub -noname SHWriteLockState
128 stub -noname SHGetEmergencyCallList
129 stub -noname SHInvalidateScreen
130 stub -noname SHBoldFontAllowed
131 stub -noname SHSetForegroundLastActivePopup
132 stub -noname SHFindForegroundMenuBar
133 stub -noname SHGetKOBits
134 stub -noname SHSetKOBits
135 stub -noname SHOnFullScreenAppActivate
136 stub -noname SHDrawUnderlineColor
137 stub -noname GetProtocol
138 stub -noname SHMakeCall
139 stub -noname DrawFocusRectColor
143 stub -noname AssociateNoteWithCall
144 stub -noname SHGetTimeFormat
145 stub -noname ?GetStandardFont@@YAJW4eFontID@@PAPAUHFONT__@@@Z
146 stub -noname ?ClearFontManager@@YAXXZ
147 stub -noname ?OnSettingChange@@YAHIJ@Z
148 stub -noname ?GetAppMetric@@YAHW4_enAppMetricID@@@Z
149 stub -noname SHInitPresetMessages
150 stub -noname SHReleasePresetMessages
151 stub -noname SHRunPresetMessagesEdit
152 stub -noname SHPopulatePresetMessageMenu
153 stub -noname SHGetPresetMessage
154 stub -noname SHSetPresetMessage
155 stub -noname SHNotificationAdd
156 stub -noname SHNotificationUpdate
157 stub -noname SHNotificationRemove
158 stub -noname SHAnimateListviewOpen
160 stub -noname PathFindNextComponent
161 stub -noname SHSetBubbleRegion
162 stub -noname SHPaintBubbleFrame
163 stub -noname SHGetPowerOnTime
164 stub -noname SHCreateCOleWindow
165 stub -noname SHNotifyAppsOnDock
166 stub -noname ?CreateBackgroundSpec@@YAJPAPAVIBackgroundSpec@@@Z
167 stub -noname SHGetMessageBoxIcon
168 stub -noname SHFadeImage
169 stub -noname SHSetAsWatermark
170 stub -noname SHSetSimToolkitMenu
171 stub -noname SHToolkitQueryShell
172 stub -noname SHGetNavBarItemRect
173 stub -noname SHNotificationGetData
174 stub -noname SHSameWindowProcesses
175 stub -noname SHPreProcessLogFont
176 stub -noname SHRegSetValueEx
177 stub -noname SHGetStyleBkColor
178 stub -noname SHGetStyleColor
179 stub -noname SHGetStyleFont
180 stub -noname NotifyAppsOnEvent
181 stub -noname SHInsertPresetMessage
182 stub -noname SHHandleHotkey
183 stub -noname SHNavigateBack
184 stub -noname SHSetBack
188 stub -noname SHFindMenuBar
189 stub -noname ?SHDrawGradientBubbleTitle@@YAXPAUtagGRADIENTTITLEINFO@@@Z
190 stub -noname CreateImageCache
191 stub -noname DrawAlignedIcon
192 stub -noname SHEnableRadio
193 stub -noname SHKeyToVerb
194 stub -noname SHProcessVerb
195 stub -noname SHNotifyAppsOnHeadset
196 stub -noname TZFindOpen
197 stub -noname TZFindNext
198 stub -noname TZGetData
199 stub -noname TZFindClose
201 stub -noname SHEscapeBubbleHtml
202 stub -noname SHOriginalClassNameFromATL
203 stub -noname SHEscapeAccelerators
204 stub -noname SHGetSimToolkitMenu
205 stub -noname SHSoundManGetDisplayNameList
206 stub -noname SHSoundManGetFileName
207 stub -noname SHSoundManGetDisplayName
208 stub -noname SHNotifyAppsOnCallConnect
209 stub -noname SHFindPreviousInstance
210 stub -noname SHNotifyAppsOnCarkit
211 stub -noname SHNotifyAppsOnSpeakerPhone
212 stub -noname SHFindPreviousInstanceEx
213 stub -noname SHGetLastActiveWindow
214 stub -noname SHNotifyAppsOnIncomingCall
215 stub -noname SHRegGetHLMDWValue
216 stub -noname SHLoadSKFromReg
217 stub -noname SHGetSystemDefaultLCID
218 stub -noname SHGetFontHeight
219 stub -noname SHGetUiInfo
220 stub -noname SHGradientInit
221 stub -noname SHGradientDeInit
222 stub -noname SHGradientDraw
223 stub -noname SHCopyBitmap
224 stub -noname SHGetCarrierBrandingFlag
225 stub -noname SHGetCarrierBranding
226 stub -noname DoEditContextMenu
227 stub -noname SHOnVoiceMailCountChange
228 stub -noname SHLoadMenuExtensions
229 stub -noname SHQueryMenuExtensions
230 stub -noname SHLoadFileContextMenuExtensions
231 stub -noname SHSetInputContext
232 stub -noname SHGetInputContext
233 stub -noname SHDrawBranding
234 stub -noname SHDrawClippedText
235 stub -noname SHMakeValidFilename
236 stub -noname VerifyTrust
237 stub -noname DisplayNotRunnableAppDialog
238 stub -noname SHOnMissedCallCountChange
239 stub -noname SHRunSafeApplet
240 stub -noname SHUnEscapeAccelerators
241 stub -noname LoadStringEtcOver
242 stub -noname SHGetLocaleInfo
243 stub -noname SHLucySendMsg
244 stub -noname SHLucyGetTestMode
245 stub -noname SHResizeDialogProc
246 stub -noname ?Dbg_DumpMenu@@YAXPBGPAUHMENU__@@@Z
247 stub -noname ?Dbg_DumpGUID@@YAXPAGABU_GUID@@@Z
248 stub -noname ?Dbg_MaskToMneStr@@YAPAGIPAG@Z
249 stub -noname GetMenuItemCountEM
250 stub -noname GetMenuItemIDEM
251 stub -noname GetMenuStateEM
252 stub -noname InsertMenuItemEM
253 stub -noname RegOpenKeyEM
254 stub -noname RegQueryValueEM
255 stub -noname CreateFontVariant
256 stub -noname SHGUIDFromStringW
257 stdcall -ordinal IUnknown_Set(ptr ptr) shlwapi.IUnknown_Set
258 stdcall -noname IUnknown_SetOwner(ptr ptr) shlwapi.IUnknown_SetOwner
259 stub -noname IUnknown_GetObjectOfPDP
260 stub -noname InitializeKH
261 stub -noname TranslateMessageKH
262 stub -noname SetKeyHoldableKH
263 stdcall -ordinal Shell_MergeMenus(long long long long long long) shell32.Shell_MergeMenus
264 stub -noname Shell_UnMergeMenus
266 stub -noname SHFixMenuIndex
267 stub -noname SHGetMenuItemData
268 stub -noname SHSetMenuItemData
269 stub -noname SHOnSAN_NOTIFY
270 stub -noname SHCleanMenu
271 stub -noname GetNextSpan
272 stub -noname GetAppHWND
273 stub -noname ClearAppHWND
274 stub -noname SetForegroundApp
275 stub -noname SHSubclassWindow
276 stub -noname SHDialogAutoClose
277 stub -noname SHSendShellMessage
278 stub -noname SHGetShellWindow
279 stub -noname HomeHideOwnedWindows
280 stub -noname SHMapCallerPtrArray
281 stub -noname SHGetMetric
282 stub -noname SHGetScreenOrientation
283 stub -noname SHFindMenuBarInternal
284 stub -noname SHStretchBitmap
285 stub -noname SHGetBitmapLogPixels
286 stub -noname HIDPI_ImageList_LoadImage
287 stub -noname HIDPI_ImageList_ReplaceIcon
288 stub -noname SHBorderRectangle
289 stub -noname SHBorderPolyline
290 stub -noname SHStretchBltBitmap
291 stub -noname SHStretchBltBitmapEx
292 stub -noname SHGetDPISpecificRegKey
293 stub -noname SHRectangle
294 stub -noname SHPolyline
295 stub -noname SHIsPreOzoneUpdate
296 stub -noname SetWindowPosOnRotate
297 stub -noname SHRCMLDialogProc
298 stub -noname SHSetDisplayRotation
299 stub -noname SHGetDisplayRotation
300 stub -noname SHSetStretchMode
301 stub -noname SetDialogAutoScrollBar
304 stub -noname SHRegGetHKCUDWValue
305 stub -noname SHGetLandscapeRotationSettings
306 stub -noname SHCopyIcon
307 stub -noname SHStretchIcon
308 stub -noname SHSkipDialogInitialFocus
310 stub -noname DPI_LoadLibraryRes
311 stub -noname DPI_LoadImageFile
312 stub -noname SHGetUIMetrics
313 stub -noname SHLoadFontFromResource
314 stub -noname SHSipMightBlockUI
315 stdcall -noname DelMRUString(long long) comctl32.DelMRUString
316 stdcall -noname CreateMRUListA(ptr) comctl32.CreateMRUListA
317 stdcall -ordinal CreateMRUListW(ptr) comctl32.CreateMRUListW
318 stdcall -noname FreeMRUList(long) comctl32.FreeMRUList
319 stdcall -noname AddMRUStringA(long str) comctl32.AddMRUStringA
320 stdcall -ordinal AddMRUStringW(long wstr) comctl32.AddMRUStringW
321 stdcall -noname FindMRUStringA(long str ptr) comctl32.FindMRUStringA
322 stdcall -noname FindMRUStringW(long wstr ptr) comctl32.FindMRUStringW
323 stdcall -noname EnumMRUListA(long long ptr long) comctl32.EnumMRUListA
324 stdcall -ordinal EnumMRUListW(long long ptr long) comctl32.EnumMRUListW
325 stdcall -noname AddMRUData(long ptr long) comctl32.AddMRUData
326 stdcall -noname FindMRUData(long ptr long ptr) comctl32.FindMRUData
327 stub -noname PopulateComboWithMRU
328 stub -noname PopulateMenuWithMRU
329 stub -noname SHDeleteTodayWallpaper
330 stub -noname DPI_ExtractIconEx
331 stub -noname SHDrawTextOverImage
332 stub -noname SHEnableSoftkey
333 stub -noname RegistryGetDWORD
334 stub -noname RegistryGetString
335 stub -noname RegistrySetDWORD
336 stub -noname RegistrySetString
337 stub -noname RegistryTestExchangeDWORD
338 stub -noname RegistryNotifyApp
339 stub -noname RegistryNotifyWindow
340 stub -noname RegistryNotifyMsgQueue
341 stub -noname RegistryCloseNotification
342 stub -noname RegistryStopNotification
343 stub -noname RegistryBatchNotification
344 stub -noname RegistryNotifyCallback
345 stub -noname SHGetLegacySupportWindow
346 stub -noname SHReleaseLegacySupportWindow
347 stub -noname IsModulePreWinCE421
348 stub -noname SHInitDialerClass
349 stub -noname SHAppendAutorunPath
350 stub -noname FileDrmIsDRM
351 stub -noname FileDrmCreateFile
352 stub -noname FileDrmCreateForwardableContent
353 stub -noname FileDrmNotifyEnable
354 stub -noname FileDrmNotifyDisable
355 stub -noname FileDrmShowLicenseInfo
356 stub -noname FileDrmHandleError
357 stub -noname FileDrmRenewRights
358 stub -noname FileDrmGetMetric
359 stub -noname FileDrmVerifyRights
360 stub -noname FileDrmCommitRights
361 stub -noname FileDrmDeleteFile
362 stub -noname FileDrmStoreContent
363 stub -noname ?IsScreenRotationSupported@@YAHXZ
364 stub -noname QueryPolicy
365 stub -noname ?SKDrawGradientBackgroundEx@@YAXPAUHDC__@@UtagRECT@@HHHH@Z
366 stub -noname CheckPhoneFeatureLevel
367 stub -noname SHLoadHelperObject
368 stub -noname SHDrawMultipleGradientBackground
369 stub -noname SHGetGradientColor
370 stub -noname SHDrawMultipleGradient
371 stub -noname SHUpdateSysColors
372 stub -noname ActiveSyncStart
373 stub -noname ActiveSyncStop
374 stub -noname SHVerifyBackgroundImageRights
375 stub -noname SHAnimationSequenceInit
376 stub -noname SHAnimationSequenceFree
377 stub -noname SHAnimationSequenceLaunch
378 stub -noname SHAnimationSequenceHandleTimer
379 stub -noname SHAnimationSequenceHalt
380 stub -noname OnDefTalkButton
381 stub -noname PopulateAndLaunchDialer
382 stub -noname SHUpdateBaseHue
383 stub -noname SHDrawIconEx
384 stub -noname SHDrawIcon
385 stub -noname SHDrawIconColor
386 stub -noname FileDrmVerifyRightsEx
387 stub -noname SndGetSoundDirectoriesList
388 stub -noname SndGetSoundFileList
389 stub -noname SndSetSound
390 stub -noname SndGetSound
391 stub -noname LoadStringEtcOverNoCache
392 stub -noname SHCameraCapture
393 stub -noname SHVerifyEventSoundRights
394 stub -noname SHTranslateQwertyToPhone
395 stub -noname ?SndSetSoundI@@YAJW4tagSND_EVENT@@PBUtagSNDFILEINFO@@HK@Z
423 stub -noname RegistryDeleteValue
1000 stub -noname SHTurnScreenOn
1003 stub -noname SHSetSoftKey
1004 stub -noname SHShowSoftKeys
1005 stub -noname UIHGetTextToStruct
1006 stub -noname UIHSetTextFromStruct
1007 stub -noname UIHLimitTextControls
1008 stub -noname UIHSetHWNDToStruct
2000 stub -noname SHVoiceTagTrain
2001 stub -noname SHVoiceTagRecognize
2002 stub -noname SHVoiceTagPlayback
2003 stub -noname SHVoiceTagDelete
2004 stub -noname ?SHGetStartMRU@@YAJPAPAVIStartMRU@@@Z
2005 stub -noname ?SHStartMRUHookProc@@YAXPBU_SHELLEXECUTEINFO@@@Z
2006 stub -noname SHIdleTimerReset
2007 stub -noname ?SHCreateBannerDisplay@@YAJPAPAVIBannerDisplay@@@Z
2008 stub -noname SHOnPluginDataChange
2009 stub -noname ?RegisterBackgroundControl@@YAJPAUHINSTANCE__@@@Z
2010 stub -noname ?AMIgnoreMetricChanges@@YAXXZ
2011 stdcall ExitWindowsEx(long long) user32.ExitWindowsEx
2012 stub -noname ?STHStreamBackgroundSpec@@YAJKPAUIStream@@PAXJPAI@Z
2013 stub -noname SHEnumFiles
2014 stub -noname SHGetSoundFileList
2015 stub -noname ?Vibrate@@YAJKPBUVIBRATENOTE@@HK@Z
2016 stub -noname ?VibrateStop@@YAJXZ
2017 stub -noname ?VibrateGetDeviceCaps@@YAHW4VIBRATEDEVICECAPS@@@Z
2018 stub -noname SHShowSimToolkitUI
2019 stub -noname VerifyFileTrust
2020 stub -noname SHEnumFolders
2021 stub -noname DMProcessConfigXML
2022 stub -noname SHRefreshStartMenu
2023 stub -noname SHGetDeviceStateInfo
2024 stub -noname ?SystemStatusDisplay_Create@@YAJKKHPAPAX@Z
2025 stub -noname ?SystemStatusDisplay_Destroy@@YAJPAX@Z
2026 stub -noname ?SystemStatusDisplay_SetAppType@@YAJPAXW4_SSDAPPTYPE@@PAIPAPBK@Z
2027 stub -noname ?SystemStatusDisplay_GetWidth@@YAJPAXIPBU_CEPROPVAL@@PAH@Z
2028 stub -noname ?SystemStatusDisplay_Draw@@YAJPAXPAUHDC__@@PBUtagRECT@@IPBU_CEPROPVAL@@K@Z
2029 stub -noname ?SystemStatusDisplay_LoadIconCache@@YAJPAXIPBU_CEPROPVAL@@K@Z
2030 stub -noname ?SystemStatusDisplay_ColorChange@@YAJPAXKK@Z
2031 stub -noname ?SystemStatusDisplay_GetBlinkRequirements@@YAJPAXIPBU_CEPROPVAL@@PAH@Z
2032 stub -noname SHCHGetCOLORREF
2033 stub -noname SHCHSetColorFromAttribute
2034 stub -noname SHCHSetColorFromString
2035 stub -noname SHImeOnKeyPress
2037 stub -noname SHImeGetClearMessage
2038 stub -noname SHImeSetModeIcon
2039 stub -noname SHImeSetCustomInputIcons
2040 stub -noname ?SystemStatusDisplay_SetCustomInputIcons@@YAJPAXPAUHBITMAP__@@@Z
2042 stub -noname GetOpenFileNameEx
2043 stub -noname SHGetSaveFileName
2044 stub -noname CalendarNewAppointment
2045 stub -noname ContactsNewContact
