#OpenAL ALC_1_0
@ stub alcCreateContext
@ stub alcMakeContextCurrent
@ stub alcProcessContext
@ stub alcSuspendContext
@ stub alcDestroyContext
@ stub alcGetCurrentContext
@ stub alcGetContextsDevice
@ stub alcOpenDevice
@ stub alcCloseDevice
@ stub alcGetError
@ stub alcIsExtensionPresent
@ stub alcGetProcAddress
@ stub alcGetEnumValue
@ stub alcGetString
@ stub alcGetIntegerv
#OpenAL AL_1_0
@ stub alEnable
@ stub alDisable
@ stub alIsEnabled
@ stub alGetString
@ stub alGetBooleanv
@ stub alGetIntegerv
@ stub alGetFloatv
@ stub alGetDoublev
@ stub alGetBoolean
@ stub alGetInteger
@ stub alGetFloat
@ stub alGetDouble
@ stub alGetError
@ stub alIsExtensionPresent
@ stub alGetProcAddress
@ stub alGetEnumValue
@ stub alListenerf
@ stub alListener3f
@ stub alListenerfv
@ stub alListeneri
@ stub alGetListenerf
@ stub alGetListener3f
@ stub alGetListenerfv
@ stub alGetListeneri
@ stub alGetListeneriv
@ stub alGenSources
@ stub alDeleteSources
@ stub alIsSource
@ stub alSourcef
@ stub alSource3f
@ stub alSourcefv
@ stub alSourcei
@ stub alGetSourcef
@ stub alGetSource3f
@ stub alGetSourcefv
@ stub alGetSourcei
@ stub alGetSourceiv
@ stub alSourcePlayv
@ stub alSourceStopv
@ stub alSourceRewindv
@ stub alSourcePausev
@ stub alSourcePlay
@ stub alSourceStop
@ stub alSourceRewind
@ stub alSourcePause
@ stub alSourceQueueBuffers
@ stub alSourceUnqueueBuffers
@ stub alGenBuffers
@ stub alDeleteBuffers
@ stub alIsBuffer
@ stub alBufferData
@ stub alGetBufferf
@ stub alGetBufferfv
@ stub alGetBufferi
@ stub alGetBufferiv
@ stub alDopplerFactor
@ stub alDopplerVelocity
@ stub alDistanceModel
#OpenAL ALC_1_1
@ stub alcCaptureOpenDevice
@ stub alcCaptureCloseDevice
@ stub alcCaptureStart
@ stub alcCaptureStop
@ stub alcCaptureSamples
#OpenAL AL_1_1
@ stub alListener3i
@ stub alListeneriv
@ stub alGetListener3i
@ stub alSource3i
@ stub alSourceiv
@ stub alGetSource3i
@ stub alBufferf
@ stub alBuffer3f
@ stub alBufferfv
@ stub alBufferi
@ stub alBuffer3i
@ stub alBufferiv
@ stub alGetBuffer3f
@ stub alGetBuffer3i
@ stub alSpeedOfSound
