@ stub PerfAddCounters
@ stub PerfCloseQueryHandle
@ stub PerfDeleteCounters
@ stub PerfEnumerateCounterSet
@ stub PerfEnumerateCounterSetInstances
@ stub PerfOpenQueryHandle
@ stub PerfQueryCounterData
@ stub PerfQueryCounterInfo
@ stub PerfQueryCounterSetRegistrationInfo
