@ stub AppendPropVariant
@ stub ConvertPropVariant
@ stub CopyPropertyStore
@ stub CreateNamedPropertyStore
@ stub DllCanUnloadNow
@ stub DllGetClassObject
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub ExtractPropVariant
@ stub MFCreate3GPMediaSink
@ stub MFCreateASFByteStreamPlugin
@ stub MFCreateASFContentInfo
@ stub MFCreateASFIndexer
@ stub MFCreateASFIndexerByteStream
@ stub MFCreateASFMediaSink
@ stub MFCreateASFMediaSinkActivate
@ stub MFCreateASFMultiplexer
@ stub MFCreateASFProfile
@ stub MFCreateASFProfileFromPresentationDescriptor
@ stub MFCreateASFSplitter
@ stub MFCreateASFStreamSelector
@ stub MFCreateASFStreamingMediaSink
@ stub MFCreateASFStreamingMediaSinkActivate
@ stub MFCreateAggregateSource
@ stub MFCreateAppSourceProxy
@ stub MFCreateAudioRenderer
@ stub MFCreateAudioRendererActivate
@ stub MFCreateByteCacheFile
@ stub MFCreateCacheManager
@ stub MFCreateCredentialCache
@ stub MFCreateDeviceSource
@ stub MFCreateDeviceSourceActivate
@ stub MFCreateDrmNetNDSchemePlugin
@ stub MFCreateFileBlockMap
@ stub MFCreateFileSchemePlugin
@ stub MFCreateHttpSchemePlugin
@ stub MFCreateLPCMByteStreamPlugin
@ stub MFCreateMP3ByteStreamPlugin
@ stub MFCreateMP3MediaSink
@ stub MFCreateMPEG4MediaSink
@ stub MFCreateMediaProcessor
@ stdcall MFCreateMediaSession(ptr ptr)
@ stub MFCreateNSCByteStreamPlugin
@ stub MFCreateNetSchemePlugin
@ stub MFCreatePMPHost
@ stub MFCreatePMPMediaSession
@ stub MFCreatePMPServer
@ stub MFCreatePresentationClock
@ stub MFCreatePresentationDescriptorFromASFProfile
@ stub MFCreateProxyLocator
@ stub MFCreateRemoteDesktopPlugin
@ stub MFCreateSAMIByteStreamPlugin
@ stub MFCreateSampleCopierMFT
@ stub MFCreateSampleGrabberSinkActivate
@ stub MFCreateSecureHttpSchemePlugin
@ stub MFCreateSequencerSegmentOffset
@ stub MFCreateSequencerSource
@ stub MFCreateSequencerSourceRemoteStream
@ stub MFCreateSimpleTypeHandler
@ stdcall MFCreateSourceResolver(ptr) mfplat.MFCreateSourceResolver
@ stub MFCreateStandardQualityManager
@ stub MFCreateTopoLoader
@ stdcall MFCreateTopology(ptr)
@ stub MFCreateTopologyNode
@ stub MFCreateTranscodeProfile
@ stub MFCreateTranscodeSinkActivate
@ stub MFCreateTranscodeTopology
@ stub MFCreateUrlmonSchemePlugin
@ stub MFCreateVideoRenderer
@ stub MFCreateVideoRendererActivate
@ stub MFCreateWMAEncoderActivate
@ stub MFCreateWMVEncoderActivate
@ stub MFEnumDeviceSources
@ stub MFGetMultipleServiceProviders
@ stdcall MFGetService(ptr ptr ptr ptr)
@ stdcall MFGetSupportedMimeTypes(ptr)
@ stub MFGetSupportedSchemes
@ stub MFGetTopoNodeCurrentType
@ stub MFReadSequencerSegmentOffset
@ stub MFRequireProtectedEnvironment
@ stub MFShutdownObject
@ stub MFTranscodeGetAudioOutputAvailableTypes
@ stub MergePropertyStore
