@ stub DMOEnum
@ stub DMOGetName
@ stub DMOGetTypes
@ stub DMOGuidToStrA
@ stub DMOGuidToStrW
@ stub DMORegister
@ stub DMOStrToGuidA
@ stub DMOStrToGuidW
@ stub DMOUnregister
@ stub MoCopyMediaType
@ stub MoCreateMediaType
@ stub MoDeleteMediaType
@ stub MoDuplicateMediaType
@ stub MoFreeMediaType
@ stub MoInitMediaType
