/*
 * Copyright (C) 2019 Zebediah Figura
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

#include "dmodshow.idl"

[
    threading(both),
    uuid(94297043-bd82-4dfd-b0de-8177739c6d20),
]
coclass DMOWrapperFilter {}

[
    helpstring("WM ASF Reader"),
    threading(both),
    uuid(187463a0-5bb7-11d3-acbe-0080c75e246e),
]
coclass WMAsfReader {}
