@ stub FwpmCalloutAdd0
@ stub FwpmCalloutCreateEnumHandle0
@ stub FwpmCalloutDeleteById0
@ stub FwpmCalloutDeleteByKey0
@ stub FwpmCalloutDestroyEnumHandle0
@ stub FwpmCalloutEnum0
@ stub FwpmCalloutGetById0
@ stub FwpmCalloutGetByKey0
@ stub FwpmCalloutGetSecurityInfoByKey0
@ stub FwpmCalloutSetSecurityInfoByKey0
@ stub FwpmCalloutSubscribeChanges0
@ stub FwpmCalloutSubscriptionsGet0
@ stub FwpmCalloutUnsubscribeChanges0
@ stub FwpmDiagnoseNetFailure0
@ stdcall FwpmEngineClose0(ptr)
@ stub FwpmEngineGetOption0
@ stub FwpmEngineGetSecurityInfo0
@ stdcall FwpmEngineOpen0(wstr long ptr ptr ptr)
@ stub FwpmEngineSetOption0
@ stub FwpmEngineSetSecurityInfo0
@ stub FwpmEventProviderCreate0
@ stub FwpmEventProviderDestroy0
@ stub FwpmEventProviderFireNetEvent0
@ stub FwpmEventProviderIsNetEventTypeEnabled0
@ stdcall FwpmFilterAdd0(ptr ptr ptr ptr)
@ stdcall FwpmFilterCreateEnumHandle0(ptr ptr ptr)
@ stub FwpmFilterDeleteById0
@ stub FwpmFilterDeleteByKey0
@ stdcall FwpmFilterDestroyEnumHandle0(ptr ptr)
@ stdcall FwpmFilterEnum0(ptr ptr long ptr ptr)
@ stub FwpmFilterGetById0
@ stub FwpmFilterGetByKey0
@ stub FwpmFilterGetSecurityInfoByKey0
@ stub FwpmFilterSetSecurityInfoByKey0
@ stub FwpmFilterSubscribeChanges0
@ stub FwpmFilterSubscriptionsGet0
@ stub FwpmFilterUnsubscribeChanges0
@ stdcall FwpmFreeMemory0(ptr)
@ stub FwpmGetAppIdFromFileName0
@ stub FwpmIPsecTunnelAdd0
@ stub FwpmIPsecTunnelDeleteByKey0
@ stub FwpmLayerCreateEnumHandle0
@ stub FwpmLayerDestroyEnumHandle0
@ stub FwpmLayerEnum0
@ stub FwpmLayerGetById0
@ stub FwpmLayerGetByKey0
@ stub FwpmLayerGetSecurityInfoByKey0
@ stub FwpmLayerSetSecurityInfoByKey0
@ stub FwpmNetEventCreateEnumHandle0
@ stub FwpmNetEventDestroyEnumHandle0
@ stub FwpmNetEventEnum0
@ stub FwpmNetEventsGetSecurityInfo0
@ stub FwpmNetEventsSetSecurityInfo0
@ stub FwpmProviderAdd0
@ stub FwpmProviderContextAdd0
@ stub FwpmProviderContextCreateEnumHandle0
@ stub FwpmProviderContextDeleteById0
@ stub FwpmProviderContextDeleteByKey0
@ stub FwpmProviderContextDestroyEnumHandle0
@ stub FwpmProviderContextEnum0
@ stub FwpmProviderContextGetById0
@ stub FwpmProviderContextGetByKey0
@ stub FwpmProviderContextGetSecurityInfoByKey0
@ stub FwpmProviderContextSetSecurityInfoByKey0
@ stub FwpmProviderContextSubscribeChanges0
@ stub FwpmProviderContextSubscriptionsGet0
@ stub FwpmProviderContextUnsubscribeChanges0
@ stub FwpmProviderCreateEnumHandle0
@ stub FwpmProviderDeleteByKey0
@ stub FwpmProviderDestroyEnumHandle0
@ stub FwpmProviderEnum0
@ stub FwpmProviderGetByKey0
@ stub FwpmProviderGetSecurityInfoByKey0
@ stub FwpmProviderSetSecurityInfoByKey0
@ stub FwpmProviderSubscribeChanges0
@ stub FwpmProviderSubscriptionsGet0
@ stub FwpmProviderUnsubscribeChanges0
@ stub FwpmSessionCreateEnumHandle0
@ stub FwpmSessionDestroyEnumHandle0
@ stub FwpmSessionEnum0
@ stdcall FwpmSubLayerAdd0(ptr ptr ptr)
@ stub FwpmSubLayerCreateEnumHandle0
@ stub FwpmSubLayerDeleteByKey0
@ stub FwpmSubLayerDestroyEnumHandle0
@ stub FwpmSubLayerEnum0
@ stdcall FwpmSubLayerGetByKey0(ptr ptr ptr)
@ stub FwpmSubLayerGetSecurityInfoByKey0
@ stub FwpmSubLayerSetSecurityInfoByKey0
@ stub FwpmSubLayerSubscribeChanges0
@ stub FwpmSubLayerSubscriptionsGet0
@ stub FwpmSubLayerUnsubscribeChanges0
@ stub FwpmTraceRestoreDefaults0
@ stub FwpmTransactionAbort0
@ stub FwpmTransactionBegin0
@ stub FwpmTransactionCommit0
@ stub FwpsAleExplicitCredentialsQuery0
@ stub FwpsClassifyUser0
@ stub FwpsFreeMemory0
@ stub FwpsGetInProcReplicaOffset0
@ stub FwpsLayerCreateInProcReplica0
@ stub FwpsLayerReleaseInProcReplica0
@ stub FwpsOpenToken0
@ stub IPsecGetStatistics0
@ stub IPsecKeyModuleAdd0
@ stub IPsecKeyModuleCompleteAcquire0
@ stub IPsecKeyModuleDelete0
@ stub IPsecSaContextAddInbound0
@ stub IPsecSaContextAddOutbound0
@ stub IPsecSaContextCreate0
@ stub IPsecSaContextCreateEnumHandle0
@ stub IPsecSaContextDeleteById0
@ stub IPsecSaContextDestroyEnumHandle0
@ stub IPsecSaContextEnum0
@ stub IPsecSaContextExpire0
@ stub IPsecSaContextGetById0
@ stub IPsecSaContextGetSpi0
@ stub IPsecSaCreateEnumHandle0
@ stub IPsecSaDbGetSecurityInfo0
@ stub IPsecSaDbSetSecurityInfo0
@ stub IPsecSaDestroyEnumHandle0
@ stub IPsecSaEnum0
@ stub IPsecSaInitiateAsync0
@ stub IkeextGetConfigParameters0
@ stub IkeextGetStatistics0
@ stub IkeextSaCreateEnumHandle0
@ stub IkeextSaDbGetSecurityInfo0
@ stub IkeextSaDbSetSecurityInfo0
@ stub IkeextSaDeleteById0
@ stub IkeextSaDestroyEnumHandle0
@ stub IkeextSaEnum0
@ stub IkeextSaGetById0
@ stub IkeextSetConfigParameters0
@ stub WSADeleteSocketPeerTargetName
@ stub WSAImpersonateSocketPeer
@ stub WSAQuerySocketSecurity
@ stub WSARevertImpersonation
@ stub WSASetSocketPeerTargetName
@ stub WSASetSocketSecurity
@ stub WfpClearIpsecProposal
@ stub WfpFillIkeProposal
@ stub WfpFillIpsecProposal
@ stub WfpFilterListDestroy
@ stub WfpFilterListIpsecTransportV4Create
@ stub WfpFilterListIpsecTransportV6Create
@ stub WfpGetV4TransportSaSelectors
@ stub wfpdiagW
