@ stub Dhcpv6AcquireParameters
@ stub Dhcpv6CApiCleanup
@ stub Dhcpv6CApiInitialize
@ stub Dhcpv6CancelOperation
@ stub Dhcpv6EnableDhcp
@ stub Dhcpv6EnableTracing
@ stub Dhcpv6FreeLeaseInfo
@ stub Dhcpv6FreeLeaseInfoArray
@ stub Dhcpv6GetTraceArray
@ stub Dhcpv6GetUserClasses
@ stub Dhcpv6IsEnabled
@ stub Dhcpv6QueryLeaseInfo
@ stub Dhcpv6QueryLeaseInfoArray
@ stub Dhcpv6ReleaseParameters
@ stub Dhcpv6ReleasePrefix
@ stub Dhcpv6ReleasePrefixEx
@ stub Dhcpv6RenewPrefix
@ stub Dhcpv6RenewPrefixEx
@ stub Dhcpv6RequestParams
@ stub Dhcpv6RequestPrefix
@ stub Dhcpv6RequestPrefixEx
@ stub Dhcpv6SetUserClass
