@ stub DhcpAcquireParameters
@ stub DhcpAcquireParametersByBroadcast
@ stdcall DhcpCApiCleanup()
@ stdcall DhcpCApiInitialize(ptr)
@ stub DhcpDeRegisterConnectionStateNotification
@ stub DhcpDeRegisterOptions
@ stub DhcpDeRegisterParamChange
@ stub DhcpDelPersistentRequestParams
@ stub DhcpEnumClasses
@ stub DhcpFallbackRefreshParams
@ stub DhcpFreeMem
@ stub DhcpGetDhcpServicedConnctions
@ stub DhcpGetNotificationStatus
@ stub DhcpHandlePnPEvent
@ stub DhcpLeaseIpAddress
@ stub DhcpLeaseIpAddressEx
@ stub DhcpNotifyConfigChange
@ stub DhcpNotifyConfigChangeEx
@ stub DhcpNotifyMediaReconnected
@ stub DhcpOpenGlobalEvent
@ stub DhcpPersistentRequestParams
@ stub DhcpQueryHWInfo
@ stub DhcpRegisterConnectionStateNotification
@ stub DhcpRegisterOptions
@ stub DhcpRegisterParamChange
@ stub DhcpReleaseIpAddressLease
@ stub DhcpReleaseIpAddressLeaseEx
@ stub DhcpReleaseParameters
@ stub DhcpRemoveDNSRegistration
@ stub DhcpRenewIpAddressLease
@ stub DhcpRenewIpAddressLeaseEx
@ stub DhcpRequestCachedParams
@ stub DhcpRequestOptions
@ stdcall DhcpRequestParams(long ptr wstr ptr int64 int64 ptr ptr wstr)
@ stub DhcpSetMSFTVendorSpecificOptions
@ stub DhcpStaticRefreshParams
@ stub DhcpUndoRequestParams
@ stub McastApiCleanup
@ stub McastApiStartup
@ stub McastEnumerateScopes
@ stub McastGenUID
@ stub McastReleaseAddress
@ stub McastRenewAddress
@ stub McastRequestAddress
@ stub ServiceMain
