@ stub ATMAddFont
@ stub ATMAddFontA
@ stub ATMAddFontEx
@ stub ATMAddFontExA
@ stub ATMAddFontExW
@ stub ATMAddFontW
@ stub ATMBBoxBaseXYShowText
@ stub ATMBBoxBaseXYShowTextA
@ stub ATMBBoxBaseXYShowTextW
@ stub ATMBeginFontChange
@ stub ATMClient
@ stub ATMEndFontChange
@ stub ATMEnumFonts
@ stub ATMEnumFontsA
@ stub ATMEnumFontsW
@ stub ATMEnumMMFonts
@ stub ATMEnumMMFontsA
@ stub ATMEnumMMFontsW
@ stdcall ATMFinish()
@ stub ATMFontAvailable
@ stub ATMFontAvailableA
@ stub ATMFontAvailableW
@ stub ATMFontSelected
@ stub ATMFontStatus
@ stub ATMFontStatusA
@ stub ATMFontStatusW
@ stub ATMForceFontChange
@ stub ATMGetBuildStr
@ stub ATMGetBuildStrA
@ stub ATMGetBuildStrW
@ stub ATMGetFontBBox
@ stub ATMGetFontInfo
@ stub ATMGetFontInfoA
@ stub ATMGetFontInfoW
@ stub ATMGetFontPaths
@ stub ATMGetFontPathsA
@ stub ATMGetFontPathsW
@ stub ATMGetGlyphList
@ stub ATMGetGlyphListA
@ stub ATMGetGlyphListW
@ stub ATMGetMenuName
@ stub ATMGetMenuNameA
@ stub ATMGetMenuNameW
@ stub ATMGetNtmFields
@ stub ATMGetNtmFieldsA
@ stub ATMGetNtmFieldsW
@ stub ATMGetOutline
@ stub ATMGetOutlineA
@ stub ATMGetOutlineW
@ stub ATMGetPostScriptName
@ stub ATMGetPostScriptNameA
@ stub ATMGetPostScriptNameW
@ stub ATMGetVersion
@ stub ATMGetVersionEx
@ stub ATMGetVersionExA
@ stub ATMGetVersionExW
@ stub ATMInstallSubstFontA
@ stub ATMInstallSubstFontW
@ stub ATMMakePFM
@ stub ATMMakePFMA
@ stub ATMMakePFMW
@ stub ATMMakePSS
@ stub ATMMakePSSA
@ stub ATMMakePSSW
@ stdcall ATMProperlyLoaded()
@ stub ATMRemoveFont
@ stub ATMRemoveFontA
@ stub ATMRemoveFontW
@ stub ATMRemoveSubstFontA
@ stub ATMRemoveSubstFontW
@ stub ATMSelectEncoding
@ stub ATMSelectObject
@ stub ATMSetFlags
@ stub ATMXYShowText
@ stub ATMXYShowTextA
@ stub ATMXYShowTextW
