@ stub BluetoothAddressToString
@ stub BluetoothDisconnectDevice
@ stub BluetoothEnableDiscovery
@ stub BluetoothEnableIncomingConnections
@ stub BluetoothEnumerateInstalledServices
@ stub BluetoothEnumerateInstalledServicesEx
@ stub BluetoothEnumerateLocalServices
@ stub BluetoothFindBrowseGroupClose
@ stub BluetoothFindClassIdClose
@ stub BluetoothFindDeviceClose
@ stub BluetoothFindFirstBrowseGroup
@ stub BluetoothFindFirstClassId
@ stub BluetoothFindFirstDevice
@ stub BluetoothFindFirstProfileDescriptor
@ stub BluetoothFindFirstProtocolDescriptorStack
@ stub BluetoothFindFirstProtocolEntry
@ stub BluetoothFindFirstRadio
@ stub BluetoothFindFirstService
@ stub BluetoothFindFirstServiceEx
@ stub BluetoothFindNextBrowseGroup
@ stub BluetoothFindNextClassId
@ stub BluetoothFindNextDevice
@ stub BluetoothFindNextProfileDescriptor
@ stub BluetoothFindNextProtocolDescriptorStack
@ stub BluetoothFindNextProtocolEntry
@ stub BluetoothFindNextRadio
@ stub BluetoothFindNextService
@ stub BluetoothFindProfileDescriptorClose
@ stub BluetoothFindProtocolDescriptorStackClose
@ stub BluetoothFindProtocolEntryClose
@ stub BluetoothFindRadioClose
@ stub BluetoothFindServiceClose
@ stub BluetoothGATTAbortReliableWrite
@ stub BluetoothGATTBeginReliableWrite
@ stub BluetoothGATTEndReliableWrite
@ stub BluetoothGATTGetCharacteristicValue
@ stub BluetoothGATTGetCharacteristics
@ stub BluetoothGATTGetDescriptorValue
@ stub BluetoothGATTGetDescriptors
@ stub BluetoothGATTGetIncludedServices
@ stub BluetoothGATTGetServices
@ stub BluetoothGATTRegisterEvent
@ stub BluetoothGATTSetCharacteristicValue
@ stub BluetoothGATTSetDescriptorValue
@ stub BluetoothGATTUnregisterEvent
@ stub BluetoothGetDeviceInfo
@ stub BluetoothGetLocalServiceInfo
@ stub BluetoothGetRadioInfo
@ stub BluetoothGetServicePnpInstance
@ stub BluetoothIsConnectable
@ stub BluetoothIsDiscoverable
@ stub BluetoothIsVersionAvailable
@ stub BluetoothRegisterForAuthentication
@ stub BluetoothRegisterForAuthenticationEx
@ stub BluetoothRemoveDevice
@ stub BluetoothSdpEnumAttributes
@ stub BluetoothSdpGetAttributeValue
@ stub BluetoothSdpGetContainerElementData
@ stub BluetoothSdpGetElementData
@ stub BluetoothSdpGetString
@ stub BluetoothSendAuthenticationResponse
@ stub BluetoothSendAuthenticationResponseEx
@ stub BluetoothSetLocalServiceInfo
@ stub BluetoothSetServiceState
@ stub BluetoothSetServiceStateEx
@ stub BluetoothUnregisterAuthentication
@ stub BluetoothUpdateDeviceRecord
@ stub BthpCheckForUnsupportedGuid
@ stub BthpCleanupBRDeviceNode
@ stub BthpCleanupDeviceLocalServices
@ stub BthpCleanupDeviceRemoteServices
@ stub BthpCleanupLEDeviceNodes
@ stub BthpEnableAllServices
@ stub BthpEnableConnectableAndDiscoverable
@ stub BthpEnableRadioSoftware
@ stub BthpFindPnpInfo
@ stub BthpGATTCloseSession
@ stub BthpInnerRecord
@ stub BthpIsBluetoothServiceRunning
@ stub BthpIsConnectableByDefault
@ stub BthpIsDiscoverable
@ stub BthpIsDiscoverableByDefault
@ stub BthpIsRadioSoftwareEnabled
@ stub BthpIsTopOfServiceGroup
@ stub BthpMapStatusToErr
@ stub BthpNextRecord
@ stub BthpRegisterForAuthentication
@ stub BthpSetServiceState
@ stub BthpSetServiceStateEx
@ stub BthpTranspose16Bits
@ stub BthpTranspose32Bits
@ stub BthpTransposeAndExtendBytes
@ stdcall -private DllCanUnloadNow()
@ stub FindNextOpenVCOMPort
@ stub InstallIncomingComPort
@ stub ShouldForceAuthentication
