@ stub RtwqAddPeriodicCallback
@ stub RtwqAllocateSerialWorkQueue
@ stub RtwqAllocateWorkQueue
@ stub RtwqBeginRegisterWorkQueueWithMMCSS
@ stub RtwqBeginUnregisterWorkQueueWithMMCSS
@ stub RtwqCancelDeadline
@ stub RtwqCancelMultipleWaitingWorkItem
@ stub RtwqCancelWorkItem
@ stub RtwqCreateAsyncResult
@ stub RtwqEndRegisterWorkQueueWithMMCSS
@ stub RtwqEndUnregisterWorkQueueWithMMCSS
@ stub RtwqGetPlatform
@ stub RtwqGetWorkQueueMMCSSClass
@ stub RtwqGetWorkQueueMMCSSPriority
@ stub RtwqGetWorkQueueMMCSSTaskId
@ stub RtwqInvokeCallback
@ stub RtwqJoinWorkQueue
@ stub RtwqLockPlatform
@ stub RtwqLockSharedWorkQueue
@ stub RtwqLockWorkQueue
@ stub RtwqPutMultipleWaitingWorkItem
@ stub RtwqPutWaitingWorkItem
@ stub RtwqPutWorkItem
@ stub RtwqRegisterPlatformEvents
@ stub RtwqRegisterPlatformWithMMCSS
@ stub RtwqRemovePeriodicCallback
@ stub RtwqScheduleWorkItem
@ stub RtwqSetDeadline
@ stub RtwqSetDeadline2
@ stub RtwqSetLongRunning
@ stub RtwqShutdown
@ stub RtwqStartup
@ stub RtwqUnjoinWorkQueue
@ stub RtwqUnlockPlatform
@ stub RtwqUnlockWorkQueue
@ stub RtwqUnregisterPlatformEvents
@ stub RtwqUnregisterPlatformFromMMCSS
