@ stub __std_acquire_shared_mutex_for_instance
@ stub __std_atomic_compare_exchange_128
@ stub __std_atomic_get_mutex
@ stub __std_atomic_has_cmpxchg16b
@ stub __std_atomic_notify_all_direct
@ stub __std_atomic_notify_all_indirect
@ stub __std_atomic_notify_one_direct
@ stub __std_atomic_notify_one_indirect
@ stub __std_atomic_set_api_level
@ stub __std_atomic_wait_direct
@ stub __std_atomic_wait_get_deadline
@ stub __std_atomic_wait_get_remaining_timeout
@ stub __std_atomic_wait_indirect
@ stub __std_bulk_submit_threadpool_work
@ stub __std_calloc_crt
@ stub __std_close_threadpool_work
@ stub __std_create_threadpool_work
@ stub __std_execution_wait_on_uchar
@ stub __std_execution_wake_by_address_all
@ stub __std_free_crt
@ stdcall __std_parallel_algorithms_hw_threads()
@ stub __std_release_shared_mutex_for_instance
@ stub __std_submit_threadpool_work
@ stub __std_tzdb_delete_current_zone
@ stub __std_tzdb_delete_leap_seconds
@ stub __std_tzdb_delete_sys_info
@ stub __std_tzdb_delete_time_zones
@ stub __std_tzdb_get_current_zone
@ stub __std_tzdb_get_leap_seconds
@ stub __std_tzdb_get_sys_info
@ stub __std_tzdb_get_time_zones
@ stub __std_wait_for_threadpool_work_callbacks
