/*
 * COM Classes for xaudio
 *
 * Copyright 2015 Andrew Eikum for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    helpstring("XAudio2.5 Class"),
    threading(both),
    uuid(4c9b6dde-6809-46e6-a278-9b6a97588670)
]
coclass XAudio25 { interface IXAudio27; }

[
    helpstring("XAudio2.5 AudioReverb Class"),
    threading(both),
    uuid(d06df0d0-8518-441e-822f-5451d5c595b8)
]
coclass AudioReverb25 { interface IXAPO; }

[
    helpstring("XAudio2.5 AudioVolumeMeter Class"),
    threading(both),
    uuid(2139e6da-c341-4774-9ac3-b4e026347f64)
]
coclass AudioVolumeMeter25 { interface IXAPO; }
