@ stub DebugExtensionInitialize
@ stub DebugExtensionNotify
@ stub DebugExtensionUninitialize
@ stub JetAddColumn
@ stub JetAddColumnA
@ stub JetAddColumnW
@ stub JetAttachDatabase2
@ stub JetAttachDatabase2A
@ stub JetAttachDatabase2W
@ stub JetAttachDatabase
@ stub JetAttachDatabaseA
@ stub JetAttachDatabaseW
@ stub JetAttachDatabaseWithStreaming
@ stub JetAttachDatabaseWithStreamingA
@ stub JetAttachDatabaseWithStreamingW
@ stub JetBackup
@ stub JetBackupA
@ stub JetBackupInstance
@ stub JetBackupInstanceA
@ stub JetBackupInstanceW
@ stub JetBackupW
@ stub JetBeginDatabaseIncrementalReseed
@ stub JetBeginDatabaseIncrementalReseedA
@ stub JetBeginDatabaseIncrementalReseedW
@ stub JetBeginExternalBackup
@ stub JetBeginExternalBackupInstance
@ stub JetBeginSession
@ stub JetBeginSessionA
@ stub JetBeginSessionW
@ stub JetBeginSurrogateBackup
@ stub JetBeginTransaction2
@ stub JetBeginTransaction
@ stub JetCloseDatabase
@ stub JetCloseFile
@ stub JetCloseFileInstance
@ stub JetCloseTable
@ stub JetCommitTransaction
@ stub JetCompact
@ stub JetCompactA
@ stub JetCompactW
@ stub JetComputeStats
@ stub JetConfigureProcessForCrashDump
@ stub JetConvertDDL
@ stub JetConvertDDLA
@ stub JetConvertDDLW
@ stub JetCreateDatabase2
@ stub JetCreateDatabase2A
@ stub JetCreateDatabase2W
@ stub JetCreateDatabase
@ stub JetCreateDatabaseA
@ stub JetCreateDatabaseW
@ stub JetCreateDatabaseWithStreaming
@ stub JetCreateDatabaseWithStreamingA
@ stub JetCreateDatabaseWithStreamingW
@ stub JetCreateIndex2
@ stub JetCreateIndex2A
@ stub JetCreateIndex2W
@ stub JetCreateIndex3A
@ stub JetCreateIndex3W
@ stub JetCreateIndex
@ stub JetCreateIndexA
@ stub JetCreateIndexW
@ stub JetCreateInstance2
@ stub JetCreateInstance2A
@ stub JetCreateInstance2W
@ stub JetCreateInstance
@ stub JetCreateInstanceA
@ stub JetCreateInstanceW
@ stub JetCreateTable
@ stub JetCreateTableA
@ stub JetCreateTableColumnIndex2
@ stub JetCreateTableColumnIndex2A
@ stub JetCreateTableColumnIndex2W
@ stub JetCreateTableColumnIndex3A
@ stub JetCreateTableColumnIndex3W
@ stub JetCreateTableColumnIndex
@ stub JetCreateTableColumnIndexA
@ stub JetCreateTableColumnIndexW
@ stub JetCreateTableW
@ stub JetDBUtilities
@ stub JetDBUtilitiesA
@ stub JetDBUtilitiesW
@ stub JetDatabaseScan
@ stub JetDefragment2
@ stub JetDefragment2A
@ stub JetDefragment2W
@ stub JetDefragment3
@ stub JetDefragment3A
@ stub JetDefragment3W
@ stub JetDefragment
@ stub JetDefragmentA
@ stub JetDefragmentW
@ stub JetDelete
@ stub JetDeleteColumn2
@ stub JetDeleteColumn2A
@ stub JetDeleteColumn2W
@ stub JetDeleteColumn
@ stub JetDeleteColumnA
@ stub JetDeleteColumnW
@ stub JetDeleteIndex
@ stub JetDeleteIndexA
@ stub JetDeleteIndexW
@ stub JetDeleteTable
@ stub JetDeleteTableA
@ stub JetDeleteTableW
@ stub JetDetachDatabase2
@ stub JetDetachDatabase2A
@ stub JetDetachDatabase2W
@ stub JetDetachDatabase
@ stub JetDetachDatabaseA
@ stub JetDetachDatabaseW
@ stub JetDupCursor
@ stub JetDupSession
@ stub JetEnableFaultInjection
@ stub JetEnableMultiInstance
@ stub JetEnableMultiInstanceA
@ stub JetEnableMultiInstanceW
@ stub JetEndDatabaseIncrementalReseed
@ stub JetEndDatabaseIncrementalReseedA
@ stub JetEndDatabaseIncrementalReseedW
@ stub JetEndExternalBackup
@ stub JetEndExternalBackupInstance2
@ stub JetEndExternalBackupInstance
@ stub JetEndSession
@ stub JetEndSurrogateBackup
@ stub JetEnumerateColumns
@ stub JetEscrowUpdate
@ stub JetExternalRestore2
@ stub JetExternalRestore2A
@ stub JetExternalRestore2W
@ stub JetExternalRestore
@ stub JetExternalRestoreA
@ stub JetExternalRestoreW
@ stub JetFreeBuffer
@ stub JetGetAttachInfo
@ stub JetGetAttachInfoA
@ stub JetGetAttachInfoInstance
@ stub JetGetAttachInfoInstanceA
@ stub JetGetAttachInfoInstanceW
@ stub JetGetAttachInfoW
@ stub JetGetBookmark
@ stub JetGetColumnInfo
@ stub JetGetColumnInfoA
@ stub JetGetColumnInfoW
@ stub JetGetCounter
@ stub JetGetCurrentIndex
@ stub JetGetCurrentIndexA
@ stub JetGetCurrentIndexW
@ stub JetGetCursorInfo
@ stub JetGetDatabaseFileInfo
@ stub JetGetDatabaseFileInfoA
@ stub JetGetDatabaseFileInfoW
@ stub JetGetDatabaseInfo
@ stub JetGetDatabaseInfoA
@ stub JetGetDatabaseInfoW
@ stub JetGetDatabasePages
@ stub JetGetIndexInfo
@ stub JetGetIndexInfoA
@ stub JetGetIndexInfoW
@ stub JetGetInstanceInfo
@ stub JetGetInstanceInfoA
@ stub JetGetInstanceInfoW
@ stub JetGetInstanceMiscInfo
@ stub JetGetLS
@ stub JetGetLock
@ stub JetGetLogFileInfo
@ stub JetGetLogFileInfoA
@ stub JetGetLogFileInfoW
@ stub JetGetLogInfo
@ stub JetGetLogInfoA
@ stub JetGetLogInfoInstance2
@ stub JetGetLogInfoInstance2A
@ stub JetGetLogInfoInstance2W
@ stub JetGetLogInfoInstance
@ stub JetGetLogInfoInstanceA
@ stub JetGetLogInfoInstanceW
@ stub JetGetLogInfoW
@ stub JetGetMaxDatabaseSize
@ stub JetGetObjectInfo
@ stub JetGetObjectInfoA
@ stub JetGetObjectInfoW
@ stub JetGetPageInfo2
@ stub JetGetPageInfo
@ stub JetGetRecordPosition
@ stub JetGetRecordSize2
@ stub JetGetRecordSize
@ stub JetGetResourceParam
@ stub JetGetSecondaryIndexBookmark
@ stub JetGetSessionInfo
@ stub JetGetSystemParameter
@ stub JetGetSystemParameterA
@ stub JetGetSystemParameterW
@ stub JetGetTableColumnInfo
@ stub JetGetTableColumnInfoA
@ stub JetGetTableColumnInfoW
@ stub JetGetTableIndexInfo
@ stub JetGetTableIndexInfoA
@ stub JetGetTableIndexInfoW
@ stub JetGetTableInfo
@ stub JetGetTableInfoA
@ stub JetGetTableInfoW
@ stub JetGetThreadStats
@ stub JetGetTruncateLogInfoInstance
@ stub JetGetTruncateLogInfoInstanceA
@ stub JetGetTruncateLogInfoInstanceW
@ stub JetGetVersion
@ stub JetGotoBookmark
@ stub JetGotoPosition
@ stub JetGotoSecondaryIndexBookmark
@ stub JetGrowDatabase
@ stub JetIdle
@ stub JetIndexRecordCount
@ stub JetInit2
@ stub JetInit3
@ stub JetInit3A
@ stub JetInit3W
@ stub JetInit
@ stub JetIntersectIndexes
@ stub JetMakeKey
@ stub JetMove
@ stub JetOSSnapshotAbort
@ stub JetOSSnapshotEnd
@ stub JetOSSnapshotFreeze
@ stub JetOSSnapshotFreezeA
@ stub JetOSSnapshotFreezeW
@ stub JetOSSnapshotGetFreezeInfo
@ stub JetOSSnapshotGetFreezeInfoA
@ stub JetOSSnapshotGetFreezeInfoW
@ stub JetOSSnapshotPrepare
@ stub JetOSSnapshotPrepareInstance
@ stub JetOSSnapshotThaw
@ stub JetOSSnapshotTruncateLog
@ stub JetOSSnapshotTruncateLogInstance
@ stub JetOpenDatabase
@ stub JetOpenDatabaseA
@ stub JetOpenDatabaseW
@ stub JetOpenFile
@ stub JetOpenFileA
@ stub JetOpenFileInstance
@ stub JetOpenFileInstanceA
@ stub JetOpenFileInstanceW
@ stub JetOpenFileSectionInstance
@ stub JetOpenFileSectionInstanceA
@ stub JetOpenFileSectionInstanceW
@ stub JetOpenFileW
@ stub JetOpenTable
@ stub JetOpenTableA
@ stub JetOpenTableW
@ stub JetOpenTempTable2
@ stub JetOpenTempTable3
@ stub JetOpenTempTable
@ stub JetOpenTemporaryTable
@ stub JetPatchDatabasePages
@ stub JetPatchDatabasePagesA
@ stub JetPatchDatabasePagesW
@ stub JetPrepareToCommitTransaction
@ stub JetPrepareUpdate
@ stub JetPrereadKeys
@ stub JetReadFile
@ stub JetReadFileInstance
@ stub JetRegisterCallback
@ stub JetRemoveLogfileA
@ stub JetRemoveLogfileW
@ stub JetRenameColumn
@ stub JetRenameColumnA
@ stub JetRenameColumnW
@ stub JetRenameTable
@ stub JetRenameTableA
@ stub JetRenameTableW
@ stub JetResetCounter
@ stub JetResetSessionContext
@ stub JetResetTableSequential
@ stub JetRestore2
@ stub JetRestore2A
@ stub JetRestore2W
@ stub JetRestore
@ stub JetRestoreA
@ stub JetRestoreInstance
@ stub JetRestoreInstanceA
@ stub JetRestoreInstanceW
@ stub JetRestoreW
@ stub JetRetrieveColumn
@ stub JetRetrieveColumns
@ stub JetRetrieveKey
@ stub JetRetrieveTaggedColumnList
@ stub JetRollback
@ stub JetSeek
@ stub JetSetColumn
@ stub JetSetColumnDefaultValue
@ stub JetSetColumnDefaultValueA
@ stub JetSetColumnDefaultValueW
@ stub JetSetColumns
@ stub JetSetCurrentIndex2
@ stub JetSetCurrentIndex2A
@ stub JetSetCurrentIndex2W
@ stub JetSetCurrentIndex3
@ stub JetSetCurrentIndex3A
@ stub JetSetCurrentIndex3W
@ stub JetSetCurrentIndex4
@ stub JetSetCurrentIndex4A
@ stub JetSetCurrentIndex4W
@ stub JetSetCurrentIndex
@ stub JetSetCurrentIndexA
@ stub JetSetCurrentIndexW
@ stub JetSetDatabaseSize
@ stub JetSetDatabaseSizeA
@ stub JetSetDatabaseSizeW
@ stub JetSetIndexRange
@ stub JetSetLS
@ stub JetSetMaxDatabaseSize
@ stub JetSetResourceParam
@ stub JetSetSessionContext
@ stub JetSetSystemParameter
@ stub JetSetSystemParameterA
@ stub JetSetSystemParameterW
@ stub JetSetTableSequential
@ stub JetSnapshotStart
@ stub JetSnapshotStartA
@ stub JetSnapshotStartW
@ stub JetSnapshotStop
@ stub JetStopBackup
@ stub JetStopBackupInstance
@ stub JetStopService
@ stub JetStopServiceInstance
@ stub JetTerm2
@ stub JetTerm
@ stub JetTest
@ stub JetTracing
@ stub JetTruncateLog
@ stub JetTruncateLogInstance
@ stub JetUnregisterCallback
@ stub JetUpdate2
@ stub JetUpdate
@ stub JetUpgradeDatabase
@ stub JetUpgradeDatabaseA
@ stub JetUpgradeDatabaseW
