@ stub CloseThemeData
@ stub DrawThemeBackground
@ stub DrawThemeBackgroundEx
@ stub DrawThemeEdge
@ stub DrawThemeIcon
@ stub DrawThemeParentBackground
@ stub DrawThemeText
@ stdcall EnableThemeDialogTexture(ptr long)
@ stdcall EnableTheming(long)
@ stub GetCurrentThemeName
@ stub GetThemeAppProperties
@ stub GetThemeBackgroundContentRect
@ stub GetThemeBackgroundExtent
@ stub GetThemeBackgroundRegion
@ stub GetThemeBool
@ stub GetThemeColor
@ stub GetThemeDocumentationProperty
@ stub GetThemeEnumValue
@ stub GetThemeFilename
@ stub GetThemeFont
@ stub GetThemeInt
@ stub GetThemeIntList
@ stub GetThemeMargins
@ stub GetThemeMetric
@ stub GetThemePartSize
@ stub GetThemePosition
@ stub GetThemePropertyOrigin
@ stub GetThemeRect
@ stub GetThemeString
@ stub GetThemeSysBool
@ stub GetThemeSysColor
@ stub GetThemeSysColorBrush
@ stub GetThemeSysFont
@ stub GetThemeSysInt
@ stub GetThemeSysSize
@ stub GetThemeSysString
@ stub GetThemeTextExtent
@ stub GetThemeTextMetrics
@ stub GetWindowTheme
@ stub HitTestThemeBackground
@ stdcall IsAppThemed()
@ stdcall IsThemeActive()
@ stub IsThemeBackgroundPartiallyTransparent
@ stub IsThemeDialogTextureEnabled
@ stub IsThemePartDefined
@ stdcall OpenThemeData(ptr wstr)
@ stub SetThemeAppProperties
@ stdcall SetWindowTheme(ptr wstr wstr)
