@ stub D3DRMColorGetAlpha
@ stub D3DRMColorGetBlue
@ stub D3DRMColorGetGreen
@ stub D3DRMColorGetRed
@ stub D3DRMCreateColorRGB
@ stub D3DRMCreateColorRGBA
@ stub D3DRMMatrixFromQuaternion
@ stub D3DRMQuaternionFromRotation
@ stub D3DRMQuaternionMultiply
@ stub D3DRMQuaternionSlerp
@ stdcall D3DRMVectorAdd(ptr ptr ptr)
@ stub D3DRMVectorCrossProduct
@ stub D3DRMVectorDotProduct
@ stub D3DRMVectorModulus
@ stub D3DRMVectorNormalize
@ stub D3DRMVectorRandom
@ stub D3DRMVectorReflect
@ stub D3DRMVectorRotate
@ stub D3DRMVectorScale
@ stub D3DRMVectorSubtract
@ stub Direct3DRMCreate
@ stub DllCanUnloadNow
@ stub DllGetClassObject
