@ stub AcceptSecurityContext
@ stub AcquireCredentialsHandleA
@ stub AcquireCredentialsHandleW
@ stub AddCredentialsA
@ stub AddCredentialsW
@ stub AddSecurityPackageA
@ stub AddSecurityPackageW
@ stub ApplyControlToken
@ stub ChangeAccountPasswordA
@ stub ChangeAccountPasswordW
@ stub CompleteAuthToken
@ stub CredMarshalTargetInfo
@ stub CredUnmarshalTargetInfo
@ stub DecryptMessage
@ stub DeleteSecurityContext
@ stub DeleteSecurityPackageA
@ stub DeleteSecurityPackageW
@ stub EncryptMessage
@ stub EnumerateSecurityPackagesA
@ stub EnumerateSecurityPackagesW
@ stub ExportSecurityContext
@ stub FreeContextBuffer
@ stub FreeCredentialsHandle
@ stub GetSecurityUserInfo
@ stub GetUserNameExA
@ stub GetUserNameExW
@ stub ImpersonateSecurityContext
@ stub ImportSecurityContextA
@ stub ImportSecurityContextW
@ stub InitializeSecurityContextA
@ stub InitializeSecurityContextW
@ stub InitSecurityInterfaceA
@ stub InitSecurityInterfaceW
@ stub LogonUserExExW
@ stub LsaCallAuthenticationPackage
@ stub LsaConnectUntrusted
@ stub LsaDeregisterLogonProcess
@ stub LsaEnumerateLogonSessions
@ stub LsaFreeReturnBuffer
@ stub LsaGetLogonSessionData
@ stub LsaLogonUser
@ stub LsaLookupAuthenticationPackage
@ stub LsaRegisterLogonProcess
@ stub LsaRegisterPolicyChangeNotification
@ stub LsaUnregisterPolicyChangeNotification
@ stub MakeSignature
@ stub QueryContextAttributesA
@ stub QueryContextAttributesExA
@ stub QueryContextAttributesExW
@ stub QueryContextAttributesW
@ stub QueryCredentialsAttributesA
@ stub QueryCredentialsAttributesExA
@ stub QueryCredentialsAttributesExW
@ stub QueryCredentialsAttributesW
@ stub QuerySecurityContextToken
@ stub QuerySecurityPackageInfoA
@ stub QuerySecurityPackageInfoW
@ stub RevertSecurityContext
@ stub SaslAcceptSecurityContext
@ stub SaslEnumerateProfilesA
@ stub SaslEnumerateProfilesW
@ stub SaslGetContextOption
@ stub SaslGetProfilePackageA
@ stub SaslGetProfilePackageW
@ stub SaslIdentifyPackageA
@ stub SaslIdentifyPackageW
@ stub SaslInitializeSecurityContextA
@ stub SaslInitializeSecurityContextW
@ stub SaslSetContextOption
@ stub SealMessage
@ stub SecCacheSspiPackages
@ stub SecDeleteUserModeContext
@ stub SeciAllocateAndSetCallFlags
@ stub SeciAllocateAndSetIPAddress
@ stub SeciFreeCallContext
@ stub SeciIsProtectedUser
@ stub SecInitUserModeContext
@ stub SetContextAttributesA
@ stub SetContextAttributesW
@ stub SetCredentialsAttributesA
@ stub SetCredentialsAttributesW
@ stub SspiCompareAuthIdentities
@ stub SspiCopyAuthIdentity
@ stub SspiDecryptAuthIdentity
@ stub SspiDecryptAuthIdentityEx
@ stdcall SspiEncodeAuthIdentityAsStrings(ptr ptr ptr ptr)
@ stdcall SspiEncodeStringsAsAuthIdentity(wstr wstr wstr ptr)
@ stub SspiEncryptAuthIdentity
@ stub SspiEncryptAuthIdentityEx
@ stub SspiExcludePackage
@ stdcall SspiFreeAuthIdentity(ptr)
@ stub SspiGetComputerNameForSPN
@ stub SspiGetTargetHostName
@ stub SspiIsAuthIdentityEncrypted
@ stdcall SspiLocalFree(ptr)
@ stub SspiMarshalAuthIdentity
@ stub SspiPrepareForCredRead
@ stdcall SspiPrepareForCredWrite(ptr wstr ptr ptr ptr ptr ptr)
@ stub SspiUnmarshalAuthIdentity
@ stub SspiUnmarshalAuthIdentityInternal
@ stub SspiValidateAuthIdentity
@ stdcall SspiZeroAuthIdentity(ptr)
@ stub UnsealMessage
@ stub VerifySignature
