@ stub BluetoothAddressToString
@ stub BluetoothAuthenticateDevice
@ stub BluetoothAuthenticateDeviceEx
@ stub BluetoothAuthenticateMultipleDevices
@ stub BluetoothAuthenticationAgent
@ stub BluetoothDisconnectDevice
@ stub BluetoothDisplayDeviceProperties
@ stub BluetoothEnableDiscovery
@ stub BluetoothEnableIncomingConnections
@ stub BluetoothEnumerateInstalledServices
@ stub BluetoothEnumerateInstalledServicesEx
@ stub BluetoothFindBrowseGroupClose
@ stub BluetoothFindClassIdClose
@ stdcall BluetoothFindDeviceClose(ptr)
@ stub BluetoothFindFirstBrowseGroup
@ stub BluetoothFindFirstClassId
@ stdcall BluetoothFindFirstDevice(ptr ptr)
@ stub BluetoothFindFirstProfileDescriptor
@ stub BluetoothFindFirstProtocolDescriptorStack
@ stub BluetoothFindFirstProtocolEntry
@ stdcall BluetoothFindFirstRadio(ptr ptr)
@ stub BluetoothFindFirstService
@ stub BluetoothFindFirstServiceEx
@ stub BluetoothFindNextBrowseGroup
@ stub BluetoothFindNextClassId
@ stub BluetoothFindNextDevice
@ stub BluetoothFindNextProfileDescriptor
@ stub BluetoothFindNextProtocolDescriptorStack
@ stub BluetoothFindNextProtocolEntry
@ stub BluetoothFindNextRadio
@ stub BluetoothFindNextService
@ stub BluetoothFindProfileDescriptorClose
@ stub BluetoothFindProtocolDescriptorStackClose
@ stub BluetoothFindProtocolEntryClose
@ stdcall BluetoothFindRadioClose(ptr)
@ stub BluetoothFindServiceClose
@ stub BluetoothGetDeviceInfo
@ stub BluetoothGetRadioInfo
@ stub BluetoothIsConnectable
@ stub BluetoothIsDiscoverable
@ stub BluetoothIsVersionAvailable
@ stub BluetoothMapClassOfDeviceToImageIndex
@ stub BluetoothMapClassOfDeviceToString
@ stub BluetoothRegisterForAuthentication
@ stub BluetoothRegisterForAuthenticationEx
@ stub BluetoothRemoveDevice
@ stub BluetoothSdpEnumAttributes
@ stub BluetoothSdpGetAttributeValue
@ stub BluetoothSdpGetContainerElementData
@ stub BluetoothSdpGetElementData
@ stub BluetoothSdpGetString
@ stub BluetoothSelectDevices
@ stub BluetoothSelectDevicesFree
@ stub BluetoothSendAuthenticationResponse
@ stub BluetoothSendAuthenticationResponseEx
@ stub BluetoothSetLocalServiceInfo
@ stub BluetoothSetServiceState
@ stub BluetoothUnregisterAuthentication
@ stub BluetoothUpdateDeviceRecord
@ stub BthpEnableAllServices
@ stub BthpFindPnpInfo
@ stub BthpMapStatusToErr
#@ stub CPlApplet
@ stub DllCanUnloadNow
@ stub DllGetClassObject
