2 stub SHChangeNotifyRegister
4 stub SHChangeNotifyDeregister
5 stub CreateStorageItemFromPath_FullTrustCaller
6 stub CreateStorageItemFromPath_FullTrustCaller_ForPackage
7 stub GatherProviderSettings
8 stub GetUserChoiceForUrl
9 stub PathContainedByManifestedKnownFolder_FullTrustCaller_ForPackage
10 stub RegisterChangeNotifications
11 stub UnregisterChangeNotifications
27 stub ILSaveToStream
28 stub SHILCreateFromPath
42 stub IsLFNDriveW
68 stub SHGetSetSettings
74 stub SHCreateStdEnumFmtEtc
75 stub PathYetAnotherMakeUniqueName
77 stub @
90 stub SHFindFiles
95 stub @
100 stub SHRestricted
147 stub SHCLSIDFromString
172 stub @
243 stub @
244 stub @
245 stub SHTestTokenMembership
264 stub @
644 stub SHChangeNotification_Lock
645 stub SHChangeNotification_Unlock
660 stub @
680 stub IsUserAnAdmin
740 stub @
750 stub @
761 stub @
764 stub @
765 stub @
781 stub @
788 stub @
789 stub @
791 stub @
814 stub @
815 stub @
816 stub @
817 stub @
818 stub @
819 stub @
823 stub @
824 stub @
825 stub @
830 stub @
844 stub @
845 stub @
846 stub ILLoadFromStreamEx
847 stub @
849 stub @
850 stub @
851 stub @
862 stub @
866 stub @
873 stub @
880 stub @
887 stub @
897 stub @
898 stub @
910 stub @
911 stub @
913 stub @
914 stub @
915 stub @
916 stub @
923 stub @
925 stub CreateStorageItemFromShellItem_FullTrustCaller_ForPackage
928 stub @
938 stub GetCachedFileUpdateInformation
942 stub CreateStorageItemFromShellItem
943 stub CreateExtrinsicPropertyStore
945 stub GetInfoForFileInUse
946 stub SHChangeNotifySuspendResume
947 stub CreateStorageProviderPropertyStore
1001 stub @
1002 stub @
1003 stub @
2000 stub @
2001 stub @
2002 stub @
2003 stub @
2004 stub @
2005 stub @
2006 stub @
2007 stub @
2008 stub @
2009 stub @

@ stub ApplyProviderSettings
@ stub AssocCreateForClasses
@ stub AssocGetDetailsOfPropKey
@ stub AssocShouldProcessUseAppToAppLaunching
@ stub BrokerAppSiloShellItemsForApplicationUserModelId
@ stub BrokerAppSiloShellItemsForPackageFamilyName
@ stub CCachedShellItem_CreateInstance
@ stub CCollectionFactory_CreateInstance
@ stub CDesktopFolder_CreateInstanceWithBindContext
@ stub CFSFolder_AdjustForSlowColumn
@ stub CFSFolder_CreateFolder
@ stub CFSFolder_IsCommonItem
@ stub CFileOperationRecorder_CreateInstance
@ stub CFreeThreadedItemContainer_CreateInstance
@ stub CMruLongList_CreateInstance
@ stub CPrivateProfileCache_Save
@ stub CRegFolder_CreateAndInit
@ stub CRegFolder_CreateInstance
@ stub CShellItemArrayAsCollection_CreateInstance
@ stub CShellItemArrayAsVirtualizedObjectArray_CreateInstance
@ stub CShellItemArrayWithCommonParent_CreateInstance
@ stub CShellItemArray_CreateInstance
@ stub CShellItem_CreateInstance
@ stub CStorageItem_GetValidatedStorageItemObject
@ stub CTaskAddDoc_Create
@ stub CViewSettings_CreateInstance
@ stub CheckSmartScreenWithAltFile
@ stub CopyDefaultLibrariesFromGroupPolicy
@ stub CreateItemArrayFromItemStore
@ stub CreateItemArrayFromObjectArray
@ stub CreateLocalizationDesktopIni
@ stub CreateSortColumnArray
@ stub CreateStorageItemFromPath_PartialTrustCaller
@ stub CreateVolatilePropertyStore
@ stub CustomStatePropertyDescription_CreateWithItemPropertyStore
@ stub CustomStatePropertyDescription_CreateWithStateIdentifier
@ stub DataAccessCaches_InvalidateForLibrary
@ stub DeserializeTextToLink
@ stub DetermineFolderDestinationParentAppID
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetActivationFactory(ptr ptr)
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -private DllMain(long long ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ stub DragQueryFileW
@ stub EnumShellItemsFromEnumFullIdList
@ stub GetCommandProviderForFolderType
@ stub GetFileUndoText
@ stub GetFindDataForPath
@ stub GetFindDataFromFileInformationByHandle
@ stub GetRegDataDrivenCommand
@ stub GetRegDataDrivenCommandWithAssociation
@ stub GetSelectionStateFromItemArray
@ stub GetSystemPersistedStorageItemList
@ stub GetSystemPersistedStorageItemListForUser
@ stub GetThreadFlags
@ stub Global_WindowsStorage_MaxIcons
@ stub Global_WindowsStorage_Untyped_FileClassSRWLock
@ stub Global_WindowsStorage_Untyped_MountPoint
@ stub Global_WindowsStorage_Untyped_pFileClassCacheTable
@ stub Global_WindowsStorage_Untyped_pFileHanderMap
@ stub Global_WindowsStorage_Untyped_rgshil
@ stub Global_WindowsStorage_afNotRedirected
@ stub Global_WindowsStorage_ccIcon
@ stub Global_WindowsStorage_csIconCache
@ stub Global_WindowsStorage_csSCN
@ stub Global_WindowsStorage_dwThreadBindCtx
@ stub Global_WindowsStorage_dwThreadInitializing
@ stub Global_WindowsStorage_esServerMode
@ stub Global_WindowsStorage_fEndInitialized
@ stub Global_WindowsStorage_fIconCacheHasBeenSuccessfullyCreated
@ stub Global_WindowsStorage_fIconCacheIsValid
@ stub Global_WindowsStorage_fNeedsInitBroadcast
@ stub Global_WindowsStorage_hwndSCN
@ stub Global_WindowsStorage_iLastSysIcon
@ stub Global_WindowsStorage_iLastSystemColorDepth
@ stub Global_WindowsStorage_iUseLinkPrefix
@ stub Global_WindowsStorage_lProcessClassCount
@ stub Global_WindowsStorage_lrFlags
@ stub Global_WindowsStorage_nImageManagerVersion
@ stub Global_WindowsStorage_tlsChangeClientProxy
@ stub Global_WindowsStorage_tlsIconCache
@ stub Global_WindowsStorage_tlsThreadFlags
@ stub Global_WindowsStorage_ulNextID
@ stub GrantPathAccess_FullTrustCaller_ForPackage
@ stub GrantWorkingDirectoryAccess_FullTrustCaller_ForPackage
@ stub HideExtension
@ stub ILAppendID
@ stub ILClone
@ stub ILCloneFirst
@ stub ILCombine
@ stub ILFindChild
@ stub ILFindLastID
@ stub ILFree
@ stub ILGetNext
@ stub ILGetSize
@ stub ILIsEqual
@ stub ILIsParent
@ stub ILRemoveLastID
@ stub IsLibraryCreatedByPolicy
@ stub IsLibraryPolicyEnabled
@ stub IsNameListedUnderKey
@ stub NeverProvidedByJunction
@ stub PathCleanupSpec
@ stub PathIsExe
@ stub PathMakeUniqueName
@ stub QueryStorageAccess_FullTrustCaller_ForPackage
@ stub QueryStorageAccess_FullTrustCaller_ForToken
@ stub RebaseOnDriveLetter
@ stub RebaseOnVolumeID
@ stub RegistryVerbs_GetHandlerMultiSelectModel
@ stub SHAssocEnumHandlers
@ stub SHAssocEnumHandlersForProtocolByApplication
@ stub SHBindToFolderIDListParent
@ stub SHBindToFolderIDListParentEx
@ stub SHBindToObject
@ stub SHBindToParent
@ stub SHChangeNotify
@ stub SHChangeNotifyRegisterThread
@ stub SHCoCreateInstanceWorker
@ stub SHCreateAssocHandler
@ stub SHCreateAssociationRegistration
@ stub SHCreateDataObject
@ stub SHCreateDefaultExtractIcon
@ stub SHCreateDirectory
@ stub SHCreateDirectoryExA
@ stub SHCreateDirectoryExW
@ stub SHCreateItemFromIDList
@ stub SHCreateItemFromParsingName
@ stub SHCreateItemFromRelativeName
@ stub SHCreateItemInKnownFolder
@ stub SHCreateItemWithParent
@ stub SHCreateItemWithParentAndChildId
@ stub SHCreateShellItemArray
@ stub SHCreateShellItemArrayFromDataObject
@ stub SHCreateShellItemArrayFromIDLists
@ stub SHCreateShellItemArrayFromShellItem
@ stub SHCreateShellItemArrayWithFolderParent
@ stub SHFileOperationWithAdditionalFlags
@ stub SHFlushSFCache
@ stub SHGetDesktopFolder
@ stub SHGetFileInfoW
@ stub SHGetFolderLocation
@ stub SHGetFolderPathA
@ stub SHGetFolderPathAndSubDirA
@ stub SHGetFolderPathAndSubDirW
@ stub SHGetFolderPathEx
@ stub SHGetFolderPathW
@ stub SHGetIDListFromObject
@ stub SHGetInstanceExplorer
@ stub SHGetItemFromObject
@ stub SHGetKnownFolderIDList
@ stub SHGetKnownFolderIDList_Internal
@ stub SHGetKnownFolderItem
@ stub SHGetKnownFolderPath
@ stub SHGetNameFromIDList
@ stub SHGetPathFromIDListEx
@ stub SHGetPathFromIDListW
@ stub SHGetSpecialFolderLocation
@ stub SHGetSpecialFolderPathA
@ stub SHGetSpecialFolderPathW
@ stub SHGetStockIconInfo
@ stub SHGetTemporaryPropertyForItem
@ stub SHHandleUpdateImage
@ stub SHKnownFolderFromCSIDL
@ stub SHKnownFolderToCSIDL
@ stub SHOpenFolderAndSelectItems
@ stub SHParseDisplayName
@ stub SHPrepareKnownFoldersCommon
@ stub SHPrepareKnownFoldersUser
@ stub SHResolveLibrary
@ stub SHSetFolderPathA
@ stub SHSetFolderPathW
@ stub SHSetKnownFolderPath
@ stub SHSetLocalizedName
@ stub SHSetTemporaryPropertyForItem
@ stub SHSysErrorMessageBox
@ stub SHUpdateImageA
@ stub SHUpdateImageW
@ stub STORAGE_AddItemToRecentDocs
@ stub STORAGE_AddNewFolderToFrequentPlaces
@ stub STORAGE_CEnumFiles_CreateInstance
@ stub STORAGE_CStatusProvider_CreateInstance
@ stub STORAGE_CStorageItem_GetValidatedStorageItem
@ stub STORAGE_CStorageItem_GetValidatedStorageItemObject
@ stub STORAGE_ClearDestinationsForAllApps
@ stub STORAGE_CreateSortColumnArrayFromListDesc
@ stub STORAGE_CreateStorageItemFromPath_FullTrustCaller
@ stub STORAGE_CreateStorageItemFromPath_FullTrustCaller_ForPackage
@ stub STORAGE_CreateStorageItemFromPath_PartialTrustCaller
@ stub STORAGE_CreateStorageItemFromShellItem_FullTrustCaller
@ stub STORAGE_CreateStorageItemFromShellItem_FullTrustCaller_ForPackage
@ stub STORAGE_CreateStorageItemFromShellItem_FullTrustCaller_ForPackage_WithProcessHandle
@ stub STORAGE_CreateStorageItemFromShellItem_FullTrustCaller_ForPackage_WithProcessHandleAndSecondaryStreamName
@ stub STORAGE_CreateStorageItemFromShellItem_FullTrustCaller_UseImplicitFlagsAndPackage
@ stub STORAGE_FillResultWithNullForKeys
@ stub STORAGE_GetShellItemFromStorageItem
@ stub STORAGE_GetSystemPersistedStorageItemList
@ stub STORAGE_MakeDestinationItem
@ stub STORAGE_PathIsEqualOrSubFolderOfKnownFolders
@ stub STORAGE_SHAddToRecentDocs
@ stub STORAGE_SHAddToRecentDocsEx
@ stub STORAGE_SHConfirmOperation
@ stub STORAGE_SHCreateDirectory
@ stub STORAGE_SHCreateDirectoryExA
@ stub STORAGE_SHCreateDirectoryExWWorker
@ stub STORAGE_SHCreateShellItemArray
@ stub STORAGE_SHCreateShellItemArrayFromDataObject
@ stub STORAGE_SHCreateShellItemArrayFromIDLists
@ stub STORAGE_SHCreateShellItemArrayFromShellItem
@ stub STORAGE_SHFileOperation
@ stub STORAGE_SHFileOperationA
@ stub STORAGE_SHFreeNameMappings
@ stub STORAGE_SHGetDesktopFolderWorker
@ stub STORAGE_SHGetPathFromMsUri
@ stub STORAGE_SHOpenFolderAndSelectItems
@ stub STORAGE_SHPathPrepareForWriteA
@ stub STORAGE_SHPathPrepareForWriteW
@ stub STORAGE_SHValidateMSUri
@ stub SendNotificationsForLibraryItem
@ stub SerializeLinkToText
@ stub SetThreadFlags
@ stub ShellExecuteA
@ stub ShellExecuteExW
@ stub ShellExecuteW
@ stub StateRepoVerbsCache_Destroy
@ stub StateRepoVerbsCache_GetContextMenuVerbs
@ stub StateRepoVerbsCache_RebuildCacheAsync
@ stub StorageItemHelpers_IsSupportedRemovablePath
@ stub Storage_Internal_GetAccessListForPackage
@ stub _CleanRecentDocs
@ stub _PredictReasonableImpact
