@ stub HttpAddFragmentToCache
@ stub HttpAddUrl
@ stub HttpAddUrlToConfigGroup
@ stub HttpCancelHttpRequest
@ stub HttpCreateAppPool
@ stub HttpCreateConfigGroup
@ stub HttpCreateFilter
@ stub HttpCreateHttpHandle
@ stub HttpDeleteConfigGroup
@ stub HttpDeleteServiceConfiguration
@ stub HttpFilterAccept
@ stub HttpFilterAppRead
@ stub HttpFilterAppWrite
@ stub HttpFilterAppWriteAndRawRead
@ stub HttpFilterClose
@ stub HttpFilterRawRead
@ stub HttpFilterRawWrite
@ stub HttpFilterRawWriteAndAppRead
@ stub HttpFlushResponseCache
@ stub HttpGetCounters
@ stub HttpInitialize
@ stub HttpInitializeServerContext
@ stub HttpOpenAppPool
@ stub HttpOpenControlChannel
@ stub HttpOpenFilter
@ stub HttpQueryAppPoolInformation
@ stub HttpQueryConfigGroupInformation
@ stub HttpQueryControlChannelInformation
@ stub HttpQueryServerContextInformation
@ stub HttpQueryServiceConfiguration
@ stub HttpReadFragmentFromCache
@ stub HttpReceiveClientCertificate
@ stub HttpReceiveHttpRequest
@ stub HttpReceiveHttpResponse
@ stub HttpReceiveRequestEntityBody
@ stub HttpRemoveAllUrlsFromConfigGroup
@ stub HttpRemoveUrl
@ stub HttpRemoveUrlFromConfigGroup
@ stub HttpSendHttpRequest
@ stub HttpSendHttpResponse
@ stub HttpSendRequestEntityBody
@ stub HttpSendResponseEntityBody
@ stub HttpSetAppPoolInformation
@ stub HttpSetConfigGroupInformation
@ stub HttpSetControlChannelInformation
@ stub HttpSetServerContextInformation
@ stub HttpSetServiceConfiguration
@ stub HttpShutdownAppPool
@ stub HttpShutdownFilter
@ stub HttpTerminate
@ stub HttpWaitForDemandStart
@ stub HttpWaitForDisconnect
