name	avifil32
type	win32

  0 stub    AVIBuildFilter
  1 stub    AVIBuildFilterA
  2 stub    AVIBuildFilterW
  3 stub    AVIClearClipboard
  4 stub    AVIFileAddRef
  5 stub    AVIFileCreateStream
  6 stub    AVIFileCreateStreamA
  7 stub    AVIFileCreateStreamW
  8 stub    AVIFileEndRecord
  9 stub    AVIFileExit
 10 stub    AVIFileGetStream
 11 stub    AVIFileInfo
 12 stub    AVIFileInfoA
 13 stub    AVIFileInfoW
 14 stub    AVIFileInit
 15 stub    AVIFileOpen
 16 stub    AVIFileOpenA
 17 stub    AVIFileOpenW
 18 stub    AVIFileReadData
 19 stub    AVIFileRelease
 20 stub    AVIFileWriteData
 21 stub    AVIGetFromClipboard
 22 stub    AVIMakeCompressedStream
 23 stub    AVIMakeFileFromStreams
 24 stub    AVIMakeStreamFromClipboard
 25 stub    AVIPutFileOnClipboard
 26 stub    AVISave
 27 stub    AVISaveA
 28 stub    AVISaveOptions
 29 stub    AVISaveOptionsFree
 30 stub    AVISaveV
 31 stub    AVISaveVA
 32 stub    AVISaveVW
 33 stub    AVISaveW
 34 stub    AVIStreamAddRef
 35 stub    AVIStreamBeginStreaming
 36 stub    AVIStreamCreate
 37 stub    AVIStreamEndStreaming
 38 stub    AVIStreamFindSample
 39 stub    AVIStreamGetFrame
 40 stub    AVIStreamGetFrameClose
 41 stub    AVIStreamGetFrameOpen
 42 stub    AVIStreamInfo
 43 stub    AVIStreamInfoA
 44 stub    AVIStreamInfoW
 45 stub    AVIStreamLength
 46 stub    AVIStreamOpenFromFile
 47 stub    AVIStreamOpenFromFileA
 48 stub    AVIStreamOpenFromFileW
 49 stub    AVIStreamRead
 50 stub    AVIStreamReadData
 51 stub    AVIStreamReadFormat
 52 stub    AVIStreamRelease
 53 stub    AVIStreamSampleToTime
 54 stub    AVIStreamSetFormat
 55 stub    AVIStreamStart
 56 stub    AVIStreamTimeToSample
 57 stub    AVIStreamWrite
 58 stub    AVIStreamWriteData
 59 stub    CLSID_AVISimpleUnMarshal
 60 stub    CreateEditableStream
 61 stub    DllCanUnloadNow
 62 stub    DllGetClassObject
 63 stub    EditStreamClone
 64 stub    EditStreamCopy
 65 stub    EditStreamCut
 66 stub    EditStreamPaste
 67 stub    EditStreamSetInfo
 68 stub    EditStreamSetInfoA
 69 stub    EditStreamSetInfoW
 70 stub    EditStreamSetName
 71 stub    EditStreamSetNameA
 72 stub    EditStreamSetNameW
 73 stub    IID_IAVIEditStream
 74 stub    IID_IAVIFile
 75 stub    IID_IAVIStream
 76 stub    IID_IGetFrame
