name	msvfw32
type	win32

  2 stub    VideoForWindowsVersion
  3 stub    DrawDibBegin
  4 stub    DrawDibChangePalette
  5 stub    DrawDibClose
  6 stub    DrawDibDraw
  7 stub    DrawDibEnd
  8 stub    DrawDibGetBuffer
  9 stub    DrawDibGetPalette
 10 stub    DrawDibOpen
 11 stub    DrawDibProfileDisplay
 12 stub    DrawDibRealize
 13 stub    DrawDibSetPalette
 14 stub    DrawDibStart
 15 stub    DrawDibStop
 16 stub    DrawDibTime
 17 stub    GetOpenFileNamePreview
 18 stub    GetOpenFileNamePreviewA
 19 stub    GetOpenFileNamePreviewW
 20 stub    GetSaveFileNamePreviewA
 21 stub    GetSaveFileNamePreviewW
 22 stub    ICClose
 23 stub    ICCompress
 24 stub    ICCompressorChoose
 25 stub    ICCompressorFree
 26 stub    ICDecompress
 27 stub    ICDraw
 28 stub    ICDrawBegin
 29 stub    ICGetDisplayFormat
 30 stub    ICGetInfo
 31 stub    ICImageCompress
 32 stub    ICImageDecompress
 33 stub    ICInfo
 34 stub    ICInstall
 35 stub    ICLocate
 36 stub    ICMThunk32
 37 stub    ICOpen
 38 stub    ICOpenFunction
 39 stub    ICRemove
 40 stub    ICSendMessage
 41 stub    ICSeqCompressFrame
 42 stub    ICSeqCompressFrameEnd
 43 stub    ICSeqCompressFrameStart
 44 stub    MCIWndCreate
 45 stub    MCIWndCreateA
 46 stub    MCIWndCreateW
 47 stub    MCIWndRegisterClass
 48 stub    StretchDIB
 49 stub    ls_ThunkData32
 50 stub    sl_ThunkData32
