@ stdcall MAPIAddress(ptr ptr str long str long ptr long long ptr ptr)
@ stdcall MAPIDeleteMail(ptr ptr str long long)
@ stdcall MAPIDetails(ptr ptr ptr long long)
@ stdcall MAPIFindNext(ptr ptr str str long long ptr)
@ stdcall MAPILogon(ptr str str long long ptr)
@ stdcall MAPILogoff(ptr ptr long long)
@ stdcall MAPIReadMail(ptr ptr str long long ptr)
@ stdcall MAPIResolveName(ptr ptr str long long ptr)
@ stdcall MAPISaveMail(ptr ptr ptr long long str)
@ stdcall MAPISendDocuments(ptr str str str long)
@ stdcall MAPISendMail(ptr ptr ptr long long)
