@ stub AccessibleChildren
@ stub AccessibleObjectFromEvent
@ stub AccessibleObjectFromPoint
@ stub AccessibleObjectFromWindow
@ stdcall CreateStdAccessibleObject(ptr long ptr ptr)
@ stub CreateStdAccessibleProxyA
@ stub CreateStdAccessibleProxyW
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub GetOleaccVersionInfo
@ stub GetRoleTextA
@ stub GetRoleTextW
@ stub GetStateTextA
@ stub GetStateTextW
@ stub IID_IAccessible
@ stub IID_IAccessibleHandler
@ stub LIBID_Accessibility
@ stub LresultFromObject
@ stub ObjectFromLresult
@ stub WindowFromAccessibleObject
