# msvcrt20.dll - MS VC++ Run Time Library
@ stub ??0Iostream_init@@QAE@AAVios@@H@Z  #
@ stub ??0Iostream_init@@QAE@XZ #
@ stub ??0filebuf@@QAE@ABV0@@Z #
@ stub ??0filebuf@@QAE@H@Z #
@ stub ??0filebuf@@QAE@HPADH@Z #
@ stub ??0filebuf@@QAE@XZ #
@ stub ??0fstream@@QAE@ABV0@@Z #
@ stub ??0fstream@@QAE@H@Z #
@ stub ??0fstream@@QAE@HPADH@Z #
@ stub ??0fstream@@QAE@PBDHH@Z #
@ stub ??0fstream@@QAE@XZ #
@ stub ??0ifstream@@QAE@ABV0@@Z #
@ stub ??0ifstream@@QAE@H@Z #
@ stub ??0ifstream@@QAE@HPADH@Z #
@ stub ??0ifstream@@QAE@PBDHH@Z #
@ stub ??0ifstream@@QAE@XZ #
@ stub ??0ios@@IAE@ABV0@@Z #
@ stub ??0ios@@IAE@XZ #
@ stub ??0ios@@QAE@PAVstreambuf@@@Z #
@ stub ??0iostream@@IAE@ABV0@@Z #
@ stub ??0iostream@@IAE@XZ #
@ stub ??0iostream@@QAE@PAVstreambuf@@@Z #
@ stub ??0istream@@IAE@ABV0@@Z #
@ stub ??0istream@@IAE@XZ #
@ stub ??0istream@@QAE@PAVstreambuf@@@Z #
@ stub ??0istream_withassign@@QAE@ABV0@@Z #
@ stub ??0istream_withassign@@QAE@PAVstreambuf@@@Z #
@ stub ??0istream_withassign@@QAE@XZ #
@ stub ??0istrstream@@QAE@ABV0@@Z #
@ stub ??0istrstream@@QAE@PAD@Z #
@ stub ??0istrstream@@QAE@PADH@Z #
@ stub ??0ofstream@@QAE@ABV0@@Z #
@ stub ??0ofstream@@QAE@H@Z #
@ stub ??0ofstream@@QAE@HPADH@Z #
@ stub ??0ofstream@@QAE@PBDHH@Z #
@ stub ??0ofstream@@QAE@XZ #
@ stub ??0ostream@@IAE@ABV0@@Z #
@ stub ??0ostream@@IAE@XZ #
@ stub ??0ostream@@QAE@PAVstreambuf@@@Z #
@ stub ??0ostream_withassign@@QAE@ABV0@@Z #
@ stub ??0ostream_withassign@@QAE@PAVstreambuf@@@Z #
@ stub ??0ostream_withassign@@QAE@XZ #
@ stub ??0ostrstream@@QAE@ABV0@@Z #
@ stub ??0ostrstream@@QAE@PADHH@Z #
@ stub ??0ostrstream@@QAE@XZ #
@ stub ??0stdiobuf@@QAE@ABV0@@Z #
@ stub ??0stdiobuf@@QAE@PAU_iobuf@@@Z #
@ stub ??0stdiostream@@QAE@ABV0@@Z #
@ stub ??0stdiostream@@QAE@PAU_iobuf@@@Z #
@ stub ??0streambuf@@IAE@PADH@Z #
@ stub ??0streambuf@@IAE@XZ #
@ stub ??0streambuf@@QAE@ABV0@@Z #
@ stub ??0strstream@@QAE@ABV0@@Z #
@ stub ??0strstream@@QAE@PADHH@Z #
@ stub ??0strstream@@QAE@XZ #
@ stub ??0strstreambuf@@QAE@ABV0@@Z #
@ stub ??0strstreambuf@@QAE@H@Z #
@ stub ??0strstreambuf@@QAE@P6APAXJ@ZP6AXPAX@Z@Z #
@ stub ??0strstreambuf@@QAE@PADH0@Z #
@ stub ??0strstreambuf@@QAE@XZ #
@ stub ??1Iostream_init@@QAE@XZ #
@ stub ??1filebuf@@UAE@XZ #
@ stub ??1fstream@@UAE@XZ #
@ stub ??1ifstream@@UAE@XZ #
@ stub ??1ios@@UAE@XZ #
@ stub ??1iostream@@UAE@XZ #
@ stub ??1istream@@UAE@XZ #
@ stub ??1istream_withassign@@UAE@XZ #
@ stub ??1istrstream@@UAE@XZ #
@ stub ??1ofstream@@UAE@XZ #
@ stub ??1ostream@@UAE@XZ #
@ stub ??1ostream_withassign@@UAE@XZ #
@ stub ??1ostrstream@@UAE@XZ #
@ stub ??1stdiobuf@@UAE@XZ #
@ stub ??1stdiostream@@UAE@XZ #
@ stub ??1streambuf@@UAE@XZ #
@ stub ??1strstream@@UAE@XZ #
@ stub ??1strstreambuf@@UAE@XZ #
@ forward ??2@YAPAXI@Z msvcrt.??2@YAPAXI@Z
@ forward ??3@YAXPAX@Z msvcrt.??3@YAXPAX@Z
@ stub ??4Iostream_init@@QAEAAV0@ABV0@@Z #
@ stub ??4filebuf@@QAEAAV0@ABV0@@Z #
@ stub ??4fstream@@QAEAAV0@AAV0@@Z #
@ stub ??4ifstream@@QAEAAV0@ABV0@@Z #
@ stub ??4ios@@IAEAAV0@ABV0@@Z #
@ stub ??4iostream@@IAEAAV0@AAV0@@Z #
@ stub ??4iostream@@IAEAAV0@PAVstreambuf@@@Z #
@ stub ??4istream@@IAEAAV0@ABV0@@Z #
@ stub ??4istream@@IAEAAV0@PAVstreambuf@@@Z #
@ stub ??4istream_withassign@@QAEAAV0@ABV0@@Z #
@ stub ??4istream_withassign@@QAEAAVistream@@ABV1@@Z #
@ stub ??4istream_withassign@@QAEAAVistream@@PAVstreambuf@@@Z #
@ stub ??4istrstream@@QAEAAV0@ABV0@@Z #
@ stub ??4ofstream@@QAEAAV0@ABV0@@Z #
@ stub ??4ostream@@IAEAAV0@ABV0@@Z #
@ stub ??4ostream@@IAEAAV0@PAVstreambuf@@@Z #
@ stub ??4ostream_withassign@@QAEAAV0@ABV0@@Z #
@ stub ??4ostream_withassign@@QAEAAVostream@@ABV1@@Z #
@ stub ??4ostream_withassign@@QAEAAVostream@@PAVstreambuf@@@Z #
@ stub ??4ostrstream@@QAEAAV0@ABV0@@Z #
@ stub ??4stdiobuf@@QAEAAV0@ABV0@@Z #
@ stub ??4stdiostream@@QAEAAV0@AAV0@@Z #
@ stub ??4streambuf@@QAEAAV0@ABV0@@Z #
@ stub ??4strstream@@QAEAAV0@AAV0@@Z #
@ stub ??4strstreambuf@@QAEAAV0@ABV0@@Z #
@ stub ??5istream@@QAEAAV0@AAC@Z #
@ stub ??5istream@@QAEAAV0@AAD@Z #
@ stub ??5istream@@QAEAAV0@AAE@Z #
@ stub ??5istream@@QAEAAV0@AAF@Z #
@ stub ??5istream@@QAEAAV0@AAG@Z #
@ stub ??5istream@@QAEAAV0@AAH@Z #
@ stub ??5istream@@QAEAAV0@AAI@Z #
@ stub ??5istream@@QAEAAV0@AAJ@Z #
@ stub ??5istream@@QAEAAV0@AAK@Z #
@ stub ??5istream@@QAEAAV0@AAM@Z #
@ stub ??5istream@@QAEAAV0@AAN@Z #
@ stub ??5istream@@QAEAAV0@AAO@Z #
@ stub ??5istream@@QAEAAV0@P6AAAV0@AAV0@@Z@Z #
@ stub ??5istream@@QAEAAV0@P6AAAVios@@AAV1@@Z@Z #
@ stub ??5istream@@QAEAAV0@PAC@Z #
@ stub ??5istream@@QAEAAV0@PAD@Z #
@ stub ??5istream@@QAEAAV0@PAE@Z #
@ stub ??5istream@@QAEAAV0@PAVstreambuf@@@Z #
@ stub ??6ostream@@QAEAAV0@C@Z #
@ stub ??6ostream@@QAEAAV0@D@Z #
@ stub ??6ostream@@QAEAAV0@E@Z #
@ stub ??6ostream@@QAEAAV0@F@Z #
@ stub ??6ostream@@QAEAAV0@G@Z #
@ stub ??6ostream@@QAEAAV0@H@Z #
@ stub ??6ostream@@QAEAAV0@I@Z #
@ stub ??6ostream@@QAEAAV0@J@Z #
@ stub ??6ostream@@QAEAAV0@K@Z #
@ stub ??6ostream@@QAEAAV0@M@Z #
@ stub ??6ostream@@QAEAAV0@N@Z #
@ stub ??6ostream@@QAEAAV0@O@Z #
@ stub ??6ostream@@QAEAAV0@P6AAAV0@AAV0@@Z@Z #
@ stub ??6ostream@@QAEAAV0@P6AAAVios@@AAV1@@Z@Z #
@ stub ??6ostream@@QAEAAV0@PAVstreambuf@@@Z #
@ stub ??6ostream@@QAEAAV0@PBC@Z #
@ stub ??6ostream@@QAEAAV0@PBD@Z #
@ stub ??6ostream@@QAEAAV0@PBE@Z #
@ stub ??6ostream@@QAEAAV0@PBX@Z #
@ stub ??7ios@@QBEHXZ #
@ stub ??Bios@@QBEPAXXZ #
@ stub ??_7filebuf@@6B@ #
@ stub ??_7fstream@@6B@ #
@ stub ??_7ifstream@@6B@ #
@ stub ??_7ios@@6B@ #
@ stub ??_7iostream@@6B@ #
@ stub ??_7istream@@6B@ #
@ stub ??_7istream_withassign@@6B@ #
@ stub ??_7istrstream@@6B@ #
@ stub ??_7ofstream@@6B@ #
@ stub ??_7ostream@@6B@ #
@ stub ??_7ostream_withassign@@6B@ #
@ stub ??_7ostrstream@@6B@ #
@ stub ??_7stdiobuf@@6B@ #
@ stub ??_7stdiostream@@6B@ #
@ stub ??_7streambuf@@6B@ #
@ stub ??_7strstream@@6B@ #
@ stub ??_7strstreambuf@@6B@ #
@ stub ??_8fstream@@7Bistream@@@ #
@ stub ??_8fstream@@7Bostream@@@ #
@ stub ??_8ifstream@@7B@ #
@ stub ??_8iostream@@7Bistream@@@ #
@ stub ??_8iostream@@7Bostream@@@ #
@ stub ??_8istream@@7B@ #
@ stub ??_8istream_withassign@@7B@ #
@ stub ??_8istrstream@@7B@ #
@ stub ??_8ofstream@@7B@ #
@ stub ??_8ostream@@7B@ #
@ stub ??_8ostream_withassign@@7B@ #
@ stub ??_8ostrstream@@7B@ #
@ stub ??_8stdiostream@@7Bistream@@@ #
@ stub ??_8stdiostream@@7Bostream@@@ #
@ stub ??_8strstream@@7Bistream@@@ #
@ stub ??_8strstream@@7Bostream@@@ #
@ stub ??_Dfstream@@QAEXXZ #
@ stub ??_Difstream@@QAEXXZ #
@ stub ??_Diostream@@QAEXXZ #
@ stub ??_Distream@@QAEXXZ #
@ stub ??_Distream_withassign@@QAEXXZ #
@ stub ??_Distrstream@@QAEXXZ #
@ stub ??_Dofstream@@QAEXXZ #
@ stub ??_Dostream@@QAEXXZ #
@ stub ??_Dostream_withassign@@QAEXXZ #
@ stub ??_Dostrstream@@QAEXXZ #
@ stub ??_Dstdiostream@@QAEXXZ #
@ stub ??_Dstrstream@@QAEXXZ #
@ stub ??_EIostream_init@@QAEPAXI@Z #
@ stub ??_Efilebuf@@UAEPAXI@Z #
@ stub ??_Efstream@@UAEPAXI@Z #
@ stub ??_Eifstream@@UAEPAXI@Z #
@ stub ??_Eios@@UAEPAXI@Z #
@ stub ??_Eiostream@@UAEPAXI@Z #
@ stub ??_Eistream@@UAEPAXI@Z #
@ stub ??_Eistream_withassign@@UAEPAXI@Z #
@ stub ??_Eistrstream@@UAEPAXI@Z #
@ stub ??_Eofstream@@UAEPAXI@Z #
@ stub ??_Eostream@@UAEPAXI@Z #
@ stub ??_Eostream_withassign@@UAEPAXI@Z #
@ stub ??_Eostrstream@@UAEPAXI@Z #
@ stub ??_Estdiobuf@@UAEPAXI@Z #
@ stub ??_Estdiostream@@UAEPAXI@Z #
@ stub ??_Estreambuf@@UAEPAXI@Z #
@ stub ??_Estrstream@@UAEPAXI@Z #
@ stub ??_Estrstreambuf@@UAEPAXI@Z #
@ stub ??_GIostream_init@@QAEPAXI@Z #
@ stub ??_Gfilebuf@@UAEPAXI@Z #
@ stub ??_Gfstream@@UAEPAXI@Z #
@ stub ??_Gifstream@@UAEPAXI@Z #
@ stub ??_Gios@@UAEPAXI@Z #
@ stub ??_Giostream@@UAEPAXI@Z #
@ stub ??_Gistream@@UAEPAXI@Z #
@ stub ??_Gistream_withassign@@UAEPAXI@Z #
@ stub ??_Gistrstream@@UAEPAXI@Z #
@ stub ??_Gofstream@@UAEPAXI@Z #
@ stub ??_Gostream@@UAEPAXI@Z #
@ stub ??_Gostream_withassign@@UAEPAXI@Z #
@ stub ??_Gostrstream@@UAEPAXI@Z #
@ stub ??_Gstdiobuf@@UAEPAXI@Z #
@ stub ??_Gstdiostream@@UAEPAXI@Z #
@ stub ??_Gstreambuf@@UAEPAXI@Z #
@ stub ??_Gstrstream@@UAEPAXI@Z #
@ stub ??_Gstrstreambuf@@UAEPAXI@Z #
@ forward ?_query_new_handler@@YAP6AHI@ZXZ msvcrt.?_query_new_handler@@YAP6AHI@ZXZ
@ forward ?_query_new_mode@@YAHXZ  msvcrt.?_query_new_mode@@YAHXZ
@ forward ?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z msvcrt.?_set_new_handler@@YAP6AHI@ZP6AHI@Z@Z
@ forward ?_set_new_mode@@YAHH@Z msvcrt.?_set_new_mode@@YAHH@Z
@ forward ?_set_se_translator@@YAP6AXIPAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z msvcrt.?_set_se_translator@@YAP6AXIPAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z
@ stub ?adjustfield@ios@@2JB #
@ stub ?allocate@streambuf@@IAEHXZ #
@ stub ?attach@filebuf@@QAEPAV1@H@Z #
@ stub ?attach@fstream@@QAEXH@Z #
@ stub ?attach@ifstream@@QAEXH@Z #
@ stub ?attach@ofstream@@QAEXH@Z #
@ stub ?bad@ios@@QBEHXZ #
@ stub ?base@streambuf@@IBEPADXZ #
@ stub ?basefield@ios@@2JB #
@ stub ?binary@filebuf@@2HB #
@ stub ?bitalloc@ios@@SAJXZ #
@ stub ?blen@streambuf@@IBEHXZ #
@ stub ?cerr@@3Vostream_withassign@@A #
@ stub ?cin@@3Vistream_withassign@@A #
@ stub ?clear@ios@@QAEXH@Z #
@ stub ?clog@@3Vostream_withassign@@A #
@ stub ?close@filebuf@@QAEPAV1@XZ #
@ stub ?close@fstream@@QAEXXZ #
@ stub ?close@ifstream@@QAEXXZ #
@ stub ?close@ofstream@@QAEXXZ #
@ stub ?clrlock@ios@@QAAXXZ #
@ stub ?clrlock@streambuf@@QAEXXZ #
@ stub ?cout@@3Vostream_withassign@@A #
@ stub ?dbp@streambuf@@QAEXXZ #
@ stub ?dec@@YAAAVios@@AAV1@@Z #
@ stub ?delbuf@ios@@QAEXH@Z #
@ stub ?delbuf@ios@@QBEHXZ #
@ stub ?doallocate@streambuf@@MAEHXZ #
@ stub ?doallocate@strstreambuf@@MAEHXZ #
@ stub ?eatwhite@istream@@QAEXXZ #
@ stub ?eback@streambuf@@IBEPADXZ #
@ stub ?ebuf@streambuf@@IBEPADXZ #
@ stub ?egptr@streambuf@@IBEPADXZ #
@ stub ?endl@@YAAAVostream@@AAV1@@Z #
@ stub ?ends@@YAAAVostream@@AAV1@@Z #
@ stub ?eof@ios@@QBEHXZ #
@ stub ?epptr@streambuf@@IBEPADXZ #
@ stub ?fLockcInit@ios@@0HA #
@ stub ?fail@ios@@QBEHXZ #
@ stub ?fd@filebuf@@QBEHXZ #
@ stub ?fd@fstream@@QBEHXZ #
@ stub ?fd@ifstream@@QBEHXZ #
@ stub ?fd@ofstream@@QBEHXZ #
@ stub ?fill@ios@@QAEDD@Z #
@ stub ?fill@ios@@QBEDXZ #
@ stub ?flags@ios@@QAEJJ@Z #
@ stub ?flags@ios@@QBEJXZ #
@ stub ?floatfield@ios@@2JB #
@ stub ?flush@@YAAAVostream@@AAV1@@Z #
@ stub ?flush@ostream@@QAEAAV1@XZ #
@ stub ?freeze@strstreambuf@@QAEXH@Z #
@ stub ?gbump@streambuf@@IAEXH@Z #
@ stub ?gcount@istream@@QBEHXZ #
@ stub ?get@istream@@QAEAAV1@AAC@Z #
@ stub ?get@istream@@QAEAAV1@AAD@Z #
@ stub ?get@istream@@QAEAAV1@AAE@Z #
@ stub ?get@istream@@QAEAAV1@AAVstreambuf@@D@Z #
@ stub ?get@istream@@QAEAAV1@PACHD@Z #
@ stub ?get@istream@@QAEAAV1@PADHD@Z #
@ stub ?get@istream@@QAEAAV1@PAEHD@Z #
@ stub ?get@istream@@QAEHXZ #
@ stub ?getdouble@istream@@AAEHPADH@Z #
@ stub ?getint@istream@@AAEHPAD@Z #
@ stub ?getline@istream@@QAEAAV1@PACHD@Z #
@ stub ?getline@istream@@QAEAAV1@PADHD@Z #
@ stub ?getline@istream@@QAEAAV1@PAEHD@Z #
@ stub ?good@ios@@QBEHXZ #
@ stub ?gptr@streambuf@@IBEPADXZ #
@ stub ?hex@@YAAAVios@@AAV1@@Z #
@ stub ?ignore@istream@@QAEAAV1@HH@Z #
@ stub ?in_avail@streambuf@@QBEHXZ #
@ stub ?init@ios@@IAEXPAVstreambuf@@@Z #
@ stub ?ipfx@istream@@QAEHH@Z #
@ stub ?is_open@filebuf@@QBEHXZ #
@ stub ?is_open@fstream@@QBEHXZ #
@ stub ?is_open@ifstream@@QBEHXZ #
@ stub ?is_open@ofstream@@QBEHXZ #
@ stub ?isfx@istream@@QAEXXZ #
@ stub ?iword@ios@@QBEAAJH@Z #
@ stub ?lock@ios@@QAAXXZ #
@ stub ?lock@streambuf@@QAEXXZ #
@ stub ?lockbuf@ios@@QAAXXZ #
@ stub ?lockc@ios@@KAXXZ #
@ stub ?lockptr@ios@@IAEPAU_RTL_CRITICAL_SECTION@@XZ #
@ stub ?lockptr@streambuf@@IAEPAU_RTL_CRITICAL_SECTION@@XZ #
@ stub ?oct@@YAAAVios@@AAV1@@Z #
@ stub ?open@filebuf@@QAEPAV1@PBDHH@Z #
@ stub ?open@fstream@@QAEXPBDHH@Z #
@ stub ?open@ifstream@@QAEXPBDHH@Z #
@ stub ?open@ofstream@@QAEXPBDHH@Z #
@ stub ?openprot@filebuf@@2HB #
@ stub ?opfx@ostream@@QAEHXZ #
@ stub ?osfx@ostream@@QAEXXZ #
@ stub ?out_waiting@streambuf@@QBEHXZ #
@ stub ?overflow@filebuf@@UAEHH@Z #
@ stub ?overflow@stdiobuf@@UAEHH@Z #
@ stub ?overflow@strstreambuf@@UAEHH@Z #
@ stub ?pbackfail@stdiobuf@@UAEHH@Z #
@ stub ?pbackfail@streambuf@@UAEHH@Z #
@ stub ?pbase@streambuf@@IBEPADXZ #
@ stub ?pbump@streambuf@@IAEXH@Z #
@ stub ?pcount@ostrstream@@QBEHXZ #
@ stub ?pcount@strstream@@QBEHXZ #
@ stub ?peek@istream@@QAEHXZ #
@ stub ?pptr@streambuf@@IBEPADXZ #
@ stub ?precision@ios@@QAEHH@Z #
@ stub ?precision@ios@@QBEHXZ #
@ stub ?put@ostream@@QAEAAV1@C@Z #
@ stub ?put@ostream@@QAEAAV1@D@Z #
@ stub ?put@ostream@@QAEAAV1@E@Z #
@ stub ?putback@istream@@QAEAAV1@D@Z #
@ stub ?pword@ios@@QBEAAPAXH@Z #
@ stub ?rdbuf@fstream@@QBEPAVfilebuf@@XZ #
@ stub ?rdbuf@ifstream@@QBEPAVfilebuf@@XZ #
@ stub ?rdbuf@ios@@QBEPAVstreambuf@@XZ #
@ stub ?rdbuf@istrstream@@QBEPAVstrstreambuf@@XZ #
@ stub ?rdbuf@ofstream@@QBEPAVfilebuf@@XZ #
@ stub ?rdbuf@ostrstream@@QBEPAVstrstreambuf@@XZ #
@ stub ?rdbuf@stdiostream@@QBEPAVstdiobuf@@XZ #
@ stub ?rdbuf@strstream@@QBEPAVstrstreambuf@@XZ #
@ stub ?rdstate@ios@@QBEHXZ #
@ stub ?read@istream@@QAEAAV1@PACH@Z #
@ stub ?read@istream@@QAEAAV1@PADH@Z #
@ stub ?read@istream@@QAEAAV1@PAEH@Z #
@ stub ?sbumpc@streambuf@@QAEHXZ #
@ stub ?seekg@istream@@QAEAAV1@J@Z #
@ stub ?seekg@istream@@QAEAAV1@JW4seek_dir@ios@@@Z #
@ stub ?seekoff@filebuf@@UAEJJW4seek_dir@ios@@H@Z #
@ stub ?seekoff@stdiobuf@@UAEJJW4seek_dir@ios@@H@Z #
@ stub ?seekoff@streambuf@@UAEJJW4seek_dir@ios@@H@Z #
@ stub ?seekoff@strstreambuf@@UAEJJW4seek_dir@ios@@H@Z #
@ stub ?seekp@ostream@@QAEAAV1@J@Z #
@ stub ?seekp@ostream@@QAEAAV1@JW4seek_dir@ios@@@Z #
@ stub ?seekpos@streambuf@@UAEJJH@Z #
@ forward ?set_terminate@@YAP6AXXZP6AXXZ@Z msvcrt.?set_terminate@@YAP6AXXZP6AXXZ@Z
@ forward ?set_unexpected@@YAP6AXXZP6AXXZ@Z msvcrt.?set_unexpected@@YAP6AXXZP6AXXZ@Z
@ stub ?setb@streambuf@@IAEXPAD0H@Z #
@ stub ?setbuf@filebuf@@UAEPAVstreambuf@@PADH@Z #
@ stub ?setbuf@fstream@@QAEPAVstreambuf@@PADH@Z #
@ stub ?setbuf@ifstream@@QAEPAVstreambuf@@PADH@Z #
@ stub ?setbuf@ofstream@@QAEPAVstreambuf@@PADH@Z #
@ stub ?setbuf@streambuf@@UAEPAV1@PADH@Z #
@ stub ?setbuf@strstreambuf@@UAEPAVstreambuf@@PADH@Z #
@ stub ?setf@ios@@QAEJJ@Z #
@ stub ?setf@ios@@QAEJJJ@Z #
@ stub ?setg@streambuf@@IAEXPAD00@Z #
@ stub ?setlock@ios@@QAAXXZ #
@ stub ?setlock@streambuf@@QAEXXZ #
@ stub ?setmode@filebuf@@QAEHH@Z #
@ stub ?setmode@fstream@@QAEHH@Z #
@ stub ?setmode@ifstream@@QAEHH@Z #
@ stub ?setmode@ofstream@@QAEHH@Z #
@ stub ?setp@streambuf@@IAEXPAD0@Z #
@ stub ?setrwbuf@stdiobuf@@QAEHHH@Z #
@ stub ?sgetc@streambuf@@QAEHXZ #
@ stub ?sgetn@streambuf@@QAEHPADH@Z #
@ stub ?sh_none@filebuf@@2HB #
@ stub ?sh_read@filebuf@@2HB #
@ stub ?sh_write@filebuf@@2HB #
@ stub ?snextc@streambuf@@QAEHXZ #
@ stub ?sputbackc@streambuf@@QAEHD@Z #
@ stub ?sputc@streambuf@@QAEHH@Z #
@ stub ?sputn@streambuf@@QAEHPBDH@Z #
@ stub ?stdiofile@stdiobuf@@QAEPAU_iobuf@@XZ #
@ stub ?stossc@streambuf@@QAEXXZ #
@ stub ?str@istrstream@@QAEPADXZ #
@ stub ?str@ostrstream@@QAEPADXZ #
@ stub ?str@strstream@@QAEPADXZ #
@ stub ?str@strstreambuf@@QAEPADXZ #
@ stub ?sunk_with_stdio@ios@@0HA #
@ stub ?sync@filebuf@@UAEHXZ #
@ stub ?sync@istream@@QAEHXZ #
@ stub ?sync@stdiobuf@@UAEHXZ #
@ stub ?sync@streambuf@@UAEHXZ #
@ stub ?sync@strstreambuf@@UAEHXZ #
@ stub ?sync_with_stdio@ios@@SAXXZ #
@ stub ?tellg@istream@@QAEJXZ #
@ stub ?tellp@ostream@@QAEJXZ #
@ forward ?terminate@@YAXXZ msvcrt.?terminate@@YAXXZ
@ stub ?text@filebuf@@2HB #
@ stub ?tie@ios@@QAEPAVostream@@PAV2@@Z #
@ stub ?tie@ios@@QBEPAVostream@@XZ #
@ stub ?unbuffered@streambuf@@IAEXH@Z #
@ stub ?unbuffered@streambuf@@IBEHXZ #
@ stub ?underflow@filebuf@@UAEHXZ #
@ stub ?underflow@stdiobuf@@UAEHXZ #
@ stub ?underflow@strstreambuf@@UAEHXZ #
@ forward ?unexpected@@YAXXZ msvcrt.?unexpected@@YAXXZ
@ stub ?unlock@ios@@QAAXXZ #
@ stub ?unlock@streambuf@@QAEXXZ #
@ stub ?unlockbuf@ios@@QAAXXZ #
@ stub ?unlockc@ios@@KAXXZ #
@ stub ?unsetf@ios@@QAEJJ@Z #
@ stub ?width@ios@@QAEHH@Z #
@ stub ?width@ios@@QBEHXZ #
@ stub ?write@ostream@@QAEAAV1@PBCH@Z #
@ stub ?write@ostream@@QAEAAV1@PBDH@Z #
@ stub ?write@ostream@@QAEAAV1@PBEH@Z #
@ stub ?writepad@ostream@@AAEAAV1@PBD0@Z #
@ stub ?ws@@YAAAVistream@@AAV1@@Z #
@ stub ?x_curindex@ios@@0HA #
@ stub ?x_lockc@ios@@0U_RTL_CRITICAL_SECTION@@A #
@ stub ?x_maxbit@ios@@0JA #
@ stub ?x_statebuf@ios@@0QAJA #
@ stub ?xalloc@ios@@SAHXZ #
@ stub ?xsgetn@streambuf@@UAEHPADH@Z #
@ stub ?xsputn@streambuf@@UAEHPBDH@Z #
@ stub $I10_OUTPUT #
@ forward _CIacos msvcrt._CIacos
@ forward _CIasin msvcrt._CIasin
@ forward _CIatan msvcrt._CIatan
@ forward _CIatan2 msvcrt._CIatan2
@ forward _CIcos msvcrt._CIcos
@ forward _CIcosh msvcrt._CIcosh
@ forward _CIexp msvcrt._CIexp
@ forward _CIfmod msvcrt._CIfmod
@ forward _CIlog msvcrt._CIlog
@ forward _CIlog10 msvcrt._CIlog10
@ forward _CIpow msvcrt._CIpow
@ forward _CIsin msvcrt._CIsin
@ forward _CIsinh msvcrt._CIsinh
@ forward _CIsqrt msvcrt._CIsqrt
@ forward _CItan msvcrt._CItan
@ forward _CItanh msvcrt._CItanh
@ forward _CxxThrowException msvcrt._CxxThrowException
@ forward _HUGE msvcrt._HUGE
@ forward _XcptFilter msvcrt._XcptFilter
@ forward __CxxFrameHandler msvcrt.__CxxFrameHandler
@ forward __CxxLongjmpUnwind msvcrt.__CxxLongjmpUnwind
@ forward __STRINGTOLD msvcrt.__STRINGTOLD
@ forward __argc msvcrt.__argc
@ forward __argv msvcrt.__argv
@ forward __dllonexit msvcrt.__dllonexit
@ forward __doserrno msvcrt.__doserrno
@ forward __fpecode msvcrt.__fpecode
@ cdecl __getmainargs(ptr ptr ptr long long) MSVCRT20__getmainargs
@ forward __initenv msvcrt.__initenv
@ forward __isascii msvcrt.__isascii
@ forward __iscsym msvcrt.__iscsym
@ forward __iscsymf msvcrt.__iscsymf
@ forward __lconv_init msvcrt.__lconv_init
@ forward __mb_cur_max msvcrt.__mb_cur_max
@ forward __p___argc msvcrt.__p___argc
@ forward __p___argv msvcrt.__p___argv
@ forward __p___initenv msvcrt.__p___initenv
@ forward __p___mb_cur_max msvcrt.__p___mb_cur_max
@ forward __p___wargv msvcrt.__p___wargv
@ forward __p___winitenv msvcrt.__p___winitenv
@ forward __p__acmdln msvcrt.__p__acmdln
@ forward __p__amblksiz msvcrt.__p__amblksiz
@ forward __p__commode msvcrt.__p__commode
@ forward __p__daylight msvcrt.__p__daylight
@ forward __p__environ msvcrt.__p__environ
@ forward __p__fmode msvcrt.__p__fmode
@ forward __p__iob msvcrt.__p__iob
@ forward __p__mbctype msvcrt.__p__mbctype
@ forward __p__osver msvcrt.__p__osver
@ forward __p__pctype msvcrt.__p__pctype
@ forward __p__pgmptr msvcrt.__p__pgmptr
@ forward __p__pwctype msvcrt.__p__pwctype
@ forward __p__timezone msvcrt.__p__timezone
@ forward __p__tzname msvcrt.__p__tzname
@ forward __p__wcmdln msvcrt.__p__wcmdln
@ forward __p__wenviron msvcrt.__p__wenviron
@ forward __p__winmajor msvcrt.__p__winmajor
@ forward __p__winminor msvcrt.__p__winminor
@ forward __p__winver msvcrt.__p__winver
@ forward __p__wpgmptr msvcrt.__p__wpgmptr
@ forward __pxcptinfoptrs msvcrt.__pxcptinfoptrs
@ forward __threadhandle msvcrt.__threadhandle
@ forward __threadid msvcrt.__threadid
@ forward __toascii msvcrt.__toascii
@ forward __wargv msvcrt.__wargv
@ cdecl __wgetmainargs(ptr ptr ptr long long) MSVCRT20__wgetmainargs
@ forward __winitenv msvcrt.__winitenv
@ forward _abnormal_termination msvcrt._abnormal_termination
@ forward _access msvcrt._access
@ forward _acmdln msvcrt._acmdln
@ forward _adj_fdiv_m16i msvcrt._adj_fdiv_m16i
@ forward _adj_fdiv_m32 msvcrt._adj_fdiv_m32
@ forward _adj_fdiv_m32i msvcrt._adj_fdiv_m32i
@ forward _adj_fdiv_m64 msvcrt._adj_fdiv_m64
@ forward _adj_fdiv_r msvcrt._adj_fdiv_r
@ forward _adj_fdivr_m16i msvcrt._adj_fdivr_m16i
@ forward _adj_fdivr_m32 msvcrt._adj_fdivr_m32
@ forward _adj_fdivr_m32i msvcrt._adj_fdivr_m32i
@ forward _adj_fdivr_m64 msvcrt._adj_fdivr_m64
@ forward _adj_fpatan msvcrt._adj_fpatan
@ forward _adj_fprem msvcrt._adj_fprem
@ forward _adj_fprem1 msvcrt._adj_fprem1
@ forward _adj_fptan msvcrt._adj_fptan
@ forward _adjust_fdiv msvcrt._adjust_fdiv
@ forward _aexit_rtn msvcrt._aexit_rtn
@ forward _amsg_exit msvcrt._amsg_exit
@ forward _assert msvcrt._assert
@ forward _atodbl msvcrt._atodbl
@ forward _atoi64 msvcrt._atoi64
@ forward _atoldbl msvcrt._atoldbl
@ forward _beep msvcrt._beep
@ forward _beginthread msvcrt._beginthread
@ forward _beginthreadex msvcrt._beginthreadex
@ forward _c_exit msvcrt._c_exit
@ forward _cabs msvcrt._cabs
@ forward _cexit msvcrt._cexit
@ forward _cgets msvcrt._cgets
@ forward _chdir msvcrt._chdir
@ forward _chdrive msvcrt._chdrive
@ forward _chgsign msvcrt._chgsign
@ forward _chmod msvcrt._chmod
@ forward _chsize msvcrt._chsize
@ forward _clearfp msvcrt._clearfp
@ forward _close msvcrt._close
@ forward _commit msvcrt._commit
@ forward _commode msvcrt._commode
@ forward _control87 msvcrt._control87
@ forward _controlfp msvcrt._controlfp
@ forward _copysign msvcrt._copysign
@ forward _cprintf msvcrt._cprintf
@ forward _cputs msvcrt._cputs
@ forward _creat msvcrt._creat
@ forward _cscanf msvcrt._cscanf
@ forward _ctype msvcrt._ctype
@ forward _cwait msvcrt._cwait
@ forward _daylight msvcrt._daylight
@ forward _dup msvcrt._dup
@ forward _dup2 msvcrt._dup2
@ forward _ecvt msvcrt._ecvt
@ forward _endthread msvcrt._endthread
@ forward _endthreadex msvcrt._endthreadex
@ forward _environ msvcrt._environ
@ forward _eof msvcrt._eof
@ forward _errno msvcrt._errno
@ forward _except_handler2 msvcrt._except_handler2
@ forward _except_handler3 msvcrt._except_handler3
@ forward _execl msvcrt._execl
@ forward _execle msvcrt._execle
@ forward _execlp msvcrt._execlp
@ forward _execlpe msvcrt._execlpe
@ forward _execv msvcrt._execv
@ forward _execve msvcrt._execve
@ forward _execvp msvcrt._execvp
@ forward _execvpe msvcrt._execvpe
@ forward _exit msvcrt._exit
@ forward _expand msvcrt._expand
@ forward _fcloseall msvcrt._fcloseall
@ forward _fcvt msvcrt._fcvt
@ forward _fdopen msvcrt._fdopen
@ forward _fgetchar msvcrt._fgetchar
@ forward _fgetwchar msvcrt._fgetwchar
@ forward _filbuf msvcrt._filbuf
@ forward _fileinfo msvcrt._fileinfo
@ forward _filelength msvcrt._filelength
@ forward _fileno msvcrt._fileno
@ forward _findclose msvcrt._findclose
@ forward _findfirst msvcrt._findfirst
@ forward _findnext msvcrt._findnext
@ forward _finite msvcrt._finite
@ forward _flsbuf msvcrt._flsbuf
@ forward _flushall msvcrt._flushall
@ forward _fmode msvcrt._fmode
@ forward _fpclass msvcrt._fpclass
@ forward _fpieee_flt msvcrt._fpieee_flt
@ forward _fpreset msvcrt._fpreset
@ forward _fputchar msvcrt._fputchar
@ forward _fputwchar msvcrt._fputwchar
@ forward _fsopen msvcrt._fsopen
@ forward _fstat msvcrt._fstat
@ forward _ftime msvcrt._ftime
@ forward _ftol msvcrt._ftol
@ forward _fullpath msvcrt._fullpath
@ forward _futime msvcrt._futime
@ forward _gcvt msvcrt._gcvt
@ forward _get_osfhandle msvcrt._get_osfhandle
@ forward _getch msvcrt._getch
@ forward _getche msvcrt._getche
@ forward _getcwd msvcrt._getcwd
@ forward _getdcwd msvcrt._getdcwd
@ forward _getdiskfree msvcrt._getdiskfree
@ forward _getdllprocaddr msvcrt._getdllprocaddr
@ forward _getdrive msvcrt._getdrive
@ forward _getdrives msvcrt._getdrives
@ forward _getmbcp msvcrt._getmbcp
@ forward _getpid msvcrt._getpid
@ forward _getsystime msvcrt._getsystime
@ forward _getw msvcrt._getw
@ forward _getws msvcrt._getws
@ forward _global_unwind2 msvcrt._global_unwind2
@ forward _heapadd msvcrt._heapadd
@ forward _heapchk msvcrt._heapchk
@ forward _heapmin msvcrt._heapmin
@ forward _heapset msvcrt._heapset
@ forward _heapused msvcrt._heapused
@ forward _heapwalk msvcrt._heapwalk
@ forward _hypot msvcrt._hypot
@ forward _i64toa msvcrt._i64toa
@ forward _i64tow msvcrt._i64tow
@ forward _initterm msvcrt._initterm
@ forward _iob msvcrt._iob
@ forward _isatty msvcrt._isatty
@ forward _isctype msvcrt._isctype
@ forward _ismbbalnum msvcrt._ismbbalnum
@ forward _ismbbalpha msvcrt._ismbbalpha
@ forward _ismbbgraph msvcrt._ismbbgraph
@ forward _ismbbkalnum msvcrt._ismbbkalnum
@ forward _ismbbkana msvcrt._ismbbkana
@ forward _ismbbkprint msvcrt._ismbbkprint
@ forward _ismbbkpunct msvcrt._ismbbkpunct
@ forward _ismbblead msvcrt._ismbblead
@ forward _ismbbprint msvcrt._ismbbprint
@ forward _ismbbpunct msvcrt._ismbbpunct
@ forward _ismbbtrail msvcrt._ismbbtrail
@ forward _ismbcalnum msvcrt._ismbcalnum
@ forward _ismbcalpha msvcrt._ismbcalpha
@ forward _ismbcdigit msvcrt._ismbcdigit
@ forward _ismbcgraph msvcrt._ismbcgraph
@ forward _ismbchira msvcrt._ismbchira
@ forward _ismbckata msvcrt._ismbckata
@ forward _ismbcl0 msvcrt._ismbcl0
@ forward _ismbcl1 msvcrt._ismbcl1
@ forward _ismbcl2 msvcrt._ismbcl2
@ forward _ismbclegal msvcrt._ismbclegal
@ forward _ismbclower msvcrt._ismbclower
@ forward _ismbcprint msvcrt._ismbcprint
@ forward _ismbcpunct msvcrt._ismbcpunct
@ forward _ismbcspace msvcrt._ismbcspace
@ forward _ismbcsymbol msvcrt._ismbcsymbol
@ forward _ismbcupper msvcrt._ismbcupper
@ forward _ismbslead msvcrt._ismbslead
@ forward _ismbstrail msvcrt._ismbstrail
@ forward _isnan msvcrt._isnan
@ forward _itoa msvcrt._itoa
@ forward _itow msvcrt._itow
@ forward _j0 msvcrt._j0
@ forward _j1 msvcrt._j1
@ forward _jn msvcrt._jn
@ forward _kbhit msvcrt._kbhit
@ forward _lfind msvcrt._lfind
@ forward _loaddll msvcrt._loaddll
@ forward _local_unwind2 msvcrt._local_unwind2
@ forward _locking msvcrt._locking
@ forward _logb msvcrt._logb
@ forward _longjmpex msvcrt._longjmpex
@ forward _lrotl msvcrt._lrotl
@ forward _lrotr msvcrt._lrotr
@ forward _lsearch msvcrt._lsearch
@ forward _lseek msvcrt._lseek
@ forward _ltoa msvcrt._ltoa
@ forward _ltow msvcrt._ltow
@ forward _makepath msvcrt._makepath
@ forward _matherr msvcrt._matherr
@ forward _mbbtombc msvcrt._mbbtombc
@ forward _mbbtype msvcrt._mbbtype
@ forward _mbccpy msvcrt._mbccpy
@ forward _mbcjistojms msvcrt._mbcjistojms
@ forward _mbcjmstojis msvcrt._mbcjmstojis
@ forward _mbclen msvcrt._mbclen
@ forward _mbctohira msvcrt._mbctohira
@ forward _mbctokata msvcrt._mbctokata
@ forward _mbctolower msvcrt._mbctolower
@ forward _mbctombb msvcrt._mbctombb
@ forward _mbctoupper msvcrt._mbctoupper
@ forward _mbctype msvcrt._mbctype
@ forward _mbsbtype msvcrt._mbsbtype
@ forward _mbscat msvcrt._mbscat
@ forward _mbschr msvcrt._mbschr
@ forward _mbscmp msvcrt._mbscmp
@ forward _mbscoll msvcrt._mbscoll
@ forward _mbscpy msvcrt._mbscpy
@ forward _mbscspn msvcrt._mbscspn
@ forward _mbsdec msvcrt._mbsdec
@ forward _mbsdup msvcrt._mbsdup
@ forward _mbsicmp msvcrt._mbsicmp
@ forward _mbsicoll msvcrt._mbsicoll
@ forward _mbsinc msvcrt._mbsinc
@ forward _mbslen msvcrt._mbslen
@ forward _mbslwr msvcrt._mbslwr
@ forward _mbsnbcat msvcrt._mbsnbcat
@ forward _mbsnbcmp msvcrt._mbsnbcmp
@ forward _mbsnbcnt msvcrt._mbsnbcnt
@ forward _mbsnbcoll msvcrt._mbsnbcoll
@ forward _mbsnbcpy msvcrt._mbsnbcpy
@ forward _mbsnbicmp msvcrt._mbsnbicmp
@ forward _mbsnbicoll msvcrt._mbsnbicoll
@ forward _mbsnbset msvcrt._mbsnbset
@ forward _mbsncat msvcrt._mbsncat
@ forward _mbsnccnt msvcrt._mbsnccnt
@ forward _mbsncmp msvcrt._mbsncmp
@ forward _mbsncoll msvcrt._mbsncoll
@ forward _mbsncpy msvcrt._mbsncpy
@ forward _mbsnextc msvcrt._mbsnextc
@ forward _mbsnicmp msvcrt._mbsnicmp
@ forward _mbsnicoll msvcrt._mbsnicoll
@ forward _mbsninc msvcrt._mbsninc
@ forward _mbsnset msvcrt._mbsnset
@ forward _mbspbrk msvcrt._mbspbrk
@ forward _mbsrchr msvcrt._mbsrchr
@ forward _mbsrev msvcrt._mbsrev
@ forward _mbsset msvcrt._mbsset
@ forward _mbsspn msvcrt._mbsspn
@ forward _mbsspnp msvcrt._mbsspnp
@ forward _mbsstr msvcrt._mbsstr
@ forward _mbstok msvcrt._mbstok
@ forward _mbstrlen msvcrt._mbstrlen
@ forward _mbsupr msvcrt._mbsupr
@ forward _memccpy msvcrt._memccpy
@ forward _memicmp msvcrt._memicmp
@ forward _mkdir msvcrt._mkdir
@ forward _mktemp msvcrt._mktemp
@ forward _msize msvcrt._msize
@ stub _mtlock
@ stub _mtunlock
@ forward _nextafter msvcrt._nextafter
@ forward _onexit msvcrt._onexit
@ forward _open msvcrt._open
@ forward _open_osfhandle msvcrt._open_osfhandle
@ forward _osver msvcrt._osver
@ forward _pclose msvcrt._pclose
@ forward _pctype msvcrt._pctype
@ forward _pgmptr msvcrt._pgmptr
@ forward _pipe msvcrt._pipe
@ forward _popen msvcrt._popen
@ forward _purecall msvcrt._purecall
@ forward _putch msvcrt._putch
@ forward _putenv msvcrt._putenv
@ forward _putw msvcrt._putw
@ forward _putws msvcrt._putws
@ forward _pwctype msvcrt._pwctype
@ forward _read msvcrt._read
@ forward _rmdir msvcrt._rmdir
@ forward _rmtmp msvcrt._rmtmp
@ forward _rotl msvcrt._rotl
@ forward _rotr msvcrt._rotr
@ forward _safe_fdiv msvcrt._safe_fdiv
@ forward _safe_fdivr msvcrt._safe_fdivr
@ forward _safe_fprem msvcrt._safe_fprem
@ forward _safe_fprem1 msvcrt._safe_fprem1
@ forward _scalb msvcrt._scalb
@ forward _searchenv msvcrt._searchenv
@ forward __seh_longjmp_unwind msvcrt._seh_longjmp_unwind
@ forward _seterrormode msvcrt._seterrormode
@ forward _setjmp msvcrt._setjmp
@ forward _setjmp3 msvcrt._setjmp3
@ forward _setmbcp msvcrt._setmbcp
@ forward _setmode msvcrt._setmode
@ forward _setsystime msvcrt._setsystime
@ forward _sleep msvcrt._sleep
@ forward _snprintf msvcrt._snprintf
@ forward _snwprintf msvcrt._snwprintf
@ forward _sopen msvcrt._sopen
@ forward _spawnl msvcrt._spawnl
@ forward _spawnle msvcrt._spawnle
@ forward _spawnlp msvcrt._spawnlp
@ forward _spawnlpe msvcrt._spawnlpe
@ forward _spawnv msvcrt._spawnv
@ forward _spawnve msvcrt._spawnve
@ forward _spawnvp msvcrt._spawnvp
@ forward _spawnvpe msvcrt._spawnvpe
@ forward _splitpath msvcrt._splitpath
@ forward _stat msvcrt._stat
@ forward _statusfp msvcrt._statusfp
@ forward _strcmpi msvcrt._strcmpi
@ forward _strdate msvcrt._strdate
@ forward _strdup msvcrt._strdup
@ forward _strerror msvcrt._strerror
@ forward _stricmp msvcrt._stricmp
@ forward _stricoll msvcrt._stricoll
@ forward _strlwr msvcrt._strlwr
@ forward _strncoll msvcrt._strncoll
@ forward _strnicmp msvcrt._strnicmp
@ forward _strnicoll msvcrt._strnicoll
@ forward _strnset msvcrt._strnset
@ forward _strrev msvcrt._strrev
@ forward _strset msvcrt._strset
@ forward _strtime msvcrt._strtime
@ forward _strupr msvcrt._strupr
@ forward _swab msvcrt._swab
@ forward _sys_errlist msvcrt._sys_errlist
@ forward _sys_nerr msvcrt._sys_nerr
@ forward _tccpy msvcrt._mbccpy
@ forward _tclen msvcrt._mbclen
@ forward _tcschr msvcrt._mbschr
@ forward _tcsclen msvcrt._mbslen
@ forward _tcscmp msvcrt._mbscmp
@ forward _tcscspn msvcrt._mbscspn
@ forward _tcsdec msvcrt._mbsdec
@ forward _tcsicmp msvcrt._mbsicmp
@ forward _tcsinc msvcrt._mbsinc
@ forward _tcslwr msvcrt._mbslwr
@ forward _tcsnbcnt msvcrt._mbsnbcnt
@ forward _tcsncat msvcrt._mbsnbcat
@ forward _tcsnccat msvcrt._mbsncat
@ forward _tcsnccmp msvcrt._mbsncmp
@ forward _tcsnccnt msvcrt._mbsnccnt
@ forward _tcsnccpy msvcrt._mbsncpy
@ forward _tcsncicmp msvcrt._mbsnicmp
@ forward _tcsncmp msvcrt._mbsnbcmp
@ forward _tcsncpy msvcrt._mbsnbcpy
@ forward _tcsncset msvcrt._mbsnset
@ forward _tcsnextc msvcrt._mbsnextc
@ forward _tcsnicmp msvcrt._mbsnbicmp
@ forward _tcsninc msvcrt._mbsninc
@ forward _tcsnset msvcrt._mbsnbset
@ forward _tcspbrk msvcrt._mbspbrk
@ forward _tcsrchr msvcrt._mbsrchr
@ forward _tcsrev msvcrt._mbsrev
@ forward _tcsset msvcrt._mbsset
@ forward _tcsspn msvcrt._mbsspn
@ forward _tcsspnp msvcrt._mbsspnp
@ forward _tcsstr msvcrt._mbsstr
@ forward _tcstok msvcrt._mbstok
@ forward _tcsupr msvcrt._mbsupr
@ forward _tell msvcrt._tell
@ forward _tempnam msvcrt._tempnam
@ forward _timezone msvcrt._timezone
@ forward _tolower msvcrt._tolower
@ forward _toupper msvcrt._toupper
@ forward _tzname msvcrt._tzname
@ forward _tzset msvcrt._tzset
@ forward _ui64toa msvcrt._ui64toa
@ forward _ui64tow msvcrt._ui64tow
@ forward _ultoa msvcrt._ultoa
@ forward _ultow msvcrt._ultow
@ forward _umask msvcrt._umask
@ forward _ungetch msvcrt._ungetch
@ forward _unlink msvcrt._unlink
@ forward _unloaddll msvcrt._unloaddll
@ forward _utime msvcrt._utime
@ forward _vsnprintf msvcrt._vsnprintf
@ forward _vsnwprintf msvcrt._vsnwprintf
@ forward _waccess msvcrt._waccess
@ forward _wasctime msvcrt._wasctime
@ forward _wchdir msvcrt._wchdir
@ forward _wchmod msvcrt._wchmod
@ forward _wcmdln msvcrt._wcmdln
@ forward _wcreat msvcrt._wcreat
@ forward _wcsdup msvcrt._wcsdup
@ forward _wcsicmp msvcrt._wcsicmp
@ forward _wcsicoll msvcrt._wcsicoll
@ forward _wcslwr msvcrt._wcslwr
@ forward _wcsncoll msvcrt._wcsncoll
@ forward _wcsnicmp msvcrt._wcsnicmp
@ forward _wcsnicoll msvcrt._wcsnicoll
@ forward _wcsnset msvcrt._wcsnset
@ forward _wcsrev msvcrt._wcsrev
@ forward _wcsset msvcrt._wcsset
@ forward _wcsupr msvcrt._wcsupr
@ forward _wctime msvcrt._wctime
@ forward _wenviron msvcrt._wenviron
@ forward _wexecl msvcrt._wexecl
@ forward _wexecle msvcrt._wexecle
@ forward _wexeclp msvcrt._wexeclp
@ forward _wexeclpe msvcrt._wexeclpe
@ forward _wexecv msvcrt._wexecv
@ forward _wexecve msvcrt._wexecve
@ forward _wexecvp msvcrt._wexecvp
@ forward _wexecvpe msvcrt._wexecvpe
@ forward _wfdopen msvcrt._wfdopen
@ forward _wfindfirst msvcrt._wfindfirst
@ forward _wfindnext msvcrt._wfindnext
@ forward _wfopen msvcrt._wfopen
@ forward _wfreopen msvcrt._wfreopen
@ forward _wfsopen msvcrt._wfsopen
@ forward _wfullpath msvcrt._wfullpath
@ forward _wgetcwd msvcrt._wgetcwd
@ forward _wgetdcwd msvcrt._wgetdcwd
@ forward _wgetenv msvcrt._wgetenv
@ forward _winmajor msvcrt._winmajor
@ forward _winminor msvcrt._winminor
@ forward _winver msvcrt._winver
@ forward _wmakepath msvcrt._wmakepath
@ forward _wmkdir msvcrt._wmkdir
@ forward _wmktemp msvcrt._wmktemp
@ forward _wopen msvcrt._wopen
@ forward _wperror msvcrt._wperror
@ forward _wpgmptr msvcrt._wpgmptr
@ forward _wpopen msvcrt._wpopen
@ forward _wputenv msvcrt._wputenv
@ forward _wremove msvcrt._wremove
@ forward _wrename msvcrt._wrename
@ forward _write msvcrt._write
@ forward _wrmdir msvcrt._wrmdir
@ forward _wsearchenv msvcrt._wsearchenv
@ forward _wsetlocale msvcrt._wsetlocale
@ forward _wsopen msvcrt._wsopen
@ forward _wspawnl msvcrt._wspawnl
@ forward _wspawnle msvcrt._wspawnle
@ forward _wspawnlp msvcrt._wspawnlp
@ forward _wspawnlpe msvcrt._wspawnlpe
@ forward _wspawnv msvcrt._wspawnv
@ forward _wspawnve msvcrt._wspawnve
@ forward _wspawnvp msvcrt._wspawnvp
@ forward _wspawnvpe msvcrt._wspawnvpe
@ forward _wsplitpath msvcrt._wsplitpath
@ forward _wstat msvcrt._wstat
@ forward _wstrdate msvcrt._wstrdate
@ forward _wstrtime msvcrt._wstrtime
@ forward _wsystem msvcrt._wsystem
@ forward _wtempnam msvcrt._wtempnam
@ forward _wtmpnam msvcrt._wtmpnam
@ forward _wtoi msvcrt._wtoi
@ forward _wtoi64 msvcrt._wtoi64
@ forward _wtol msvcrt._wtol
@ forward _wunlink msvcrt._wunlink
@ forward _wutime msvcrt._wutime
@ forward _y0 msvcrt._y0
@ forward _y1 msvcrt._y1
@ forward _yn msvcrt._yn
@ forward abort msvcrt.abort
@ forward abs msvcrt.abs
@ forward acos msvcrt.acos
@ forward asctime msvcrt.asctime
@ forward asin msvcrt.asin
@ forward atan msvcrt.atan
@ forward atan2 msvcrt.atan2
@ forward atexit msvcrt.atexit
@ forward atof msvcrt.atof
@ forward atoi msvcrt.atoi
@ forward atol msvcrt.atol
@ forward bsearch msvcrt.bsearch
@ forward calloc msvcrt.calloc
@ forward ceil msvcrt.ceil
@ forward clearerr msvcrt.clearerr
@ forward clock msvcrt.clock
@ forward cos msvcrt.cos
@ forward cosh msvcrt.cosh
@ forward ctime msvcrt.ctime
@ forward difftime msvcrt.difftime
@ forward div msvcrt.div
@ forward exit msvcrt.exit
@ forward exp msvcrt.exp
@ forward fabs msvcrt.fabs
@ forward fclose msvcrt.fclose
@ forward feof msvcrt.feof
@ forward ferror msvcrt.ferror
@ forward fflush msvcrt.fflush
@ forward fgetc msvcrt.fgetc
@ forward fgetpos msvcrt.fgetpos
@ forward fgets msvcrt.fgets
@ forward fgetwc msvcrt.fgetwc
@ forward fgetws msvcrt.fgetws
@ forward floor msvcrt.floor
@ forward fmod msvcrt.fmod
@ forward fopen msvcrt.fopen
@ forward fprintf msvcrt.fprintf
@ forward fputc msvcrt.fputc
@ forward fputs msvcrt.fputs
@ forward fputwc msvcrt.fputwc
@ forward fputws msvcrt.fputws
@ forward fread msvcrt.fread
@ forward free msvcrt.free
@ forward freopen msvcrt.freopen
@ forward frexp msvcrt.frexp
@ forward fscanf msvcrt.fscanf
@ forward fseek msvcrt.fseek
@ forward fsetpos msvcrt.fsetpos
@ forward ftell msvcrt.ftell
@ forward fwprintf msvcrt.fwprintf
@ forward fwrite msvcrt.fwrite
@ forward fwscanf msvcrt.fwscanf
@ forward getc msvcrt.getc
@ forward getchar msvcrt.getchar
@ forward getenv msvcrt.getenv
@ forward gets msvcrt.gets
@ forward getwc msvcrt.getwc
@ forward getwchar msvcrt.getwchar
@ forward gmtime msvcrt.gmtime
@ forward is_wctype msvcrt.is_wctype
@ forward isalnum msvcrt.isalnum
@ forward isalpha msvcrt.isalpha
@ forward iscntrl msvcrt.iscntrl
@ forward isdigit msvcrt.isdigit
@ forward isgraph msvcrt.isgraph
@ forward isleadbyte msvcrt.isleadbyte
@ forward islower msvcrt.islower
@ forward isprint msvcrt.isprint
@ forward ispunct msvcrt.ispunct
@ forward isspace msvcrt.isspace
@ forward isupper msvcrt.isupper
@ forward iswalnum msvcrt.iswalnum
@ forward iswalpha msvcrt.iswalpha
@ forward iswascii msvcrt.iswascii
@ forward iswcntrl msvcrt.iswcntrl
@ forward iswctype msvcrt.iswctype
@ forward iswdigit msvcrt.iswdigit
@ forward iswgraph msvcrt.iswgraph
@ forward iswlower msvcrt.iswlower
@ forward iswprint msvcrt.iswprint
@ forward iswpunct msvcrt.iswpunct
@ forward iswspace msvcrt.iswspace
@ forward iswupper msvcrt.iswupper
@ forward iswxdigit msvcrt.iswxdigit
@ forward isxdigit msvcrt.isxdigit
@ forward labs msvcrt.labs
@ forward ldexp msvcrt.ldexp
@ forward ldiv msvcrt.ldiv
@ forward localeconv msvcrt.localeconv
@ forward localtime msvcrt.localtime
@ forward log msvcrt.log
@ forward log10 msvcrt.log10
@ forward longjmp msvcrt.longjmp
@ forward malloc msvcrt.malloc
@ forward mblen msvcrt.mblen
@ forward mbstowcs msvcrt.mbstowcs
@ forward mbtowc msvcrt.mbtowc
@ forward memchr msvcrt.memchr
@ forward memcmp msvcrt.memcmp
@ forward memcpy msvcrt.memcpy
@ forward memmove msvcrt.memmove
@ forward memset msvcrt.memset
@ forward mktime msvcrt.mktime
@ forward modf msvcrt.modf
@ forward perror msvcrt.perror
@ forward pow msvcrt.pow
@ forward printf msvcrt.printf
@ forward putc msvcrt.putc
@ forward putchar msvcrt.putchar
@ forward puts msvcrt.puts
@ forward putwc msvcrt.putwc
@ forward putwchar msvcrt.putwchar
@ forward qsort msvcrt.qsort
@ forward raise msvcrt.raise
@ forward rand msvcrt.rand
@ forward realloc msvcrt.realloc
@ forward remove msvcrt.remove
@ forward rename msvcrt.rename
@ forward rewind msvcrt.rewind
@ forward scanf msvcrt.scanf
@ forward setbuf msvcrt.setbuf
@ forward setlocale msvcrt.setlocale
@ forward setvbuf msvcrt.setvbuf
@ forward signal msvcrt.signal
@ forward sin msvcrt.sin
@ forward sinh msvcrt.sinh
@ forward sprintf msvcrt.sprintf
@ forward sqrt msvcrt.sqrt
@ forward srand msvcrt.srand
@ forward sscanf msvcrt.sscanf
@ forward strcat msvcrt.strcat
@ forward strchr msvcrt.strchr
@ forward strcmp msvcrt.strcmp
@ forward strcoll msvcrt.strcoll
@ forward strcpy msvcrt.strcpy
@ forward strcspn msvcrt.strcspn
@ forward strerror msvcrt.strerror
@ forward strftime msvcrt.strftime
@ forward strlen msvcrt.strlen
@ forward strncat msvcrt.strncat
@ forward strncmp msvcrt.strncmp
@ forward strncpy msvcrt.strncpy
@ forward strpbrk msvcrt.strpbrk
@ forward strrchr msvcrt.strrchr
@ forward strspn msvcrt.strspn
@ forward strstr msvcrt.strstr
@ forward strtod msvcrt.strtod
@ forward strtok msvcrt.strtok
@ forward strtol msvcrt.strtol
@ forward strtoul msvcrt.strtoul
@ forward strxfrm msvcrt.strxfrm
@ forward swprintf msvcrt.swprintf
@ forward swscanf msvcrt.swscanf
@ forward system msvcrt.system
@ forward tan msvcrt.tan
@ forward tanh msvcrt.tanh
@ forward time msvcrt.time
@ forward tmpfile msvcrt.tmpfile
@ forward tmpnam msvcrt.tmpnam
@ forward tolower msvcrt.tolower
@ forward toupper msvcrt.toupper
@ forward towlower msvcrt.towlower
@ forward towupper msvcrt.towupper
@ forward ungetc msvcrt.ungetc
@ forward ungetwc msvcrt.ungetwc
@ forward vfprintf msvcrt.vfprintf
@ forward vfwprintf msvcrt.vfwprintf
@ forward vprintf msvcrt.vprintf
@ forward vsprintf msvcrt.vsprintf
@ forward vswprintf msvcrt.vswprintf
@ forward vwprintf msvcrt.vwprintf
@ forward wcscat msvcrt.wcscat
@ forward wcschr msvcrt.wcschr
@ forward wcscmp msvcrt.wcscmp
@ forward wcscoll msvcrt.wcscoll
@ forward wcscpy msvcrt.wcscpy
@ forward wcscspn msvcrt.wcscspn
@ forward wcsftime msvcrt.wcsftime
@ forward wcslen msvcrt.wcslen
@ forward wcsncat msvcrt.wcsncat
@ forward wcsncmp msvcrt.wcsncmp
@ forward wcsncpy msvcrt.wcsncpy
@ forward wcspbrk msvcrt.wcspbrk
@ forward wcsrchr msvcrt.wcsrchr
@ forward wcsspn msvcrt.wcsspn
@ forward wcsstr msvcrt.wcsstr
@ forward wcstod msvcrt.wcstod
@ forward wcstok msvcrt.wcstok
@ forward wcstol msvcrt.wcstol
@ forward wcstombs msvcrt.wcstombs
@ forward wcstoul msvcrt.wcstoul
@ forward wcsxfrm msvcrt.wcsxfrm
@ forward wctomb msvcrt.wctomb
@ forward wprintf msvcrt.wprintf
@ forward wscanf msvcrt.wscanf
