@ stdcall D3DXCreateBuffer(long ptr)
@ stdcall D3DXCreateFont(ptr ptr ptr)
@ stdcall D3DXGetFVFVertexSize(long)
@ stdcall D3DXAssembleShader(ptr long long ptr ptr ptr)
@ stdcall D3DXAssembleShaderFromFileA(ptr long ptr ptr ptr)
@ stdcall D3DXAssembleShaderFromFileW(ptr long ptr ptr ptr)
