#ifndef __WINE_AUTHORS_H
#define __WINE_AUTHORS_H

static const char * const SHELL_People[] =
{
    "James Abbatiello",
    "Howard Abrams",
    "Mark G. Adams",
    "Bruno Afonso",
    "Guy Albertelli",
    "Gustavo Junior Alves",
    "Bob Amstadt",
    "Dag Asheim",
    "Jim Aston",
    "Martin Ayotte",
    "Viktor Babrian",
    "Karl Backström",
    "Bradley Baetz",
    "Peter Bajusz",
    "Andre Malafaya Baptista",
    "Aaron Barnes",
    "Marcel Baur",
    "Francis Beaudet",
    "Tom Bech",
    "Matthew Becker",
    "Georg Beyerle",
    "Ross Biro",
    "Dennis Björklund",
    "Zygo Blaxell",
    "Martin Boehme",
    "Francois Boisvert",
    "Pim Bollen",
    "Uwe Bonnes",
    "Peter Bortas",
    "Noel Borthwick",
    "Erik Bos",
    "Fons Botman",
    "Justin Bradford",
    "John Brezak",
    "Andrew Bulhak",
    "John Burton",
    "Jonathan Buzzard",
    "Jose Marcos López Caravaca",
    "Eddie Carpenter",
    "Niels de Carpentier",
    "Mike Castle",
    "Ron Cemer",
    "Gordon Chaffee",
    "Gael de Chalendar",
    "Jimen Ching",
    "Geoff Clare",
    "Robert 'Admiral' Coeyman",
    "Richard Cohen",
    "Jean-Claude Cote",
    "Stephen Crowley",
    "Pascal Cuoq",
    "David A. Cuthbert",
    "Brian Joseph Czapiga",
    "Ulrich Czekalla",
    "Huw D. M. Davies",
    "Moses DeJong",
    "Roman Dolejsi",
    "Frans van Dorsselaer",
    "Rikhardur Egilsson",
    "Morten Eriksen",
    "Chris Faherty",
    "Carsten Fallesen",
    "Paul Falstad",
    "David Faure",
    "Wesley Filardo",
    "Claus Fischer",
    "Olaf Flebbe",
    "Chad Fraleigh",
    "Matthew Francis",
    "Philippe Froidevaux",
    "Peter Galbavy",
    "Peter Ganten",
    "Ramon Garcia",
    "Jeff Garzik",
    "Julio Cesar Gazquez",
    "Klaas van Gend",
    "Abey George",
    "Brian Gerst",
    "Matthew Ghio",
    "Jody Goldberg",
    "François Gouget",
    "Hans de Graaff",
    "David Grant",
    "Albert den Haan",
    "Jess Haas",
    "Robert W Hall",
    "Noomen Hamza",
    "Charles M. Hannum",
    "Adrian Harvey",
    "John Harvey",
    "Kalevi J Hautaniemi",
    "Bill Hawes",
    "Lars Heete",
    "Cameron Heide",
    "Bernd Herd",
    "Theodore S. Hetke",
    "Jochen Hoenicke",
    "Kevin Holbrook",
    "Nick Holloway",
    "Onno Hovers",
    "Jeffrey Hsu",
    "Peter Hunnisett",
    "Miguel de Icaza",
    "Jukka Iivonen",
    "Kostya Ivanov",
    "Lee Jaekil",
    "Niels Kristian Bech Jensen",
    "Jeff Johann",
    "Alexandre Julliard",
    "Bang Jun-Young",
    "James Juran",
    "Achim Kaiser",
    "Alexander Kanavin",
    "Jukka Kangas",
    "Pavel Kankovsky",
    "Michael Karcher",
    "Niclas Karlsson",
    "Jochen Karrer",
    "Andreas Kirschbaum",
    "Rein Klazes",
    "Albrecht Kleine",
    "Dietmar Kling",
    "Eric Kohl",
    "Jon Konrath",
    "Alex Korobka",
    "Zoltan Kovacs",
    "Greg Kreider",
    "Anand Kumria",
    "Ove Kåven",
    "Scott A. Laird",
    "David Lee Lambert",
    "Stephen Langasek",
    "Dan Langlois",
    "Alexander Larsson",
    "Stefan Leichter",
    "Karl Lessard",
    "Pascal Lessard",
    "Andrew Lewycky",
    "Per Lindström",
    "Brian Litzinger",
    "Juergen Lock",
    "Martin von Loewis",
    "Michiel van Loon",
    "Richard A Lough",
    "Alexander V. Lukyanov",
    "Jiuming Luo",
    "Stephane Lussier",
    "David Luyer",
    "José Marcos López",
    "Kenneth MacDonald",
    "Peter MacDonald",
    "Pierre Mageau",
    "William Magro",
    "Juergen Marquardt",
    "Ricardo Massaro",
    "Keith Matthews",
    "Joerg Mayer",
    "Michael McCormack",
    "Jason McMullan",
    "Caolan McNamara",
    "Marcus Meissner",
    "Graham Menhennitt",
    "David Metcalfe",
    "Paul Millar",
    "Bruce Milner",
    "Steffen Moeller",
    "Andreas Mohr",
    "Slava Monich",
    "James Moody",
    "Chris Morgan",
    "Kai Morich",
    "Richard Mortimer",
    "Vasudev Mulchandani",
    "Philippe De Muyter",
    "Itai Nahshon",
    "Jonathan Naylor",
    "Tim Newsome",
    "Thuy Nguyen",
    "Kristian Nielsen",
    "Henrik Olsen",
    "Gerard Patel",
    "Michael Patra",
    "Dimitrie O. Paun",
    "Bernd Paysan",
    "Brad Pepers",
    "Jim Peterson",
    "Gerald Pfeifer",
    "Dave Pickles",
    "Ian Pilcher",
    "Michael Poole",
    "Eric Pouech",
    "Robert Pouliot",
    "Chad Powell",
    "Joseph Pranevich",
    "Alex Priem",
    "Paul Quinn",
    "Pete Ratzlaff",
    "Ron Record",
    "Petter Reinholdtsen",
    "Keith Reynolds",
    "Slaven Rezic",
    "John Richardson",
    "Rick Richardson",
    "Douglas Ridgway",
    "Robert Riggs",
    "Bernhard Rosenkraenzer",
    "Pavel Roskin",
    "Herbert Rosmanith",
    "Johannes Ruscheinski",
    "Adam Sacarny",
    "Ivan de Saedeleer",
    "Thomas Sandford",
    "Constantine Sapuntzakis",
    "Pablo Saratxaga",
    "Carl van Schaik",
    "Daniel Schepler",
    "Christian Schlaile",
    "Peter Schlaile",
    "Ulrich Schmid",
    "Bernd Schmidt",
    "Ian Schmidt",
    "Juergen Schmied",
    "Ingo Schneider",
    "Victor Schneider",
    "Yngvi Sigurjonsson",
    "Stephen Simmons",
    "Jesper Skov",
    "Rick Sladkey",
    "William Smith",
    "Jaroslaw Piotr Sobieszek",
    "Patrick Spinler",
    "Sylvain St-Germain",
    "Gavriel State",
    "Norman Stevens",
    "Dominik Strasser",
    "Patrik Stridvall",
    "Vadim Strizhevsky",
    "Bertho Stultiens",
    "Charles Suprin",
    "James Sutherland",
    "Erik Svendsen",
    "Tristan Tarrant",
    "Andrew Taylor",
    "Joshua Thielen",
    "Dirk Thierbach",
    "Jean-Louis Thirot",
    "Duncan C Thomson",
    "Adrian Thurston",
    "Goran Thyni",
    "Steve Tibbett",
    "Dmitry Timoshkov",
    "Jimmy Tirtawangsa",
    "Jon Tombs",
    "Linus Torvalds",
    "Luc Tourangeau",
    "Gregory Trubetskoy",
    "Petri Tuomola",
    "Sergey Turchanov",
    "Lionel Ulmer",
    "Moshe Vainer",
    "Michael Veksler",
    "Sven Verdoolaege",
    "Todd Vierling",
    "Erez Volk",
    "Jerome Vouillon",
    "Ronan Waide",
    "Martin Walker",
    "Eric Warnke",
    "Leigh Wedding",
    "Randy Weems",
    "Manfred Weichel",
    "Ulrich Weigand",
    "Morten Welinder",
    "Jeremy White",
    "Len White",
    "Lawson Whitney",
    "Jan Willamowius",
    "Carl Williams",
    "Eric Williams",
    "Cliff Wright",
    "Karl Guenter Wuensch",
    "Eric Youngdale",
    "James Youngman",
    "Nikita V. Youshchenko",
    "Mikolaj Zalewski",
    "John Zero",
    "Yuxi Zhang",
    "Nathan Zorich",
    "Luiz Otavio L. Zorzella",
    "Per Ångström",
    0
};

#endif  /* __WINE_AUTHORS_H */
