/*
 * Copyright 2022 Ziqing Hui for CodeWeavers
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

 import "d2d1_1.idl";

[
    object,
    uuid(9b8b1336-00a5-4668-92b7-ced5d8bf9b7b),
    local,
]
interface ID2D1VertexBuffer : IUnknown
{
    HRESULT Map(
        [out] BYTE **data,
        [in] UINT32 size
    );
    HRESULT Unmap();
}

[
    object,
    uuid(688d15c3-02b0-438d-b13a-d1b44c32c39a),
    local,
]
interface ID2D1ResourceTexture : IUnknown
{
    HRESULT Update(
        [in] const UINT32 *min_extents,
        [in] const UINT32 *max_extents,
        [in] const UINT32 *strides,
        [in] UINT32 dimensions,
        [in] const BYTE *data,
        [in] UINT32 data_size
    );
}
