/* Do not modify this file -- it is automatically generated! */

#ifndef __WINE_DEBUGTOOLS_H
#include "debugtools.h"
#endif

/* Definitions for channels identifiers */
#define dbch_1 0
#define dbch_2 1
#define dbch_3 2
#define dbch_4 3
#define dbch_5 4
#define dbch_6 5
#define dbch_accel 6
#define dbch_advapi 7
#define dbch_animate 8
#define dbch_aspi 9
#define dbch_atom 10
#define dbch_bitblt 11
#define dbch_bitmap 12
#define dbch_caret 13
#define dbch_cdaudio 14
#define dbch_class 15
#define dbch_clipboard 16
#define dbch_clipping 17
#define dbch_combo 18
#define dbch_comboex 19
#define dbch_comm 20
#define dbch_commctrl 21
#define dbch_commdlg 22
#define dbch_console 23
#define dbch_crtdll 24
#define dbch_cursor 25
#define dbch_dc 26
#define dbch_dde 27
#define dbch_ddeml 28
#define dbch_ddraw 29
#define dbch_debug 30
#define dbch_dialog 31
#define dbch_dinput 32
#define dbch_dll 33
#define dbch_dosfs 34
#define dbch_dosmem 35
#define dbch_dplay 36
#define dbch_driver 37
#define dbch_dsound 38
#define dbch_edit 39
#define dbch_event 40
#define dbch_exec 41
#define dbch_file 42
#define dbch_fixup 43
#define dbch_font 44
#define dbch_gdi 45
#define dbch_global 46
#define dbch_graphics 47
#define dbch_header 48
#define dbch_heap 49
#define dbch_hook 50
#define dbch_hotkey 51
#define dbch_icon 52
#define dbch_imagelist 53
#define dbch_int 54
#define dbch_int10 55
#define dbch_int21 56
#define dbch_int31 57
#define dbch_key 58
#define dbch_keyboard 59
#define dbch_ldt 60
#define dbch_listbox 61
#define dbch_listview 62
#define dbch_local 63
#define dbch_mci 64
#define dbch_mcianim 65
#define dbch_mciwave 66
#define dbch_mdi 67
#define dbch_menu 68
#define dbch_message 69
#define dbch_metafile 70
#define dbch_midi 71
#define dbch_mmaux 72
#define dbch_mmio 73
#define dbch_mmsys 74
#define dbch_mmtime 75
#define dbch_module 76
#define dbch_mpr 77
#define dbch_msg 78
#define dbch_msvideo 79
#define dbch_nonclient 80
#define dbch_ntdll 81
#define dbch_ole 82
#define dbch_pager 83
#define dbch_palette 84
#define dbch_pidl 85
#define dbch_print 86
#define dbch_process 87
#define dbch_profile 88
#define dbch_progress 89
#define dbch_prop 90
#define dbch_psdrv 91
#define dbch_rebar 92
#define dbch_reg 93
#define dbch_region 94
#define dbch_relay 95
#define dbch_resource 96
#define dbch_s 97
#define dbch_scroll 98
#define dbch_security 99
#define dbch_segment 100
#define dbch_selector 101
#define dbch_sem 102
#define dbch_sendmsg 103
#define dbch_shell 104
#define dbch_shm 105
#define dbch_snoop 106
#define dbch_sound 107
#define dbch_static 108
#define dbch_statusbar 109
#define dbch_stress 110
#define dbch_string 111
#define dbch_syscolor 112
#define dbch_system 113
#define dbch_tab 114
#define dbch_task 115
#define dbch_text 116
#define dbch_thread 117
#define dbch_thunk 118
#define dbch_timer 119
#define dbch_toolbar 120
#define dbch_toolhelp 121
#define dbch_tooltips 122
#define dbch_trackbar 123
#define dbch_treeview 124
#define dbch_tweak 125
#define dbch_uitools 126
#define dbch_updown 127
#define dbch_ver 128
#define dbch_virtual 129
#define dbch_vxd 130
#define dbch_win 131
#define dbch_win16drv 132
#define dbch_win32 133
#define dbch_wing 134
#define dbch_winsock 135
#define dbch_wnet 136
#define dbch_x11 137
#define dbch_x11drv 138
/* Definitions for classes identifiers */
#define dbcl_fixme 0
#define dbcl_err 1
#define dbcl_warn 2
#define dbcl_trace 3
