/* Do not modify this file -- it is automatically generated! */

#ifndef __WINE_DEBUGTOOLS_H
#include "debugtools.h"
#endif

/* Definitions for channels identifiers */
#define dbch_accel 0
#define dbch_advapi 1
#define dbch_aspi 2
#define dbch_atom 3
#define dbch_bitblt 4
#define dbch_bitmap 5
#define dbch_caret 6
#define dbch_cd 7
#define dbch_cdaudio 8
#define dbch_class 9
#define dbch_clipboard 10
#define dbch_clipping 11
#define dbch_combo 12
#define dbch_comm 13
#define dbch_commctrl 14
#define dbch_commdlg 15
#define dbch_console 16
#define dbch_crtdll 17
#define dbch_cursor 18
#define dbch_dc 19
#define dbch_dde 20
#define dbch_ddeml 21
#define dbch_ddraw 22
#define dbch_debug 23
#define dbch_dialog 24
#define dbch_dinput 25
#define dbch_dll 26
#define dbch_dosfs 27
#define dbch_dosmem 28
#define dbch_dplay 29
#define dbch_driver 30
#define dbch_dsound 31
#define dbch_edit 32
#define dbch_event 33
#define dbch_exec 34
#define dbch_file 35
#define dbch_fixup 36
#define dbch_font 37
#define dbch_gdi 38
#define dbch_global 39
#define dbch_graphics 40
#define dbch_header 41
#define dbch_heap 42
#define dbch_hook 43
#define dbch_icon 44
#define dbch_imagelist 45
#define dbch_int 46
#define dbch_int21 47
#define dbch_int31 48
#define dbch_key 49
#define dbch_keyboard 50
#define dbch_ldt 51
#define dbch_listbox 52
#define dbch_local 53
#define dbch_mci 54
#define dbch_mcianim 55
#define dbch_mciwave 56
#define dbch_mdi 57
#define dbch_menu 58
#define dbch_message 59
#define dbch_metafile 60
#define dbch_midi 61
#define dbch_mmaux 62
#define dbch_mmio 63
#define dbch_mmsys 64
#define dbch_mmtime 65
#define dbch_module 66
#define dbch_mpr 67
#define dbch_msg 68
#define dbch_nonclient 69
#define dbch_ntdll 70
#define dbch_ole 71
#define dbch_palette 72
#define dbch_print 73
#define dbch_process 74
#define dbch_profile 75
#define dbch_progress 76
#define dbch_prop 77
#define dbch_psdrv 78
#define dbch_reg 79
#define dbch_region 80
#define dbch_relay 81
#define dbch_resource 82
#define dbch_scroll 83
#define dbch_security 84
#define dbch_segment 85
#define dbch_selector 86
#define dbch_sem 87
#define dbch_sendmsg 88
#define dbch_shell 89
#define dbch_shm 90
#define dbch_snoop 91
#define dbch_sound 92
#define dbch_static 93
#define dbch_stress 94
#define dbch_string 95
#define dbch_syscolor 96
#define dbch_system 97
#define dbch_task 98
#define dbch_text 99
#define dbch_thread 100
#define dbch_thunk 101
#define dbch_timer 102
#define dbch_toolbar 103
#define dbch_toolhelp 104
#define dbch_tweak 105
#define dbch_uitools 106
#define dbch_updown 107
#define dbch_ver 108
#define dbch_virtual 109
#define dbch_vxd 110
#define dbch_win 111
#define dbch_win16drv 112
#define dbch_win32 113
#define dbch_wing 114
#define dbch_winsock 115
#define dbch_wnet 116
#define dbch_x11 117
#define dbch_x11drv 118
/* Definitions for classes identifiers */
#define dbcl_fixme 0
#define dbcl_err 1
#define dbcl_warn 2
#define dbcl_trace 3
