/* Do not modify this file -- it is automatically generated! */

#ifndef __WINE_DEBUGTOOLS_H
#include "debugtools.h"
#endif

/* Definitions for channels identifiers */
#define dbch_accel 0
#define dbch_advapi 1
#define dbch_animate 2
#define dbch_aspi 3
#define dbch_atom 4
#define dbch_avifile 5
#define dbch_bitblt 6
#define dbch_bitmap 7
#define dbch_caret 8
#define dbch_cdaudio 9
#define dbch_class 10
#define dbch_clipboard 11
#define dbch_clipping 12
#define dbch_combo 13
#define dbch_comboex 14
#define dbch_comm 15
#define dbch_commctrl 16
#define dbch_commdlg 17
#define dbch_console 18
#define dbch_crtdll 19
#define dbch_cursor 20
#define dbch_datetime 21
#define dbch_dc 22
#define dbch_dde 23
#define dbch_ddeml 24
#define dbch_ddraw 25
#define dbch_debug 26
#define dbch_delayhlp 27
#define dbch_dialog 28
#define dbch_dinput 29
#define dbch_dll 30
#define dbch_dosfs 31
#define dbch_dosmem 32
#define dbch_dplay 33
#define dbch_driver 34
#define dbch_dsound 35
#define dbch_edit 36
#define dbch_event 37
#define dbch_exec 38
#define dbch_file 39
#define dbch_fixup 40
#define dbch_font 41
#define dbch_gdi 42
#define dbch_global 43
#define dbch_graphics 44
#define dbch_header 45
#define dbch_heap 46
#define dbch_hook 47
#define dbch_hotkey 48
#define dbch_icon 49
#define dbch_imagehlp 50
#define dbch_imagelist 51
#define dbch_imm 52
#define dbch_int 53
#define dbch_int10 54
#define dbch_int16 55
#define dbch_int17 56
#define dbch_int19 57
#define dbch_int21 58
#define dbch_int31 59
#define dbch_io 60
#define dbch_ipaddress 61
#define dbch_key 62
#define dbch_keyboard 63
#define dbch_ldt 64
#define dbch_listbox 65
#define dbch_listview 66
#define dbch_local 67
#define dbch_mci 68
#define dbch_mcianim 69
#define dbch_mciavi 70
#define dbch_mcimidi 71
#define dbch_mciwave 72
#define dbch_mdi 73
#define dbch_menu 74
#define dbch_message 75
#define dbch_metafile 76
#define dbch_midi 77
#define dbch_mmaux 78
#define dbch_mmio 79
#define dbch_mmsys 80
#define dbch_mmtime 81
#define dbch_module 82
#define dbch_monthcal 83
#define dbch_mpr 84
#define dbch_msacm 85
#define dbch_msg 86
#define dbch_msvideo 87
#define dbch_nativefont 88
#define dbch_nonclient 89
#define dbch_ntdll 90
#define dbch_ole 91
#define dbch_pager 92
#define dbch_palette 93
#define dbch_pidl 94
#define dbch_print 95
#define dbch_process 96
#define dbch_profile 97
#define dbch_progress 98
#define dbch_prop 99
#define dbch_propsheet 100
#define dbch_psapi 101
#define dbch_psdrv 102
#define dbch_ras 103
#define dbch_rebar 104
#define dbch_reg 105
#define dbch_region 106
#define dbch_relay 107
#define dbch_resource 108
#define dbch_scroll 109
#define dbch_security 110
#define dbch_segment 111
#define dbch_selector 112
#define dbch_sem 113
#define dbch_sendmsg 114
#define dbch_server 115
#define dbch_shell 116
#define dbch_shm 117
#define dbch_snoop 118
#define dbch_sound 119
#define dbch_static 120
#define dbch_statusbar 121
#define dbch_stress 122
#define dbch_string 123
#define dbch_syscolor 124
#define dbch_system 125
#define dbch_tab 126
#define dbch_tapi 127
#define dbch_task 128
#define dbch_text 129
#define dbch_thread 130
#define dbch_thunk 131
#define dbch_timer 132
#define dbch_toolbar 133
#define dbch_toolhelp 134
#define dbch_tooltips 135
#define dbch_trackbar 136
#define dbch_treeview 137
#define dbch_ttydrv 138
#define dbch_tweak 139
#define dbch_unknown 140
#define dbch_updown 141
#define dbch_ver 142
#define dbch_virtual 143
#define dbch_vxd 144
#define dbch_wave 145
#define dbch_win 146
#define dbch_win16drv 147
#define dbch_win32 148
#define dbch_wing 149
#define dbch_winsock 150
#define dbch_wnet 151
#define dbch_x11 152
#define dbch_x11drv 153
/* Definitions for classes identifiers */
#define dbcl_fixme 0
#define dbcl_err 1
#define dbcl_warn 2
#define dbcl_trace 3
