/*
 * Copyright 2022 Alex Henrie
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

[
    uuid(56f9f44f-f74c-4e38-99bc-9f3ebd3d696a)
]
library ShellCoreObjects
{
    [
        uuid(208d2c60-3aea-1069-a2d7-08002b30309d)
    ]
    coclass NetworkPlaces
    {
        interface IShellFolder2;
    }

    [
        uuid(00021400-0000-0000-c000-000000000046)
    ]
    coclass ShellDesktop
    {
        interface IShellFolder2;
    }

    [
        uuid(f3364ba0-65b9-11ce-a9ba-00aa004ae837)
    ]
    coclass ShellFSFolder
    {
        interface IShellFolder2;
    }

    [
        uuid(9ac9fbe1-e0a2-4ad6-b4ee-e212013ea917)
    ]
    coclass ShellItem
    {
        interface IShellItem2;
    }
}
