1 stub CertConfigureTrustA
2 stub CertConfigureTrustW
3 stub CertTrustCertPolicy
4 stub CertTrustCleanup
5 stub CertTrustFinalPolicy
6 stub CertTrustInit
7 stub DecodeAttrSequence
8 stub DecodeRecipientID
9 stub EncodeAttrSequence
10 stub EncodeRecipientID
11 stub FormatPKIXEmailProtection
12 stub FormatVerisignExtension
13 stub CertModifyCertificatesToTrust
14 stub CertSelectCertificateA
15 stub CertSelectCertificateW
16 stub CertViewPropertiesA
17 stub CertViewPropertiesW
18 stub DllRegisterServer
19 stub DllUnregisterServer
20 stub GetFriendlyNameOfCertA
21 stub GetFriendlyNameOfCertW
