@ stub CapabilitiesRequestAndCapabilitiesReply
@ stub DXVA2CreateDirect3DDeviceManager9
@ stub DXVA2CreateVideoService
@ stub DegaussMonitor
@ stub DestroyPhysicalMonitor
@ stub DestroyPhysicalMonitors
@ stub GetCapabilitiesStringLength
@ stub GetMonitorBrightness
@ stub GetMonitorCapabilities
@ stub GetMonitorColorTemperature
@ stub GetMonitorContrast
@ stub GetMonitorDisplayAreaPosition
@ stub GetMonitorDisplayAreaSize
@ stub GetMonitorRedGreenOrBlueDrive
@ stub GetMonitorRedGreenOrBlueGain
@ stub GetMonitorTechnologyType
@ stub GetNumberOfPhysicalMonitorsFromHMONITOR
@ stub GetNumberOfPhysicalMonitorsFromIDirect3DDevice9
@ stub GetPhysicalMonitorsFromHMONITOR
@ stub GetPhysicalMonitorsFromIDirect3DDevice9
@ stub GetTimingReport
@ stub GetVCPFeatureAndVCPFeatureReply
@ stub OPMGetVideoOutputsFromHMONITOR
@ stub OPMGetVideoOutputsFromIDirect3DDevice9Object
@ stub RestoreMonitorFactoryColorDefaults
@ stub RestoreMonitorFactoryDefaults
@ stub SaveCurrentMonitorSettings
@ stub SaveCurrentSettings
@ stub SetMonitorBrightness
@ stub SetMonitorColorTemperature
@ stub SetMonitorContrast
@ stub SetMonitorDisplayAreaPosition
@ stub SetMonitorDisplayAreaSize
@ stub SetMonitorRedGreenOrBlueDrive
@ stub SetMonitorRedGreenOrBlueGain
@ stub SetVCPFeature
@ stub UABGetCertificate
