@ stub WSDAddFirewallCheck
@ stub WSDCancelNetworkChangeNotify
@ stub WSDCopyNameList
@ stub WSDNotifyNetworkChange
@ stub WSDRemoveFirewallCheck
@ stub WSDXMLCompareNames
@ stub WSDAllocateLinkedMemory
@ stub WSDAttachLinkedMemory
@ stub WSDCompareEndpoints
@ stub WSDCopyEndpoint
@ stub WSDCreateDeviceHost2
@ stub WSDCreateDeviceHost
@ stub WSDCreateDeviceHostAdvanced
@ stub WSDCreateDeviceProxy2
@ stub WSDCreateDeviceProxy
@ stub WSDCreateDeviceProxyAdvanced
@ stub WSDCreateDiscoveryProvider2
@ stub WSDCreateDiscoveryProvider
@ stub WSDCreateDiscoveryPublisher2
@ stub WSDCreateDiscoveryPublisher
@ stub WSDCreateHttpAddress
@ stub WSDCreateHttpMessageParameters
@ stub WSDCreateHttpTransport
@ stub WSDCreateMetadataAgent
@ stub WSDCreateOutboundAttachment
@ stub WSDCreateUdpAddress
@ stub WSDCreateUdpMessageParameters
@ stub WSDCreateUdpTransport
@ stub WSDDetachLinkedMemory
@ stub WSDFreeLinkedMemory
@ stub WSDGenerateFault
@ stub WSDGenerateFaultEx
@ stub WSDGenerateRandomDelay
@ stub WSDGetConfigurationOption
@ stub WSDProcessFault
@ stub WSDSetConfigurationOption
@ stub WSDUriDecode
@ stub WSDUriEncode
@ stub WSDXMLAddChild
@ stub WSDXMLAddSibling
@ stub WSDXMLBuildAnyForSingleElement
@ stub WSDXMLCleanupElement
@ stub WSDXMLCreateContext
@ stub WSDXMLGetNameFromBuiltinNamespace
@ stub WSDXMLGetValueFromAny
