# OpenCL 1.0
@ stub clBuildProgram
@ stub clCreateBuffer
@ stub clCreateCommandQueue
@ stub clCreateContext
@ stub clCreateContextFromType
@ stub clCreateFromGLBuffer
@ stub clCreateFromGLRenderbuffer
@ stub clCreateFromGLTexture2D
@ stub clCreateFromGLTexture3D
@ stub clCreateImage2D
@ stub clCreateImage3D
@ stub clCreateKernel
@ stub clCreateKernelsInProgram
@ stub clCreateProgramWithBinary
@ stub clCreateProgramWithSource
@ stub clCreateSampler
@ stub clEnqueueAcquireGLObjects
@ stub clEnqueueBarrier
@ stub clEnqueueCopyBuffer
@ stub clEnqueueCopyBufferToImage
@ stub clEnqueueCopyImage
@ stub clEnqueueCopyImageToBuffer
@ stub clEnqueueMapBuffer
@ stub clEnqueueMapImage
@ stub clEnqueueMarker
@ stub clEnqueueNDRangeKernel
@ stub clEnqueueNativeKernel
@ stub clEnqueueReadBuffer
@ stub clEnqueueReadImage
@ stub clEnqueueReleaseGLObjects
@ stub clEnqueueTask
@ stub clEnqueueUnmapMemObject
@ stub clEnqueueWaitForEvents
@ stub clEnqueueWriteBuffer
@ stub clEnqueueWriteImage
@ stub clFinish
@ stub clFlush
@ stub clGetCommandQueueInfo
@ stub clGetContextInfo
@ stub clGetDeviceIDs
@ stub clGetDeviceInfo
@ stub clGetEventInfo
@ stub clGetEventProfilingInfo
@ stub clGetExtensionFunctionAddress
@ stub clGetGLObjectInfo
@ stub clGetGLTextureInfo
@ stub clGetImageInfo
@ stub clGetKernelInfo
@ stub clGetKernelWorkGroupInfo
@ stub clGetMemObjectInfo
@ stub clGetPlatformIDs
@ stub clGetPlatformInfo
@ stub clGetProgramBuildInfo
@ stub clGetProgramInfo
@ stub clGetSamplerInfo
@ stub clGetSupportedImageFormats
@ stub clReleaseCommandQueue
@ stub clReleaseContext
@ stub clReleaseEvent
@ stub clReleaseKernel
@ stub clReleaseMemObject
@ stub clReleaseProgram
@ stub clReleaseSampler
@ stub clRetainCommandQueue
@ stub clRetainContext
@ stub clRetainEvent
@ stub clRetainKernel
@ stub clRetainMemObject
@ stub clRetainProgram
@ stub clRetainSampler
@ stub clSetCommandQueueProperty
@ stub clSetKernelArg
@ stub clUnloadCompiler
@ stub clWaitForEvents
