#!/bin/sh

bit_array_test
bit_array=$?

dde_mem_test
mem=$?

hash_test
hash=$?

shm_semaph_test 
semaph=$?

dde_atom_test
atom=$?

dde_proc_test 1 > proc_server &
sleep 1
dde_proc_test > proc_client 
fgrep "DDE:receive sent message. msg=03e0 wPar=fffb lPar=00000004" proc_server &&
fgrep "DDE_GetRemoteMessage: sending ACK to wnd=fffb, proc=1" proc_server &&
fgrep "get_ack: received DDE_ACK message" proc_client 
proc=$?
rm proc_client proc_server

shm_fragment_test | diff TEST_FRAGMENT.std -
fragment=$?

echo ====================================================================
echo Test results:

echo -n "bit_array "
if [ $bit_array -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi

echo -n "dde_mem "
if [ $mem -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi

echo -n "hash "
if [ $hash -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi

echo -n "shm_semaph "
if [ $semaph -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi

echo -n "dde_proc "
if [ $proc -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi

echo -n "shm_fragment "
if [ $fragment -eq 0 ] ; then echo OK ; else echo "** ERROR **" ; fi
