@ stub -arch=win32 ?<Dispose>@Exception@Platform@@U$AAAXXZ
@ stub -arch=win64 ?<Dispose>@Exception@Platform@@UE$AAAXXZ
@ cdecl -arch=win32 ??0ChangedStateException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_ChangedStateException_hstring_ctor
@ cdecl -arch=win64 ??0ChangedStateException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_ChangedStateException_hstring_ctor
@ stub -arch=win32 ?Equals@Exception@Platform@@U$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@Exception@Platform@@UE$AAA_NPE$AAVObject@2@@Z
@ stub -arch=win32 ?Equals@MTAThreadAttribute@Platform@@Q$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@MTAThreadAttribute@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub -arch=win32 ?Equals@Object@Platform@@Q$AAA_NP$AAV12@@Z
@ stub -arch=win64 ?Equals@Object@Platform@@QE$AAA_NPE$AAV12@@Z
@ stub -arch=win32 ?Equals@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@Q$AAA_NP$AAVObject@4@@Z
@ stub -arch=win64 ?Equals@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAA_NPE$AAVObject@4@@Z
@ stub -arch=win32 ?Equals@STAThreadAttribute@Platform@@Q$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@STAThreadAttribute@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ cdecl -arch=win32 ?Equals@Type@Platform@@U$AAA_NP$AAVObject@2@@Z(ptr ptr) platform_type_Equals_Object
@ cdecl -arch=win64 ?Equals@Type@Platform@@UE$AAA_NPE$AAVObject@2@@Z(ptr ptr) platform_type_Equals_Object
@ stub -arch=win32 ?Equals@ValueType@Platform@@Q$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@ValueType@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub -arch=win32 ?Equals@char16@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@char16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@float32@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@float32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@float64@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@float64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ cdecl -arch=win32 ??0ChangedStateException@Platform@@Q$AAA@XZ(ptr) platform_ChangedStateException_ctor
@ cdecl -arch=win64 ??0ChangedStateException@Platform@@QE$AAA@XZ(ptr) platform_ChangedStateException_ctor
@ stub -arch=win32 ?Equals@int16@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@int16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@int32@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@int32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@int64@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@int64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@int8@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@int8@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@uint16@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@uint16@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@uint32@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@uint32@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@uint64@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@uint64@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=win32 ?Equals@uint8@default@@QAA_NP$AAVObject@Platform@@@Z
@ stub -arch=win64 ?Equals@uint8@default@@QEAA_NPE$AAVObject@Platform@@@Z
@ stub -arch=i386 ?EventSourceAdd@Details@Platform@@YG?AVEventRegistrationToken@Foundation@Windows@@PAPAXPAUEventLock@12@P$AAVDelegate@2@@Z
@ stub -arch=arm ?EventSourceAdd@Details@Platform@@YA?AVEventRegistrationToken@Foundation@Windows@@PAPAXPAUEventLock@12@P$AAVDelegate@2@@Z
@ stub -arch=win64 ?EventSourceAdd@Details@Platform@@YA?AVEventRegistrationToken@Foundation@Windows@@PEAPEAXPEAUEventLock@12@PE$AAVDelegate@2@@Z
@ stub -arch=i386 ?EventSourceGetTargetArray@Details@Platform@@YGPAXPAXPAUEventLock@12@@Z
@ stub -arch=arm ?EventSourceGetTargetArray@Details@Platform@@YAPAXPAXPAUEventLock@12@@Z
@ stub -arch=win64 ?EventSourceGetTargetArray@Details@Platform@@YAPEAXPEAXPEAUEventLock@12@@Z
@ cdecl -arch=win32 ??0ClassNotRegisteredException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_ClassNotRegisteredException_hstring_ctor
@ cdecl -arch=win64 ??0ClassNotRegisteredException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_ClassNotRegisteredException_hstring_ctor
@ stub -arch=i386 ?EventSourceGetTargetArrayEvent@Details@Platform@@YGPAXPAXIPBXPA_J@Z
@ stub -arch=arm ?EventSourceGetTargetArrayEvent@Details@Platform@@YAPAXPAXIPBXPA_J@Z
@ stub -arch=win64 ?EventSourceGetTargetArrayEvent@Details@Platform@@YAPEAXPEAXIPEBXPEA_J@Z
@ stub -arch=i386 ?EventSourceGetTargetArraySize@Details@Platform@@YGIPAX@Z
@ stub -arch=arm ?EventSourceGetTargetArraySize@Details@Platform@@YAIPAX@Z
@ stub -arch=win64 ?EventSourceGetTargetArraySize@Details@Platform@@YAIPEAX@Z
@ stub -arch=i386 ?EventSourceInitialize@Details@Platform@@YGXPAPAX@Z
@ stub -arch=arm ?EventSourceInitialize@Details@Platform@@YAXPAPAX@Z
@ stub -arch=win64 ?EventSourceInitialize@Details@Platform@@YAXPEAPEAX@Z
@ stub -arch=i386 ?EventSourceRemove@Details@Platform@@YGXPAPAXPAUEventLock@12@VEventRegistrationToken@Foundation@Windows@@@Z
@ stub -arch=arm ?EventSourceRemove@Details@Platform@@YAXPAPAXPAUEventLock@12@VEventRegistrationToken@Foundation@Windows@@@Z
@ stub -arch=win64 ?EventSourceRemove@Details@Platform@@YAXPEAPEAXPEAUEventLock@12@VEventRegistrationToken@Foundation@Windows@@@Z
@ stub -arch=i386 ?EventSourceUninitialize@Details@Platform@@YGXPAPAX@Z
@ stub -arch=arm ?EventSourceUninitialize@Details@Platform@@YAXPAPAX@Z
@ stub -arch=win64 ?EventSourceUninitialize@Details@Platform@@YAXPEAPEAX@Z
@ stub -arch=i386 ?FlushFactoryCache@@YGXXZ
@ stub -arch=arm ?FlushFactoryCache@@YAXXZ
@ stub -arch=win64 ?FlushFactoryCache@@YAXXZ
@ cdecl -arch=win32 ?Free@Heap@Details@Platform@@SAXPAX@Z(ptr) Free
@ cdecl -arch=win64 ?Free@Heap@Details@Platform@@SAXPEAX@Z(ptr) Free
@ cdecl -arch=win32 ?FreeException@Heap@Details@Platform@@SAXPAX@Z(ptr) FreeException
@ cdecl -arch=win64 ?FreeException@Heap@Details@Platform@@SAXPEAX@Z(ptr) FreeException
@ stub -arch=i386 ?GetActivationFactory@Details@Platform@@YGJPAVModuleBase@1WRL@Microsoft@@PAUHSTRING__@@PAPAUIActivationFactory@@@Z
@ stub -arch=arm ?GetActivationFactory@Details@Platform@@YAJPAVModuleBase@1WRL@Microsoft@@PAUHSTRING__@@PAPAUIActivationFactory@@@Z
@ stub -arch=win64 ?GetActivationFactory@Details@Platform@@YAJPEAVModuleBase@1WRL@Microsoft@@PEAUHSTRING__@@PEAPEAUIActivationFactory@@@Z
@ stdcall -arch=i386 ?GetActivationFactoryByPCWSTR@@YGJPAXAAVGuid@Platform@@PAPAX@Z(wstr ptr ptr) GetActivationFactoryByPCWSTR
@ stdcall -arch=arm ?GetActivationFactoryByPCWSTR@@YAJPAXAAVGuid@Platform@@PAPAX@Z(wstr ptr ptr) GetActivationFactoryByPCWSTR
@ stdcall -arch=win64 ?GetActivationFactoryByPCWSTR@@YAJPEAXAEAVGuid@Platform@@PEAPEAX@Z(wstr ptr ptr) GetActivationFactoryByPCWSTR
@ cdecl -arch=win32 ??0ClassNotRegisteredException@Platform@@Q$AAA@XZ(ptr) platform_ClassNotRegisteredException_ctor
@ cdecl -arch=win64 ??0ClassNotRegisteredException@Platform@@QE$AAA@XZ(ptr) platform_ClassNotRegisteredException_ctor
@ stub -arch=win32 ?GetCmdArguments@Details@Platform@@YAPAPA_WPAH@Z
@ stub -arch=win64 ?GetCmdArguments@Details@Platform@@YAPEAPEA_WPEAH@Z
@ stub -arch=win32 ?GetHashCode@Attribute@Metadata@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Attribute@Metadata@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Boolean@Platform@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@Boolean@Platform@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@Delegate@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Delegate@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Enum@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Enum@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Exception@Platform@@U$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Exception@Platform@@UE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Guid@Platform@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@Guid@Platform@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@MTAThreadAttribute@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@MTAThreadAttribute@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Object@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Object@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAAHXZ
@ stub -arch=win32 ??0Delegate@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0Delegate@Platform@@QE$AAA@XZ
@ stub -arch=win32 ?GetHashCode@STAThreadAttribute@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@STAThreadAttribute@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@Type@Platform@@U$AAAHXZ
@ stub -arch=win64 ?GetHashCode@Type@Platform@@UE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@ValueType@Platform@@Q$AAAHXZ
@ stub -arch=win64 ?GetHashCode@ValueType@Platform@@QE$AAAHXZ
@ stub -arch=win32 ?GetHashCode@char16@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@char16@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@float32@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@float32@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@float64@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@float64@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@int16@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@int16@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@int32@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@int32@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@int64@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@int64@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@int8@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@int8@default@@QEAAHXZ
@ cdecl -arch=win32 ??0DisconnectedException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_DisconnectedException_hstring_ctor
@ cdecl -arch=win64 ??0DisconnectedException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_DisconnectedException_hstring_ctor
@ stub -arch=win32 ?GetHashCode@uint16@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@uint16@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@uint32@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@uint32@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@uint64@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@uint64@default@@QEAAHXZ
@ stub -arch=win32 ?GetHashCode@uint8@default@@QAAHXZ
@ stub -arch=win64 ?GetHashCode@uint8@default@@QEAAHXZ
@ stub -arch=i386 ?GetIBoxArrayVtable@Details@Platform@@YGPAXPAX@Z
@ stub -arch=arm ?GetIBoxArrayVtable@Details@Platform@@YAPAXPAX@Z
@ stub -arch=win64 ?GetIBoxArrayVtable@Details@Platform@@YAPEAXPEAX@Z
@ stub -arch=i386 ?GetIBoxVtable@Details@Platform@@YGPAXPAX@Z
@ stub -arch=arm ?GetIBoxVtable@Details@Platform@@YAPAXPAX@Z
@ stub -arch=win64 ?GetIBoxVtable@Details@Platform@@YAPEAXPEAX@Z
@ stdcall -arch=i386 ?GetIidsFn@@YGJHPAKPBU__s_GUID@@PAPAVGuid@Platform@@@Z(long ptr ptr ptr) GetIidsFn
@ stdcall -arch=arm ?GetIidsFn@@YAJHPAKPBU__s_GUID@@PAPAVGuid@Platform@@@Z(long ptr ptr ptr) GetIidsFn
@ stdcall -arch=win64 ?GetIidsFn@@YAJHPEAKPEBU__s_GUID@@PEAPEAVGuid@Platform@@@Z(long ptr ptr ptr) GetIidsFn
@ stub -arch=i386 ?GetObjectContext@Details@Platform@@YGPAUIUnknown@@XZ
@ stub -arch=arm ?GetObjectContext@Details@Platform@@YAPAUIUnknown@@XZ
@ stub -arch=win64 ?GetObjectContext@Details@Platform@@YAPEAUIUnknown@@XZ
@ stub -arch=i386 ?GetProxyImpl@Details@Platform@@YGJPAUIUnknown@@ABU_GUID@@0PAPAU3@@Z
@ stub -arch=arm ?GetProxyImpl@Details@Platform@@YAJPAUIUnknown@@ABU_GUID@@0PAPAU3@@Z
@ stub -arch=win64 ?GetProxyImpl@Details@Platform@@YAJPEAUIUnknown@@AEBU_GUID@@0PEAPEAU3@@Z
@ stub -arch=win32 ?GetType@Boolean@Platform@@QAAP$AAVType@2@XZ
@ stub -arch=win64 ?GetType@Boolean@Platform@@QEAAPE$AAVType@2@XZ
@ cdecl -arch=win32 ??0DisconnectedException@Platform@@Q$AAA@XZ(ptr) platform_DisconnectedException_ctor
@ cdecl -arch=win64 ??0DisconnectedException@Platform@@QE$AAA@XZ(ptr) platform_DisconnectedException_ctor
@ stub -arch=win32 ?GetType@Guid@Platform@@QAAP$AAVType@2@XZ
@ stub -arch=win64 ?GetType@Guid@Platform@@QEAAPE$AAVType@2@XZ
@ stub -arch=win32 ?GetType@Object@Platform@@Q$AAAP$AAVType@2@XZ
@ stub -arch=win64 ?GetType@Object@Platform@@QE$AAAPE$AAVType@2@XZ
@ stub -arch=win32 ?GetType@char16@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@char16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@float32@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@float32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@float64@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@float64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@int16@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@int16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@int32@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@int32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@int64@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@int64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@int8@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@int8@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@uint16@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@uint16@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ??0Enum@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0Enum@Platform@@QE$AAA@XZ
@ stub -arch=win32 ?GetType@uint32@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@uint32@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@uint64@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@uint64@default@@QEAAPE$AAVType@Platform@@XZ
@ stub -arch=win32 ?GetType@uint8@default@@QAAP$AAVType@Platform@@XZ
@ stub -arch=win64 ?GetType@uint8@default@@QEAAPE$AAVType@Platform@@XZ
@ cdecl -arch=win32 ?GetTypeCode@Type@Platform@@SA?AW4TypeCode@2@P$AAV12@@Z(ptr) platform_type_GetTypeCode
@ cdecl -arch=win64 ?GetTypeCode@Type@Platform@@SA?AW4TypeCode@2@PE$AAV12@@Z(ptr) platform_type_GetTypeCode
@ stub -arch=i386 ?GetWeakReference@Details@Platform@@YGPAU__abi_IUnknown@@Q$ADVObject@2@@Z
@ stub -arch=arm ?GetWeakReference@Details@Platform@@YAPAU__abi_IUnknown@@Q$ADVObject@2@@Z
@ stub -arch=win64 ?GetWeakReference@Details@Platform@@YAPEAU__abi_IUnknown@@QE$ADVObject@2@@Z
@ stub -arch=i386 ?InitControlBlock@ControlBlock@Details@Platform@@AAEXPAX_N11@Z
@ stub -arch=arm ?InitControlBlock@ControlBlock@Details@Platform@@AAAXPAX_N11@Z
@ stub -arch=win64 ?InitControlBlock@ControlBlock@Details@Platform@@AEAAXPEAX_N11@Z
@ cdecl ?InitializeData@Details@Platform@@YAJH@Z(long) InitializeData
@ stub -arch=win32 ?Intersect@Rect@Foundation@Windows@@QAAXV123@@Z
@ stub -arch=win64 ?Intersect@Rect@Foundation@Windows@@QEAAXV123@@Z
@ stub -arch=win32 ?IntersectsWith@Rect@Foundation@Windows@@QAA_NV123@@Z
@ stub -arch=win64 ?IntersectsWith@Rect@Foundation@Windows@@QEAA_NV123@@Z
@ stub -arch=win32 ?Invert@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QAAXXZ
@ stub -arch=win64 ?Invert@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QEAAXXZ
@ cdecl -arch=win32 ??0Exception@Platform@@Q$AAA@H@Z(ptr long) platform_Exception_ctor
@ cdecl -arch=win64 ??0Exception@Platform@@QE$AAA@H@Z(ptr long) platform_Exception_ctor
@ stub -arch=win32 ?ReCreateException@Exception@Platform@@SAP$AAV12@H@Z
@ stub -arch=win64 ?ReCreateException@Exception@Platform@@SAPE$AAV12@H@Z
@ stub -arch=win32 ?ReferenceEquals@Object@Platform@@SA_NP$AAV12@0@Z
@ stub -arch=win64 ?ReferenceEquals@Object@Platform@@SA_NPE$AAV12@0@Z
@ stub -arch=win32 ?ReferenceEquals@Object@Platform@@SA_NP$AAVString@2@0@Z
@ stub -arch=win64 ?ReferenceEquals@Object@Platform@@SA_NPE$AAVString@2@0@Z
@ stub -arch=i386 ?RegisterFactories@Details@Platform@@YGP$AAVObject@2@PAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@P6GXXZ@Z
@ stub -arch=arm ?RegisterFactories@Details@Platform@@YAP$AAVObject@2@PAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@P6GXXZ@Z
@ stub -arch=win64 ?RegisterFactories@Details@Platform@@YAPE$AAVObject@2@PEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@P6AXXZ@Z
@ stub -arch=i386 ?ReleaseInContextImpl@Details@Platform@@YGJPAUIUnknown@@0@Z
@ stub -arch=arm ?ReleaseInContextImpl@Details@Platform@@YAJPAUIUnknown@@0@Z
@ stub -arch=win64 ?ReleaseInContextImpl@Details@Platform@@YAJPEAUIUnknown@@0@Z
@ thiscall -arch=i386 ?ReleaseTarget@ControlBlock@Details@Platform@@AAEXXZ(ptr) control_block_ReleaseTarget
@ cdecl -arch=arm ?ReleaseTarget@ControlBlock@Details@Platform@@AAAXXZ(ptr) control_block_ReleaseTarget
@ cdecl -arch=win64 ?ReleaseTarget@ControlBlock@Details@Platform@@AEAAXXZ(ptr) control_block_ReleaseTarget
@ stub -arch=i386 ?ResolveWeakReference@Details@Platform@@YGP$AAVObject@2@ABU_GUID@@PAPAU__abi_IUnknown@@@Z
@ stub -arch=arm ?ResolveWeakReference@Details@Platform@@YAP$AAVObject@2@ABU_GUID@@PAPAU__abi_IUnknown@@@Z
@ stub -arch=win64 ?ResolveWeakReference@Details@Platform@@YAPE$AAVObject@2@AEBU_GUID@@PEAPEAU__abi_IUnknown@@@Z
@ stub -arch=i386 ?RunApplicationServer@Details@Platform@@YGXPAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@PB_W@Z
@ stub -arch=arm ?RunApplicationServer@Details@Platform@@YAXPAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@PB_W@Z
@ stub -arch=win64 ?RunApplicationServer@Details@Platform@@YAXPEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@PEB_W@Z
@ stub -arch=i386 ?RunServer@Details@Platform@@YGXPAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@PB_W@Z
@ stub -arch=arm ?RunServer@Details@Platform@@YAXPAPAVModuleBase@1WRL@Microsoft@@PAPAU__abi_Module@@PB_W@Z
@ stub -arch=win64 ?RunServer@Details@Platform@@YAXPEAPEAVModuleBase@1WRL@Microsoft@@PEAPEAU__abi_Module@@PEB_W@Z
@ stub -arch=i386 ?TerminateModule@Details@Platform@@YG_NPAVModuleBase@1WRL@Microsoft@@@Z
@ stub -arch=arm ?TerminateModule@Details@Platform@@YA_NPAVModuleBase@1WRL@Microsoft@@@Z
@ stub -arch=win64 ?TerminateModule@Details@Platform@@YA_NPEAVModuleBase@1WRL@Microsoft@@@Z
@ cdecl -arch=win32 ??0Exception@Platform@@Q$AAA@HP$AAVString@1@@Z(ptr long ptr) platform_Exception_hstring_ctor
@ cdecl -arch=win64 ??0Exception@Platform@@QE$AAA@HPE$AAVString@1@@Z(ptr long ptr) platform_Exception_hstring_ctor
@ stub -arch=win32 ?ToInt32@IntPtr@Platform@@QAAHXZ
@ stub -arch=win64 ?ToInt32@IntPtr@Platform@@QEAAHXZ
@ stub -arch=win32 ?ToString@Attribute@Metadata@Platform@@Q$AAAP$AAVString@3@XZ
@ stub -arch=win64 ?ToString@Attribute@Metadata@Platform@@QE$AAAPE$AAVString@3@XZ
@ stub -arch=win32 ?ToString@Boolean@Platform@@QAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@Boolean@Platform@@QEAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@Delegate@Platform@@Q$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@Delegate@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@Enum@Platform@@Q$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@Enum@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@Exception@Platform@@U$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@Exception@Platform@@UE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@Guid@Platform@@QAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@Guid@Platform@@QEAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@MTAThreadAttribute@Platform@@Q$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@MTAThreadAttribute@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@Q$AAAP$AAVString@4@XZ
@ stub -arch=win64 ?ToString@OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAAPE$AAVString@4@XZ
@ stub -arch=win32 ?ToString@STAThreadAttribute@Platform@@Q$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@STAThreadAttribute@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?<Dispose>@String@Platform@@U$AAAXXZ
@ stub -arch=win64 ?<Dispose>@String@Platform@@UE$AAAXXZ
@ cdecl -arch=win32 ??0FailureException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_FailureException_hstring_ctor
@ cdecl -arch=win64 ??0FailureException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_FailureException_hstring_ctor
@ cdecl -arch=win32 ?ToString@Type@Platform@@U$AAAP$AAVString@2@XZ(ptr) platform_type_ToString
@ cdecl -arch=win64 ?ToString@Type@Platform@@UE$AAAPE$AAVString@2@XZ(ptr) platform_type_ToString
@ stub -arch=win32 ?ToString@ValueType@Platform@@Q$AAAP$AAVString@2@XZ
@ stub -arch=win64 ?ToString@ValueType@Platform@@QE$AAAPE$AAVString@2@XZ
@ stub -arch=win32 ?ToString@char16@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@char16@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@float32@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@float32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@float64@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@float64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@int16@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@int16@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@int32@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@int32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@int64@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@int64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@int8@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@int8@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@uint16@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@uint16@default@@QEAAPE$AAVString@Platform@@XZ
@ cdecl -arch=win32 ??0FailureException@Platform@@Q$AAA@XZ(ptr) platform_FailureException_ctor
@ cdecl -arch=win64 ??0FailureException@Platform@@QE$AAA@XZ(ptr) platform_FailureException_ctor
@ stub -arch=win32 ?ToString@uint32@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@uint32@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@uint64@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@uint64@default@@QEAAPE$AAVString@Platform@@XZ
@ stub -arch=win32 ?ToString@uint8@default@@QAAP$AAVString@Platform@@XZ
@ stub -arch=win64 ?ToString@uint8@default@@QEAAPE$AAVString@Platform@@XZ
@ cdecl ?UninitializeData@Details@Platform@@YAXH@Z(long) UninitializeData
@ stub -arch=win32 ?Union@Rect@Foundation@Windows@@QAAXV123@@Z
@ stub -arch=win64 ?Union@Rect@Foundation@Windows@@QEAAXV123@@Z
@ stub -arch=win32 ?Union@Rect@Foundation@Windows@@QAAXVPoint@23@@Z
@ stub -arch=win64 ?Union@Rect@Foundation@Windows@@QEAAXVPoint@23@@Z
@ stub -arch=win32 ?WriteLine@Console@Details@Platform@@SAXP$AAVObject@3@@Z
@ stub -arch=win64 ?WriteLine@Console@Details@Platform@@SAXPE$AAVObject@3@@Z
@ stub -arch=win32 ?WriteLine@Console@Details@Platform@@SAXP$AAVString@3@@Z
@ stub -arch=win64 ?WriteLine@Console@Details@Platform@@SAXPE$AAVString@3@@Z
@ stub ?WriteLine@Console@Details@Platform@@SAXXZ
@ stub -arch=i386 ?__abi_FailFast@@YGXXZ
@ stub -arch=arm ?__abi_FailFast@@YAXXZ
@ stub -arch=win64 ?__abi_FailFast@@YAXXZ
@ stub -arch=win32 ??0GridLength@Xaml@UI@Windows@@QAA@NW4GridUnitType@123@@Z
@ stub -arch=win64 ??0GridLength@Xaml@UI@Windows@@QEAA@NW4GridUnitType@123@@Z
@ stub -arch=i386 ?__abi_ObjectToString@__abi_details@@YGP$AAVString@Platform@@P$AAVObject@3@_N@Z
@ stub -arch=arm ?__abi_ObjectToString@__abi_details@@YAP$AAVString@Platform@@P$AAVObject@3@_N@Z
@ stub -arch=win64 ?__abi_ObjectToString@__abi_details@@YAPE$AAVString@Platform@@PE$AAVObject@3@_N@Z
@ stub -arch=win32 ?__abi_Resolve@ControlBlock@Details@Platform@@UAGJAAVGuid@3@PAPAU__abi_IInspectable@@@Z
@ stub -arch=win64 ?__abi_Resolve@ControlBlock@Details@Platform@@UEAAJAEAVGuid@3@PEAPEAU__abi_IInspectable@@@Z
@ stdcall -arch=i386 ?__abi_WinRTraiseAccessDeniedException@@YGXXZ() __abi_WinRTraiseAccessDeniedException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseAccessDeniedException@@YAXXZ() __abi_WinRTraiseAccessDeniedException
@ stdcall -arch=i386 ?__abi_WinRTraiseCOMException@@YGXJ@Z(long) __abi_WinRTraiseCOMException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseCOMException@@YAXJ@Z(long) __abi_WinRTraiseCOMException
@ stdcall -arch=i386 ?__abi_WinRTraiseChangedStateException@@YGXXZ() __abi_WinRTraiseChangedStateException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseChangedStateException@@YAXXZ() __abi_WinRTraiseChangedStateException
@ stdcall -arch=i386 ?__abi_WinRTraiseClassNotRegisteredException@@YGXXZ() __abi_WinRTraiseClassNotRegisteredException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseClassNotRegisteredException@@YAXXZ() __abi_WinRTraiseClassNotRegisteredException
@ stdcall -arch=i386 ?__abi_WinRTraiseDisconnectedException@@YGXXZ() __abi_WinRTraiseDisconnectedException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseDisconnectedException@@YAXXZ() __abi_WinRTraiseDisconnectedException
@ stdcall -arch=i386 ?__abi_WinRTraiseFailureException@@YGXXZ() __abi_WinRTraiseFailureException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseFailureException@@YAXXZ() __abi_WinRTraiseFailureException
@ stdcall -arch=i386 ?__abi_WinRTraiseInvalidArgumentException@@YGXXZ() __abi_WinRTraiseInvalidArgumentException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseInvalidArgumentException@@YAXXZ() __abi_WinRTraiseInvalidArgumentException
@ stdcall -arch=i386 ?__abi_WinRTraiseInvalidCastException@@YGXXZ() __abi_WinRTraiseInvalidCastException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseInvalidCastException@@YAXXZ() __abi_WinRTraiseInvalidCastException
@ stub -arch=win32 ??0IntPtr@Platform@@QAA@H@Z
@ stub -arch=win64 ??0IntPtr@Platform@@QEAA@H@Z
@ stdcall -arch=i386 ?__abi_WinRTraiseNotImplementedException@@YGXXZ() __abi_WinRTraiseNotImplementedException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseNotImplementedException@@YAXXZ() __abi_WinRTraiseNotImplementedException
@ stdcall -arch=i386 ?__abi_WinRTraiseNullReferenceException@@YGXXZ() __abi_WinRTraiseNullReferenceException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseNullReferenceException@@YAXXZ() __abi_WinRTraiseNullReferenceException
@ stdcall -arch=i386 ?__abi_WinRTraiseObjectDisposedException@@YGXXZ() __abi_WinRTraiseObjectDisposedException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseObjectDisposedException@@YAXXZ() __abi_WinRTraiseObjectDisposedException
@ stdcall -arch=i386 ?__abi_WinRTraiseOperationCanceledException@@YGXXZ() __abi_WinRTraiseOperationCanceledException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseOperationCanceledException@@YAXXZ() __abi_WinRTraiseOperationCanceledException
@ stdcall -arch=i386 ?__abi_WinRTraiseOutOfBoundsException@@YGXXZ() __abi_WinRTraiseOutOfBoundsException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseOutOfBoundsException@@YAXXZ() __abi_WinRTraiseOutOfBoundsException
@ stdcall -arch=i386 ?__abi_WinRTraiseOutOfMemoryException@@YGXXZ() __abi_WinRTraiseOutOfMemoryException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseOutOfMemoryException@@YAXXZ() __abi_WinRTraiseOutOfMemoryException
@ stdcall -arch=i386 ?__abi_WinRTraiseWrongThreadException@@YGXXZ() __abi_WinRTraiseWrongThreadException
@ stdcall -arch=arm,win64 ?__abi_WinRTraiseWrongThreadException@@YAXXZ() __abi_WinRTraiseWrongThreadException
@ stub -arch=i386 ?__abi_cast_Object_to_String@__abi_details@@YGP$AAVString@Platform@@_NP$AAVObject@3@@Z
@ stub -arch=arm ?__abi_cast_Object_to_String@__abi_details@@YAP$AAVString@Platform@@_NP$AAVObject@3@@Z
@ stub -arch=win64 ?__abi_cast_Object_to_String@__abi_details@@YAPE$AAVString@Platform@@_NPE$AAVObject@3@@Z
@ stub -arch=i386 ?__abi_cast_String_to_Object@__abi_details@@YGP$AAVObject@Platform@@P$AAVString@3@@Z
@ stub -arch=arm ?__abi_cast_String_to_Object@__abi_details@@YAP$AAVObject@Platform@@P$AAVString@3@@Z
@ stub -arch=win64 ?__abi_cast_String_to_Object@__abi_details@@YAPE$AAVObject@Platform@@PE$AAVString@3@@Z
@ stdcall -arch=i386 ?__abi_make_type_id@@YGP$AAVType@Platform@@ABU__abi_type_descriptor@@@Z(ptr) __abi_make_type_id
@ stdcall -arch=arm ?__abi_make_type_id@@YAP$AAVType@Platform@@ABU__abi_type_descriptor@@@Z(ptr) __abi_make_type_id
@ stdcall -arch=win64 ?__abi_make_type_id@@YAPE$AAVType@Platform@@AEBU__abi_type_descriptor@@@Z(ptr) __abi_make_type_id
@ stub -arch=win32 ??0IntPtr@Platform@@QAA@PAX@Z
@ stub -arch=win64 ??0IntPtr@Platform@@QEAA@PEAX@Z
@ stub -arch=i386 ?__abi_translateCurrentException@@YGJ_N@Z
@ stub -arch=arm ?__abi_translateCurrentException@@YAJ_N@Z
@ stub -arch=win64 ?__abi_translateCurrentException@@YAJ_N@Z
@ stub -arch=i386 ?__getActivationFactoryByHSTRING@@YGJPAUHSTRING__@@AAVGuid@Platform@@PAPAX@Z
@ stub -arch=arm ?__getActivationFactoryByHSTRING@@YAJPAUHSTRING__@@AAVGuid@Platform@@PAPAX@Z
@ stub -arch=win64 ?__getActivationFactoryByHSTRING@@YAJPEAUHSTRING__@@AEAVGuid@Platform@@PEAPEAX@Z
@ stub -arch=win32 ?get@Bottom@Rect@Foundation@Windows@@QAAMXZ
@ stub -arch=win64 ?get@Bottom@Rect@Foundation@Windows@@QEAAMXZ
@ stub ?get@BreakOnAllocationId@Heap@Details@Platform@@SAHXZ
@ stub ?get@BreakOnFreeId@Heap@Details@Platform@@SAHXZ
@ stub ?get@CurrentAllocationId@Heap@Details@Platform@@SAHXZ
@ stub ?get@Empty@Rect@Foundation@Windows@@SA?AV234@XZ
@ stub ?get@Empty@Size@Foundation@Windows@@SA?AV234@XZ
@ cdecl -arch=win32 ?get@FullName@Type@Platform@@Q$AAAP$AAVString@3@XZ(ptr) platform_type_get_FullName
@ cdecl -arch=win64 ?get@FullName@Type@Platform@@QE$AAAPE$AAVString@3@XZ(ptr) platform_type_get_FullName
@ stub -arch=win32 ?get@HasInverse@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QAA_NXZ
@ stub -arch=win64 ?get@HasInverse@Matrix3D@Media3D@Media@Xaml@UI@Windows@@QEAA_NXZ
@ cdecl -arch=win32 ??0InvalidArgumentException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_InvalidArgumentException_hstring_ctor
@ cdecl -arch=win64 ??0InvalidArgumentException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_InvalidArgumentException_hstring_ctor
@ cdecl -arch=win32 ?get@Message@Exception@Platform@@Q$AAAP$AAVString@3@XZ(ptr) platform_exception_get_Message
@ cdecl -arch=win64 ?get@Message@Exception@Platform@@QE$AAAPE$AAVString@3@XZ(ptr) platform_exception_get_Message
@ stub ?get@ObjectCount@Heap@Details@Platform@@SAHXZ
@ stub -arch=win32 ?get@Right@Rect@Foundation@Windows@@QAAMXZ
@ stub -arch=win64 ?get@Right@Rect@Foundation@Windows@@QEAAMXZ
@ stub ?get@TrackingLevel@Heap@Details@Platform@@SA?AW4HeapAllocationTrackingLevel@34@XZ
@ stub ?set@BreakOnAllocationId@Heap@Details@Platform@@SAXH@Z
@ stub ?set@BreakOnFreeId@Heap@Details@Platform@@SAXH@Z
@ stub ?set@TrackingLevel@Heap@Details@Platform@@SAXW4HeapAllocationTrackingLevel@34@@Z
@ cdecl -arch=win32 ??0InvalidArgumentException@Platform@@Q$AAA@XZ(ptr) platform_InvalidArgumentException_ctor
@ cdecl -arch=win64 ??0InvalidArgumentException@Platform@@QE$AAA@XZ(ptr) platform_InvalidArgumentException_ctor
@ cdecl -arch=win32 ??0InvalidCastException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_InvalidCastException_hstring_ctor
@ cdecl -arch=win64 ??0InvalidCastException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_InvalidCastException_hstring_ctor
@ cdecl -arch=win32 ??0InvalidCastException@Platform@@Q$AAA@XZ(ptr) platform_InvalidCastException_ctor
@ cdecl -arch=win64 ??0InvalidCastException@Platform@@QE$AAA@XZ(ptr) platform_InvalidCastException_ctor
@ stub -arch=win32 ??0MTAThreadAttribute@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0MTAThreadAttribute@Platform@@QE$AAA@XZ
@ stub -arch=win32 ?<Dispose>@Type@Platform@@U$AAAXXZ
@ stub -arch=win64 ?<Dispose>@Type@Platform@@UE$AAAXXZ
@ cdecl -arch=win32 ??0NotImplementedException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_NotImplementedException_hstring_ctor
@ cdecl -arch=win64 ??0NotImplementedException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_NotImplementedException_hstring_ctor
@ cdecl -arch=win32 ??0NotImplementedException@Platform@@Q$AAA@XZ(ptr) platform_NotImplementedException_ctor
@ cdecl -arch=win64 ??0NotImplementedException@Platform@@QE$AAA@XZ(ptr) platform_NotImplementedException_ctor
@ cdecl -arch=win32 ??0NullReferenceException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_NullReferenceException_hstring_ctor
@ cdecl -arch=win64 ??0NullReferenceException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_NullReferenceException_hstring_ctor
@ cdecl -arch=win32 ??0NullReferenceException@Platform@@Q$AAA@XZ(ptr) platform_NullReferenceException_ctor
@ cdecl -arch=win64 ??0NullReferenceException@Platform@@QE$AAA@XZ(ptr) platform_NullReferenceException_ctor
@ stub -arch=win32 ??0Object@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0Object@Platform@@QE$AAA@XZ
@ cdecl -arch=win32 ??0ObjectDisposedException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_ObjectDisposedException_hstring_ctor
@ cdecl -arch=win64 ??0ObjectDisposedException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_ObjectDisposedException_hstring_ctor
@ cdecl -arch=win32 ??0ObjectDisposedException@Platform@@Q$AAA@XZ(ptr) platform_ObjectDisposedException_ctor
@ cdecl -arch=win64 ??0ObjectDisposedException@Platform@@QE$AAA@XZ(ptr) platform_ObjectDisposedException_ctor
@ stub -arch=win32 ??0OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0OnePhaseConstructedAttribute@CompilerServices@Runtime@Platform@@QE$AAA@XZ
@ cdecl -arch=win32 ??0OperationCanceledException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_OperationCanceledException_hstring_ctor
@ cdecl -arch=win64 ??0OperationCanceledException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_OperationCanceledException_hstring_ctor
@ cdecl -arch=win32 ??0OperationCanceledException@Platform@@Q$AAA@XZ(ptr) platform_OperationCanceledException_ctor
@ cdecl -arch=win64 ??0OperationCanceledException@Platform@@QE$AAA@XZ(ptr) platform_OperationCanceledException_ctor
@ cdecl -arch=win32 ??0AccessDeniedException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_AccessDeniedException_hstring_ctor
@ cdecl -arch=win64 ??0AccessDeniedException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_AccessDeniedException_hstring_ctor
@ cdecl -arch=win32 ??0OutOfBoundsException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_OutOfBoundsException_hstring_ctor
@ cdecl -arch=win64 ??0OutOfBoundsException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_OutOfBoundsException_hstring_ctor
@ cdecl -arch=win32 ??0OutOfBoundsException@Platform@@Q$AAA@XZ(ptr) platform_OutOfBoundsException_ctor
@ cdecl -arch=win64 ??0OutOfBoundsException@Platform@@QE$AAA@XZ(ptr) platform_OutOfBoundsException_ctor
@ cdecl -arch=win32 ??0OutOfMemoryException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_OutOfMemoryException_hstring_ctor
@ cdecl -arch=win64 ??0OutOfMemoryException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_OutOfMemoryException_hstring_ctor
@ cdecl -arch=win32 ??0OutOfMemoryException@Platform@@Q$AAA@XZ(ptr) platform_OutOfMemoryException_ctor
@ cdecl -arch=win64 ??0OutOfMemoryException@Platform@@QE$AAA@XZ(ptr) platform_OutOfMemoryException_ctor
@ stub -arch=win32 ??0Rect@Foundation@Windows@@QAA@VPoint@12@0@Z
@ stub -arch=win64 ??0Rect@Foundation@Windows@@QEAA@VPoint@12@0@Z
@ stub -arch=win32 ??0Rect@Foundation@Windows@@QAA@VPoint@12@VSize@12@@Z
@ stub -arch=win64 ??0Rect@Foundation@Windows@@QEAA@VPoint@12@VSize@12@@Z
@ stub -arch=win32 ??0RepeatBehavior@Animation@Media@Xaml@UI@Windows@@QAA@N@Z
@ stub -arch=win64 ??0RepeatBehavior@Animation@Media@Xaml@UI@Windows@@QEAA@N@Z
@ stub -arch=win32 ??0STAThreadAttribute@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0STAThreadAttribute@Platform@@QE$AAA@XZ
@ stub -arch=win32 ??0SizeT@Platform@@QAA@H@Z
@ stub -arch=win64 ??0SizeT@Platform@@QEAA@H@Z
@ stub -arch=win32 ??0SizeT@Platform@@QAA@PAX@Z
@ stub -arch=win64 ??0SizeT@Platform@@QEAA@PEAX@Z
@ cdecl -arch=win32 ??0AccessDeniedException@Platform@@Q$AAA@XZ(ptr) platform_AccessDeniedException_ctor
@ cdecl -arch=win64 ??0AccessDeniedException@Platform@@QE$AAA@XZ(ptr) platform_AccessDeniedException_ctor
@ stub -arch=win32 ??0Type@Platform@@Q$AAA@P$AAVObject@1@@Z
@ stub -arch=win64 ??0Type@Platform@@QE$AAA@PE$AAVObject@1@@Z
@ stub -arch=win32 ??0Type@Platform@@Q$AAA@VIntPtr@1@@Z
@ stub -arch=win64 ??0Type@Platform@@QE$AAA@VIntPtr@1@@Z
@ stub -arch=win32 ??0Type@Platform@@Q$AAA@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub -arch=win64 ??0Type@Platform@@QE$AAA@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub -arch=win32 ??0ValueType@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0ValueType@Platform@@QE$AAA@XZ
@ cdecl -arch=win32 ??0WrongThreadException@Platform@@Q$AAA@P$AAVString@1@@Z(ptr ptr) platform_WrongThreadException_hstring_ctor
@ cdecl -arch=win64 ??0WrongThreadException@Platform@@QE$AAA@PE$AAVString@1@@Z(ptr ptr) platform_WrongThreadException_hstring_ctor
@ cdecl -arch=win32 ??0WrongThreadException@Platform@@Q$AAA@XZ(ptr) platform_WrongThreadException_ctor
@ cdecl -arch=win64 ??0WrongThreadException@Platform@@QE$AAA@XZ(ptr) platform_WrongThreadException_ctor
@ stub -arch=win32 ??0char16@default@@QAA@_W@Z
@ stub -arch=win64 ??0char16@default@@QEAA@_W@Z
@ stub -arch=win32 ??0float32@default@@QAA@M@Z
@ stub -arch=win64 ??0float32@default@@QEAA@M@Z
@ stub -arch=win32 ??0float64@default@@QAA@N@Z
@ stub -arch=win64 ??0float64@default@@QEAA@N@Z
@ stub -arch=win32 ??0int16@default@@QAA@F@Z
@ stub -arch=win64 ??0int16@default@@QEAA@F@Z
@ stub -arch=win32 ??0Attribute@Metadata@Platform@@Q$AAA@XZ
@ stub -arch=win64 ??0Attribute@Metadata@Platform@@QE$AAA@XZ
@ stub -arch=win32 ??0int32@default@@QAA@H@Z
@ stub -arch=win64 ??0int32@default@@QEAA@H@Z
@ stub -arch=win32 ??0int64@default@@QAA@_J@Z
@ stub -arch=win64 ??0int64@default@@QEAA@_J@Z
@ stub -arch=win32 ??0int8@default@@QAA@C@Z
@ stub -arch=win64 ??0int8@default@@QEAA@C@Z
@ stub -arch=win32 ??0uint16@default@@QAA@G@Z
@ stub -arch=win64 ??0uint16@default@@QEAA@G@Z
@ stub -arch=win32 ??0uint32@default@@QAA@I@Z
@ stub -arch=win64 ??0uint32@default@@QEAA@I@Z
@ stub -arch=win32 ??0uint64@default@@QAA@_K@Z
@ stub -arch=win64 ??0uint64@default@@QEAA@_K@Z
@ stub -arch=win32 ??0uint8@default@@QAA@E@Z
@ stub -arch=win64 ??0uint8@default@@QEAA@E@Z
@ stub ??BIntPtr@Platform@@SA?AV01@H@Z
@ stub -arch=win32 ??BIntPtr@Platform@@SA?AV01@PAX@Z
@ stub -arch=win64 ??BIntPtr@Platform@@SA?AV01@PEAX@Z
@ stub -arch=win32 ??BIntPtr@Platform@@SAPAXV01@@Z
@ stub -arch=win64 ??BIntPtr@Platform@@SAPEAXV01@@Z
@ stub -arch=win32 ??0Boolean@Platform@@QAA@_N@Z
@ stub -arch=win64 ??0Boolean@Platform@@QEAA@_N@Z
@ stub -arch=win32 ??BType@Platform@@SA?AVTypeName@Interop@Xaml@UI@Windows@@P$AAV01@@Z
@ stub -arch=win64 ??BType@Platform@@SA?AVTypeName@Interop@Xaml@UI@Windows@@PE$AAV01@@Z
@ stub -arch=win32 ??BType@Platform@@SAP$AAV01@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub -arch=win64 ??BType@Platform@@SAPE$AAV01@VTypeName@Interop@Xaml@UI@Windows@@@Z
@ stub ??DMatrix3D@Media3D@Media@Xaml@UI@Windows@@SA?AV012345@V012345@0@Z
@ stub ??GDuration@Xaml@UI@Windows@@SA?AV0123@V0123@0@Z
@ stub ??HDuration@Xaml@UI@Windows@@SA?AV0123@V0123@0@Z
@ stub ??MDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??NDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??ODuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub ??PDuration@Xaml@UI@Windows@@SA_NV0123@0@Z
@ stub -arch=win32 ?AlignedAllocate@Heap@Details@Platform@@SAPAXII@Z
@ stub -arch=win64 ?AlignedAllocate@Heap@Details@Platform@@SAPEAX_K00@Z
@ cdecl -arch=win32 ??0COMException@Platform@@Q$AAA@H@Z(ptr long) platform_COMException_ctor
@ cdecl -arch=win64 ??0COMException@Platform@@QE$AAA@H@Z(ptr long) platform_COMException_ctor
@ stub -arch=win32 ?AlignedAllocate@Heap@Details@Platform@@SAPAXIII@Z
@ stub -arch=win64 ?AlignedAllocate@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub -arch=win32 ?AlignedAllocateException@Heap@Details@Platform@@SAPAXII@Z
@ stub -arch=win64 ?AlignedAllocateException@Heap@Details@Platform@@SAPEAX_K00@Z
@ stub -arch=win32 ?AlignedAllocateException@Heap@Details@Platform@@SAPAXIII@Z
@ stub -arch=win64 ?AlignedAllocateException@Heap@Details@Platform@@SAPEAX_K0@Z
@ stub -arch=win32 ?AlignedFree@Heap@Details@Platform@@SAXPAX@Z
@ stub -arch=win64 ?AlignedFree@Heap@Details@Platform@@SAXPEAX@Z
@ stub -arch=win32 ?AlignedFreeException@Heap@Details@Platform@@SAXPAX@Z
@ stub -arch=win64 ?AlignedFreeException@Heap@Details@Platform@@SAXPEAX@Z
@ cdecl -arch=win32 ?Allocate@Heap@Details@Platform@@SAPAXI@Z(long) Allocate
@ cdecl -arch=win64 ?Allocate@Heap@Details@Platform@@SAPEAX_K@Z(long) Allocate
@ cdecl -arch=win32 ?Allocate@Heap@Details@Platform@@SAPAXII@Z(long long) AllocateWithWeakRef
@ cdecl -arch=win64 ?Allocate@Heap@Details@Platform@@SAPEAX_K0@Z(long long) AllocateWithWeakRef
@ cdecl -arch=win32 ?AllocateException@Heap@Details@Platform@@SAPAXI@Z(long) AllocateException
@ cdecl -arch=win64 ?AllocateException@Heap@Details@Platform@@SAPEAX_K0@Z(long long) AllocateExceptionWithWeakRef
@ cdecl -arch=win32 ?AllocateException@Heap@Details@Platform@@SAPAXII@Z(long long) AllocateExceptionWithWeakRef
@ cdecl -arch=win64 ?AllocateException@Heap@Details@Platform@@SAPEAX_K@Z(long) AllocateException
@ stub ?Compare@Duration@Xaml@UI@Windows@@SAHV1234@0@Z
@ cdecl -arch=win32 ??0COMException@Platform@@Q$AAA@HP$AAVString@1@@Z(ptr long ptr) platform_COMException_hstring_ctor
@ cdecl -arch=win64 ??0COMException@Platform@@QE$AAA@HPE$AAVString@1@@Z(ptr long ptr) platform_COMException_hstring_ctor
@ stub -arch=win32 ?Contains@Rect@Foundation@Windows@@QAA_NVPoint@23@@Z
@ stub -arch=win64 ?Contains@Rect@Foundation@Windows@@QEAA_NVPoint@23@@Z
@ cdecl -arch=win32 ?CreateException@Exception@Platform@@SAP$AAV12@H@Z(long) CreateException
@ cdecl -arch=win64 ?CreateException@Exception@Platform@@SAPE$AAV12@H@Z(long) CreateException
@ cdecl -arch=win32 ?CreateException@Exception@Platform@@SAP$AAV12@HP$AAVString@2@@Z(long ptr) CreateExceptionWithMessage
@ cdecl -arch=win64 ?CreateException@Exception@Platform@@SAPE$AAV12@HPE$AAVString@2@@Z(long ptr) CreateExceptionWithMessage
@ stdcall -arch=i386 ?CreateValue@Details@Platform@@YGP$AAVObject@2@W4TypeCode@2@PBX@Z(long ptr) CreateValue
@ stdcall -arch=arm ?CreateValue@Details@Platform@@YAP$AAVObject@2@W4TypeCode@2@PBX@Z(long ptr) CreateValue
@ stdcall -arch=win64 ?CreateValue@Details@Platform@@YAPE$AAVObject@2@W4TypeCode@2@PEBX@Z(long ptr) CreateValue
@ stub ?EnableFactoryCache@@YAXXZ
@ stub -arch=win32 ?EnumerateAllocatedObjects@Heap@Details@Platform@@SAXP$AAVHeapEntryHandler@23@@Z
@ stub -arch=win64 ?EnumerateAllocatedObjects@Heap@Details@Platform@@SAXPE$AAVHeapEntryHandler@23@@Z
@ stub -arch=win32 ?Equals@Attribute@Metadata@Platform@@Q$AAA_NP$AAVObject@3@@Z
@ stub -arch=win64 ?Equals@Attribute@Metadata@Platform@@QE$AAA_NPE$AAVObject@3@@Z
@ stub -arch=win32 ?Equals@Boolean@Platform@@QAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@Boolean@Platform@@QEAA_NPE$AAVObject@2@@Z
@ stub -arch=win32 ?Equals@Delegate@Platform@@Q$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@Delegate@Platform@@QE$AAA_NPE$AAVObject@2@@Z
@ stub -arch=win32 ?Equals@Enum@Platform@@Q$AAA_NP$AAVObject@2@@Z
@ stub -arch=win64 ?Equals@Enum@Platform@@QE$AAA_NPE$AAVObject@2@@Z
