1 stub WinBioNotifyPasswordChange
2 stub _BioLogonIdentifiedUser

@ stub WinBioAcquireFocus
@ stub WinBioAsyncEnumBiometricUnits
@ stub WinBioAsyncEnumDatabases
@ stub WinBioAsyncEnumServiceProviders
@ stub WinBioAsyncMonitorFrameworkChanges
@ stub WinBioAsyncOpenFramework
@ stub WinBioAsyncOpenSession
@ stub WinBioCancel
@ stub WinBioCaptureSample
@ stub WinBioCaptureSampleWithCallback
@ stub WinBioCloseFramework
@ stub WinBioCloseSession
@ stub WinBioControlUnit
@ stub WinBioControlUnitPrivileged
@ stub WinBioDeleteTemplate
@ stub WinBioDiscardTicket
@ stub WinBioEnrollAuthorize
@ stub WinBioEnrollBegin
@ stub WinBioEnrollCapture
@ stub WinBioEnrollCaptureWithCallback
@ stub WinBioEnrollCommit
@ stub WinBioEnrollDiscard
@ stub WinBioEnrollRevoke
@ stub WinBioEnrollSelect
@ stub WinBioEnumBiometricUnits
@ stub WinBioEnumDatabases
@ stub WinBioEnumEnrollments
@ stub WinBioEnumServiceProviders
@ stub WinBioFree
@ stub WinBioGetCredentialState
@ stub WinBioGetCredentialWithTicket
@ stub WinBioGetDomainLogonSetting
@ stub WinBioGetEnabledSetting
@ stub WinBioGetEnrolledFactors
@ stub WinBioGetGestureMetadata
@ stub WinBioGetLastBioUseTime
@ stub WinBioGetLogonSetting
@ stub WinBioGetPolicyProtectionSupport
@ stub WinBioGetProperty
@ stub WinBioGetProtectionPolicy
@ stub WinBioIdentify
@ stub WinBioIdentifyAndReleaseTicket
@ stub WinBioIdentifyWithCallback
@ stub WinBioLocateSensor
@ stub WinBioLocateSensorWithCallback
@ stub WinBioLockUnit
@ stub WinBioLogonIdentifiedUser
@ stub WinBioMonitorPresence
@ stub WinBioNgcAuthorizeEnrollment
@ stub WinBioNgcCloseAuthorizationSession
@ stub WinBioNgcGetAuthorizationWithTicket
@ stub WinBioNgcOpenAuthorizationSession
@ stub WinBioOpenSession
@ stub WinBioProtectData
@ stub WinBioProtectDataWithPolicy
@ stub WinBioRegisterEventMonitor
@ stub WinBioRegisterServiceMonitor
@ stub WinBioReleaseFocus
@ stub WinBioRemoveAllCredentials
@ stub WinBioRemoveAllDomainCredentials
@ stub WinBioRemoveCredential
@ stub WinBioSetCredential
@ stub WinBioSetMSACredential
@ stub WinBioSetProperty
@ stub WinBioUnlockUnit
@ stub WinBioUnprotectData
@ stub WinBioUnregisterEventMonitor
@ stub WinBioUnregisterServiceMonitor
@ stub WinBioVerify
@ stub WinBioVerifyAndReleaseTicket
@ stub WinBioVerifyWithCallback
@ stub WinBioWait
