@ stub BackupPerfRegistryToFileW
@ stub InstallPerfDllA
@ stub InstallPerfDllW
@ stub LoadMofFromInstalledServiceA
@ stub LoadMofFromInstalledServiceW
@ stub LoadPerfCounterTextStringsA
@ stub LoadPerfCounterTextStringsW
@ stub RestorePerfRegistryFromFileW
@ stub SetServiceAsTrustedA
@ stub SetServiceAsTrustedW
@ stub UnloadPerfCounterTextStringsA
@ stub UnloadPerfCounterTextStringsW
@ stub UpdatePerfNameFilesA
@ stub UpdatePerfNameFilesW
