1 stdcall -private DllMain(long long ptr)
2 stdcall XInputEnable(long)
3 stub XInputGetAudioDeviceIds(long ptr ptr ptr ptr)
4 stdcall XInputGetBatteryInformation(long long ptr)
5 stdcall XInputGetCapabilities(long long ptr)
6 stdcall XInputGetKeystroke(long long ptr)
7 stdcall XInputGetState(long ptr)
8 stdcall XInputSetState(long ptr)
