17 stub InitErrors
18 stub PostError
19 stub InitSSAutoEnterThread
20 stub UpdateError
22 stub LoadStringRC
23 stub ReOpenMetaDataWithMemory

@ stub CallFunctionShim
@ stub CloseCtrs
@ stub ClrCreateManagedInstance
@ stub CoEEShutDownCOM
@ stub CoInitializeCor
@ stub CoInitializeEE
@ stub CoUninitializeCor
@ stub CoUninitializeEE
@ stub CollectCtrs
@ stub CorBindToCurrentRuntime
@ stub CorBindToRuntime
@ stub CorBindToRuntimeByCfg
@ stub CorBindToRuntimeByPath
@ stub CorBindToRuntimeByPathEx
@ stub CorBindToRuntimeEx
@ stub CorBindToRuntimeHost
@ stub CorDllMainWorker
@ stub CorExitProcess
@ stub CorGetSvc
@ stub CorIsLatestSvc
@ stub CorMarkThreadInThreadPool
@ stub CorTickleSvc
@ stub CreateConfigStream
@ stub CreateDebuggingInterfaceFromVersion
@ stub DllCanUnloadNow
@ stub DllGetClassObject
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub EEDllGetClassObjectFromClass
@ stub EEDllRegisterServer
@ stub EEDllUnregisterServer
@ stub GetAssemblyMDImport
@ stub GetCORRequiredVersion
@ stub GetCORRootDirectory
@ stub GetCORSystemDirectory
@ stub GetCORVersion
@ stub GetCompileInfo
@ stub GetFileVersion
@ stub GetHashFromAssemblyFile
@ stub GetHashFromAssemblyFileW
@ stub GetHashFromBlob
@ stub GetHashFromFile
@ stub GetHashFromFileW
@ stub GetHashFromHandle
@ stub GetHostConfigurationFile
@ stub GetMetaDataInternalInterface
@ stub GetMetaDataInternalInterfaceFromPublic
@ stub GetMetaDataPublicInterfaceFromInternal
@ stub GetPermissionRequests
@ stub GetPrivateContextsPerfCounters
@ stub GetProcessExecutableHeap
@ stub GetRealProcAddress
@ stub GetRequestedRuntimeInfo
@ stub GetRequestedRuntimeVersion
@ stub GetRequestedRuntimeVersionForCLSID
@ stub GetStartupFlags
@ stub GetTargetForVTableEntry
@ stub GetTokenForVTableEntry
@ stub GetVersionFromProcess
@ stub GetXMLElement
@ stub GetXMLElementAttribute
@ stub GetXMLObject
@ stub LoadLibraryShim
@ stub LoadLibraryWithPolicyShim
@ stub LoadStringRCEx
@ stub LockClrVersion
@ stub MetaDataGetDispenser
@ stub OpenCtrs
@ stub ReOpenMetaDataWithMemoryEx
@ stub RunDll@ShimW
@ stub RuntimeOSHandle
@ stub RuntimeOpenImage
@ stub RuntimeReleaseHandle
@ stub SetTargetForVTableEntry
@ stub StrongNameCompareAssemblies
@ stub StrongNameErrorInfo
@ stub StrongNameFreeBuffer
@ stub StrongNameGetBlob
@ stub StrongNameGetBlobFromImage
@ stub StrongNameGetPublicKey
@ stub StrongNameHashSize
@ stub StrongNameKeyDelete
@ stub StrongNameKeyGen
@ stub StrongNameKeyGenEx
@ stub StrongNameKeyInstall
@ stub StrongNameSignatureGeneration
@ stub StrongNameSignatureGenerationEx
@ stub StrongNameSignatureSize
@ stub StrongNameSignatureVerification
@ stub StrongNameSignatureVerificationEx
@ stub StrongNameSignatureVerificationFromImage
@ stub StrongNameTokenFromAssembly
@ stub StrongNameTokenFromAssemblyEx
@ stub StrongNameTokenFromPublicKey
@ stub TranslateSecurityAttributes
@ stdcall _CorDllMain(long long ptr)
@ stdcall _CorExeMain2(ptr long ptr ptr ptr)
@ stdcall _CorExeMain()
@ stdcall _CorImageUnloading(ptr)
@ stdcall _CorValidateImage(ptr ptr)
