@ stub DnsAcquireContextHandle_A
@ stub DnsAcquireContextHandle_UTF8
@ stub DnsAcquireContextHandle_W
@ stub DnsAddRecordSet_A
@ stub DnsAddRecordSet_UTF8
@ stub DnsAddRecordSet_W
@ stub DnsAllocateRecord
@ stub DnsApiHeapReset
@ stub DnsAsyncRegisterHostAddrs_A
@ stub DnsAsyncRegisterHostAddrs_UTF8
@ stub DnsAsyncRegisterHostAddrs_W
@ stub DnsAsyncRegisterInit
@ stub DnsAsyncRegisterTerm
@ stub DnsCheckNameCollision_A
@ stub DnsCheckNameCollision_UTF8
@ stub DnsCheckNameCollision_W
@ stub DnsCopyStringEx
@ stub DnsCreateReverseNameStringForIpAddress
@ stub DnsCreateStandardDnsNameCopy
@ stub DnsCreateStringCopy
@ stub DnsDhcpSrvRegisterHostName_W
@ stub DnsDhcpSrvRegisterInit
@ stub DnsDhcpSrvRegisterTerm
@ stub DnsDisableAdapterDomainNameRegistration
@ stub DnsDisableBNodeResolverThread
@ stub DnsDisableDynamicRegistration
@ stub DnsDowncaseDnsNameLabel
@ stub DnsEnableAdapterDomainNameRegistration
@ stub DnsEnableBNodeResolverThread
@ stub DnsEnableDynamicRegistration
@ stub DnsExtractRecordsFromMessage_UTF8
@ stub DnsExtractRecordsFromMessage_W
@ stub DnsFindAuthoritativeZone
@ stub DnsFlushResolverCache
@ stub DnsFlushResolverCacheEntry_A
@ stub DnsFlushResolverCacheEntry_UTF8
@ stub DnsFlushResolverCacheEntry_W
@ stub DnsFreeAdapterInformation
@ stub DnsFreeNetworkInformation
@ stub DnsFreeSearchInformation
@ stub DnsGetBufferLengthForStringCopy
@ stub DnsGetCacheDataTable
@ stub DnsGetDnsServerList
@ stub DnsGetDomainName
@ stub DnsGetHostName_A
@ stub DnsGetHostName_UTF8
@ stub DnsGetHostName_W
@ stub DnsGetIpAddressInfoList
@ stub DnsGetIpAddressList
@ stub DnsGetLastServerUpdateIP
@ stub DnsGetMaxNumberOfAddressesToRegister
@ stub DnsGetNetworkInformation
@ stub DnsGetPrimaryDomainName_A
@ stub DnsGetPrimaryDomainName_UTF8
@ stub DnsGetPrimaryDomainName_W
@ stub DnsGetSearchInformation
@ stub DnsIpv6AddressToString
@ stub DnsIpv6StringToAddress
@ stub DnsIsAdapterDomainNameRegistrationEnabled
@ stub DnsIsAMailboxType
@ stub DnsIsDynamicRegistrationEnabled
@ stub DnsIsStatusRcode
@ stub DnsIsStringCountValidForTextType
@ stub DnsMapRcodeToStatus
@ stub DnsModifyRecordSet_A
@ stub DnsModifyRecordSet_UTF8
@ stub DnsModifyRecordSet_W
@ stub DnsModifyRecordsInSet_A
@ stub DnsModifyRecordsInSet_UTF8
@ stub DnsModifyRecordsInSet_W
@ stub DnsNameCompare_A
@ stub DnsNameCompareEx_A
@ stub DnsNameCompareEx_UTF8
@ stub DnsNameCompareEx_W
@ stub DnsNameCompare_W
@ stub DnsNameCopy
@ stub DnsNameCopyAllocate
@ stub DnsNotifyResolver
@ stub DnsQuery_A
@ stub DnsQueryConfig
@ stub DnsQueryEx
@ stub DnsQuery_UTF8
@ stub DnsQuery_W
@ stub DnsRecordBuild_UTF8
@ stub DnsRecordBuild_W
@ stub DnsRecordCompare
@ stub DnsRecordCopyEx
@ stub DnsRecordListFree
@ stub DnsRecordSetCompare
@ stub DnsRecordSetCopyEx
@ stub DnsRecordSetDetach
@ stub DnsRecordStringForType
@ stub DnsRecordStringForWritableType
@ stub DnsRecordTypeForName
@ stub DnsRelationalCompare_UTF8
@ stub DnsRelationalCompare_W
@ stub DnsReleaseContextHandle
@ stub DnsRemoveRegistrations
@ stub DnsReplaceRecordSetA
@ stub DnsReplaceRecordSet_A
@ stub DnsReplaceRecordSetUTF8
@ stub DnsReplaceRecordSet_UTF8
@ stub DnsReplaceRecordSetW
@ stub DnsReplaceRecordSet_W
@ stub DnsServiceNotificationDeregister_A
@ stub DnsServiceNotificationDeregister_UTF8
@ stub DnsServiceNotificationDeregister_W
@ stub DnsServiceNotificationRegister_A
@ stub DnsServiceNotificationRegister_UTF8
@ stub DnsServiceNotificationRegister_W
@ stub DnsSetMaxNumberOfAddressesToRegister
@ stub DnsStatusString
@ stub DnsStringCopyAllocateEx
@ stub DnsUnicodeToUtf8
@ stub DnsUpdate
@ stub DnsUpdateTest_A
@ stub DnsUpdateTest_UTF8
@ stub DnsUpdateTest_W
@ stub DnsUtf8ToUnicode
@ stub DnsValidateName_A
@ stub DnsValidateName_UTF8
@ stub DnsValidateName_W
@ stub DnsValidateUtf8Byte
@ stub DnsWinsRecordFlagForString
@ stub DnsWinsRecordFlagString
@ stub DnsWriteQuestionToBuffer_UTF8
@ stub DnsWriteQuestionToBuffer_W
@ stub DnsWriteReverseNameStringForIpAddress
@ stub GetCurrentTimeInSeconds
