@ stub BluetoothAuthenticateDevice
@ stub BluetoothAuthenticateMultipleDevices
@ stub BluetoothAuthenticationAgent
@ stub BluetoothDisconnectDevice
@ stub BluetoothDisplayDeviceProperties
@ stub BluetoothEnableDiscovery
@ stub BluetoothEnableIncomingConnections
@ stub BluetoothEnumerateInstalledServices
@ stub BluetoothFindBrowseGroupClose
@ stub BluetoothFindClassIdClose
@ stub BluetoothFindDeviceClose
@ stub BluetoothFindFirstBrowseGroup
@ stub BluetoothFindFirstClassId
@ stub BluetoothFindFirstDevice
@ stub BluetoothFindFirstProfileDescriptor
@ stub BluetoothFindFirstProtocolDescriptorStack
@ stub BluetoothFindFirstProtocolEntry
@ stub BluetoothFindFirstRadio
@ stub BluetoothFindFirstService
@ stub BluetoothFindNextBrowseGroup
@ stub BluetoothFindNextClassId
@ stub BluetoothFindNextDevice
@ stub BluetoothFindNextProfileDescriptor
@ stub BluetoothFindNextProtocolDescriptorStack
@ stub BluetoothFindNextProtocolEntry
@ stub BluetoothFindNextRadio
@ stub BluetoothFindNextService
@ stub BluetoothFindProfileDescriptorClose
@ stub BluetoothFindProtocolDescriptorStackClose
@ stub BluetoothFindProtocolEntryClose
@ stub BluetoothFindRadioClose
@ stub BluetoothFindServiceClose
@ stub BluetoothGetDeviceInfo
@ stub BluetoothGetRadioInfo
@ stub BluetoothIsConnectable
@ stub BluetoothIsDiscoverable
@ stub BluetoothMapClassOfDeviceToImageIndex
@ stub BluetoothMapClassOfDeviceToString
@ stub BluetoothRegisterForAuthentication
@ stub BluetoothRemoveDevice
@ stub BluetoothSdpEnumAttributes
@ stub BluetoothSdpGetAttributeValue
@ stub BluetoothSdpGetContainerElementData
@ stub BluetoothSdpGetElementData
@ stub BluetoothSdpGetString
@ stub BluetoothSelectDevices
@ stub BluetoothSelectDevicesFree
@ stub BluetoothSendAuthenticationResponse
@ stub BluetoothSetServiceState
@ stub BluetoothUnregisterAuthentication
@ stub BluetoothUpdateDeviceRecord
#@ stub CPlApplet
