@ stub CTEAllocateString
@ stub CTEBlock
@ stub CTEBlockWithTracker
@ stub CTEInitEvent
@ stub CTEInitString
@ stub CTEInitTimer
@ stub CTEInitialize
@ stub CTEInsertBlockTracker
@ stub CTELogEvent
@ stub CTERemoveBlockTracker
@ stub CTEScheduleCriticalEvent
@ stub CTEScheduleDelayedEvent
@ stub CTEScheduleEvent
@ stub CTESignal
@ stub CTEStartTimer
@ stub CTESystemUpTime
@ stub DllInitialize
@ stub DllUnload
@ stub TdiBuildNetbiosAddress
@ stub TdiBuildNetbiosAddressEa
@ stub TdiCopyBufferToMdl
@ stub TdiCopyBufferToMdlWithReservedMappingAtDpcLevel
@ stub TdiCopyMdlChainToMdlChain
@ stub TdiCopyMdlToBuffer
@ stub TdiDefaultChainedRcvDatagramHandler
@ stub TdiDefaultChainedRcvExpeditedHandler
@ stub TdiDefaultChainedReceiveHandler
@ stub TdiDefaultConnectHandler
@ stub TdiDefaultDisconnectHandler
@ stub TdiDefaultErrorHandler
@ stub TdiDefaultRcvDatagramHandler
@ stub TdiDefaultRcvExpeditedHandler
@ stub TdiDefaultReceiveHandler
@ stub TdiDefaultSendPossibleHandler
@ stub TdiDeregisterAddressChangeHandler
@ stub TdiDeregisterDeviceObject
@ stub TdiDeregisterNetAddress
@ stub TdiDeregisterNotificationHandler
@ stub TdiDeregisterPnPHandlers
@ stub TdiDeregisterProvider
@ stub TdiEnumerateAddresses
@ stub TdiGet9FTriageBlock
@ stub TdiInitialize
@ stub TdiMapUserRequest
@ stub TdiMatchPdoWithChainedReceiveContext
@ stub TdiOpenNetbiosAddress
@ stub TdiPnPPowerComplete
@ stub TdiPnPPowerRequest
@ stub TdiProviderReady
@ stub TdiRegisterAddressChangeHandler
@ stub TdiRegisterDeviceObject
@ stub TdiRegisterNetAddress
@ stub TdiRegisterNotificationHandler
@ stub TdiRegisterPnPHandlers
@ stub TdiRegisterProvider
@ stub TdiReturnChainedReceives
