@ stdcall BTCpuGetBopCode()
#@ stub BTCpuGetContext
@ stdcall BTCpuProcessInit()
#@ stub BTCpuResetToConsistentState
#@ stub BTCpuSetContext
@ stdcall BTCpuSimulate()
#@ stub BTCpuTurboThunkControl
#@ stub TurboDispatchJumpAddressEnd
#@ stub TurboDispatchJumpAddressStart
