@ stub CryptCATVerifyMember
@ stub CryptCATAdminAcquireContext
@ stub CryptCATAdminAddCatalog
@ stub CryptCATAdminCalcHashFromFileHandle
@ stub CryptCATAdminEnumCatalogFromHash
@ stub CryptCATAdminReleaseCatalogContext
@ stub CryptCATAdminReleaseContext
@ stub CryptCATCDFClose
@ stub CryptCATCDFEnumAttributes
@ stub CryptCATCDFEnumAttributesWithCDFTag
@ stub CryptCATCDFEnumCatAttributes
@ stub CryptCATCDFEnumMembers
@ stub CryptCATCDFEnumMembersByCDFTag
@ stub CryptCATCDFOpen
@ stub CryptCATCatalogInfoFromContext
@ stub CryptCATClose
@ stub CryptCATEnumerateAttr
@ stub CryptCATEnumerateCatAttr
@ stub CryptCATEnumerateMember
@ stub CryptCATGetAttrInfo
@ stub CryptCATGetCatAttrInfo
@ stub CryptCATGetMemberInfo
@ stub CryptCATHandleFromStore
@ stub CryptCATOpen
@ stub CryptCATPersistStore
@ stub CryptCATPutAttrInfo
@ stub CryptCATPutCatAttrInfo
@ stub CryptCATPutMemberInfo
@ stub CryptCATStoreFromHandle
@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub IsCatalogFile
@ stub MsCatConstructHashTag
@ stub MsCatFreeHashTag
