#! /usr/bin/perl -w
#
# Copyright 1999, 2000, 2001 Patrik Stridvall
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#

use strict;

require Cwd;

my $tool = $0;
$tool =~ s%^(?:.*?/)?([^/]+)$%$1%;

$_ = Cwd::cwd();
while($_) {
    my $file = "$_/tools/winapi/$tool";
    if(-e $file) {
	exec("$file @ARGV");
    }
    s%/[^/]*$%%;
}
print STDERR "$0: $tool: can't link to command\n";
