@ stub LogonIdFromWinStationNameA
@ stub LogonIdFromWinStationNameW
@ stub RemoteAssistancePrepareSystemRestore
@ stub ServerGetInternetConnectorStatus
@ stub ServerLicensingClose
@ stub ServerLicensingDeactivateCurrentPolicy
@ stub ServerLicensingFreePolicyInformation
@ stub ServerLicensingGetAvailablePolicyIds
@ stub ServerLicensingGetPolicy
@ stub ServerLicensingGetPolicyInformationA
@ stub ServerLicensingGetPolicyInformationW
@ stub ServerLicensingLoadPolicy
@ stub ServerLicensingOpenA
@ stub ServerLicensingOpenW
@ stub ServerLicensingSetPolicy
@ stub ServerLicensingUnloadPolicy
@ stub ServerQueryInetConnectorInformationA
@ stub ServerQueryInetConnectorInformationW
@ stub ServerSetInternetConnectorStatus
@ stub WinStationActivateLicense
@ stub WinStationAutoReconnect
@ stub WinStationBroadcastSystemMessage
@ stub WinStationCheckLoopBack
@ stub WinStationCloseServer
@ stub WinStationConnectA
@ stub WinStationConnectCallback
@ stub WinStationConnectW
@ stub WinStationDisconnect
@ stub WinStationEnumerateA
@ stub WinStationEnumerateLicenses
@ stub WinStationEnumerateProcesses
@ stdcall WinStationEnumerateW(ptr ptr ptr)
@ stub WinStationEnumerate_IndexedA
@ stub WinStationEnumerate_IndexedW
@ stub WinStationFreeGAPMemory
@ stub WinStationFreeMemory
@ stub WinStationGenerateLicense
@ stdcall WinStationGetAllProcesses(ptr long ptr ptr)
@ stub WinStationGetLanAdapterNameA
@ stub WinStationGetLanAdapterNameW
@ stub WinStationGetMachinePolicy
@ stdcall WinStationGetProcessSid(ptr long int64 ptr ptr)
@ stub WinStationGetTermSrvCountersValue
@ stub WinStationInstallLicense
@ stub WinStationIsHelpAssistantSession
@ stub WinStationNameFromLogonIdA
@ stub WinStationNameFromLogonIdW
@ stub WinStationNtsdDebug
@ stub WinStationOpenServerA
@ stub WinStationOpenServerW
@ stdcall WinStationQueryInformationA(ptr long long ptr long ptr)
@ stdcall WinStationQueryInformationW(ptr long long ptr long ptr)
@ stub WinStationQueryLicense
@ stub WinStationQueryLogonCredentialsW
@ stub WinStationQueryUpdateRequired
@ stdcall WinStationRegisterConsoleNotification(ptr ptr long)
@ stub WinStationRemoveLicense
@ stub WinStationRenameA
@ stub WinStationRenameW
@ stub WinStationReset
@ stub WinStationSendMessageA
@ stub WinStationSendMessageW
@ stub WinStationSendWindowMessage
@ stub WinStationServerPing
@ stub WinStationSetInformationA
@ stub WinStationSetInformationW
@ stub WinStationSetPoolCount
@ stub WinStationShadow
@ stub WinStationShadowStop
@ stub WinStationShutdownSystem
@ stub WinStationTerminateProcess
@ stdcall WinStationUnRegisterConsoleNotification(ptr ptr)
@ stdcall WinStationVirtualOpen(ptr ptr ptr)
@ stub WinStationWaitSystemEvent
@ stub _NWLogonQueryAdmin
@ stub _NWLogonSetAdmin
@ stub _WinStationAnnoyancePopup
@ stub _WinStationBeepOpen
@ stub _WinStationBreakPoint
@ stub _WinStationCallback
@ stub _WinStationCheckForApplicationName
@ stub _WinStationFUSCanRemoteUserDisconnect
@ stub _WinStationGetApplicationInfo
@ stub _WinStationNotifyDisconnectPipe
@ stub _WinStationNotifyLogoff
@ stub _WinStationNotifyLogon
@ stub _WinStationNotifyNewSession
@ stub _WinStationReInitializeSecurity
@ stub _WinStationReadRegistry
@ stub _WinStationShadowTarget
@ stub _WinStationShadowTargetSetup
@ stub _WinStationUpdateClientCachedCredentials
@ stub _WinStationUpdateSettings
@ stub _WinStationUpdateUserConfig
@ stub _WinStationWaitForConnect
