@ stub AddVirtualDiskParent
@ stub AttachVirtualDisk
@ stub BreakMirrorVirtualDisk
@ stub CompactVirtualDisk
@ stub CreateVirtualDisk
@ stub DeleteVirtualDiskMetadata
@ stub DetachVirtualDisk
@ stub EnumerateVirtualDiskMetadata
@ stub ExpandVirtualDisk
@ stub GetAllAttachedVirtualDiskPhysicalPaths
@ stdcall GetStorageDependencyInformation(long long long ptr ptr)
@ stub GetVirtualDiskInformation
@ stub GetVirtualDiskMetadata
@ stub GetVirtualDiskOperationProgress
@ stub GetVirtualDiskPhysicalPath
@ stub MergeVirtualDisk
@ stub MirrorVirtualDisk
@ stub OpenVirtualDisk
@ stub ResizeVirtualDisk
@ stub SetVirtualDiskInformation
@ stub SetVirtualDiskMetadata
